### ISSUE TITLE
Not working on Brave

### ISSUE THREAD

**Issue by Fornball** [Anarios/return-youtube-dislike#10]
I have loaded the package and temporarily disabled all the other extensions, yet im still getting this [error](https://imgur.com/a/sE6iyCu).
Seems to be brave only, as loading in the package on microsoft chrome worked and the dislikes showed.

**Comment by lnx00** [comment]
Try using the userscript with Violentmonkey (or something similar). It works for me on brave.

**Comment by Timeox2k** [comment]
I'm using Brave Beta without any Issue.

**Comment by 0luismario0** [comment]
It works without any issues for me. I'm using:
- OS Manjaro Linux
  - Kernel 5.13.19-2-MANJARO
  - Desktop environment Plasma 5.23.3
- Brave 1.32.106 [Chromium: 96.0.4664.45 (Official Build)]
  - Revision 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
  - JavaScript V8 9.6.180.12
- return-youtube-dislike v0.0.0.7

**Comment by Dr-S-Otter** [comment]
I'd advise adding it through the chrome web store cause that worked perfectly for me (also on Brave)
