### ISSUE TITLE
[Feature Request] Log users’ likes and dislikes to interpolate total dislikes

### ISSUE THREAD

**Issue by FayneAldan** [Anarios/return-youtube-dislike#100]
Not sure if this is within the scope of the project, but it would cool if the extension could log the user's likes and dislikes to the server and use that information to predict YouTube's dislike count by comparing YouTube's like count to Return YouTube Dislike's like count.

**Comment by DARKDRAGON532** [comment]
Already in work

**Comment by FayneAldan** [comment]
Any chance this can be reopened so people know this is a planned feature that hasn't been added yet?
