### ISSUE TITLE
Plugin no longer working in my Brave Browser

### ISSUE THREAD

**Issue by koloman360** [Anarios/return-youtube-dislike#1005]
### Discussed in https://github.com/Anarios/return-youtube-dislike/discussions/1004

<div type='discussions-op-text'>

<sup>Originally posted by **koloman360** December  5, 2023</sup>
Using Windows Brave V1.47.186 with RYD V3.0.0.12 . All Brave shields are disabled. </div>

**Comment by Anarios** [comment]
Fixed in v3.0.0.14
