### ISSUE TITLE
Dislike not showing in Shorts

### ISSUE THREAD

**Issue by n0753w** [Anarios/return-youtube-dislike#1009]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Microsoft Edge

### Browser Version

119.0.2151.97

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.13

### Video link where you see the problem

https://www.youtube.com/shorts/q9uSAFxgavY

### What happened?

Dislikes don't seem to show on shorts when viewed from browser. 

### How to reproduce/recreate?

Simply just go to any YT Short on MS Edge. 

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by GladistonXD** [comment]
The button changed its name, I made a correction here.
https://github.com/Anarios/return-youtube-dislike/issues/998

**Comment by fadster** [comment]
The Chrome version was updated on Dec 4 but it still has that problem. Dislike count does not appear on shorts.

**Comment by Anarios** [comment]
Fixed in v3.0.0.14
