### ISSUE TITLE
Dislike count / metadata showing in Share button

### ISSUE THREAD

**Issue by freshgum-bubbles** [Anarios/return-youtube-dislike#1010]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Firefox

### Browser Version

v120

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.12

### Video link where you see the problem

https://www.youtube.com/watch?v=F8OZTdhoAVo

### What happened?

The dislike text shows inside the Share button instead of the dislike button.
This seems like a bug.

## Examples

![image](https://github.com/Anarios/return-youtube-dislike/assets/85623267/e1ae827d-d3e2-4b8b-bab5-884c276d9218)

![image](https://github.com/Anarios/return-youtube-dislike/assets/85623267/ba1eae02-89e6-4f18-8407-636dd6bb1c89)

## DOM Snapshot

Here's a snapshot of the relevant DOM area, for reference.

![image](https://github.com/Anarios/return-youtube-dislike/assets/85623267/525b17cd-2d0b-4f88-92ef-f1f7d1d01ff2)

### How to reproduce/recreate?

Use YouTube :P

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by knedl1k** [comment]
Same issue here. Firefox v120, extension v3.0.0.12.

**Comment by fadster** [comment]
The extension was updated on December 4th but it's still broken.

**Comment by CartltonCrazeIsBackIGuess** [comment]
same issue - Firefox 120.0.1

**Comment by zPhenomm** [comment]
same issue Firefox v120.0.1 Extension v3.0.0.12

Also I think the bar for the like/dislike ratio should only be under the like/dislike buttons and not extend under the share button. Might be related to the issue.

**Comment by sabrt00th** [comment]
Same thing's happening to me. Firefox v120.0.1, extension v3.0.0.12. Pretty sure this wasn't an issue before I updated FF, so maybe something changed?

**Comment by gguy825** [comment]
Having the same issue on 120.0.1 too.

**Comment by thowtue** [comment]
Same issue here, Firefox 116.0.3

**Comment by MookyMcSass** [comment]
Same. Firefox 120.0.1

**Comment by boykokanev** [comment]
Same issue, Waterfox G6.0.6

**Comment by MookyMcSass** [comment]
> Same. Firefox 120.0.1

Now fixed I guess

**Comment by TsukiZero** [comment]
I had to uninstall and reinstall the extension for it to fix it up. Oddly, the Userscript didn't have that bug, it only lacked the bar.

**Comment by MrKoddy** [comment]
Dislikes are back but after hitting the like or dislike button, the number of dislikes isn't displayed anymore

**Comment by fadster** [comment]
> Dislikes are back but after hitting the like or dislike button, the number of dislikes isn't displayed anymore

Not only that but you actually have to click twice for the dislike to register.

**Comment by freshgum-bubbles** [comment]
> It fixed itself. Works fine now

I believe that's due to it pulling down the selectors for the dislike buttons from a central server, according to the code on GitHub.  The dev just needed to change what the server reported.

I'll keep track of this for a little bit and, if it's fixed, I'll close the issue.

**Comment by fadster** [comment]
> > It fixed itself. Works fine now
> 
> I believe that's due to it pulling down the selectors for the dislike buttons from a central server, according to the code on GitHub. The dev just needed to change what the server reported.
> 
> I'll keep track of this for a little bit and, if it's fixed, I'll close the issue.

It did NOT "fix itself". Did you read the comments above yours? Try clicking on the dislike button, see what happens. Leave this issue open until the developer actually fixes it.

**Comment by Wolterhon** [comment]
> It did NOT "fix itself".
It did. Dislikes are now shown next to the dislike button, that was the initial problem and is the main topic of this issue. I am not meant to test everything under the sun before posting a simple comment on an issue. By saying that it worked fine I meant that the dislike count came back to its intended place. I use the dislike button on rare occasions so no wonder I didn't experience the new bug you're talking about.

> Did you read the comments above yours?
No.

> Leave this issue open until the developer actually fixes it.
It's not even my issue 😭

**Comment by fadster** [comment]
> > It did NOT "fix itself".
> 
> It did. Dislikes are now shown next to the dislike button, that was the initial problem and is the main topic of this issue. I am not meant to test everything under the sun before posting a simple comment on an issue. By saying that it worked fine I meant that the dislike count came back to its intended place. I use the dislike button on rare occasions so no wonder I didn't experience the new bug you're talking about.

The point is, the feature is still broken.

> > Leave this issue open until the developer actually fixes it.
> 
> It's not even my issue 😭

If you look closely, you'll notice I wasn't replying to you.

**Comment by Wolterhon** [comment]
> If you look closely, you'll notice I wasn't replying to you.

> It did NOT "fix itself". Did you read the comments above yours?

You were obviously talking to me at first so yeah.

**Comment by fadster** [comment]
> > If you look closely, you'll notice I wasn't replying to you.
> 
> > It did NOT "fix itself". Did you read the comments above yours?
> 
> You were obviously talking to me at first so yeah.

Do you not know how to follow a reply chain?

**Comment by Wolterhon** [comment]
> Do you not know how to follow a reply chain?

Whatever that is in your book. Ability to quote parts of messages is there for a reason.

**Comment by fadster** [comment]
> > Do you not know how to follow a reply chain?
> 
> Whatever that is in your book. Ability to quote parts of messages is there for a reason.

I included the complete reply chain intentionally. If you're going to comment on public forums, you should learn how quotes are displayed and interpreted.

**Comment by Wolterhon** [comment]
> I included the complete reply chain intentionally. If you're going to comment on public forums, you should learn how quotes are displayed and interpreted.

On forums that I am on when people reply to multiple people they multi-quote. And usually they split them into multiple quotes, sometimes of the same post. Quit this unspoken rules stuff.

**Comment by fadster** [comment]
> On forums that I am on when people reply to multiple people they multi-quote. And usually they split them into multiple quotes, sometimes of the same post. Quit this unspoken rules stuff.

It's not a "rule", it's a matter of correctly parsing the number of vertical bars framing the quote. Anyway, I suggest we drop this, we are polluting the issue at hand.

**Comment by freshgum-bubbles** [comment]
> > > It fixed itself. Works fine now
> > 
> > 
> > I believe that's due to it pulling down the selectors for the dislike buttons from a central server, according to the code on GitHub. The dev just needed to change what the server reported.
> > I'll keep track of this for a little bit and, if it's fixed, I'll close the issue.
> 
> It did NOT "fix itself". Did you read the comments above yours? Try clicking on the dislike button, see what happens. Leave this issue open until the developer actually fixes it.

I read them, and it works fine for me.  Perhaps you should detail what version of the extension you use, your browser version, and the rest of what the issue template requires, as opposed to polluting the issue with arguments over semantics.

**Comment by fadster** [comment]
> I read them, and it works fine for me. 

Good for you! If it doesn't work on all supported platforms, it's still broken. I'll just create another issue.

> polluting the issue with arguments over semantics.

Tell that to the other guy.

**Comment by Moondarker** [comment]
Ohh what a drama. Anyways, please confirm if you still have any issues once you get the v3.0.0.14 update

**Comment by Anarios** [comment]
Fixed in 3.0.0.14
