### ISSUE TITLE
Dislike count disappeared after clicking dislike when uBlock Origin is enabled

### ISSUE THREAD

**Issue by Ayx03** [Anarios/return-youtube-dislike#1012]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

120.0.6099.71

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.13

### Video link where you see the problem

I don't think it's related

### What happened?

The dislike count disappeared after clicking on the dislike button when uBlock Origin is enabled

https://github.com/Anarios/return-youtube-dislike/assets/75155322/a3f3f8f1-8f92-4711-ae61-9099271772e0

### How to reproduce/recreate?

Install uBlock Origin and Return YouTube Dislike, open a video, click on dislike.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by fadster** [comment]
Clicking on dislike doesn't even seem to increase the dislike count reliably anymore. The extension is broken.

**Comment by chrism229** [comment]
I see both likes and dislikes, but if I click 'Like' the dislikes count disappears. This is without uBlock Origin enabled.

**Comment by Moondarker** [comment]
Please confirm this if this is still an issue on v3.0.0.14

**Comment by Ayx03** [comment]
Fixed in v3.0.0.14, but the Firefox version is still on v3.0.0.13

**Comment by chrism229** [comment]
Fixed for Vivaldi with V3.0.014, but as stated above, Firefox is still at V3.0.0.13.

**Comment by Ayx03** [comment]
The Firefox version got the update public too.

**Comment by chrism229** [comment]
Working OK in Firefox with v3.0.0.14
