### ISSUE TITLE
Dislike count vanishes till page refresh

### ISSUE THREAD

**Issue by MInecrafterPictures** [Anarios/return-youtube-dislike#1014]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome Canary

### Browser Version

122.0.6171.0

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.13

### Video link where you see the problem

https://www.youtube.com/watch?v=73AEJMQYnys

### What happened?

When I click the like or dislike button the dislike count is gone. I can bypass this by refreshing the page after clicking the button.

### How to reproduce/recreate?

Click like/dislike

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by MInecrafterPictures** [comment]
Also, the like/dislike bar is broken

**Comment by MrKoddy** [comment]
I have this issue

**Comment by Quicksilver151** [comment]
I have the issue where i dont see the number of dislikes till i press the dislike button. but the dislikes disappear again when i press the like button (firefox)

**Comment by fadster** [comment]
It's totally broken. Not only does the dislike count disappear the first time you click the dislike button, you have to click it twice for it to register, which makes this extension very unreliable now.
