### ISSUE TITLE
Dislikes not showing

### ISSUE THREAD

**Issue by Pentazer** [Anarios/return-youtube-dislike#1017]
### Have you tried to find similar issues (open or recently closed)?

- [X] Yes, this issue is not a duplicate

### Browser

OperaGX

### Browser Version

Chromium version:118.0.5993.118

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.12

### Video link where you see the problem

https://www.youtube.com/watch?v=v1vXC-vKgKg

### What happened?

Latest update was supposed to restore dislike counter that was no longer showing. Have just installed the latest version and dislikes are still not showing on videos. 
![image](https://github.com/Anarios/return-youtube-dislike/assets/54109677/da925aa9-a248-4959-977b-ba56e3371468)
![image](https://github.com/Anarios/return-youtube-dislike/assets/54109677/e2a47a9e-ef88-48e4-98a2-d53cf2011b9d)

### How to reproduce/recreate?

Load any video. Tested multiple of different genres. 

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Anarios** [comment]
Update to v3.0.0.14 please.
