### ISSUE TITLE
(Feature Request): Use ArchiveTeam's Youtube Dislikes archive instead of the Youtube API in the future

### ISSUE THREAD

**Issue by chavez-carlos** [Anarios/return-youtube-dislike#102]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Utilize the ArchiveTeam's Youtube Dislikes archive from archive.org instead of the Youtube API once its available.
The data isn't uploaded yet but theres about 710M+ items already archived: https://tracker.archiveteam.org/youtube-dislikes/
More information: https://wiki.archiveteam.org/index.php/YouTube#Removal_of_public_video_dislikes_.28December_2021.29

### Ways to implement this!

I doubt archive.org (where ArchiveTeam data is stored at) would be fast enough, so it would be necessary to have another way to store and request the data fast enough.
I would recommend [SkyDB](https://blog.sia.tech/skydb-a-mutable-database-for-the-decentralized-web-7170beeaa985); I have used their "skynet" platform and its amazing how fast and cheap it is, its sort of decentralized too.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by DARKDRAGON532** [comment]
Already in plan, thanks for the implementation methods though

**Comment by Myzel394** [comment]
@chavez-carlos do you know where to find the list of dislikes associated with the video id? The only thing I found is https://archive.org/details/archiveteam_youtubedislikes_20211211123803_62132b09. However, I can't figure out, how to use it :/
