### ISSUE TITLE
Bring back the colored like/dislike ratio

### ISSUE THREAD

**Issue by CHJ85** [Anarios/return-youtube-dislike#1027]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Hi there. I'm using this CSS as a userscript to bring back the green and red color ratio.
Thought you'd like to use this in your extension, as it does make it easier to see the ratio difference. And it looks nicer than the black and gray one.
```
var css = document.createElement("style");
css.innerHTML=`
  #return-youtube-dislike-bar-container, #ryd-bar-container
  {
    background: red !important;
  }
  
  #return-youtube-dislike-bar, #ryd-bar
  {
    background: lime !important;
  }
`;
document.head.appendChild(css);
```

### Can you work on this?

- [ ] Yes
- [ ] No

### Will you be available for follow-up questions to help developers implement this?

Yes

**Comment by Nightcaat** [comment]
Thank you for the suggestion, but we actually already have this :)

RYD has a colorize ratio bar option with the classic red and green as the default.
You can access RYD settings by clicking the gear icon in the top-right corner of the extension popup.

**Comment by CHJ85** [comment]
Oh yea. Can't believe I didn't noticed that before. 😀
Thanks.
