### ISSUE TITLE
Dislike count not showing up at all in Firefox and Brave

### ISSUE THREAD

**Issue by lunarparking** [Anarios/return-youtube-dislike#1029]
### Have you tried to find similar issues (open or recently closed)?

- [X] Yes, this issue is not a duplicate

### Browser

Firefox and Brave

### Browser Version

Latest versions of both

### Extension or Userscript?

Extension

### Extension/Userscript Version

Latest version

### Video link where you see the problem

Every video I try

### What happened?

Extension not working at all. Nothing shows up with the extension and I get a "0" with the userscript. 

### How to reproduce/recreate?

Click video. 

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by FrostDK01** [comment]
Not working for Chrome either. Don't know much about the development but seems the API used by the extension has failed (https://returnyoutubedislikeapi.com/votes?videoId=<VideoID>).

**Comment by Anarios** [comment]
Upgrading database cluster, some downtime is expected, all should be back in ~15 minutes.

**Comment by maxyudin** [comment]
This happened because YouTube continuously changes the page markup, so we just have to wait for the update and for Firefox and Chrome to accept it. It's not the first time this has happened, so be patient.

**Comment by Anarios** [comment]
> This happened because YouTube continuously changes the page markup, so we just have to wait for the update and for Firefox and Chrome to accept it. It's not the first time this has happened, so be patient.

nah, it's backend infrastructure upgrade this time, but it will be up faster, so - good news.

**Comment by Mehmuod** [comment]
Yup, the problem seems to be universal.

**Comment by maxyudin** [comment]
> > This happened because YouTube continuously changes the page markup, so we just have to wait for the update and for Firefox and Chrome to accept it. It's not the first time this has happened, so be patient.
> 
> nah, it's backend infrastructure upgrade this time, but it will be up faster, so - good news.

Yeah, I already realized that and had already deleted my comment at the time you wrote your reply.

**Comment by Mouadabdelghafouraitali** [comment]
The API itself is down

**Comment by NicoTheCinderace** [comment]
> Upgrading database cluster, some downtime is expected, all should be back in ~15 minutes.

Still down here.

**Comment by CopoliotXtester** [comment]
damn , feel so uncomfortable without dislike. It's like walking into a restaurant without knowing the review.

**Comment by NicoTheCinderace** [comment]
"but it will be up faster" they said...


...It's not up at all.

**Comment by EricE549X** [comment]
same here, using safari userscript. mostly shows up as 0 dislikes tho

**Comment by Cragsand** [comment]
The API currently returns Error 502 bad gateway

**Comment by Brandon98SE** [comment]
Still not working, this makes it so hard to tell if tutorials are fake or genuine.

I'm watching a tutorial about how to make whipped creme and the tutorial I'm watching starts in the bathroom. 
I don't think that is where you make custard.

**Comment by Anarios** [comment]
We're back.

**Comment by theblackhole** [comment]
@Brandon98SE 
> Still not working, this makes it so hard to tell if tutorials are fake or genuine.
> 
> I'm watching a tutorial about how to make cream and the tutorial I'm watching starts in the bathroom. I don't think that is the where the cream I am looking for is made lmfao.
> 
> Edit: wording.

Let me guess... HowToBasic? 😁

**Comment by maxyudin** [comment]
Please don't panic, put your knowledge in the piggy bank. If there is no knowledge, then keep quiet and wait for the update.

**Comment by Mouadabdelghafouraitali** [comment]
All good now, everything is working as usual. Thanks!
