### ISSUE TITLE
Enhanced Metrics - add likes:views:dislikes in the ratio bar

### ISSUE THREAD

**Issue by ntruter42** [Anarios/return-youtube-dislike#1031]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

The bar underneath the likes/dislikes counts currently displays the ratio of likes:dislikes and this gives a nice quick visual idea of the value or reception of a video. I would like to propose an enhancement to include views in this ratio bar so that the metric for the bar is likes:views:dislikes. This would make the likes and dislikes ratios relative to the views, instead of being relative to one another.

**Example:**
Take a video with 1M views, but only 900 likes and 100 (extrapolated) dislikes. The ratio of likes:dislikes will be 9:1 (indicating a very much liked video), but a more telling ratio is views:likes, which I'm guessing is 1:0.000009 (meaning people didn't feel compelled to click like) or likes:views:dislikes, which I'm roughly guessing is 0.000009:1:0.000001.

+++++++--- (likes:dislikes)
+++======- (likes:views:dislikes)
=======+++ (views:likes)

**Reasons:**
1. Some people view videos and if it's not that great, they won't even bother to like or dislike the video and that is an indication of poor to mediocre content.
2. It provides a better understanding not only of the reception of a video, but also of the active engagement (if the video triggers a strong positive or negative response).
3. This metric is more accurate than how I think you are currently extrapolating dislike counts, because view count is freely available from YouTube.
4. If, for some reason, dislike counts becomes increasingly difficult to extrapolate, views:likes can be a fallback metric which serves a similar purpose (content quality assessment).
5. Some users may have privacy concerns related to their own dislikes being part of your aggregated data (not that you're using irresponsibly or anything), but for this feature you don't need their dislikes data.
6. The option to hide augmented dislikes data and focus solely on the views:likes ratio adds a valuable layer of customization, simplicity, and positivity to the user experience.

Maybe this can be turned off by default in order to not break or mess with what you've already got going. Users might also be able to choose to hide the augmented dislikes data from the bar to see only views:likes ratio whilst keeping it next to the thumbs down icon. Possible configurations could be to include views:comments (user engagement), views:days (popularity / trending) or subscribers:views (popularity / re-viewability).

Those might be moving away from the name of the extension, but it adds value anyway.

### Can you work on this?

- [ ] Yes
- [X] No

### Will you be available for follow-up questions to help developers implement this?

Yes

**Comment by ntruter42** [comment]
I just had a look at the ratio of views to likes/dislikes of some videos and I realise now that the likes and dislikes on the ratio bar wouldn't even be visible on almost all videos, because there's just too many views compared to likes/dislikes. Closing this one immediately 🤦

**Comment by Anarios** [comment]
There are plans for "raw" stats, where you'd only see actual clicks from actual extension users. But no timeline for it.
