### ISSUE TITLE
Userscript: Dislike count decrease on click when uBlock Origin is enabled

### ISSUE THREAD

**Issue by Ayx03** [Anarios/return-youtube-dislike#1039]
### Have you tried to find similar issues (open or recently closed)?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

122.0.6261.95

### Extension or Userscript?

Userscript

### Extension/Userscript Version

3.1.4

### Video link where you see the problem

Not related

### What happened?

The dislike count decreased on click when it should increase when uBlock Origin is enabled.
![image](https://github.com/Anarios/return-youtube-dislike/assets/75155322/be5c0267-a9f9-4b5e-ab6e-6f76318dadaf)
![image](https://github.com/Anarios/return-youtube-dislike/assets/75155322/22dab298-32f5-4952-b784-98b9e25d5985)

### How to reproduce/recreate?

Enable uBlock Origin along with the UserScript. I used ViolentMonkey 2.18.0.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by kokonguyen191** [comment]
Any extra ublock filters you are using? Have you tried refreshing the page after disliking a video? Does the dislike go away or the number go back up or something similar? I can't seem to recreate the issue with the exact same browser and extension version

**Comment by krystian3w** [comment]
Sometimes I reduce the number and use uBo with slightly non-standard lists for Polish sites.

**Comment by Ayx03** [comment]
Seem to be fixed in 3.1.5, do anyone know where the source code of the user script is?

**Comment by Ayx03** [comment]
@kokonguyen191 I wasn't using any extra uBlock filters, maybe you're on the new version of extension? I was on userscript 3.1.4

**Comment by krystian3w** [comment]
This is probably the source code of script:

https://github.com/Anarios/return-youtube-dislike/tree/main/Extensions/UserScript

If I understand PR correctly, maybe someone forgot to update the number to 3.1.6.

**Comment by Nightcaat** [comment]
> Seem to be fixed in 3.1.5

Going to close this then, thanks :)
