### ISSUE TITLE
(Bug): Does nothing on older versions of FF both in extention and userscript

### ISSUE THREAD

**Issue by RosinSmoke** [Anarios/return-youtube-dislike#104]
### Browser

Firefox

### Browser Version

72.0b9

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.0.0.0

### Video link where you see the problem

any

### What happened?

How old FF does this addon support? I keep FF72 folder just for Youtube since it's the last version where 1.25x speed does not break the sound quality in favor of 3x like in 73+ (where do they even find the websites who offer these speeds?), and this addon would be nice to have, but as of now it doesn't show dislike number in either variant

**Comment by Anarios** [comment]
Get newer version of browser? )
