### ISSUE TITLE
Dislike Count is no longer appearing after YouTube page layout change.

### ISSUE THREAD

**Issue by darth-crunchus** [Anarios/return-youtube-dislike#1043]
### Have you tried to find similar issues (open or recently closed)?

- [X] Yes, this issue is not a duplicate

### Browser

Mozilla Firefox

### Browser Version

124.0.2

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.14

### Video link where you see the problem

It's everywhere, but here's an example: https://www.youtube.com/watch?v=P2rjxK9aZ24

### What happened?

YouTube has updated their page layout and it appears, that outside of shorts, dislike count is no longer displayed on long-form videos.

### How to reproduce/recreate?

Go to a long-form video.  Dislike button is present, but dislike count is not.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by InitPatch** [comment]
I found a workaround using another Chrome extension called [YouTube Enhancer ](https://chromewebstore.google.com/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle)
Because like many of you (I suppose), I really really hate this new layout! I sent feedback to Google and I encourage you all to do the same (Go to YouTube, click on your avatar, and down below you'll see a link "Send Feedback"); eventually, they'll come

After I installed it, I was able to see the dislikes again:
<img width="187" alt="image" src="https://github.com/Anarios/return-youtube-dislike/assets/15719066/717d8512-28f2-46e4-9481-9cc4ac2e4815">

**Comment by darth-crunchus** [comment]
> I found a workaround using another Chrome extension called [YouTube Enhancer ](https://chromewebstore.google.com/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle) Because like many of you (I suppose), I really really hate this new layout! I sent feedback to Google and I encourage you all to do the same (Go to YouTube, click on your avatar, and down below you'll see a link "Send Feedback"); eventually, they'll revert it to the old one 🤞

That's all well and good for Chrome users, but that doesn't help Firefox users.  Or did you not read the Browser this bug was reported for?

**Comment by InitPatch** [comment]
> > I found a workaround using another Chrome extension called [YouTube Enhancer ](https://chromewebstore.google.com/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle) Because like many of you (I suppose), I really really hate this new layout! I sent feedback to Google and I encourage you all to do the same (Go to YouTube, click on your avatar, and down below you'll see a link "Send Feedback"); eventually, they'll revert it to the old one 🤞
> 
> That's all well and good for Chrome users, but that doesn't help Firefox users. Or did you not read the Browser this bug was reported for?

My bad, I've only read the title... I'll delete my post then.

**Comment by theblackhole** [comment]
I was ready to fork the project to fix this issue then I discovered that the selectors are defined by the API (https://[returnyoutubedislikeapi.com/configs/selectors](https://returnyoutubedislikeapi.com/configs/selectors)) so the only thing we can do, is wait for @Anarios to update it since it's closed source.

(And I think this raises the question of opening API sources #45 I imagine it's not easy to be the only person maintaining the backend)

**Comment by Anarios** [comment]
@theblackhole - the backend just serves the same content as present in https://returnyoutubedislikeapi.com/configs/selectors file.

It's done via API to allow for fuster updates, without a need to release a new extension version (which takes up to 2 weeks in review).

My problem is that I couldn't catch the new UI, no matter how much I tried - I always get served with the old one. And I couldn't fix it blidnly, with just HTMLs sent by users.

So if you can check what breaks for you with the new UI - I'd update the selectors immediatelly.

**Comment by theblackhole** [comment]
@Anarios - After investigation, the selectors returned by the API were ultimately not the cause. This was the selector used to check if the video is loaded, which is in the code and which I was able to correct. I'm doing tests on different browsers (with old and new UI) then I'll open a PR if it's conclusive ;)

> @theblackhole - the backend just serves the same content as present in https://returnyoutubedislikeapi.com/configs/selectors file.

You're right. Sorry if I wasn't clear: I used "backend" in my last sentence as a synonym for API to avoid repetition, even if it's not exactly the same.

> It's done via API to allow for faster updates, without a need to release a new extension version (which takes up to 2 weeks in review).

Yeah that's a great design choice to avoid review delays, even with the current closed source limitation.

**Comment by Anarios** [comment]
Submitted for review.

The zips for local install are also available here.
https://github.com/Anarios/return-youtube-dislike/releases/tag/v3.0.0.15

**Comment by theblackhole** [comment]
I downloaded the 3.0.0.16 already available in the chrome webstore and the fix works on my side (+ the release zip for Firefox too).

Firefox update should be available soon via the store @darth-crunchus

**Comment by kariudo** [comment]
This seems broken again in the "new UI":

![image](https://github.com/Anarios/return-youtube-dislike/assets/1364939/6797dec4-fdc5-404c-8243-38d36f6f2278)

`Version: 3.0.0.16`

**Comment by theblackhole** [comment]
@kariudo Unfortunately I don't have the new (spring 2024) UI anymore (I don't know why) so I can't help this time :/
