### ISSUE TITLE
Ratio line reaches into area under share button

### ISSUE THREAD

**Issue by MesaBlack** [Anarios/return-youtube-dislike#1044]
### Have you tried to find similar issues (open or recently closed)?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

Version 123.0.6312.112 (Official Build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.14

### Video link where you see the problem

https://www.youtube.com/watch?v=06NdTuDreck

### What happened?

The ratio bar extended into the share button area.
![image](https://github.com/Anarios/return-youtube-dislike/assets/132141735/1b1ca10b-fe68-46cc-af04-f89a600f6c93)

### How to reproduce/recreate?

Just watch the video and see the ratio?

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by theblackhole** [comment]
Hello. Unfortunately, I can't reproduce the issue.
- Do you still have the problem?

If yes:
- Does it do this on any video?
- Are you zoomed in? (Press Ctrl+0 to reset the zoom or open the chrome menu and set the zoom to 100%)
- Could you post the screen detection result of this website https://screenresolutiontest.com/ ?
- Have you tried to disable all extensions except Return Youtube Dislike? (If you have many extensions and don't want to disable them one by one, the easiest way is to allow Return Youtube Dislike to run in Incognito mode then launch a new youtube video in an incognito tab)

**Comment by MesaBlack** [comment]
it's gone
