### ISSUE TITLE
Setting to Disable Percentage Bar

### ISSUE THREAD

**Issue by Kekerykek** [Anarios/return-youtube-dislike#1053]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

A setting for disabling the percentage bar below the like/dislike buttons would be nice.

### Will you be available for follow-up questions to help developers implement this?

Yes

**Comment by kokonguyen191** [comment]
I see you are using the extension version but if you don't mind installing the userscript version (which IMO is superior because you can get updates or even custom fixes whenever you want), the option is already in the script version.
