### ISSUE TITLE
(Feature Request): 

### ISSUE THREAD

**Issue by crystal-calx** [Anarios/return-youtube-dislike#106]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Is it possible to show the exact number of dislikes and likes rather than the abbreviated number?

### Ways to implement this!

I do not know.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by aurilly** [comment]
Until December 13th 2021, it does show the exact number of dislikes. Past that date, the YouTube API does not return dislikes so it **must** be estimated.
