### ISSUE TITLE
Newly uploaded videos fail with 404 error

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [Anarios/return-youtube-dislike#1062]
### Have you tried to find similar issues (open or recently closed)?

- [X] Yes, this issue is not a duplicate

### Browser

Any

### Browser Version

Any

### Extension or Userscript?

Userscript

### Extension/Userscript Version

Na

### Video link where you see the problem

https://youtu.be/bZgFFwP03Jk

### What happened?

As of this writing, this is an example video (but all recent will also give the same error):

https://returnyoutubedislikeapi.com/votes?videoId=bZgFFwP03Jk

```
{
  "type": "https://tools.ietf.org/html/rfc9110#section-15.5.5",
  "title": "Not Found",
  "status": 404,
  "traceId": "00-35bf04dcbc56ee3c398094ecd7d707ba-521590bddad1b615-00"
}
```

But, any older videos still work:
https://returnyoutubedislikeapi.com/votes?videoId=UnrU5vxCHxw

```
{
  "id": "UnrU5vxCHxw",
  "dateCreated": "2024-06-18T00:36:34.098572Z",
  "likes": 0,
  "dislikes": 0,
  "rating": 0,
  "viewCount": 118,
  "deleted": false
}
```

### How to reproduce/recreate?

Call the `votes` end point for any video recently uploaded

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by HattieJosh** [comment]
For whatever reason, ongoing live streams do not appear to be impacted

**Comment by HattieJosh** [comment]
It's inconsistent with live streams started since around the time this was reported. Ones from higher subscribed channels (I.E. Penguinz0) seem to work while lower subbed channels do not

**Comment by 03bgood** [comment]
Its happening with the newest uploads from the past 24 hours.

**Comment by Anarios** [comment]
Resolved for videos, working on streams\premieres

**Comment by Anarios** [comment]
Streams seem to be fixed too
