### ISSUE TITLE
Disproportionate Dislikes on a YouTuber

### ISSUE THREAD

**Issue by InklingGirl** [Anarios/return-youtube-dislike#1063]
### Have you tried to find similar issues (open or recently closed)?

- [X] Yes, this issue is not a duplicate

### Browser

Brave Browser

### Browser Version

1.67.134 Chromium: 126.0.6478.186 (Official Build) (64-bit) 

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.16

### Video link where you see the problem

https://www.youtube.com/watch?v=0KSbMU0_uLo

### What happened?

The channel _Redeemed Zoomer_ has a disproportionate, implausible amount of dislikes reported, which the channel has contradicted: https://www.youtube.com/channel/UCiLqiXa5O85APUBQV7X5w9Q/community?lb=UgkxQy9YhD-yN0qf5dIxl5aegXxrSyYifmSN
![dislikes](https://github.com/user-attachments/assets/f91192d7-3adc-455a-a434-cb4e4c396776)

### How to reproduce/recreate?

Go to any of _Redeemed Zoomer_'s videos.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Anarios** [comment]
I see some suspicious activity there, probably botting, thanks for the report, I'll investigate.

**Comment by InklingGirl** [comment]
Thanks, there's no question.

**Comment by Tali64** [comment]
This situation makes me wonder if we can improve the dislike estimations; the current system, while it gets the job done, can be biased especially when extension users' like to dislike ratio is far off from the actual ratio. Obviously, allowing creators to submit their own dislike counts as has been requested quite a bit in the past would mostly fix this, but that can't be the only thing we can do to improve the dislike count.

**Comment by InklingGirl** [comment]
> can be biased especially when extension users' like to dislike ratio is far off from the actual ratio

In this case it's worse than that, the extension is reporting more dislikes than are even possible to have disliked it period, as far as I can tell.

> allowing creators to submit their own dislike counts as has been requested quite a bit in the past would mostly fix this

This works, but could be susceptible to bad actors at some point.

**Comment by Anarios** [comment]
Detected some botting activity on that channel, looks like he's acquired some haters who spent serious amount of time into affecting dislike counts on his videos.

And due to the channel being relatively small sized - I didn't catch it fast enough. My apologies to the channel owner.

Most of the videos have significantly improved scores now.

And thanks again for the report.

![image](https://github.com/user-attachments/assets/20ffc436-5d73-4854-9f61-7673d6f5840c)

**Comment by Tali64** [comment]
Quite a few other videos on the channel have like-to-dislike ratios under 50%: [https://www.youtube.com/watch?v=bsfVWiu0GsA](https://www.youtube.com/watch?v=bsfVWiu0GsA) [https://www.youtube.com/watch?v=9NlZRc5oKUc](https://www.youtube.com/watch?v=9NlZRc5oKUc) [https://www.youtube.com/watch?v=MpxzjuzSNIw](https://www.youtube.com/watch?v=MpxzjuzSNIw) [https://www.youtube.com/watch?v=9XTXAonu5Ho](https://www.youtube.com/watch?v=9XTXAonu5Ho) [https://www.youtube.com/watch?v=D8s2TDoSc00](https://www.youtube.com/watch?v=D8s2TDoSc00) - this shows why verifying that the data is accurate is important, if these scores are botted as well. Implementing the ability for creators to submit their own dislike counts would help greatly and would be a feature I'd use if I were a content creator.

**Comment by Anarios** [comment]
@Tali64 it's cache, these videos have normal scores too - just takes some time.

![image](https://github.com/user-attachments/assets/d4a4e082-0629-49b5-97b6-99d6e599b4d1)

**Comment by Tali64** [comment]
Alright then.
