### ISSUE TITLE
Option to hide pescy YT info banner

### ISSUE THREAD

**Issue by ScruffR** [Anarios/return-youtube-dislike#1065]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Not sure whether this fits into this extension, but I do dislike these patronizing info banners about "C19", "climate", ...
Hence I'd like to see an option to hide these.

### Ways to implement this!

This should be possible by simply slapping a "hidden" attribute into the <div id="clarify-box" ...> tag

### Can you work on this?

- [ ] Yes
- [X] No

### Will you be available for follow-up questions to help developers implement this?

Yes

**Comment by Anarios** [comment]
Not in the scope of this extension. Should be fixable with adblockers - probably uBlock origin has a rule list for these
