### ISSUE TITLE
Dislikes Not Working for ReVanced / ReVanced Extended

### ISSUE THREAD

**Issue by 03bgood** [Anarios/return-youtube-dislike#1070]
### Have you tried to find similar issues (open or recently closed)?

- [ ] Yes, this issue is not a duplicate

### Browser

N/A

### Browser Version

N/A

### Extension or Userscript?

N/A

### Extension/Userscript Version

N/A

### Video link where you see the problem

N/A

### What happened?

Both RV and RVX don't show dislikes. RV says "Dislikes not available (Status 500)"

### How to reproduce/recreate?

Happens on any video

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by TayMcKenzieNZ** [comment]
I believe Google / YouTube have changed something on their end to purposely break it, this also comes after the whole MrBeast dislike bombing that happened recently... It was working fine yesterday now suddenly, doesn't... Very suspicious, though could just be a UI change with youtube, as this issue has happened before in Oct 2023.

**Comment by Anarios** [comment]
Server was down, all good now.
