### ISSUE TITLE
Return dislike extension not working on youtube.com (07.08.2024)

### ISSUE THREAD

**Issue by VulpesMayori** [Anarios/return-youtube-dislike#1072]
### Have you tried to find similar issues (open or recently closed)?

- [X] Yes, this issue is not a duplicate

### Browser

Microsoft Edge for Business

### Browser Version

127.0.2651.86

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.16

### Video link where you see the problem

https://www.youtube.com/watch?v=BMOIvar57vs

### What happened?

The dislike counter is not showing up at all. It's like the extension was removed.

### How to reproduce/recreate?

All YouTube videos.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Dharengo** [comment]
Having the same issue.

**Comment by TayMcKenzieNZ** [comment]
I believe Google / YouTube have changed something on their end to purposely break it, this also comes after the whole MrBeast dislike bombing that happened recently... It was working fine yesterday now suddenly, doesn't... Very suspicious, though could just be a UI change with youtube, as this issue has happened before in Oct 2023.

**Comment by MartinEesmaa** [comment]
Well, it received 502 Gateway Error which is made too much request causing crash for an unknown reason...
It wasn't extension problem, but it was API problem.

![youtubereturndislikeapigatewayerror](https://github.com/user-attachments/assets/1bc41ce9-f1c9-4003-85ad-778920f99d48)

- Martin Eesmaa

**Comment by darkmarauder97** [comment]
Same here. I'm on Firefox v129.0.

Using extension version 3.0.0.16

**Comment by squillzzz** [comment]
at first it showed the dislikes, just the bar was centered and it said 0 dislikes. now it looks just like the normal youtube version/disabled extension.

**Comment by MartinEesmaa** [comment]
now its back

**Comment by Dharengo** [comment]
Huh, it's back for me too. What's going on?

**Comment by MartinEesmaa** [comment]
> Huh, it's back for me too. What's going on?

The owner server of VPS may be rebooted or the Cloudflare server.

- Martin Eesmaa

**Comment by squillzzz** [comment]
sweet.

**Comment by TayMcKenzieNZ** [comment]
Also working for me. Thanks for the heads up, Martin!

**Comment by Anarios** [comment]
Server was down, all good now.
