### ISSUE TITLE
Return YouTube Dislike is damaged today

### ISSUE THREAD

**Issue by gigigigi53** [Anarios/return-youtube-dislike#1093]
### Have you tried to find similar issues (open or recently closed)?

- [x] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

Chrome v129.0.6668.90

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.17

### Video link where you see the problem

https://www.youtube.com/watch?v=BbrRWwMKea0

### What happened?

Today, October 8th, 2024, Return YouTube Dislike just got damaged and it seems creepy (because it's October, jokes aside)...
Only the button and not the counter is shown:
![image](https://github.com/user-attachments/assets/3433b808-3d55-47a2-97c1-50dbff74ebca)

### How to reproduce/recreate?

So you open YouTube, then do anything to open the video (whether it's a link, search result or from channel), and you see the dislikes are not visible (right now).

That happens to certain videos though.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

No

**Comment by IronClaw99** [comment]
Having the same issue. Hope this gets fixed soon.

**Comment by Pentazer** [comment]
This

**Comment by ENTPRESTIGIOUS** [comment]
Same on Firefox/LibreWolf

**Comment by Quicksilver151** [comment]
Same issue (firefox)

looks like youtube updated its ui again

**Comment by Mouadabdelghafouraitali** [comment]
The API itself is down : 

![image](https://github.com/user-attachments/assets/ed26e094-1d64-4b4b-ad34-ba562bca4171)

**Comment by mafen** [comment]
i get this in my console 
![image](https://github.com/user-attachments/assets/e82df6ab-5ae1-4025-9df2-c36b42792490)

**Comment by Ate329** [comment]
Same issue with Firefox 131.0 (64-bit) running on NixOS 24.11

**Comment by Anarios** [comment]
Building index on DB, caused some downtime. Will be up in ~30 minutes.

**Comment by gigigigi53** [comment]
> The API itself is down :
> 
> ![image](https://private-user-images.githubusercontent.com/24398682/374703656-ed26e094-1d64-4b4b-ad34-ba562bca4171.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTk1NTgsIm5iZiI6MTcyODQxOTI1OCwicGF0aCI6Ii8yNDM5ODY4Mi8zNzQ3MDM2NTYtZWQyNmUwOTQtMWQ2NC00YjRiLWFkMzQtYmE1NjJiY2E0MTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDIwMjczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZmEwYjc2NGJhOWE5ODQ3MzA1MDE5YjhlMGNlYTdiMWY5NjYxNmRmNDkxNGFjMjk1NDM0YmVjN2MyMGZlY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VPN_1Emkw5vAChInztkdoVKTmMpZX8Fj5a-owQRIiKw)

ok :( I can wait

**Comment by gigigigi53** [comment]
> > The API itself is down :
> > ![image](https://private-user-images.githubusercontent.com/24398682/374703656-ed26e094-1d64-4b4b-ad34-ba562bca4171.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTk1NTgsIm5iZiI6MTcyODQxOTI1OCwicGF0aCI6Ii8yNDM5ODY4Mi8zNzQ3MDM2NTYtZWQyNmUwOTQtMWQ2NC00YjRiLWFkMzQtYmE1NjJiY2E0MTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDIwMjczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZmEwYjc2NGJhOWE5ODQ3MzA1MDE5YjhlMGNlYTdiMWY5NjYxNmRmNDkxNGFjMjk1NDM0YmVjN2MyMGZlY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VPN_1Emkw5vAChInztkdoVKTmMpZX8Fj5a-owQRIiKw)
> 
> ok :( I can wait

"Please try again in a few minutes."? MORE LIKE HOURS, DAYS, WEEKS, MONTHS, YEARS, DECADES, CENTURIES, MILLENIALS OR FOREVER!!

**Comment by gigigigi53** [comment]
> Building index on DB, caused some downtime. Will be up in ~30 minutes.

Alright

**Comment by Pikamander2** [comment]
> Building index on DB, caused some downtime. Will be up in ~30 minutes.

It's been 31 minutes and it's still down. Anyone wanna join my class action suit?

**Comment by Anarios** [comment]
> Anyone wanna join my class action suit?

I'm safe due to ~ sign.

**Comment by MickCasanova** [comment]
Same issue here on Firefox...

**Comment by angrybird121** [comment]
same issue with vivaldi

**Comment by rphlmm** [comment]
> Building index on DB, caused some downtime. Will be up in ~30 minutes.

What's up? Any problem? @Anarios

**Comment by ImpenetrableNoble** [comment]
I've been having the same issue through my android smartphone as well. So I agree I think the API server is probably down.

**Comment by IronClaw99** [comment]
> Building index on DB, caused some downtime. Will be up in ~30 minutes.

It's been over two hours and it's still down. Any updates?

**Comment by ENTPRESTIGIOUS** [comment]
Still down.

**Comment by Anarios** [comment]
![image](https://github.com/user-attachments/assets/00baa0f6-16e1-42d4-b127-6d19e5fe1c63)

**Comment by TigerBears-111** [comment]
Also got the same issue.

**Comment by kushmittal2009** [comment]
Same issue, Entire Api is still offline

**Comment by cesar738** [comment]
having the same issue, refreshed a youtube webpage and it just disappeared

**Comment by NicoTheCinderace** [comment]
> > Anyone wanna join my class action suit?
> 
> I'm safe due to ~ sign.
> 
> It's like Musk saying that he hopes that full self driving will work next year. For 10 years.


Hey, Any updates? It's been down all day.

**Comment by Anarios** [comment]
> > > Anyone wanna join my class action suit?
> > 
> > 
> > I'm safe due to ~ sign.
> > It's like Musk saying that he hopes that full self driving will work next year. For 10 years.
> 
> Hey, Any updates? It's been down all day.

Waiting as fast as I can.

**Comment by taxmeifyoucan** [comment]
Just joining the wait here guys, hope you've been waiting well

**Comment by 03bgood** [comment]
Even if Neal Mohan's pathetic ass resigns one day, it won't matter because someone else worse than him and Susan will come along and continue to ruin YouTube, instead of trying make a better.

**Comment by 42useGitHub** [comment]
I'm dying can't see dislikes : (

**Comment by thepwrtank18** [comment]
the conspiracy theorists are conspiracy theorizing: https://x.com/LiberalHivemind/status/1843736094434832840

**Comment by cesar738** [comment]
> Building index on DB, caused some downtime. Will be up in ~30 minutes.

bro, its been 5 HOURs

**Comment by cesar738** [comment]
just checked the api website, got a 404

**Comment by CandorEl** [comment]
as far as I'm aware this only works if Youtube keeps the Dislikes accessible in the API, if they change that you can never get Dislikes again

**Comment by Moosyu** [comment]
> as far as I'm aware this only works if Youtube keeps the Dislikes accessible in the API, if they change that you can never get Dislikes again

they removed that like years ago dude its just estimating now

**Comment by zerobit97** [comment]
I have the same problem

**Comment by As0mn** [comment]
I don't know how much longer I can last without dislikes.

**Comment by cesar738** [comment]
> I don't know how much longer I can last without dislikes.

ya not alone buddy
😔

**Comment by beepbeepbean** [comment]
i'll be on the lookout over the next few days/weeks for this to be fixed
at least it's not as actively annoying as when youtube decided to put the comments on the right and the recommended videos on the bottom for some reason

**Comment by susbaconhairman** [comment]
I'm having the same issue on Firefox 131.

**Comment by cesar738** [comment]
im dying without dislike
i just wanna see if 2018 yt rewind got more dislikes

**Comment by mfcummings** [comment]
Missing my dislikes on Brave [Version 1.70.123 Chromium: 129.0.6668.89 (Official Build) (64-bit)]
and Chrome Version 129.0.6668.90 (Official Build) (64-bit)

**Comment by AdobeFan16** [comment]
I'm having the same issue as well

**Comment by DhihanA** [comment]
Gee wilkers I sure do hope this gets fixed soon tyty

**Comment by ThePip** [comment]
Hi... I have used this lovely extension for a long time, and was horrified to see no dislike count today... using firefox here. I see people are waiting very actively here, just thought I would jump on to say thank you very much for the extension, I love it. I too hope it comes back soon, but I just thought maybe an appreciative user saying thanks might give you a smile. Best of luck getting the api back up, you got this.

**Comment by geekercz** [comment]
Brave - same issue.

**Comment by Anarios** [comment]
We're back.

**Comment by MickCasanova** [comment]
Yay!! Same here, working again.

**Comment by cesar738** [comment]
works!!!

**Comment by ENTPRESTIGIOUS** [comment]
yep it works again! POG!

**Comment by mfcummings** [comment]
Woohoo! Up again! who woulda thunk the "Thumbs Down" would be so meaningful, a real Populist Vote.

**Comment by mrkrabs206** [comment]
It's back

**Comment by AdobeFan16** [comment]
Finally, Return YouTube Dislike is now working again
________________________________
De: mrkrabs206 ***@***.***>
Enviado: miércoles, 9 de octubre de 2024 7:10
Para: Anarios/return-youtube-dislike ***@***.***>
Cc: AdobeFan16 ***@***.***>; Comment ***@***.***>
Asunto: Re: [Anarios/return-youtube-dislike] Return YouTube Dislike is damaged today (Issue #1093)


And 69 likes
