### ISSUE TITLE
"Like button" voice trigger animation causes dislikes to disappear

### ISSUE THREAD

**Issue by cpguy5089** [Anarios/return-youtube-dislike#1104]
### Have you tried to find similar issues (open or recently closed)?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

Chrome 130.0.6723.117

### Extension or Userscript?

Userscript

### Extension/Userscript Version

3.1.4

### Video link where you see the problem

https://www.youtube.com/watch?v=obX2WdINsZo

### What happened?

With the semi-newish youtube feature that causes things to get a glowy outline when certain things are said (ie "subscribe" and "like button"), if the like button section lights up it causes the dislike counter to disappear.

### How to reproduce/recreate?

View any video that will cause the like button to get highlighted - For example https://www.youtube.com/watch?v=obX2WdINsZo - The counter will get the glow as normal, but the dislike counter will vanish after the animation finishes.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by jpa102** [comment]
maybe try [updating the userscript version to 3.1.5](https://github.com/Anarios/return-youtube-dislike/blob/main/Extensions/UserScript/Return%20Youtube%20Dislike.user.js) and see if it fixes the issue

**Comment by cpguy5089** [comment]
Had no idea there was an update, looks like it fixed it.
