### ISSUE TITLE
YouTube Dislikes stopped working. (11/29/24)

### ISSUE THREAD

**Issue by NicoTheCinderace** [Anarios/return-youtube-dislike#1106]
### Have you tried to find similar issues (open or recently closed)?

- [x] Yes, this issue is not a duplicate

### Browser

Firefox

### Browser Version

Version 133.0 

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.18

### Video link where you see the problem

https://www.youtube.com/watch?v=6vjG34uyPz0

### What happened?

YouTube Dislikes stopped showing up.

### How to reproduce/recreate?

Watch a video.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

![Here we go again 2](https://github.com/user-attachments/assets/96694a2c-f537-4467-93e7-7745ddfdf2ab)

**Comment by NicoTheCinderace** [comment]
Looks like the API itself is down. Trying to reach the API website returns nothing.

**Comment by IronClaw99** [comment]
Same issue.

**Comment by NicoTheCinderace** [comment]
> Same issue.

Yeah, I checked the API's website. Currently dead. Need to wait for @Anarios to fix this.

**Comment by Snowy-Fluffy** [comment]
same

**Comment by NicoTheCinderace** [comment]
Looks like it's been fixed. Will be closing this issue.
