### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [Anarios/return-youtube-dislike#1109]
### Have you tried to find similar issues (open or recently closed)?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

130.0.6723.117 (Official Build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.18

### Video link where you see the problem

*

### What happened?

The API is down right now.

![image](https://github.com/user-attachments/assets/9d65aa7b-8ce8-488e-a7e6-65ac92c91e9d)

### How to reproduce/recreate?

The API is down right now.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by HydeYYHH** [comment]
Same issue.

**Comment by IronClaw99** [comment]
Same here.

**Comment by IronClaw99** [comment]
Hopefully @Anarios can look into this.

**Comment by Mouadabdelghafouraitali** [comment]
Solved !

**Comment by Anarios** [comment]
Ran out of space for DB. Over 7TB now :'(
