### ISSUE TITLE
(Feature Request): Access to api dislike count past December 13th

### ISSUE THREAD

**Issue by MrRobinhq** [Anarios/return-youtube-dislike#111]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Did you look into possibilities of accessing the dislike count past December 13th? There is an option to apply for an api extension that would give you access to dislikes, but you probably can't use it to share that data with 3rd parties. However, I can't imagine that there will be no leaked data, so maybe its worth it to look into this when the time comes.

### Ways to implement this!

Find an api that doesn't give af about googles terms & conditions

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by DARKDRAGON532** [comment]
Nah, no more accurate and real dislike counts after 13th
