### ISSUE TITLE
(Feature Request): This is not 100% related to the project

### ISSUE THREAD

**Issue by xSpecialFoodx** [Anarios/return-youtube-dislike#113]
### Extension or Userscript?

Both

### Request or suggest a new feature!

soon the api will get changed most likely.
i thought that it would be great to have a database for all the dislikes in the videos in youtube, so that in future when the api gets disabled the database will get used as an extension.
soon there will be no way to create such a database.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by DARKDRAGON532** [comment]
https://tracker.archiveteam.org/youtube-dislikes/

**Comment by xSpecialFoodx** [comment]
> https://tracker.archiveteam.org/youtube-dislikes/

is there a way i can contribute

**Comment by DARKDRAGON532** [comment]
> =================================== HOW TO HELP ===================================
> 
> === Installation
> Head over to https://www.virtualbox.org/wiki/Downloads and choose the one for your operating system:
> For Windows its https://download.virtualbox.org/virtualbox/6.1.30/VirtualBox-6.1.30-148432-Win.exe
> For Mac its https://download.virtualbox.org/virtualbox/6.1.30/VirtualBox-6.1.30-148432-OSX.dmg
> For Linux Distros check https://www.virtualbox.org/wiki/Linux_Downloads
> Run and install the application you have downloaded.
> === Setup
> Next click here to download the archiveteam warrior os for the virtual machine https://warriorhq.archiveteam.org/downloads/warrior3/archiveteam-warrior-v3-20171013.ova
> Run "Oracle VM VirtualBox" on your computer
> On the top left click "File > Import Appliance"
> Then choose the folder icon on the bottom right and select "archiveteam-warrior-v3-20171013.ova" where you downloaded it.
> Click next and continue the installation of the os with recommended settings.
> === OS
> Select the new VM in the left hand side and at the top click "Start" in green.
> Wait for the os to install all its dependencies until you are brought to a screen with "=== Archive Team Warrior===" Listed.
> Next leave the vm open and head over to your normal web browser and go to http://127.0.0.1:8001/ in the web browser.
> === Site Settings
> Head over to the settings page and choose a username to be listed as!
> Select the "Available projects" tab and click the  "Work on this project" button next to the "YouTube dislikes" project.
> Head over to the "Current project" tab to view all the work being done.
> === Finished
> Congratulations you are helping archive youtube dislikes from your own computer. 😄
>
