### ISSUE TITLE
(Feature Request): 

### ISSUE THREAD

**Issue by andre-merzky** [Anarios/return-youtube-dislike#118]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Please remove the toolbar icon.  It's yet another icon which eats up space and does not provide any functionality (which cannot be provided elsewhere).  Too many plugins add an icon for no good reason.  

Thanks for the extension! :-)

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by TimGels** [comment]
Fyi, if you are using Firefox, you can disable it showing on the toolbar.
