### ISSUE TITLE
(Feature Request): Dislike database

### ISSUE THREAD

**Issue by Dezzmeister** [Anarios/return-youtube-dislike#124]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Access to dislike counts will be removed on December 13th and as of writing this it seems like the plan is to use archived data and some statistics to provide a dislike estimate. My proposal is to build a separate backend that tracks each user's disliked videos. If you dislike/view/like a video, it is stored by this backend; if you view a video, you see statistics such as

- dislike/view ratio, calculated with dislikes and views stored by the backend. These will be less than or equal to the actual dislike and view counts stored by YouTube. With high enough views, this will approximate the actual dislike/view ratio.
- like/dislike ratio, calculated with disliked and likes stored by the backend. Again, with high enough views, this will approximate the actual like/dislike ratio.

I imagine that these statistics will approximate the true values over time as more people use the extension. I can build this feature for you, but I would like to know if you want it before I do such a thing.

### Ways to implement this!

We can implement this by investing in some cloud storage (I am most familiar with AWS; I have never used their database solutions before but some quick research suggests that DynamoDB or Aurora might be worth looking into.) We will need a database with User and Video entities at the very least. A user has a list of liked videos, a list of viewed videos, and a list of disliked videos. Inversely, a video has a list of users who viewed it, users who liked it, and users who disliked it. (With a relational database, these relationships can be modeled with join tables instead of bulky and inefficient "lists.") When a user views, likes, or dislikes a video, we update the database accordingly. When a user views a video, if the video already exists in the database, we fetch the view count, like count, and dislike count and display the dislike/view and like/dislike ratios on the page.

### Can you work on this?

- [X] Yes
- [ ] No

**Comment by niwla23** [comment]
That is already being discussed in #109

**Comment by Anarios** [comment]
Already bein done.
