### ISSUE TITLE
(Feature Request): Pale Moon Compatibility

### ISSUE THREAD

**Issue by Zorgodon** [Anarios/return-youtube-dislike#128]
### Extension or Userscript?

Userscript

### Request or suggest a new feature!

Is there any chance you could make the userscript compatible with Pale Moon/UXP Browsers (http://www.palemoon.org) ?

### Can you work on this?

- [ ] Yes
- [ ] No

**Comment by laughingsheep** [comment]
What part of the userscript doesn't work in Pale Moon?

**Comment by Zorgodon** [comment]
The error in the console is:
```
expected expression, got '.'          Return_Youtube_Dislike.user.js:28:7
```

Line 28: ` ?.querySelector("#top-level-buttons-computed");`

If I comment it out, I get the same error, now for 
Line 236: `if (getButtons()?.offsetParent && isVideoLoaded()) {`

It seems PM doesn't like the '?.' syntax, but unfortunately I don't know JS so I'm not sure what '?.' means.
The script doesn't log 'starting up' to the console as it's getting bogged down in what it thinks are errors in the function
definitions.
I'm using `Greasemonkey 3.31.4` by the way.

**Comment by laughingsheep** [comment]
The userscript is made for Tampermonkey as seen on the website https://www.returnyoutubedislike.com/install.
Can you use tampermonkey instead?

Btw, the ? in line 236 is part of Optional Chaining which is a feature introduced in 2020.

**Comment by Zorgodon** [comment]
Changing `.?` to `.` made it work.

According to [Mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), the latter returns an error rather than a string.

I don't see any errors in my console on PM or Chrome when running with the change, so I think this is a sensible patch to increase browser compatibility.

**Comment by Zorgodon** [comment]
Patch here (currently closed as it removes the hover stats feature that doesn't work in PM):
https://github.com/Anarios/return-youtube-dislike/pull/234
