### ISSUE TITLE
(kinda) Doesn't work on Edge

### ISSUE THREAD

**Issue by igorvereshch** [Anarios/return-youtube-dislike#13]
Hi, I've tried using your UserScript code in Tampermonkey on Microsoft Edge (version 95.0.1020.53 64-bit version) and it doesn't work.

Tried figuring out why it doesn't and discovered that getButtons() method returns component from wrong container
![have](https://user-images.githubusercontent.com/80777345/142604655-389ffba6-f25b-42a3-b006-9f039b3a5566.png)
That component is not displayed on screen, the displayed one is 
![want](https://user-images.githubusercontent.com/80777345/142606592-ab57ccd6-d58d-4c86-9746-eac9697d3858.png)

Changed id method getButtons() looks for from menu-container to actions-inner and everything works for me.

**Comment by Anarios** [comment]
Thanks, will check. And special thanks for investigation

**Comment by mphelp** [comment]
@igorvereshch You can use the chrome web store extension because edge is Chromium

**Comment by mphelp** [comment]
@Anarios please close eventually, thanks

**Comment by igorvereshch** [comment]
@mphelp thanks for the advice, completely forgot about that. @Anarios I'm closing this issue.
