### ISSUE TITLE
(Feature Request): Edge Add-on Store

### ISSUE THREAD

**Issue by dreaddr** [Anarios/return-youtube-dislike#132]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Include it in Microsofts Edge Add On store front as well. Adds diversity beyond just Google (parent company of YT) Chrome Store having the extension.

### Ways to implement this!

Publish it there

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by sy-b** [comment]
Go to Chrome Webstore & follow normal procedure.
"Edge", "Chrome" & many other browsers are based on "Chromium Project". Hence, their extensions are mostly cross compatible.

I confirm that  the extension is working on Edge after downloading from Chrome Webstore.

**Comment by dreaddr** [comment]
> Go to Chrome Webstore & follow normal procedure. "Edge", "Chrome" & many other browsers are based on "Chromium Project". Hence, their extensions are mostly cross compatible.
> 
> I confirm that the extension is working on Edge after downloading from Chrome Webstore.

Yes that works but what I'm asking for is the specific publication to the Edge Add-on store.

**Comment by win98se** [comment]
> What I'm asking for is the specific publication to the Edge Add-on store.

+1, some users may not prefer to install extensions from Chrome Web Store, hence this request.

**Comment by dftf-stu** [comment]
Hi @Anarios.  Just wondering if there's been any-more thought on adding your extension to the [Edge Add-Ons Store](https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home)?

Two reasons I'd suggest.

First: another extension in there is stealing your name and logo, obviously capitalising on the fact that users are looking for your extension, but as it's not there, they've taken your place:

![Image](https://github.com/user-attachments/assets/c6d69470-212d-4805-8a01-ad79bcc19bb1)

And their extension is less-safe, given it requests access to "data on all websites" 😲😬, not just YouTube-owned domains.

Second: other similar-extensions in the Edge Store have between them at-least ~115,000 downloads.  I'd suspect many of those may have become users of your extension, were it to have been available:

![Image](https://github.com/user-attachments/assets/ab104c78-0eb8-4e64-b731-e8fc9902be61)

And possibly third: were Microsoft ever to stop allowing add-ons from the Google Chrome store to be added, clearly that would then mean your one couldn't be used there.  Not aware of any plans for that currently, but you never know.  (I believe via the Group Policies for when Edge is managed by enterprises though, limiting to the Edge Add-Ons store and blocking Google's is possible.)

Thanks
