### ISSUE TITLE
(Feature Request): Getting additional dislike count from a specific comment(s)

### ISSUE THREAD

**Issue by WhiteSp1rit** [Anarios/return-youtube-dislike#135]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

If Youtube interferes with other ways to get the dislike count, maybe this idea can be used:

Scan comments under the video, and if a comment with the content "dislike" (written just like that, with no additional symbols or anything else in it, with case-insensitive comparison) is encountered, count the comment as 1 dislike, and all upvotes on it as additional dislikes for the video. 

That way users will always have the ability to dislike AND dislikes to be counted, as long as the comments are still enabled.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by Anarios** [comment]
Not very reliable, not looking in that direction for now.
