### ISSUE TITLE
(Feature Request): Store data on decentralized blockchain.

### ISSUE THREAD

**Issue by Originalimoc** [Anarios/return-youtube-dislike#138]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Independently store plugin users' like dislike count of specific video ID, preferably on decentralized storage Blockchain like IPFS, or Arweave(super cheap option given data is so small if encoded correctly, let's get a donation option?) 
Backend data structure: ($VideoID,$LikeClickedByPluginUsers, $LikeClickedByPluginUsers), then estimate dislike on the frontend upon loading.(already done?)

As long because all we need most is ratio, this will work pretty well down the line LONG TERM I think, if enough people using it.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by rdev** [comment]
This will get very expensive very quickly the more people use this extension

**Comment by LeoDog896** [comment]
https://gun.eco is a much better alternative instead.

**Comment by sy-b** [comment]
In my opinion, that might be a problem, when users want their data to be deleted.
If we store just the dislikes on blockchain, then - how will the users will be able to remove the dislike when they un-dislike the video?

If we store both Dislike and Un-Dislike counts, then its easy to vandalize this (by bloating it with loth of data) by programming both to continuously dislike & Un-dislike.

If a solution to this is available, then it maybe a right thing to do.

Any other reason(s) for doing this?

**Comment by SquirrelsMcGee** [comment]
Not everything has to involve a blockchain

For something as relatively simple as this project, which is effectively just an API for retrieving Dislikes for YouTube videos, a server-client model works perfectly well, and is better in many ways (as mentioned above)

Are there any real benefits that a blockchain provides that can't already be solved with a scalable server?

**Comment by rdev** [comment]
Yes, please stop trying to shove blockchain everywhere it doesn't belong 😬 
This type of extension is waaaaaaay better served by a conventional DB
If scaling becomes a problem, data can be easily migrated to any high scalability DB like Cosmos or Dynamo in the future. 
@sy-b's mutability concern is also valid
Blockchain is not only unneeded here, it's detrimental to the goal

**Comment by Originalimoc** [comment]
> Not everything has to involve a blockchain
> 
> For something as relatively simple as this project, which is effectively just an API for retrieving Dislikes for YouTube videos, a server-client model works perfectly well, and is better in many ways (as mentioned above)
> 
> Are there any real benefits that a blockchain provides that can't already be solved with a scalable server?

Simple reason: I just don't want this project has single point of failure.

**Comment by Originalimoc** [comment]
Maybe a regular public archive then?

**Comment by Originalimoc** [comment]
> Yes, please stop trying to shove blockchain everywhere it doesn't belong 😬
> This type of extension is waaaaaaay better served by a conventional DB
> If scaling becomes a problem, data can be easily migrated to any high scalability DB like Cosmos or Dynamo in the future.
> @sy-b's mutability concern is also valid
> Blockchain is not only unneeded here, it's detrimental to the goal

Any idea then? To prevent single point of failure. Fork doesn't count because that means users have to all migrate to a new plugin.

**Comment by sy-b** [comment]
> Any idea then? To prevent single point of failure. Fork doesn't count because that means users have to all migrate to a new plugin.

The forks access the same database unless modified to not do so.
If you are asking for database, then,

- Multiple backups (by better funding) is the only viable option right now.
- Trusted volunteers can be given access to download complete database as backups (in encrypted form).
But I doubt, that this isn't the right time for it.

This issue should be brought up again in future.
(maybe not as "decentralized blockchain", but more as for preventing data loss)
