### ISSUE TITLE
(Feature Request): Add a new improved metric

### ISSUE THREAD

**Issue by webian** [Anarios/return-youtube-dislike#139]
### Extension or Userscript?

Both

### Request or suggest a new feature!

The real problem is not that the number of dislikes has disappeared. The real problem is that a user can no longer presume the quality of a video at a glance.

Before the removal, we mentally made an approximate ratio between likes and dislikes:
- 1043 likes | 23 dislikes = good video
- 3M likes | 19M dislikes = YouTube Rewind 2018

But it is not said that there is not a better way.

Maybe a new metric, based on the various statistic data available for a video, can be introduced by this extension and this could be even better than the old like/dislike comparison.

I hope this thought comes in handy and thanks for the effort!

### Can you work on this?

- [ ] Yes
- [ ] No

**Comment by rdev** [comment]
What is the definition of a "real problem"? 🤔 
The purpose of the extension is stated in it's name 😅 
Like/Dislike is a good metric and it has worked for years. IMO additional metrics, whatever those might be, aren't and shouldn't be the scope of this extension

**Comment by rdev** [comment]
Bringing back dislikes restores the metric everyone knows and is used to, solving the quality judgement problem 🤔

**Comment by webian** [comment]
Nothing against. But I think that even if something has been around for a long time and people are used to, it can still be changed with something better.

**Comment by Anarios** [comment]
Sponsorblock are moving in that direction, you can have a look at them. We're going to stick with simple likes\dislikes for now
