### ISSUE TITLE
(Feature Request): Allows Archiving of YouTube Video Dislikes on Webpage

### ISSUE THREAD

**Issue by jackienailham97** [Anarios/return-youtube-dislike#148]
### Extension or Userscript?

Both

### Request or suggest a new feature!

I want to be able to have a page on the official webpage where users can archive video's dislikes for safe keeping for the future. This would allow users opt not to use the extension to save webpages or for people who use YouTube front-ends who have the YouTube link but prefer not to open the YouTube link in a browser that has the extension loaded.
The user can just go to a specific link on the webpage and enter the YouTube URL and hit a button on the site to save the page's dislike count.

### Ways to implement this!

We could have this feature implemented by having a page similar to web.archive.org/save but with saving YouTube links only.
There could be an indication of if this is the first time that a specific video link has been saved on the extension or archive or just a update to the dislike count. There can also be rate limiting for users who are sending in too many links such as hCaptcha/reCaptcha is desired, and the user does not need to register. There can be an indication on when the website sucessfully saved the dislike count.
This should be able to successfully used until the API's are shut down by YouTube, but after that, there can be more tweaks to just adjust to the new situation.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by sy-b** [comment]
Anything like that would only work till YouTube API allows.

A similar thing is being done here by the archive.org team. They are scraping dislikes from all YouTube videos
You can help them.
- Go to https://tracker.archiveteam.org/youtube-dislikes/ 
- Click on "Run your own ArchiveTeam Warrior"
- Follow the instructions there.
- It should be something like [this](https://www.youtube.com/watch?v=_nzD-QpmePE)

**Comment by JustAnotherArchivist** [comment]
For the record, ArchiveTeam is **not** affiliated with the Internet Archive aka archive.org, although we do upload virtually all our archived data there.

**Comment by sy-b** [comment]
> A similar thing is being done here by the archive.org team. They are scraping dislikes from all YouTube videos
You can help them.

If anyone needs a guide [here it is](https://sy-b.github.io/redirects/0/Setup-ArchiveTeam-Warrior-in-Virtual-Box).

**Comment by CreaZyp154** [comment]
Someone should close this issue now
