### ISSUE TITLE
url based comment plugin

### ISSUE THREAD

**Issue by mtemel123** [Anarios/return-youtube-dislike#15]
we need independent comment/like browser extension. channels and site owner changing or delete users comments. 
disqus.com is not easy every domain and url. 
what about think url based comment plugin?

**Comment by Anarios** [comment]
Comments might be integrated into this extension (for videos without comments) later. But it's not set in stone.

**Comment by SirLich** [comment]
I would vote heavily against this. There exists many such plugins already, and all of them have low activity rates. Lets focus on what we *can* deliver with high quality.

**Comment by Anarios** [comment]
Yeah, I was talking very distant future, after everything else is perfect and stable. This could come as a separate satelite-extension as well.

**Comment by DARKDRAGON532** [comment]
I agree with @SirLich, let's not focus too much on the distant future and focus more on the present, we need to make this extension more stable and have more users.

**Comment by laughingsheep** [comment]
Since this is only for showing Youtube dislike i would suggest closing this issue

**Comment by AidOnline01** [comment]
Although dislikes are top priority, issue with video owners deleting all comments with opposed opinion is still important. Scam or misleading videos can have naturally high positive like/dislike rate, but be, nevertheless, harmful for auditory. 
I really hope that in future this plugin will implement this feature, as it is gathering massive auditory.

**Comment by DARKDRAGON532** [comment]
Well I guess it's more of a possibility to make an independent commenting system, but first lets make the extension stable before branching off into different ideas.

**Comment by Frontesque** [comment]
not related to dislikes
