### ISSUE TITLE
(Bug): NAN Instead of Dislike Count

### ISSUE THREAD

**Issue by KendallDoesCoding** [Anarios/return-youtube-dislike#152]
### Browser

Google Chrome

### Browser Version

Fully updated Chrome

### Extension or Userscript?

Extension

### Extension/Userscript Version

Current Version on Chrome Web Store

### Video link where you see the problem

https://youtu.be/UgOkob1DKKo

### What happened?

A bug happened!

It's showing NAN, instead of dislike count.

**Comment by LaszloRobert** [comment]
Hello,

This bug was already reported https://github.com/Anarios/return-youtube-dislike/issues/142

**Comment by KendallDoesCoding** [comment]
> Hello,
> 
> This bug was already reported #142

Thanks for informing, will close this ticket
