### ISSUE TITLE
(Feature Request): 

### ISSUE THREAD

**Issue by McJoe21** [Anarios/return-youtube-dislike#154]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

https://youtube-links.github.io/links.json a list of YouTube channels and videos for you.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by daniel-pg** [comment]
I bet the URLs are not formatted properly in the .json file you sent, because none of them contain uppercase letters

**Comment by Frontesque** [comment]
this is from the [ArchiveTeam](https://github.com/ArchiveTeam). We are already using their service. You didn't need to open this as a feature request.
