### ISSUE TITLE
Add to README/FAQ on site that people can help scrape data via ArchiveTeam Warrior

### ISSUE THREAD

**Issue by LeggoMahEggo** [Anarios/return-youtube-dislike#157]
I only found the following by digging through the issues. I highly recommend adding this in places where people can easily see it - I would have missed it otherwise (currently running a warrior as I type this)

_Anything like that would only work till YouTube API allows.

A similar thing is being done here by the archive.org team. They are scraping dislikes from all YouTube videos
You can help them.
- Go to https://tracker.archiveteam.org/youtube-dislikes/ 
- Click on "Run your own ArchiveTeam Warrior"
- Follow the instructions there.
- It should be something like [this](https://www.youtube.com/watch?v=_nzD-QpmePE)_

_Originally posted by @sy-b in https://github.com/Anarios/return-youtube-dislike/issues/148#issuecomment-984485600_

**Comment by JustAnotherArchivist** [comment]
For the record, ArchiveTeam is **not** affiliated with the Internet Archive aka archive.org, although we do upload virtually all our archived data there.
