### ISSUE TITLE
[Documentation] Could a direct link to the installation site be added to the main README?

### ISSUE THREAD

**Issue by rubyFeedback** [Anarios/return-youtube-dislike#160]
Could a direct link to the installation site be added to the main README?

I think this would be convenient so people can just click; sometimes if you
search via google you find odd results or similarly named results, which is
why such a direct link may be useful.

Edit: Oh I see, the homepage mentions it and has a download button. I sort
of expected this to be at mozilla; perhaps that could be clarified where the
 user should then install it though.

**Comment by PickleNik** [comment]
> Could a direct link to the installation site be added to the main README?
> 
> I think this would be convenient so people can just click; sometimes if you search via google you find odd results or similarly named results, which is why such a direct link may be useful.
> 
> Edit: Oh I see, the homepage mentions it and has a download button. I sort of expected this to be at mozilla; perhaps that could be clarified where the user should then install it though.

https://returnyoutubedislike.com/install
I'm not sure I understand the question, could you clarify?

**Comment by PickleNik** [comment]
People usually come from the website to Github, not the other way around. 👾
