### ISSUE TITLE
(Website Addition): Add XMR donation method

### ISSUE THREAD

**Issue by cheeseyfish** [Anarios/return-youtube-dislike#163]
Add Monero to the donations page on the website. This allows users to support the project without KYC.

**Comment by PickleNik** [comment]
> Add Monero to the donations page on the website. This allows users to support the project without KYC.
![monero](https://user-images.githubusercontent.com/31113245/144724721-07c28616-07cb-429d-9da8-68db9b416b63.png)

Should be added to the website soon I assume

**Comment by Anarios** [comment]
I'll do it.
