### ISSUE TITLE
(Feature Request): Add donation links on homepage & in extension

### ISSUE THREAD

**Issue by sy-b** [Anarios/return-youtube-dislike#167]
### Request or suggest a new feature!

We want more people to fund this. right?
So, make it easy for people to find those links.

**Edit:**

Like this

![Return YouTube Dislike _ suggested page (#167)](https://user-images.githubusercontent.com/94835959/144621967-e95640df-7fab-4c52-911e-366d9459b7b1.png)

**Comment by Shigetorum635** [comment]
Website side already has it:
https://returnyoutubedislike.com/donate

Extension should have it though.

**Comment by sy-b** [comment]
I meant the link on home page, not on a separate page. (like install button)

For normal people that big install button is the only thing they'll pay attention to.
Also the beautifully designed, the page isn't having much to show.

When project gets enough funding, it can be moved to a separate page (as it is now).

**Comment by PickleNik** [comment]
<img width="393" alt="Screen Shot 2021-12-04 at 4 25 10 PM" src="https://user-images.githubusercontent.com/31113245/144725013-1cd7947a-d87b-4e9c-b0d2-02c8a5f5b988.png">

**Comment by sy-b** [comment]
👍
