### ISSUE TITLE
(Bug): Dislike ratio persists between youtube videos

### ISSUE THREAD

**Issue by lilblizzard** [Anarios/return-youtube-dislike#169]
### Browser

Firefox

### Browser Version

94.0.2 (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.0

### Video link where you see the problem

https://streamable.com/vxw9nn

### What happened?

A video with no dislikes is played. Then, the user goes to a new video that has dislikes. If the user returns to the first video, the dislike ratio from the second persists.

**Comment by Stef16Robbe** [comment]
Can't reproduce anymore on Firefox, I think this issue has been fixed. Could you check again?
