### ISSUE TITLE
(Bug): Locale Number Formatting comma

### ISSUE THREAD

**Issue by Pdzly** [Anarios/return-youtube-dislike#170]
### Browser

Google Chrome

### Browser Version

Chrome Version 96.0.4664.45 (Offizieller Build) (64-Bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

newest

### Video link where you see the problem

https://www.youtube.com/watch?v=4Ir7e_3JOwM

### What happened?

The dislike count is a comma number 

<img width="159" alt="image" src="https://user-images.githubusercontent.com/34943569/144639487-2083d047-0f5a-4470-9e5b-01ddc8a9be60.png">

**Comment by DARKDRAGON532** [comment]
That is due to your language's number formatting. Will add an option to fix though.

**Comment by Frontesque** [comment]
This is a known issue. This has to due with your browser's locale being different from youtube's.

**Comment by Pdzly** [comment]
Ok 👍🏼
