### ISSUE TITLE
(Bug): Dislike counter doesn't get updated after page refresh

### ISSUE THREAD

**Issue by code-hero-projects** [Anarios/return-youtube-dislike#173]
### Browser

Google Chrome

### Browser Version

96.0.4664.45

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.0

### Video link where you see the problem

https://www.youtube.com/watch?v=NlW0A5LjY74&ab_channel=Ludwig

### What happened?

This happened on the video that I linked but you can check the bug at any video which still didn't hit 1K dislikes.

I don't know if this is the intended behavior or not, but I pressed the dislike button on a video, the counter went up but on page refresh the counter stayed the same as it was before the dislike button press. I'll leave some images down below.

Before pressing the dislike:
![before-pressiong-dislike](https://user-images.githubusercontent.com/91946848/144670667-ad72d4ab-133c-4685-9f31-da72035952ba.png)

After pressing the dislike:
![after-pressing-dislike](https://user-images.githubusercontent.com/91946848/144670693-f232838b-f18d-4acb-81fa-a9876b50818c.png)

After reloading the page;
![after-reload](https://user-images.githubusercontent.com/91946848/144670711-a81a685d-3f63-4b19-b501-4b6fae75fe18.png)

Shouldn't the counter be incremented after the page is reloaded?

**Comment by cyberrrr** [comment]
Possibly +1 to the estimated dislike count on the client side if the user has disliked the video

**Comment by avinashjsap** [comment]
This is a temporary situation because the dislike count is calculated based on the average rating.
After disliking the video, the average rating is not updated immediately. So when you refresh, the newly calculated dislike is also the same as the old one. It might take few hours to reflect

**Comment by code-hero-projects** [comment]
alright, thanks for the quick response, keep on the awesome work!
