### ISSUE TITLE
(Bug): Liking and disliking a video back and forth increases the number next to the dislike button

### ISSUE THREAD

**Issue by 5h3i1ah** [Anarios/return-youtube-dislike#174]
### Browser

Google Chrome

### Browser Version

96.0.4664.45 (64 bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.0

### Video link where you see the problem

https://www.youtube.com/watch?v=Pl6gUYq-oxY (though it also happens on any other video)

### What happened?

When alternating between Like and Dislike, the number displayed next to the Dislike button does not decrease when you click Like but still increases when you click back on Dislike. This allows you to increment the counter indefinitely on your screen. Un-disliking without Liking appropriately subtracts 1 from the displayed Dislike count. This bug does not affect the Like/Dislike bar or the hover-over Like/Dislike display.
![image](https://user-images.githubusercontent.com/17099837/144675120-2151dbf9-b46d-49ab-9146-8ddc0ee523cf.png)

**Comment by Frontesque** [comment]
Ill look into this
