### ISSUE TITLE
Firefox fork compatibility

### ISSUE THREAD

**Issue by spamman63** [Anarios/return-youtube-dislike#177]
The addon only works on newer version mainline firefox, but it doesn't work on Basilisk, PaleMoon or Waterfox Classic. Could it be made to work with these older firefox versions?

**Comment by Frontesque** [comment]
It only works for the new firefox because it's what is currently maintained by Mozilla. If you want to use it on the older versions, you can just use the Userscript. We are trying to maintain as few extensions as possible.
