### ISSUE TITLE
(Feature Request): allow using ones own yt api account to constantly fetch dislike count

### ISSUE THREAD

**Issue by 123234345434543454545456** [Anarios/return-youtube-dislike#179]
### Extension or Userscript?

Both

### Request or suggest a new feature!

title says all

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by Frontesque** [comment]
This is impossible with the current way that the plugin works. The data isn't fetched by the extension, it is fetched by our servers and reported back to you. There also isn't really a use for this as the youtube API is discontinued in 9 days.
