### ISSUE TITLE
Display exact likes/dislikes count

### ISSUE THREAD

**Issue by iamtakingiteasy** [Anarios/return-youtube-dislike#18]
Before removing dislikes, youtube was displaying exact (to integer) number of likes/dislikes when ratio bar was hovered.

**Comment by DARKDRAGON532** [comment]
Which version are you using?

**Comment by iamtakingiteasy** [comment]
v0.0.0.4 in extension form, 80.0.4170.63 chrome/opera, latest at the moment, with ratio bar first introduced. Ratio bar itself has no tooltip with exact numbers, buttons have tooltips with suggesting text only: "I like this" / "I dislike this".

**Comment by Anarios** [comment]
Good point, exact numbers will be added.
