### ISSUE TITLE
(Bug): 

### ISSUE THREAD

**Issue by yodaluca23** [Anarios/return-youtube-dislike#181]
### Browser

Opera GX

### Browser Version

LVL 3 (core: 81.0.4196.61)

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.0

### Video link where you see the problem

https://www.youtube.com/watch?v=bxn8yTOvJBM

### What happened?

The Dislike button does not show up in the comments still.

**Comment by DavidSaguna** [comment]
The dislike button for comments isn't even supposed to show up. We are only archiving video dislikes, not comment dislikes.
