### ISSUE TITLE
(Feature Request & bug): Website page with yoomoney acts weird

### ISSUE THREAD

**Issue by DavidSaguna** [Anarios/return-youtube-dislike#185]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

I'd like to make you aware that the yoomoney page with the white box has 2 issues (on the website https://returnyoutubedislike.com/pay/yoomoney): 

1. Not centered on the middle
2. Seems kind of blurred and small (photo below)

![Screenshot_152](https://user-images.githubusercontent.com/51415612/144706983-93749d93-d184-490a-a490-a60a2f3264b3.png)

As you can see, the part where you are supposed to pay has the issues while the rest of the website is aligned correctly and not blurry. 

### Ways to implement this!

Maybe check if the alignment is good and about the blurry part I'm not very sure.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by PickleNik** [comment]
Solved in #175 , feel free to close this
@Frontesque 
@Anarios
