### ISSUE TITLE
We need to build a database saving youtube dislikes of existing videos before the 13th december!

### ISSUE THREAD

**Issue by LifeIsStrange** [Anarios/return-youtube-dislike#187]
### Extension or Userscript?

external but the DB would be used by the extension.

### Request or suggest a new feature!

Basically it would be a key value store having for key e.g the video url and as value the last recorded dislike count.
One would need to scrap all of youtube videos ideally.
If this is not done, all existing dislike data since the creation of youtube will be lost, forever.

### Ways to implement this!

no id about how to exhaustively scrap youtube public videos.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by DavidSaguna** [comment]
This is already what we are doing. Check [this](https://tracker.archiveteam.org/youtube-dislikes/#show-all) for details and how you can contribuite

**Comment by LifeIsStrange** [comment]
Amazing, you are modern heroes!
How many percents of YouTube videos do you think will be indexed in it before the 13th December?

**Comment by DavidSaguna** [comment]
Well we archive the popular ones first, and then the remaining ones if we have time. The system is based on people's watch history if they like to share it, it will go in a database and computers will use computing power to see how many dislikes are there and to archive them. Logic: Less populat videos = less people watching = less chances of it getting archived.

Rn we done about  2.33B videos. Best case there are 30B videos and the most possible and reasonable is about 89B videos as I heard from someone. You can check the progress for yourself at the link above :)

**Comment by DavidSaguna** [comment]
The percent depends but i think we will get the important videos for sure
