### ISSUE TITLE
(Bug): Ratio bar not rendering correctly with zero dislikes

### ISSUE THREAD

**Issue by Craftplorer** [Anarios/return-youtube-dislike#188]
### Browser

Brave Version 1.32.113 

### Browser Version

Chromium: 96.0.4664.45

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.0

### Video link where you see the problem

https://www.youtube.com/watch?v=wE2YNLDYIAw

### What happened?

On the video with zero dislikes the ratio bar is shown as 50%.
Only when disliking the video the ratio bar is rendered correctly.
See Screenshots.
![zero](https://user-images.githubusercontent.com/5890132/144712618-c84fefca-ae66-4e59-b52a-26d024ca4a6c.PNG)
![one](https://user-images.githubusercontent.com/5890132/144712620-d12431ba-3b16-4c73-830e-f94ec758d6ad.PNG)

**Comment by DavidSaguna** [comment]
Can reproduce too.

**Comment by Craftplorer** [comment]
Looks like this is a problem with the YouTube API and how often its updated.

**Comment by MarcelRobitaille** [comment]
@Craftplorer what makes you say that? Smells to me like bad ratio math not handling division by zero properly.

**Comment by Craftplorer** [comment]
> @Craftplorer what makes you say that? Smells to me like bad ratio math not handling division by zero properly.
@MarcelRobitaille 
`  const widthPercent =
      likes + dislikes > 0 ? (likes / (likes + dislikes)) * 100 : 50;`
I looked at the code. No problem with division by zero here. 
The video I linked was recently published and the YouTube API was returning zero likes/dislikes so the code was defaulting to 50%. Seems like the YouTube API takes some time to update the likes/dislikes.

**Comment by MarcelRobitaille** [comment]
Hm that's weird. likes > 0 and dislikes == 0 should be 100 IMO

**Comment by Craftplorer** [comment]
> Hm that's weird. likes > 0 and dislikes == 0 should be 100 IMO

It is. But the extension uses the API response to render the ratio bar. And if the API response deviates from the like count displayed on the YouTube website we end up in this situation. So basically the Extension "sees" something different as the user. 
Taking the like count from the website would not work because then the ratio might be incorrect as the website and API are updated differently.

**Comment by MarcelRobitaille** [comment]
It uses the API response to render the dislike count and the ratio bar. I don't get how things are getting out of sync as you say. The ratio should just be a derived property of likes and dislikes. I don't see how it would get out of sync if the likes and dislikes are up to date.

**Comment by Craftplorer** [comment]
[Random Video](https://www.youtube.com/watch?v=I5ZYf1UFw_o)
If you check out this random video you can see that the ratio bar is working perfectly with zero dislikes.
The problem is just that the video I linked was recently published so the API from YouTube was reporting the likes/dislikes as zero. The Website on the other hand was reporting a more recent like count. So YouTubes website and API are out of sync. 
The reason I believe the ratio bar renders correctly if I dislike the video would be that the extension uses a cached API result with my local dislike to update the ratio bar. 
The problem is basically how YouTube updates there API and as they are removing the dislikes from the API anyways there is no point in fixing this "bug".
