### ISSUE TITLE
(Bug): dislike button disappears after leaving browser open for a long time

### ISSUE THREAD

**Issue by wasakoki** [Anarios/return-youtube-dislike#189]
### Browser

vivaldi

### Browser Version

3.8.2259.42  (latest stable)

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.0

### Video link where you see the problem

n/a (all videos)

### What happened?

i leave my computer on overnight with my browser open, usually with some tabs open with youtube videos, and i've noticed every time i use my computer the next morning the dislike counter doesnt exist, it's as if the extension isn't installed at all. refreshing the page/going to a new video does nothing, but completely closing out my browser and reopening fixes the problem temporarily.

i've reproduced this every night since i installed the extension (4 times)

**Comment by Anarios** [comment]
Thanks, will look into it.

**Comment by wasakoki** [comment]
so, apparently i was 2 major versions behind on vivaldi because the browser stopped auto-updating as i was used to it doing and my poor judgement misunderstood "stable channel" as being the latest stable.. oops ^^

anyways, i updated to the REAL latest stable version of the browser and havent had the issue two nights in a row, so i think the issue was just using an outdated browser version (more specifically, my guess would be how vivaldi handled waking up hibernated/inactive tabs in the old version). either way the issue is fixed and i think it was because because of an outdated browser on my end. if you all agree feel free to close the issue ^^

**Comment by Anarios** [comment]
Should be fixed now, feel free to reopen if still happens
