### ISSUE TITLE
(Bug): Next track key not working with extension on

### ISSUE THREAD

**Issue by Hans-xwh** [Anarios/return-youtube-dislike#191]
### Browser

Google Chorme

### Browser Version

96.0.4664.45 (Official Build) (64 bits) (cohort: Stable)

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.0

### Video link where you see the problem

Any video

### What happened?

When the extension is active, the next track key on my keyboard stops working for youtube videos, but with the extension dissabled it works fine

**Comment by Frontesque** [comment]
Do you mean media keys on your keyboard?

**Comment by Hans-xwh** [comment]
> Do you mean media keys on your keyboard?

Yes, but play/pause key works fine, the problem is only with next/previous track key :/

**Comment by Hans-xwh** [comment]
Edit: I reinstalled the extension and now it works fine. Sorry!
