### ISSUE TITLE
(Bug): Lorem ipsum text in settings

### ISSUE THREAD

**Issue by edbrunton** [Anarios/return-youtube-dislike#192]
### Browser

Microsoft Edge

### Browser Version

Microsoft Edge Version 96.0.1054.43 (Official build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.0

### Video link where you see the problem

N/A

### What happened?

User setting helptext are Lorem ipsum text
![image](https://user-images.githubusercontent.com/31941201/144721607-8fe2f534-b38d-43f3-9f5c-3492722d6fcb.png)

**Comment by edbrunton** [comment]
Appears to be caused by commit 1fc81b445fd1571f12118ec79ef1245586df11b9
Recommend changing to Disable Ratio Bar and Disable API Unlisted
![image](https://user-images.githubusercontent.com/31941201/144721795-85e0b300-4972-410d-a537-15ebd1655740.png)

**Comment by Anarios** [comment]
Fixed in latest version (coming soon)
