### ISSUE TITLE
(Bug): YouYube Music

### ISSUE THREAD

**Issue by Ascor8522** [Anarios/return-youtube-dislike#195]
### Browser

Google Chrome

### Browser Version

Google Chrome 96.0.4664.45 (64 bits) (cohort: Stable)

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.0

### Video link where you see the problem

https://music.youtube.com/watch?v=WEcPAs9gC70

### What happened?

While listening to music on **YouTube Music**, the extensions throws errors in the background on a loop.

```
Uncaught TypeError: Cannot read properties of null (reading 'offsetParent')
    at getButtons (return-youtube-dislike.script.js:18)
    at checkForJS_Finish (return-youtube-dislike.script.js:186)
getButtons @ return-youtube-dislike.script.js:18
checkForJS_Finish @ return-youtube-dislike.script.js:186
```

## Steps to reproduce

1. Go on YouTube Music.
2. Listen to some music
3. Check the console full of that same error

**Comment by mphelp** [comment]
@Frontesque @Anarios looks like #204 closes this issue 👍
