### ISSUE TITLE
(Bug): Cannot read properties of null (reading 'offsetParent')

### ISSUE THREAD

**Issue by DivyanshByte** [Anarios/return-youtube-dislike#199]
### Browser

Google Chrome

### Browser Version

Chrome v96

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.0

### Video link where you see the problem

Every where on Youtube

### What happened?

When I Open Console, I see a lot of errors saying:

```
return-youtube-dislike.script.js:18 Uncaught TypeError: Cannot read properties of null (reading 'offsetParent')
    at getButtons (return-youtube-dislike.script.js:18)
    at checkForJS_Finish (return-youtube-dislike.script.js:186)
```

This Is Coming On Every video I open, even on youtube homepage.

**Comment by wge44** [comment]
Getting a very similar error
```
Uncaught TypeError: Cannot read properties of null (reading 'offsetParent')
    at getButtons (return-youtube-dislike.script.js:18)
    at checkForJS_Finish (return-youtube-dislike.script.js:184)
```
It seems to only happen when signed in for me, when clearing browser data the extension works again

**Comment by mphelp** [comment]
@wge44 @DivyanshByte Caused by a simple missing null check on the element here `if (document.getElementById("menu-container").offsetParent === null) {` 

I'm putting in a fix, see below.
