### ISSUE TITLE
Ratio bar disabled

### ISSUE THREAD

**Issue by RafalRambo** [Anarios/return-youtube-dislike#20]
It is possible to disable this bar or add options on/off this in extension settings.
![Screen Shot 20-11-21 001](https://user-images.githubusercontent.com/57037648/142731265-ac27da4e-b267-497a-8c90-2ce7c657ffd7.JPG)

**Comment by Anarios** [comment]
Yep, customization options will be added

**Comment by dr2okevin** [comment]
I like the buttons and bar colored, so I used this userstyle for a long time: https://userstyles.org/styles/167450/colourful-youtube-ratings

Would be nice if either that kind of user style is supported, or if the extension brings own color options.

**Comment by PickleNik** [comment]
re: #186
