### ISSUE TITLE
(Bug): 0 dislikes displayed when likes and dislikes are disabled

### ISSUE THREAD

**Issue by DetachHead** [Anarios/return-youtube-dislike#200]
### Browser

edge

### Browser Version

95.0.1020.53

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.0

### Video link where you see the problem

https://www.youtube.com/watch?v=vVP4QuRMqgk

### What happened?

![image](https://user-images.githubusercontent.com/57028336/144735624-6eda4702-67a2-43b6-b27f-8f3668c58791.png)

**Comment by yt11sf** [comment]
https://github.com/Anarios/return-youtube-dislike/issues/196#issuecomment-986149805

**Comment by DetachHead** [comment]
that's a different issue i think. i think that it shouldn't touch videos where both likes and dislikes are disabled, but instead it incorrectly shows 0 dislikes.

**Comment by ShadyMedic** [comment]
It's not always 0, if the video has any dislikes, it displays the count and the ratio. I think that if the creator decides to hide the like count, this extension should respect that and not fetch or display the dislike count.

![image](https://user-images.githubusercontent.com/19894267/144743544-e3a7f22a-035e-46d4-8000-00031bcbe27b.png)

**Comment by thesusian** [comment]
Fixed in #395
