### ISSUE TITLE
(Feature Request): Someone should upload the archiveteam-warrior-v3-20171013.ova

### ISSUE THREAD

**Issue by Pdzly** [Anarios/return-youtube-dislike#207]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Someone should upload that on a faster hoster because it takes on my line from germany like 2 hours

### Ways to implement this!

upload it to mega.nz
( i would do it after the 2 hours download)

### Can you work on this?

- [X] Yes
- [ ] No

**Comment by DavidSaguna** [comment]
I think there is something wrong with your connexion because I downloaded it in 15 seconds but I uploaded my warrior ova file to mega if you'd like to try it:
https://mega.nz/file/FxIjGQaZ#moPlJ2TBiE7tAhhvgTsJjtvaxsp2YU4hSydYvFJvLmQ

**Comment by RDKRACZ** [comment]
It is already available from their Github.

**Comment by Pdzly** [comment]
Ok i saw the github download too late yeah.
