### ISSUE TITLE
(Feature Request): Signed-out Likes / Dislikes

### ISSUE THREAD

**Issue by JeffRockatansky** [Anarios/return-youtube-dislike#208]
### Extension or Userscript?

Both

### Request or suggest a new feature!

It would be nice to store likes too without Google account for those who don't want to register one.

### Ways to implement this!

It will require some duplication prevention:
* Local storage
* Decentralized FOSS 3rd-party auth (Matrix? XMPP? IRC?)
* Unique ID (UUID?) and | or cryptography (GPG key?)

### Can you work on this?

- [X] Yes
- [X] No

**Comment by JeffRockatansky** [comment]
Both checks means that I will certainly need some help with this.

**Comment by sy-b** [comment]
>It would be nice to store likes & dislikes without Google account.

Currently its not using Google account

If you meant that for future, check #109

**Comment by JeffRockatansky** [comment]
@sy-b 
It is now only stores dislikes. It might as well store likes too.

**Comment by sy-b** [comment]
> It is now only stores dislikes. It might as well store likes too.

But why should it store likes?

**Comment by JeffRockatansky** [comment]
> But why

It already stores dislikes. Might as well store likes too. For those who don't want to log in their Google account every time they open YouTube. Ant for those who don't want a Google account at all.

**Comment by sy-b** [comment]
Likes are visible anyways
&  as of now, the extension doesn't need any account.

In future if it uses some kind of user authentication system then that would be certainly be for counting dislikes. If a person doesn't sign in to YT then no likes/dislikes will be collected by YT. And then it doesn't make any sense to make the extension collect anything from user. User can still use the extension for viewing dislikes.

**Comment by hrichiksite** [comment]
Maybe a fingerprinting of user device would  help prevent duplication of votes.

**Comment by Anarios** [comment]
I want dislike and like count to be somewhat similar to what creator sees in creator studio. If we let users without accounts vote - these numbers will differ more and more over time, and there will be no way to prove validity of extension's dislike counts.
