### ISSUE TITLE
(Bug): 0 dislikes has ratio bar at half instead of full

### ISSUE THREAD

**Issue by Willy-JL** [Anarios/return-youtube-dislike#210]
### Browser

Brave

### Browser Version

Brave: 1.29.79 Chromium: 93.0.4577.63

### Extension or Userscript?

Extension

### Extension/Userscript Version

Version 1.1.0.2

### Video link where you see the problem

https://user-images.githubusercontent.com/49810075/144750597-7e80156d-e3aa-4926-b2ba-ac5bdf0bcb30.png

### What happened?

With 0 dislikes the like ratio bar is at half instead of full.
![image](https://user-images.githubusercontent.com/49810075/144750597-7e80156d-e3aa-4926-b2ba-ac5bdf0bcb30.png)

**Comment by JacynoAdam** [comment]
I'm not experienced with extensions, but I dug a bit through code and I think I found the culprit. As far as I can tell, two things need to happen for this:
- API returns 0 likes and 0 dislikes - that causes a 50% bar to appear. If there were any likes and no dislikes, as far as I can tell the bar would be at 100% as it was meant to be
- YouTube has no dislikes - which I think is now always the case.

It looks like reading likes count from the page, requires dislike count to be different than 0 as well (which is never the case now), so even though API returned 0 and 0, while scrapping the website returned 2400 and 0, the second pair is not considered acceptable so the 0 likes 0 dislikes bar stays.

I'm not sure what's the best way to fix it, considering API response would usually be better than website response, so just accepting 0 dislikes from the web response could cause something like API returning 2000 and 100, while website returning 2000 and 0 and overwriting the more accurate API response.

My idea would be to change:
`if (response.likes && response.dislikes)` to something like
`if (response.likes && response.dislikes || response.likes != 0 && old_likes == 0)`, where you would have to set and store `old_likes` somehow in the API response.

To be honest I'm interested to see what the best solution is here.

**Comment by johan0A** [comment]
same on firefox

**Comment by Anarios** [comment]
Should be fixed now, feel free to reopen if still happens
