### ISSUE TITLE
Option to show like/dislike percentage instead of full like/dislike count

### ISSUE THREAD

**Issue by Nightcaat** [Anarios/return-youtube-dislike#211]
![image](https://user-images.githubusercontent.com/26909213/144755140-44cc257b-4071-47a0-915a-fae307cbe23a.png)

**Comment by SirLich** [comment]
If... this does make it into a feature (I'm actually somewhat in favor), I would rather see it represented as a single number (like percentage), not two. 

Additionally... isn't that what the 'bar' is for?

**Comment by magnus-ISU** [comment]
That's what the bar is for, but its nice to have the actual numerical proportion rather than a vague line.

Agree a single number would be nicer.

**Comment by ErykDarnowski** [comment]
I think it would be nice to give users a couple options of displaying this info:
- 190 / 10 - 95%
- 95% / 5%
- 95%

**Comment by ErykDarnowski** [comment]
Got a dirty implementaion of this ^ done already, I'll work on this more tomorrow.

**Comment by Nightcaat** [comment]
Good stuff :]

I got a notification here and cloned your fork but I couldn’t get it to work on either browser. It looks like you re-forked the repository so I assume you’re still working on it?

**Comment by ErykDarnowski** [comment]
It's actually fully implemented already! After I fix this last bug I'm pushing it to my fork ;)

**Comment by ErykDarnowski** [comment]
It's done :)

**Comment by Nightcaat** [comment]
Oops, forgot to close my own issue. Fixed in #560
