### ISSUE TITLE
(Feature Request): Return Youtube Comments

### ISSUE THREAD

**Issue by mat926** [Anarios/return-youtube-dislike#217]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Implement a comment section for videos that have disabled comments

### Ways to implement this!

Similar to dislikes, have  a community based database for comments. 

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by SirLich** [comment]
I am very, very against this. Various "comment everywhere" plugins exist, and they are all dumpster fires. 

They are almost definitionally a victim of their own success, as a large user-base is too expensive, and a small one has no interactivity. 

I hope the team at RYTD will keep their scope *small*, and limited to dislikes, or similar quality metrics.

**Comment by mphelp** [comment]
++ I'm with @SirLich on this one

**Comment by trakevital** [comment]
How about pulling a twitter and limiting the comment length to 120 characters and 1 comment per YouTube video

**Comment by DragShot** [comment]
> How about pulling a twitter and limiting the comment length to 120 characters and 1 comment per YouTube video?

That would be even worse lmao

**Comment by Frontesque** [comment]
This is not what this extension is aiming to do.
