### ISSUE TITLE
I can't get the script or extension to work

### ISSUE THREAD

**Issue by jmuff44xv** [Anarios/return-youtube-dislike#22]
**Script**
Tampermonkey 4.13 reports:
"eslint: null - parsing error: unexpected token" on the line 21:
"?.querySelector("#top-level-buttons-computed");".

**Extension**
When I try to "load unpacked" the folder into which I extracted the contents of the zip, Chromium reports:
"Invalid value for 'web_accessible_resources[0]'."
"Could not load manifest."

Chromium v78 is maybe kinda old (sorry), but it would be cool if you could make it work without update. I do have the latest version of Tampermonkey, I think (Tampermonkey v4.13).

**Comment by DARKDRAGON532** [comment]
If I'm not wrong, Chromium v78 was released in 2019.
For the tampermonkey script, on line 21, `?.` is a javascript feature introduced in 2020, which is why it probably isnt working.

I think the error for the extension is happening because your chromium version is too old.

**Comment by Anarios** [comment]
Can't support old browsers now, sorry. Might look at it later, but low priority
