### ISSUE TITLE
(Feature Request): Show accuracy in some way

### ISSUE THREAD

**Issue by KeinDahLahzey** [Anarios/return-youtube-dislike#221]
### Extension or Userscript?

Both

### Request or suggest a new feature!

I suggested this in the discord but felt that it might be good to add here so its not lost/fully explained in one go. 

Anyhow a system of some kind to display how accurate the dislike count is once the API closes off. 

### Ways to implement this!

There are a few ways to implement on the front end but the way i immediately thought of was a colored tier system.

Tier 1: Creator has shared dislike count.
Tier 2: Dislikes were archived and there is extension user data to adequately update.
Tier 3: Dislikes were not archived but enough extension users to sample data for accurate dislike count.
Tier 4 : Not enough extension users to sample reliable data from.

To display this the like number would be changed to a different color to indicate the reliability ranging from green at tier 1 to red at tier 4. 

Another idea would be to have 'badges' beside the dislikes to display this, and hovering over this would explain the tier system and what tier that video is.

As for working on the back end, it should know how it is deriving the dislikes and shouldn't be super hard, but then again i have no experience working on projects like this.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by mattphelps-8451** [comment]
@KeinDahLahzey 
About Tier 2: There will always be the possibility for user extension dislikes on a video that has a large percentage of archived dislikes. Maybe this tier could set a threshold i.e. "At least 50% of dislikes on this video were archived" (and the other 50% or less are extension user-provided)

About Tier 4: Would you imagine dislikes not showing? Or an estimate of dislikes instead?

About Tier 4: Would

**Comment by KeinDahLahzey** [comment]
@mattphelps-8451 

There might actually may need to be another tier in between the existing 3 and 4. This one would be "Dislikes were archived but not enough extension users to estimate further dislikes". Though having the percentage of dislikes from extension users and the archive would be handy.

As for dislikes showing on tier 4, I imagine that you would hover over and then it would tell you its estimate, but also that it may be wildly inaccurate since not enough data has been sampled. This would be to provide emphasis on the fact that it is inaccurate instead of people just looking and ignoring the accuracy.

**Comment by sy-b** [comment]
similar to #114
but that tier idea is better that percentage

**Comment by Anarios** [comment]
I will close this one because #221 is the same, but we can continue there. The basic idea is very similar.
