### ISSUE TITLE
How do I change the language of the output? (Not a bug, but i wanted to know)

### ISSUE THREAD

**Issue by rlelchev** [Anarios/return-youtube-dislike#226]
### Browser

Qutebrowser

### Browser Version

Qutebrowser v2.4.0 based on Chromium 83.0.4103.122

### Extension or Userscript?

Userscript

### Extension/Userscript Version

0.6.1

### Video link where you see the problem

Everywhere

### What happened?

In my language we use "1 хил." instead of "1K" and "1 мнл." instead of "1M". That makes a difference between the display of the like count and dislike count. Any way i can change how the script gets the youtube api response?

**Comment by DARKDRAGON532** [comment]
If you want to change the dislike language then change your browsers language (to probably english UK/US).
If you want to change the like language then change youtubes language.
A fix will be added soon.

**Comment by rlelchev** [comment]
I do not want to change the browser's language all together. I was just wondering if there was an easy way to change the way returnyoutubedislike displays dislikes

**Comment by DARKDRAGON532** [comment]
> I do not want to change the browser's language all together. I was just wondering if there was an easy way to change the way returnyoutubedislike displays dislikes

well there is #239 now, maybe you can clone the repository and load it manually until it gets merged?

**Comment by rlelchev** [comment]
@DARKDRAGON532 Thanks! That did the trick!
