### ISSUE TITLE
(Bug): Dislikes of Private Videos are "NAN"

### ISSUE THREAD

**Issue by GammelSami** [Anarios/return-youtube-dislike#230]
### Browser

Firefox, Chrome

### Browser Version

Firefox 94, Chrome 96

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.2

### Video link where you see the problem

https://imgur.com/a/mllv1KO

### What happened?

If private videos have no dislikes, the counter gets replaced with NAN.
If private videos have dislikes, the counter is correct.

**Comment by mphelp** [comment]
@GammelSami Can you provide video URL or video ID?

**Comment by GammelSami** [comment]
That doesn't make sense, because the videos are on private. You need to upload one and put it on private by yourself.

Private with 0 Dislikes: https://youtu.be/L5OE4sleU4s (has never been public)
Private with 342 Dislikes: https://youtu.be/h3ChNbIq5_E (has once been public)

**Comment by Anarios** [comment]
> @mphelp That doesn't make sense, because the videos are on private. You need to upload one and put it on private by yourself.
> 
> Private with 0 Dislikes: https://youtu.be/L5OE4sleU4s (has never been public) Private with 342 Dislikes: https://youtu.be/h3ChNbIq5_E (has once been public)

extension is not going to work for private videos. But yeah - NaN should't be displayed
