### ISSUE TITLE
(Bug): Dislike counter going negative (sometimes) - side effect of #59

### ISSUE THREAD

**Issue by sy-b** [Anarios/return-youtube-dislike#232]
### Extension or Userscript?
Extension.

### Extension version
1.1.0.2

### Video link where you see the problem
Wherever the dislikes aren't rounded off. i.e. not as 2.1K
for e.g. test here: https://youtu.be/B1AkHCdqTsc

### What happened?
The dislike count starts going down, even if I am not signed in.
& eventually goes to negative.

A side effect of #59 

![bug in RYD negative dilikes](https://user-images.githubusercontent.com/94835959/144902411-f2176177-caf1-44b2-aac7-ab1c9106012a.PNG)

https://user-images.githubusercontent.com/94835959/144904484-e3f8fcf3-b119-45d4-adf1-a9235f374ed8.mp4

**Comment by sy-b** [comment]
Possible ways to mitigate this:
1. Check if that sign-in button is available
2. If dislikes == 0 , don't reduce any further

**Comment by erkanokyay** [comment]
This issue only appears whenever im not logged in. If i try to reproduce this being logged in, the dislike count goes back to what it was before. 

Tested on:
- Brave Version 1.32.115 Chromium: 96.0.4664.93
- Chrome Version 95.0.4638.54
