### ISSUE TITLE
(Bug): Dislike count doesn't go back down when pressing like after pressing dislike

### ISSUE THREAD

**Issue by dokugaron** [Anarios/return-youtube-dislike#237]
### Browser

Brave

### Browser Version

Brave: 1.32.113 Chromium: 96

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.2

### Video link where you see the problem

Affects all videos

### What happened?

If you click like after clicking dislike, the dislike count does not go back to what it was before clicking dislike, like it should. If you click dislike again, the count goes up by one more. You can keep alternating between like and dislike and the count will keep going up. It does not persist after reloading the page.
![2021-12-07 01-25-33](https://user-images.githubusercontent.com/82846166/144978074-536d2327-dbb8-4bd1-b8f1-9b3d83121866.gif)

**Comment by VidithM** [comment]
I believe this is the same as #232

**Comment by sy-b** [comment]
> I believe this is the same as #232

This is also side effect of #59
but not same as #232

**Comment by USBDongleGoblin** [comment]
I've encountered a similar issue #255. The main difference is that you don't need to be signed in, and you only need to keep clicking dislike.

**Comment by Anarios** [comment]
Should be fixed now, feel free to reopen if still happens
