### ISSUE TITLE
(Bug): 

### ISSUE THREAD

**Issue by miladganjali** [Anarios/return-youtube-dislike#238]
### Browser

Google Chrom

### Browser Version

latest

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=k7lytyRgBwE

### What happened?

The ratio is not right
![Untitled](https://user-images.githubusercontent.com/8298544/144997927-fe553427-fecd-4153-bdcf-992e38aa7d0f.png)

**Comment by DARKDRAGON532** [comment]
Try refreshing the page a few times or reinstalling the extension
