### ISSUE TITLE
A bold idea: the app should have its own voting system

### ISSUE THREAD

**Issue by ixfd64** [Anarios/return-youtube-dislike#24]
One alternative to extrapolation would be for the app to use its own voting system. In a nutshell, the app would provide its own "like" and "dislike" buttons. Users who register an account would be able to use this feature. In addition to scraped data from YouTube, the app would also display "like" and "dislike" data collected from the app's users.

Of course, the downside is that it might cost a lot to run this service in the event that it becomes popular.

**Comment by Razodiac** [comment]
It requires a much bigger server to do so, most likely bigger than what the developers of this extension is able to afford. It is better if it was run by a separate company that is able to afford the cost of counting all dislikes over time.

**Comment by Anarios** [comment]
It's on the roadmap, and should be implemented before december 13th. 

The buttons will stay the same, but when you click - you will send a message to youtube AND to the extension backend, therefore allowing us to count downvotes.
