### ISSUE TITLE
Enable the discussions tab for this repository

### ISSUE THREAD

**Issue by sy-b** [Anarios/return-youtube-dislike#240]
Reasons:
- For discussions that are not issues.
- For people who aren't on discord or don't want to be for whatever reason
- Slightly less informal than discord
- Can serve as official notice board (for wider public)
- Discord is good. But just to have an easily searchable idea/question/etc.
- Once discussion on discord gets lost in the ocean of old messages, no one cares & its likely to be repeated.

**Comment by dabockster** [comment]
Agreed on all of this. Discord servers can feel like "secret" clubs at times and move too fast to retain any useful knowledge (without excessive screenshotting).

**Comment by Anarios** [comment]
Done, thanks.
