### ISSUE TITLE
(Feature Request): Readme: "Help archiving dislikes": (5) Download OVA links to version 3.0, instead of 3.2 (latest)

### ISSUE THREAD

**Issue by flyingcyril** [Anarios/return-youtube-dislike#243]
### Extension or Userscript?

Both

### Request or suggest a new feature!

In this project's landing page / readme, under section "Help archiving dislikes", point 5, the instruction links to ArchiveTeam's warrior version 3.0 from 2017, instead of the latest warrior from 2021, version 3.2. I'm not sure if this is a problem, but I assume a newer version is better. I've used 3.2 for this project without issue. 

### Ways to implement this!

On this project's landing page / readme, under the section "Help archiving dislikes":

Please update the text and the hyperlink, from 

5. Download "archiveteam-warrior-v3-20171013.ova" ([mirror link](https://warriorhq.archiveteam.org/downloads/warrior3/archiveteam-warrior-v3-20171013.ova))

to

5. Download "archiveteam-warrior-v3.2-20210306" ([mirror link](https://warriorhq.archiveteam.org/downloads/warrior3/archiveteam-warrior-v3.2-20210306.ova))

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by Slapbox** [comment]
@PickleNik @Anarios this seems like it should be high priority. The currently links OVA won't even run for me. The version @flyingcyril linked _does_ work - at least a lot further than the first image did. Still loading up.

**Comment by DARKDRAGON532** [comment]
#254 resolves this
