### ISSUE TITLE
(Bug): No Dislike Count Shown

### ISSUE THREAD

**Issue by CurtisTD** [Anarios/return-youtube-dislike#249]
### Browser

FireFox

### Browser Version

FireFox 94

### Extension or Userscript?

Extension

### Extension/Userscript Version

Version 1.1.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=vC5JnJD9KzY

### What happened?

A bug happened!

I installed the extension today for the first time. I have tried seeing any dislikes on any video, and it just defaults to the new 'DISLIKE' count.

Happens on any video, can't seem to find any that work.

**Comment by Makeineer** [comment]
Can confirm this one. Seems to resonate specifically with timestamped videos on my end.

**Comment by krystian3w** [comment]
See too #244

**Comment by DARKDRAGON532** [comment]
Is this still happening?

**Comment by krystian3w** [comment]
Maybe server side bug (I unable reproduce on Windows 7 with FF95).

**Comment by DARKDRAGON532** [comment]
There was an API outage near the time this issue was opened, might be due to that.

**Comment by Anarios** [comment]
Should be fixed now, feel free to reopen if still happens
