### ISSUE TITLE
(Bug) Dislikes can be added while signed out

### ISSUE THREAD

**Issue by USBDongleGoblin** [Anarios/return-youtube-dislike#255]
### Browser

Firefox

### Browser Version

95.0 (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=Rx4IURmHjV0

### What happened?

Exactly what the title says. The worst part is that if you keep clicking the button, the dislikes keep going down.

This could end up being a major issue once YouTube removes dislikes from the API, and the extension switches over to it's own database.

**Comment by cupiditys** [comment]
its already been fixed, extensions on the web stores just havent been updated yet
