### ISSUE TITLE
(Bug) Cannot see any dislikes

### ISSUE THREAD

**Issue by NLogDEV** [Anarios/return-youtube-dislike#257]
### Browser

Google Chrome

### Browser Version

96.0.4664.93

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.2

### Video link where you see the problem

youtube.com/?watch=*

### What happened?

Like the title
I cannot see the dislike count, I tried to wait, refresh the page but nothing happens

**Comment by DARKDRAGON532** [comment]
Try reinstalling

**Comment by Tenmak** [comment]
> Try reinstalling

It works ! Had the same issue !

**Comment by AizenMikoto** [comment]
I'm having the same issue, I have to uninstal and reinstal it everytime i launch Chrome.

**Comment by rubyFeedback** [comment]
That's strange. Is youtube somehow registering it and trying counter-measures? I also had recently other problems, e. g. I no longer see the comment upvotes ... very odd to me.

**Comment by Frontesque** [comment]
You might have the new youtube layout/theme as shown below?
![new theme](https://user-images.githubusercontent.com/27463495/145727036-ef176399-e608-4892-aa2e-1df4c1fb7f7a.png)

This is known to have issues with the extension as youtube is changing how the dislike button works under the hood.

**Comment by Anarios** [comment]
should be fixed in 2.0, feel free to reopen if still happens for you.
