### ISSUE TITLE
(Bug): Like, Dislike bar after video description 

### ISSUE THREAD

**Issue by kdpuvvadi** [Anarios/return-youtube-dislike#259]
### Browser

Google Chrome

### Browser Version

v96

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=qcNhqYBr2To

### What happened?

Normal View on videos 

![image](https://user-images.githubusercontent.com/7326255/145552001-beb3045a-a68b-44e7-90a6-6d86ea683a41.png)

But On Most videos

![image](https://user-images.githubusercontent.com/7326255/145552036-c7fb65ef-7ca3-42fe-b3d2-b0033ad5f977.png)

and

![image](https://user-images.githubusercontent.com/7326255/145552053-e8f286e4-18f2-4f33-aa46-e18bc901875a.png)

**Comment by DARKDRAGON532** [comment]
That's youtube's new UI, nothing we can do about it.

**Comment by DARKDRAGON532** [comment]
Actually my bad, I misunderstood the issue, does it resolve if you remove the extension?

**Comment by kdpuvvadi** [comment]
Hoo, New UI, I'm not aware of this. But only Showing up on some videos.

**Comment by kdpuvvadi** [comment]
> Actually my bad, I misunderstood the issue, does it resolve if you remove the extension?

Yes, it does.

**Comment by DARKDRAGON532** [comment]
Yup, If i reduce my browser window size using the new ui (regardless of whether i have the extension installed or not) it becomes like the screenshots you sent.

**Comment by kdpuvvadi** [comment]
Yep, Seems like that. On my 27" monitor it seems fine but not on 13" 15"

**Comment by 3rd3** [comment]
@DARKDRAGON532 Isn't the ratio bar missing?

**Comment by DARKDRAGON532** [comment]
> @DARKDRAGON532 Isn't the ratio bar missing?

It isnt, are you using the latest version of the extension?

**Comment by 3rd3** [comment]
@DARKDRAGON532 Looks like big brother is doing experiments with me: https://github.com/Anarios/return-youtube-dislike/issues/522#issuecomment-1086901182

**Comment by DARKDRAGON532** [comment]
> @DARKDRAGON532 Looks like big brother is doing experiments with me: [#522 (comment)](https://github.com/Anarios/return-youtube-dislike/issues/522#issuecomment-1086901182)

rip
