### ISSUE TITLE
Google Chrome detects unusual traffic when searching on google while extension is enabled

### ISSUE THREAD

**Issue by fadihh** [Anarios/return-youtube-dislike#260]
Google Chrome detects unusual traffic when searching on google while extension is enabled

**Comment by Anarios** [comment]
Extension shouldn't even work on google search pages (it doesn't have permissions to do so). Only on youtube. I'll investigate.
Do you get image captcha?

**Comment by fadihh** [comment]
Yes I do get captcha
I always get the captcha when i search while the extension is enabled. 
When I turned it off, i could search without google detecting unusual traffic.

**Comment by Anarios** [comment]
Should be fixed now, feel free to reopen if still happens
