### ISSUE TITLE
(Bug): Commit #1959c8b CORS regression

### ISSUE THREAD

**Issue by Zorgodon** [Anarios/return-youtube-dislike#262]
### Browser

Chromium

### Browser Version

96

### Extension or Userscript?

Userscript

### Extension/Userscript Version

199f086

### Video link where you see the problem

https://www.youtube.com/watch?v=49ASUFQgWZE

### What happened?

Merge Commit 1959c8b changes ``fetch(`https://www.youtube.com`` back to ``fetch(`https://youtube.com/watch?v=``,
causing the bug described in Pull #244 to reappear. The upstream extension is unaffected.

**Comment by Zorgodon** [comment]
Same for ``isMobile``, `` url: `https://www.youtube.com`` has regressed back to ``url: `https://youtube.com``

**Comment by DARKDRAGON532** [comment]
Oops, sorry about that, should be fixed in #263 


> Same for `isMobile`, `` url: `https://www.youtube.com `` has regressed back to `` url: `https://youtube.com ``

Which line? I can't find it

**Comment by Zorgodon** [comment]
My bad. Line 223 (under `isMobile`) wasn't affected.
