### ISSUE TITLE
(Feature Request): Add support to Yandex Browser

### ISSUE THREAD

**Issue by BerserkSoul1989** [Anarios/return-youtube-dislike#265]
### Extension or Userscript?

Userscript

### Request or suggest a new feature!

Hi there devs ;)
Could you please add support of this extension to Yandex Browser?
I know this browser is based on Chrome but it seems like it's not working in my PC.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by DARKDRAGON532** [comment]
is the extension throwing any errors? anything in console?

**Comment by krystian3w** [comment]
Yandex on PC, macOS and Android should suppor chrome web store.

On PC and macOS was also support Opera addon store.

**Comment by Felix14-v2** [comment]
Today, the extension has completely stopped working in Yandex.Browser. Other platforms looks fine.
![image](https://user-images.githubusercontent.com/75726196/145896295-37c02bff-d944-4897-9079-61cbdb20a774.png)
![image](https://user-images.githubusercontent.com/75726196/145896356-2444be7a-22e4-431d-8cb6-c412321be9f4.png)

**Comment by krystian3w** [comment]
Today Google should killed count in own API so backend based on backup and own "magic" like trakcing who clicked if have addon, maybe good add telemery into user.js if `greasyfork` / `openuserjs` allow tracking in own rules/privacy policy.

**Comment by Anarios** [comment]
Works in YBrowser in version 2.0.0.1
