### ISSUE TITLE
(Feature Request): Replace/Co-exist next to the Like/Dislike button

### ISSUE THREAD

**Issue by resuta566** [Anarios/return-youtube-dislike#266]
### Extension or Userscript?

Both

### Request or suggest a new feature!

How about adding a separate like/dislike button that would replace or be side by side with the Youtube like/dislike button. 

This would really help with newly uploaded videos.

Of course, we need a user registration for this and bot checking. SO this might not be really feasible.

### Ways to implement this!

Adding a custom button next to YTs like/dislike btn. 

### Can you work on this?

- [X] Yes
- [ ] No

**Comment by DARKDRAGON532** [comment]
Already in work

**Comment by resuta566** [comment]
that's freaking awesome!!!!!
