### ISSUE TITLE
The counter is incorrect

### ISSUE THREAD

**Issue by SamuelViol** [Anarios/return-youtube-dislike#28]
is marking 0, 1 or 2 depending on the video (not only on linus videos)
yes, linus has few dislikes, but only 1?

![Captura de tela 2021-11-21 223308](https://user-images.githubusercontent.com/33838969/142788506-a83eaa27-644f-4a75-8e33-4a58d54c6767.png)

**Comment by Anarios** [comment]
Latest version as well?

**Comment by SamuelViol** [comment]
> Latest version as well?

yes i am using the latest version. Today I haven't seen this bug occur, but I'll stay tuned

**Comment by Anarios** [comment]
@SamuelViol 
is it still an issue on newest version?

**Comment by pundoo** [comment]
Can confirm, the api returns incorrect like/dislike/view count, especially for newer videos. Something is not right at the backend. You can check hadzy.com for actual stats, if that helps.

**Comment by Anarios** [comment]
> Can confirm, the api returns incorrect like/dislike/view count, especially for newer videos. Something is not right at the backend. You can check hadzy.com for actual stats, if that helps.

don't forget that data is cached. We simply can't update it too often, and if it's a couple of days old - dislikes will be off.

But we're working on improvement.

**Comment by nattadasu** [comment]
Issue was also caught on my end:

* Browser: Vivaldi 4.3.2439.65 (Stable channel) (64-bit)
* Version: 0.5, Userscript release.
* Tested on: Newest release video from:
   * LTT:   
      ![Screenshot from Linus Tech Tips' latest video](https://user-images.githubusercontent.com/49780229/142990761-436056e5-15f8-4090-a95b-705542f52148.png)
   * Tom Scott:
      ![Screenshot from Tom Scott's latest video](https://user-images.githubusercontent.com/49780229/142990933-0db24246-e7c3-4318-9dde-25334c80955b.png)
* Snapshot taken at: `2021-11-23T08:24:00Z`

Hopefully there's workaround for this :'D

**Comment by Anarios** [comment]
> Issue was also caught on my end:
> 
> * Browser: Vivaldi 4.3.2439.65 (Stable channel) (64-bit)
> * Version: 0.5, Userscript release.
> * Tested on: Newest release video from:
>   
>   * LTT:
>     ![Screenshot from Linus Tech Tips' latest video](https://user-images.githubusercontent.com/49780229/142990761-436056e5-15f8-4090-a95b-705542f52148.png)
>   * Tom Scott:
>     ![Screenshot from Tom Scott's latest video](https://user-images.githubusercontent.com/49780229/142990933-0db24246-e7c3-4318-9dde-25334c80955b.png)
> * Snapshot taken at: `2021-11-23T08:24:00Z`
> 
> Hopefully there's workaround for this :'D

links would be nice. But as I said - this is just slow cached update rate, if a video is new  - dislikes won't update for a day or two.

**Comment by pundoo** [comment]
Since YouTube Data API has request quota limit, the only workaround I can think of is, being able to set own auth credentials and send request directly from the client. But the set-up process gonna be cumbersome for an average user.. so, we gotta deal with the current situation unfortunately. Plus dislike stat from API isn't gonna last longer anyway (?)

**Comment by Anarios** [comment]
> Since YouTube Data API has request quota limit, the only workaround I can think of is, being able to set own auth credentials and send request directly from the client. But the set-up process gonna be cumbersome for an average user.. so, we gotta deal with the current situation unfortunately. Plus dislike stat from API isn't gonna last longer anyway (?)

exactly.

**Comment by SamuelViol** [comment]
> @SamuelViol is it still an issue on newest version?

I've updated to the latest version, and I've been testing it for some time, so far it's normal. tanks

**Comment by SamuelViol** [comment]
> Since YouTube Data API has request quota limit, the only workaround I can think of is, being able to set own auth credentials and send request directly from the client. But the set-up process gonna be cumbersome for an average user.. so, we gotta deal with the current situation unfortunately. Plus dislike stat from API isn't gonna last longer anyway (?)

i imagine that youtube will either return with the counter, or will prevent access to apis.
