### ISSUE TITLE
(Feature Request): Add automated likes to all videos

### ISSUE THREAD

**Issue by canslaughter** [Anarios/return-youtube-dislike#283]
### Extension or Userscript?

Both

### Request or suggest a new feature!

For a few months now, I have been liking all the videos I watch except those I dislike—even before the dislikes were removed. At first I thought of it as a way give more weight to my dislikes, but now it's become essential to expressing my opinion. Let's start flagging all videos with likes except the ones we truly hate. Likes/dislikes were always there to express discontent anyways. This was its main purpose, in my opinion. Thanks!

### Ways to implement this!

No idea. Sorry.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by spaz926** [comment]
In my opinion, this is outside of the scope of the project.

**Comment by ItIsMeCall911** [comment]
is this how it feel when u are high on copium 😦

**Comment by Bobby99as** [comment]
This would be dumb to add

**Comment by Anarios** [comment]
would violate "one purpose per extension" rule
