### ISSUE TITLE
(Bug): (Very) inaccurate dislike ratios for upcoming videos/streams

### ISSUE THREAD

**Issue by FredrIQ** [Anarios/return-youtube-dislike#285]
### Browser

Google Chrome

### Browser Version

96.0.4664.93

### Extension or Userscript?

Extension

### Extension/Userscript Version

(how do I check? I installed it from the Chrome "store")

### Video link where you see the problem

https://www.youtube.com/watch?v=AfOlYg1k2NA

### What happened?

Pending videos seem to have an inaccurate dislike ratio. While I, of course, can't confirm this 100%, this one has a like rate of 33%ish while past videos (back when dislikes were still shown in the API) in the same series had a dislike rate of around 2-3%. This leads me to suspect that something strange is going on for upcoming videos in particular.

I know that the extension cannot substitute for true counts, but I just wanted to address one case where it seems to do its prediction very badly, which might be a result of errors in how it predicts dislike counts.

**Comment by thesusian** [comment]
Can you check if this has been fixed, it works fie for me.

**Comment by FredrIQ** [comment]
I mean, when I posted the issue, the video hadn't yet been uploaded and was merely just pending later upload, so it no longer applies to that video anyway.

I suppose I can close this for now, and post a new issue if I encounter it again on a new video.
