### ISSUE TITLE
(Bug): -0 dislikes shown if a video does not have any likes and dislikes

### ISSUE THREAD

**Issue by glenlalo** [Anarios/return-youtube-dislike#288]
### Browser

Both

### Browser Version

latest

### Extension or Userscript?

Extension

### Extension/Userscript Version

latest

### Video link where you see the problem

new videos with no dislike and no likes

### What happened?

![grafik](https://user-images.githubusercontent.com/77680105/145808437-9fb0009d-053f-4470-8626-fa0120ebd6b2.png)

**Comment by Haxorzz** [comment]
Sometimes it also appears as "NAN"

**Comment by Zenphia** [comment]
Probably a side effect of the removal of the "dislike" field from the YouTube Data API.

**Comment by Haxorzz** [comment]
@Zenphia well actually it happens when it tries to show dislikes on a video with hidden ratings
