### ISSUE TITLE
Doesn't work on Safari with UserScripts

### ISSUE THREAD

**Issue by mmykhaylov** [Anarios/return-youtube-dislike#29]
I'm using an AppStore app called UserScripts to inject JS into the page. It does so, but for some reason the dislikes are nowhere to be found. In the Dev Console I see ReferenceError: Can't find variable: GM. No other extensions are installed, so I am unsure as to what causes the error

**Comment by DARKDRAGON532** [comment]
https://gist.github.com/DARKDRAGON532/40001f0bac6f52c348bceae1de88b161
Does this work?

**Comment by Sega-Zero** [comment]
@DARKDRAGON532 works only after page reload

**Comment by DARKDRAGON532** [comment]
@Sega-Zero I don't know why that's happening, also this script will probably stop working in a few days due to the new ui so maybe when it gets updated ill try and see whats causing that
