### ISSUE TITLE
(Bug): Dislike count is NAN

### ISSUE THREAD

**Issue by MChelik** [Anarios/return-youtube-dislike#293]
### Browser

Firefox

### Browser Version

95

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.0.0.0

### Video link where you see the problem

https://www.youtube.com/watch?v=YczDFgFWUNU

### What happened?

It shows number of dislikes as "NAN"

**Comment by Reflekks** [comment]
Getting this as well

**Comment by spartanatreyu** [comment]
Can confirm:

<img width="722" alt="Mind-killer___Dune_OST_-_YouTube" src="https://user-images.githubusercontent.com/3240456/145909525-5fac106a-7d0d-4d31-a555-83b4fb5b022e.png">

It seems to appear and disappear sporadically. Sometimes changing the video in a playlist or refreshing the page causes it to work but then doing it again makes it disappear. A little hard to replicate unfortunately.

**Comment by sunnyjim5** [comment]
Google probably pulled API support because i see it everywhere

**Comment by davFaithid** [comment]
I have this same issue, though it only affects certain videos for me.

Here are two screenshots I took of two separate videos posted today hours apart, one affected and one not. 

[![Works](https://i.postimg.cc/8sTtB404/Screenshot-2021-12-13-at-19-44-01-Analogue-Pocket-Review-The-Ultimate-FPGA-Handheld-MVG.png)](https://postimg.cc/8sTtB404) [![Broken](https://i.postimg.cc/JH7xr7kv/Screenshot-2021-12-13-at-19-44-11-Charlie-puth-Don-t-like-her-anymore.png)](https://postimg.cc/JH7xr7kv)

I have no idea why one shows its dislikes and the other just displays NAN.

**Comment by Anarios** [comment]
Fixed in Firefox 2.0.0.1

**Comment by Anarios** [comment]
Feel free to reopen if not fixed

**Comment by MChelik** [comment]
hi @Anarios 

how the extension works when they removed the API yesterday?

**Comment by PolishDudeWithAHardToSpellName** [comment]
> how the extension works when they removed the API yesterday?

They will mostly rely on extrapolating the percentage of dislikes submitted by addon users and recorded stats from before YT pulled the plug.

https://returnyoutubedislike.com/faq - 4th question for the most info currently available
