### ISSUE TITLE
(Bug): Chrome extension web link to Github broken

### ISSUE THREAD

**Issue by cyrildtm** [Anarios/return-youtube-dislike#294]
### Browser

Chrome

### Browser Version

96.0.4664.93

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.0.0.0

### Video link where you see the problem

N/A

### What happened?

Click on extension button, click on "Github" link button, displays page not found. 
The link goes to https://github.com/Anarios/ryd but the repo has a different name.

**Comment by Anarios** [comment]
fixed in 2.0.0.1
