### ISSUE TITLE
(Bug): Showing NAN next to dislikes

### ISSUE THREAD

**Issue by KernalPenguino** [Anarios/return-youtube-dislike#298]
### Browser

Firefox

### Browser Version

Firefox 95.0

### Extension or Userscript?

Extension

### Extension/Userscript Version

Version 0.6.1

### Video link where you see the problem

https://www.youtube.com/watch?v=xTz1Aix647c

### What happened?

It shows NAN on the dislikes and it's not just in this video but also other videos
![image](https://user-images.githubusercontent.com/53450325/145921603-cfdbee65-c6e2-4d58-b30c-da285890b253.png)

**Comment by Anarios** [comment]
update to latest extesnion version, it's fixed

**Comment by Anarios** [comment]
Reopen if it's not
