### ISSUE TITLE
(Feature Request): 

### ISSUE THREAD

**Issue by MarcosLoq** [Anarios/return-youtube-dislike#299]
### Extension or Userscript?

Userscript

### Request or suggest a new feature!

Activate public counter of likes in videos where the counter of likes has been deactivated by the user

### Ways to implement this!

Greetings to the developer of this useful YouTube extension (coming soon to YT Vanced). I ask you to get to work on a function that allows you to see the likes in the videos whose user who uploaded the video has deactivated the public counter of likes for some reason or another.

See the example:
![image](https://user-images.githubusercontent.com/95730525/145926510-6bc5138c-5f0f-46e6-b973-25264eb30ea5.png)

Thanks in advance and keep working on fixing internal bugs and stuff.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by cupiditys** [comment]
personally dont think something like this will be added for not only the reasons stated on #196 but also it would significantly increase the database size for something thats probably only on less than 0.01% of videos (and only going down)

**Comment by Anarios** [comment]
Fill title
