### ISSUE TITLE
(Feature Request): Add button to watch age-restricted videos

### ISSUE THREAD

**Issue by UniqueName12345** [Anarios/return-youtube-dislike#302]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Certain videos are age-restricted, and since I don't seem to find any extension to add a button to ignore warning and watch video, but rather just watch the video by default, I want this to be a feature of this extension.

### Steps to implement this!

- [ ]  Scraping every age-restricted video and putting it in a database called "agerestrictedvideos", and everytime an extension user watches one of those videos, add a button.
- [ ] Using the cron job to see number of dislikes on video, then decide whether to hide the button or show it below the "Confirm" button.
- [ ] Add button that says "Whatever, just watch the video."
- [ ] If title says "ADULTS ONLY", add age confirmation.

### Can you work on this?

- [ ] Yes
- [ ] No

**Comment by Anarios** [comment]
Would breal google's "single purpose" rule for extesnions.

**Comment by UniqueName12345** [comment]
...then make a new extension?
