### ISSUE TITLE
[Suggestion] Make the like/dislike independent from YT.

### ISSUE THREAD

**Issue by IvoryOwl92** [Anarios/return-youtube-dislike#303]
First off, I apologize if someone suggested this before...

Since YT is dropping the API soon, which will harm the effectiveness of the extension... what if extension gave us the option to like/dislike the content we're watching, independently from YT? Like in the form a pop up, extra buttons, etc? This data would then be recorded and pass on to the developers so they can make better estimations or to update the like/dislike count?

**Comment by Anarios** [comment]
Api is already down, dislikes are already independent

**Comment by IvoryOwl92** [comment]
Off... I guess I was a bit slow on the uptake there...
Still, the suggestion stands, I hope?
