### ISSUE TITLE
there is a bug that you need to fix

### ISSUE THREAD

**Issue by josephcrosmanplays532** [Anarios/return-youtube-dislike#304]
so basically, when i disliked a video and reloaded it, it disapeared! i need you team to attempt to fix this bug if you can. here is video proof of it happening. https://www.youtube.com/watch?v=K2syzLMvsq8

**Comment by Anarios** [comment]
Just a visual bug, don't worry.

**Comment by josephcrosmanplays532** [comment]
k

**Comment by SamuelAnimates2006** [comment]
I need to fix this.
