### ISSUE TITLE
(Feature Request): Dislike ratio from comments

### ISSUE THREAD

**Issue by rumca-js** [Anarios/return-youtube-dislike#305]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

We already know that thumbs down API might not work in the future.

Instead we can promote an idea in community to create comments with precise text, lik "I dislike". The comment has upvotes. The number of upvotes on such comment would be equal to the number of downvotes.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by Sierra410** [comment]
There is already a database that tracks likes and dislikes of the extension's users.

**Comment by Sollace** [comment]
A major flaw with this is that people posting "I dislike" in comments all the time could be construed as spam and youtube's (already objectionable) bots would start to remove them automatically.

And that's precluding the uploaders themselves manually removing these comments, a problem that can extend even to those "like this comment to dislike the video comments". Comments in general are not a reliable way to judge a video's rating. The only thing we have to work with that can't be messed with in any way is upvotes vs views.

**Comment by Anarios** [comment]
api doesn't work since 13th. Comments are too unreliable, so not using it right now.
