### ISSUE TITLE
Please do NOT post issues about "NaN" in the dislike count!

### ISSUE THREAD

**Issue by Zenphia** [Anarios/return-youtube-dislike#306]
**This issue can be resolved by reinstalling the extension. Don't open issues every 5 minutes.**

**Comment by odog8** [comment]
may I say that the issue doesn't just display NaN, sometimes it displays 'Dislike' as if the extension isnt on

**Comment by Kiina** [comment]
What about getting NaN on the latest userscript?

**Comment by Write** [comment]
> What about getting NaN on the latest userscript?

Reinstall it. Worked for me

**Comment by smojphase** [comment]
I was having the NaN issue on Tampermonkey for Safari after reinstalling but what solved it was:
-Uninstall, close Safari, install again.

**Comment by Lalarian** [comment]
Hello!
What about the Tampermonkey script?
Disabling/Enabling or removing and reinserting did not help.
Thanks!

**Comment by pbates5** [comment]
I've uninstalled, closed my browser, and reinstalled both extension and tampermonkey userscript, I'm still only seeing "DISLIKE" for every video instead of the dislike count.

**Comment by woodrow73** [comment]
What fixed it for me was (in order) restarting chrome, disabling the extension, clicking on a YT video, then re-enabling it.

**Comment by Anarios** [comment]
No more reports, so closing this.
