### ISSUE TITLE
(Feature Request): dislikes

### ISSUE THREAD

**Issue by CrownScorpion** [Anarios/return-youtube-dislike#307]
### Browser

google chrome

### Browser Version

im not sure

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.0.0.1

### Video link where you see the problem

all videos

### What happened?

youtube updated and now all videos show 0 dislikes me and my bud have the same problem no matter what vid it shows 0 dislikes

**Comment by Anarios** [comment]
reisntall extension, restart chrome.
