### ISSUE TITLE
Dislike count not showing on latest Youtube rollout

### ISSUE THREAD

**Issue by odog8** [Anarios/return-youtube-dislike#308]
### Browser

Google Chrome

### Browser Version

Version 96.0.4664.110

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.0.0.1

### Video link where you see the problem

https://www.youtube.com/watch?v=3gypp2m_51s

### What happened?

The Dislike count is hidden on this video, even though I have the extension enabled.
![image](https://user-images.githubusercontent.com/36713157/146088886-c9aff8bb-2f69-4eb8-917a-4b67e31a2a82.png)

**Comment by k0lourful** [comment]
Firefox 95.0, ver 2.0.0.1, can confirm. Console output:
`[return youtube dislike]: {"likes":2894,"dislikes":null,"viewCount":82452} ryd.content-script.js:17:15`
Happens on all videos

**Comment by ArmokGoB** [comment]
Can confirm this is an issue on Firefox 95.0

**Comment by odog8** [comment]
if you dislike the video, it shows, but only one dislike.

**Comment by vsczpv** [comment]
Can also confirm, Firefox 95 on Linux.

**Comment by hades42** [comment]
Can confirm this issue on Brave Browser version 1.31.87. This dislike is disable on all the video on Youtube

**Comment by odog8** [comment]
apologies, this issue is the one and the same as the pinned issue. Please try reinstalling Return Youtube Dislike after uninstalling.

**Comment by Anarios** [comment]
Check again?

**Comment by hades42** [comment]
yes, reinstalling help me, the dislike button is working again

**Comment by WesselKroos** [comment]
Reinstalling did not work for me on Chrome, I'm still stuck on version 2.0.0.1. 
I guess the latest version will roll out at a later date for some Chrome users.

**Comment by LakesideWatchtower** [comment]
Reinstalling did not work on Firefox 96.0b5 not on Edge beta 97.0.1072.34. I'm on version 2.0.0.2.
