### ISSUE TITLE
(Feature Request): Implement webpack to use ES6 modules

### ISSUE THREAD

**Issue by leonbubova** [Anarios/return-youtube-dislike#310]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

It would be awesome if we setup webpack for this project. That way we would be able to use ES6 modules and could split our code up into different modules/files, as I started to do in [#282](https://github.com/Anarios/return-youtube-dislike/pull/282)

Right now it's not possible to do that, because the way chrome extensions are built prevents ES6 module usage.

### Ways to implement this!

Create package inside of the repo, install webpack, configure it so it behaves the same as it does right now, just with ES6 functionality.

I already finished that and made it work, but I do want to finalize that PR with a brief documentation on how to use webpack in the Get Started part of the [CONTRIBUTING.md](https://github.com/Anarios/return-youtube-dislike/blob/main/CONTRIBUTING.md)

### Can you work on this?

- [X] Yes
- [ ] No

**Comment by leonbubova** [comment]
This is covered in the following [PR](https://github.com/Anarios/return-youtube-dislike/pull/311)

**Comment by DARKDRAGON532** [comment]
Well i was adding parcel in #251

**Comment by leonbubova** [comment]
Ah shit, I had a look at the open PRs before to check for a webpack implementation, but I didn't recognize parcel to be honest, my bad :/

**Comment by DARKDRAGON532** [comment]
> Ah shit, I had a look at the open PRs before to check for a webpack implementation, but I didn't recognize parcel to be honest, my bad :/

its fine, i dont know whether its better to use parcel or webpack in this context, i guess ill leave it to Anarios to decide and then convert the codebase to typescript incase yours gets merged
