### ISSUE TITLE
(Bug): Neither extension or userscript are working

### ISSUE THREAD

**Issue by pbates5** [Anarios/return-youtube-dislike#313]
### Browser

Waterfox

### Browser Version

2021.10

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.0.0.1

### Video link where you see the problem

youtube.com

### What happened?

For a while I used the Tampermonkey script Youtube Restore Dislike Counters by syndiate. Unfortunately the removal of the API has made that script defunct, so I'm trying to switch to this one. Unfortunately neither the userscript or browser add-on is working for me, is it simply too late for me to try and install this now that the dislike data is gone?

**Comment by DARKDRAGON532** [comment]
It's working fine for me, is the extension throwing any errors? Have you tried reinstalling it a couple of times?

**Comment by Anarios** [comment]
Waterfox is not officially supported.
