### ISSUE TITLE
(Bug): 

### ISSUE THREAD

**Issue by shamshitty** [Anarios/return-youtube-dislike#314]
### Browser

Google Chrome

### Browser Version

Version 96.0

### Extension or Userscript?

Userscript

### Extension/Userscript Version

Version 0.6.1

### Video link where you see the problem

every video

### What happened?

Likes appear for a split second before appearing as "NAN". This appears to be happening on every video I click on.
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/68004605/146120880-eac99edc-a046-4e4a-b9c4-777cd1ca79c9.gif)

**Comment by shamshitty** [comment]
wait i just saw someone saying not to open issues regarding this problem, sorry

**Comment by DARKDRAGON532** [comment]
> wait i just saw someone saying not to open issues regarding this problem, sorry

Its alright, just update to the latest version and you should be fine.

**Comment by Anarios** [comment]
0.6.1 is ancient. Update
