### ISSUE TITLE
(Feature Request): Create your own database for dislikes now that the API is gone

### ISSUE THREAD

**Issue by kangarko** [Anarios/return-youtube-dislike#318]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

The idea is to create a "layer" above YouTube for dislikes.

There used to be an extension inserting its own comments above YouTube ones, now it's the time to insert your own dislike data and when clicked, issue a call to your own database from where they are fetched and shown properly now that the official API is gone.

We could use a cloud server such as Amazon AWS to distribute load. Users could sponsor this. 

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by sy-b** [comment]
That's exactly how it works!
