### ISSUE TITLE
Option for youtubers to share dislike count

### ISSUE THREAD

**Issue by omerson01** [Anarios/return-youtube-dislike#322]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

I think it will be a nice option for youtubers to share the dislike coint on thwir videos because they are the only ones that actually get the full data.

### Ways to implement this!

Read the dislike value from the stats page when the youtuber enters it. It is also possible to try and replicate the api request for it, although it will be a bit unsafe. It should also be a flag that they can turn on/off.

### Can you work on this?

- [X] Yes
- [ ] No

**Comment by JacksonChen666** [comment]
i believe this is already planned

**Comment by Anarios** [comment]
this is planned and there are a few duplicates
