### ISSUE TITLE
(Feature Request): Show archived like count

### ISSUE THREAD

**Issue by fourteen-1** [Anarios/return-youtube-dislike#325]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Feature where the dislike and like count as is currently is archived and shown? Letting the like count continue to increase while the dislike count is frozen in time can and will result in unfair ratios in the future. Maybe show the like count number at the time of archiving while hovering as a tooltip?

### Ways to implement this!

Show it as a tool tip on hovering over the Like/dislike count.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by Anarios** [comment]
In development
