### ISSUE TITLE
(Feature Request): Replace dislikes, with own dislikes coming from the AddOn

### ISSUE THREAD

**Issue by progward** [Anarios/return-youtube-dislike#327]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Since the dislikes definitely won't be accurate enough with the new system, I think it might be a good idea to replace the youtube dislikes entirely with your own. 

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by Anarios** [comment]
No, I prefer keeping the numbers close to youtube's. If there will be, in fact, a problem - it will be done.
