### ISSUE TITLE
(Feature Request): Documentation for integrations

### ISSUE THREAD

**Issue by bbilly1** [Anarios/return-youtube-dislike#328]
### Extension or Userscript?

Both

### Request or suggest a new feature!

I've been working on [TubeArchivist](https://github.com/bbilly1/tubearchivist/), a selfhosted YouTube media server and downloader. So I was wondering what your stance is on other services integrating in this API, both for getting ratings as well as posting back to your API. 

I know, your API is open and it's easy enough to reconstruct the requests, but I still wanted to ask.

### Ways to implement this!

So this will require a minimal amount of documentation to get started, for example:
- First a mention that this is *ok* to do for responsible netizens.
- API endpoints, expected return data and how the queries should be formed.
- Expected error messages
- Any restrictions like rate limiting
- Requirements for your monitoring like user agent string or headers

I know, early stages and things might change, but I think as long as the changes are documented and announced with some time, this would be ok.

### Can you work on this?

- [X] Yes
- [ ] No

**Comment by leonbubova** [comment]
Disclaimer: I am not sure what @Anarios stance is on "Is it ok to use the API for third-party apps/outside use" but if it's allowed/encouraged I would love to see an API documentation publicly available 👍🏻

**Comment by Anarios** [comment]
http://returnyoutubedislikeapi.com/swagger

Not documentation, but it's something.

Third party use is encouraged. There are a couple of requirements. 1. It should be clearly attributed. 2. There are rate limits of 100 per minute and 10 000 per day (but it can be adjusted if you contact me)

**Comment by bbilly1** [comment]
Thanks for your response. That sounds very reasonable, and yes, rate limiting shouldn't be a problem. I can make a pullrequest later against the readme to add a "API Documentation" section with some *getting started* info, to make sure you don't get more of the same questions here.

**Comment by Anarios** [comment]
I'd appreciate that.

**Comment by bbilly1** [comment]
There is another merge request describing a POST request and a python example link. Closing this issue now.
