### ISSUE TITLE
(Feature Request): Allow creators to connect their accounts to the API so the dislike counts can be pulled from their videos

### ISSUE THREAD

**Issue by ScamCast** [Anarios/return-youtube-dislike#329]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Allow creators to connect their accounts so their dislike counts can be pushed to the dislike API.

### Ways to implement this!

Youtube API

### Can you work on this?

- [ ] Yes
- [ ] No

**Comment by DARKDRAGON532** [comment]
In plan
