### ISSUE TITLE
(Feature Request): Stop request going to YouTube

### ISSUE THREAD

**Issue by mifi** [Anarios/return-youtube-dislike#338]
### Extension or Userscript?

Both

### Request or suggest a new feature!

First: I'm not sure if it's been suggested before as I don't know what to search for TBH. If it has already been suggested, maybe we can add it to the site's FAQ so you don't get more issues like this.

I love this extension, it's such a great initiative to put pressure on YouTube to hopefully reconsider their wrongdoings.

**Suggestion:** Make the extension **block** Like/Dislike requests to YouTube's servers. I don't see why we as users should even provide YouTube with this data *for free*, when they don't even give us the data back! This could put more pressure on YouTube if they see that they are missing out on like/dislike data analytics from the millions of users using this extensions.

BTW I checked devtools, and I can confirm that a request is still being sent to `/youtubei/v1/like/like` even with the extension installed.

What do you think about this?

### Ways to implement this!

Implement some code that blocks the default event handler on like/dislike buttons

### Can you work on this?

- [X] Yes
- [ ] No

**Comment by Anarios** [comment]
It might get the extension blocked as "malicious interfering with how website works".

**Comment by mifi** [comment]
What about the user script? It cannot be blocked, right?
