### ISSUE TITLE
(Bug): Seems like this isn't working anymore. Not sure if youtube removed the API or if the extension just broke.

### ISSUE THREAD

**Issue by vizthex123** [Anarios/return-youtube-dislike#340]
### Browser

Google Chrome

### Browser Version

96.0.4664.110

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.0.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=PDrooC2K9so

### What happened?

The dislike counter isn't showing the number anymore. Tried on several other videos and it still won't work.

**Comment by Voyajer** [comment]
I see 678 dislikes on that video

**Comment by MagentaPuppy** [comment]
try reinstalling the addon

**Comment by pbates5** [comment]
I've reinstalled the addon and userscript several times, restarted the browser (Waterfox), reinstalled and tested first the add-on then the userscript (on multiple videos), and I still have yet to see either one display dislikes on any video.

**Comment by anesuc** [comment]
Uninstalling and re-installing did it for me

**Comment by Anarios** [comment]
Contact me in discord if you can, may be a short screensharing session where we could debug it. Works for most people.

If you're behind NAT and there are REALLY many users on same IP - you could've been IP blocked for too many requests (so that's something I would need to adjust as well)

**Comment by Sirri69** [comment]
Not working for me either, I'm using Brave Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit). 

I'll be happy to send screenshots, screen recordings, or even hop on calls if that helps with debugging in any way.

**Comment by Anarios** [comment]
@Sirri69, if you can join discord (link available at our site) we could have a call - would be huge help for us

**Comment by jackc0re** [comment]
Since today, I don't see dislikes as well. Chrome 96.0.4664.110

**Comment by Anarios** [comment]
@jackc0re, try reinstalling extension. There is a a bug in chromium that causes service worker to randomly die and not start untill extension is restarted

https://bugs.chromium.org/p/chromium/issues/detail?id=1271154

**Comment by xenova** [comment]
All I had to do was disable, then re-enable the extension in chrome://extensions/

**Comment by cyrildtm** [comment]
Any feedback from OP? Is this still happening? Does the reinstall trick get around the bug at least for a while?

**Comment by vizthex123** [comment]
seems like it's been fixed now. I don't check github often, sorry for the late response.
