### ISSUE TITLE
(Bug): Dislike count is not shown from watching clip videos

### ISSUE THREAD

**Issue by JaylyDev** [Anarios/return-youtube-dislike#341]
### Browser

Google Chrome

### Browser Version

Chrome 96

### Extension or Userscript?

Extension

### Extension/Userscript Version

v2.0.0.3

### Video link where you see the problem

Every video clicked from youtube.com/clip/* (eg: https://www.youtube.com/clip/Ugkx1n_jkLEL2UqYHYhQAgsTubg39oXckcfy)

### What happened?

When an user clicked on a video via YouTube clip feature, dislike extension doesn't work. 
Assuming the extension only request dislike count when browsing https://youtube.com/watch?v=* and not including https://youtube.com/clip/*

**How to reproduce:**
- Create a clip from any video that supports clip feature
- Copy the clip url (starts with `https://youtube.com/clip/*`)
- Paste the URL

**Expected Results:**
- See the dislike count from videos clicked from `https://youtube.com/clip/*`

**Comment by vaguerant** [comment]
This is a known issue, see pull request #324.
