### ISSUE TITLE
(Feature Request): Green and red bar options

### ISSUE THREAD

**Issue by alidan** [Anarios/return-youtube-dislike#342]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Up till youtube killing the api, I used scripts to return the green and red dislike bar, I am wondering if its possible to make a green and red bar for like and dislike though this extension, possibly even user assignable colors for like and dislike. as it currently stands the contrast between dark grey and grey is very hard to notice, and while I can look at the numbers and see, it would be better if it was possible to do that at a glance. 

### Ways to implement this!

user options on the extension, its possibly already able to be done on the script, or possibly use the same parameters as other color changing scripts

https://greasyfork.org/en/scripts/12603-old-youtube-rating-colours/code 

is specifically what I use, i'm sure there are others. 

### Can you work on this?

- [ ] Yes
- [X] No

I have almost 0 ability to implement settings in well documented scripts, I would not be able to help.

**Comment by Anarios** [comment]
already suggested
