### ISSUE TITLE
(Bug): Possible bug with the API - Votes not being counted

### ISSUE THREAD

**Issue by leonbubova** [Anarios/return-youtube-dislike#343]
### Browser

Google Chrome

### Browser Version

96.0.4664.110

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.0.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=wYDJ0vxg1lU

### What happened?

Hey there, while extensively testing for https://github.com/Anarios/return-youtube-dislike/pull/282 I found some issues where the votes where not being correctly recognized by the API. Votes were being sent correctly in the background script and according to the network tab, but the response from the API always hat the same dislike count.

I thought I perhaps introduced some bugs in my branch and tested with the current main branch a well and found out that I had this problem there as well.

Are there some restrictions on the API that prevent me from sending anymore votes after a certain amount of testing? I must've sent around 100-200 requests to the API yesterday evening. I also tried this with various different videos.

Could someone double check for me, that current main and https://github.com/Anarios/return-youtube-dislike/pull/282 work correctly and that this is maybe caused by restrictions of the API?

I can make some screenshots or a short video showing the bug tomorrow, but I have to leave for today.

**Comment by Anarios** [comment]
Nah, it just doesn't change immediatelly. Or it can think that you're trying to bot the video, or some other reasons. You shouldn't see a change immediatelly.

**Comment by leonbubova** [comment]
> Nah, it just doesn't change immediatelly.
So it just does take some time for the votes to be recognized?
When I get back a confirmedVote call from the API, can I assume that everything is working as expected?

**Comment by Anarios** [comment]
> When I get back a confirmedVote call from the API, can I assume that everything is working as expected?

No, you can only assume that the PoW task was solved correctly. (but that's the only info that the client is going to get).

**Comment by Anarios** [comment]
So basically you, as a client, did everything correctly, yes.

**Comment by leonbubova** [comment]
I see, that's good to know. Makes me think that what I did in #282 is working as intended <3

Btw is the API code also open source? Would love to have a look at what's happening behind the scenes.

**Comment by Anarios** [comment]
> Btw is the API code also open source?

Not yet, too easy to bot votes if you have backend sources :( It will be available once we switch to google oAuth.
