### ISSUE TITLE
(Bug): Update website FAQ to reflect the deletion of the API that occured Dec 13th, 2021

### ISSUE THREAD

**Issue by stopmotio** [Anarios/return-youtube-dislike#347]
### Browser

Firefox

### Browser Version

FF 95

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.0.0.3

### Video link where you see the problem

this is not about the extension, but about the site

### What happened?

The site has not been updated to reflect the current state of the official API dislike. (dead) We should change it so that we still say how we originally got dislike counts, but that it is now estimates and old data.

I would do it myself but Vue scares me and I stick it pretty vanilla with my code, so I'm not sure if what I'll do will break it and I'm not in the mood to set up another IDE

**Comment by Techie-Pi** [comment]
This has been done recently in #362, although the change looks like isn't deployed yet

**Comment by thesusian** [comment]
I think this has been solved
