### ISSUE TITLE
(Feature Request): Version Number

### ISSUE THREAD

**Issue by UnderscoreX5** [Anarios/return-youtube-dislike#350]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Adding the version number to the extension could be really useful for troubleshooting, changelogs and safety + it's not hard to do.

### Ways to implement this!

Perhaps it could be formatted as v0.1 where v1 is the stable relase, but any other method works. It could be added in the extension's menu in the bottom right corner.

### Can you work on this?

- [x] Yes
- [ ] No

**Comment by himanshudabas** [comment]
Perhaps something like this:

![image](https://user-images.githubusercontent.com/20219940/146681578-0c787cd9-f85d-4a00-8415-ed464560d2bd.png)


are you working on this?

**Comment by UnderscoreX5** [comment]
Yes. I set up a pretty raw version of it. I tried making it show up above the buttons since it also looked good but it might be too distracting.

**Comment by cyrildtm** [comment]
Implemented in commit db666735e4edb4af69b51f352df25013e5119fb6

**Comment by Anarios** [comment]
Was implemented
