### ISSUE TITLE
(Feature Request): More Information about actualy Dislikes / Extrapolation

### ISSUE THREAD

**Issue by fukuimaunicorn** [Anarios/return-youtube-dislike#353]
### Extension or Userscript?

Userscript

### Request or suggest a new feature!

You mentioned the plugin now works by extrapolating the dislikes made by plugin users.

I would love to have the option to see the actual amount of dislikes made extension users and the extrapolated value. 

This is due to me apreciating the estimated values, but not fully trusting them. I don't know how well you are addressing biases like that plugin users are probably more attached to the dislike button than non plugin users, but mabye you're doing a great job. Nonetheless I'd love to see this, and I think this little bit of extra information could be really easy to build in, yet a great improvement to the plugin and it's authenticity. ^^

### Ways to implement this!

Maybe this extra information could be provided when hovering over the dislike button or count, in a small container.

Considering that the plugin already changes the dom, this should be rather easy to implement as long as your API supports it.

(To the "Can you work on this" I could definitly help, but I honestly don't think that I have the professionalism yet to take responsibilty for code in such a large plugin. So if I have some supervisor who I can ask for direction I could probably build it)

### Can you work on this?

- [X] Yes
- [X] No

**Comment by sy-b** [comment]
@fukuimaunicorn 

I suggest you to check if this issue is a duplicate

**Comment by himanshudabas** [comment]
we did discuss something like this,
here's something that I made some time ago:

https://user-images.githubusercontent.com/20219940/146689467-e8f57ea7-57a1-442e-b921-f442e45e8dea.mp4

(don't judge me for the color, icon or animations :), I literally used most of the code from a codepen )

**Comment by sy-b** [comment]
related to
#108 #114 #286 & #221 (closed)

**Comment by fukuimaunicorn** [comment]
Okay. I searched the other issues about "extrapolated" because that's what I really cared about so I over sighted. None of them really clearly mention the insights into the estemations that I would like but they are close enough as well as going in the same direction.
So I'm gonna close this here for now, for the sake of anyone moderating issues staying sane.

Sorry to bother, have a great Christmas ^^
