### ISSUE TITLE
Assign issues

### ISSUE THREAD

**Issue by VidithM** [Anarios/return-youtube-dislike#354]
Could we start assigning issues to people who volunteer to work on them? That way it will be easy to see which issues are already in progress and which need somebody to work on them

**Comment by Anarios** [comment]
Sure. Do you need additional permissions?

**Comment by VidithM** [comment]
Yes, write access is needed to assign issues

**Comment by Frontesque** [comment]
We have been working on trying to do this, but most people here don't volunteer to fix the issues. Join our discord if you haven't already for more information.
