### ISSUE TITLE
(Feature Request): Remove dislike buttons from comments

### ISSUE THREAD

**Issue by pcroland** [Anarios/return-youtube-dislike#355]
### Extension or Userscript?

Both

### Request or suggest a new feature!

It would be a nice little cosmetic. The dislike button on comments is really useless since it doesn't subtract from the like count and there's no dislike count on them.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by danielhjacobs** [comment]
I mean I wouldn't call the dislike button on comments useless.  It causes comments to go lower down in the comments section so you don't see them very easily when looking at the comments.  If you go on a video and you scroll to the very bottom of the comments section you'll usually see a comment that that that video's audience is very likely to disagree with.

**Comment by pcroland** [comment]
Hmmm, I did not know that, thanks.

**Comment by andymcblane** [comment]
I thought it did nothing (see thread) 

https://old.reddit.com/r/youtube/comments/aax7mh/what_does_the_dislike_button_on_youtube_comments/ed5fiup/

**Comment by UnderscoreX5** [comment]
As others pointed out it's not completely useless + it's a change that doesn't really make sense in this kind of extension

**Comment by Anarios** [comment]
I share opinion with comments above

**Comment by danielhjacobs** [comment]
> I thought it did nothing (see thread)
> 
> https://old.reddit.com/r/youtube/comments/aax7mh/what_does_the_dislike_button_on_youtube_comments/ed5fiup/

See https://old.reddit.com/r/youtube/comments/aax7mh/what_does_the_dislike_button_on_youtube_comments/ecwcbs8/. This is the accurate comment.  There's reason the bottom comment on Mario maker YouTubers I watch is often about how Mario Maker content sucks, has one like, and yet always shows up underneath comments with zero likes.

**Comment by andymcblane** [comment]
still isn't overly relevant for this extension
