### ISSUE TITLE
(Feature Request): Only display an approximate value of dislikes if YouTube also returns likes as an approximate value.

### ISSUE THREAD

**Issue by Pabszito** [Anarios/return-youtube-dislike#364]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

I don't know if I'm explaining this right, but here's the thing: for me, dislikes are displayed as "1,7 MIL" (as an example), while likes are displayed as an "exact value" (150.749).

Here's an example:
![image](https://user-images.githubusercontent.com/37744843/147273539-66c50bc1-c093-44ca-9be3-3c9ffb736254.png)

I can even see the exact amount of dislikes that the video has, so it shouldn't be that hard to implement it:
![image](https://user-images.githubusercontent.com/37744843/147273118-42000b14-fe1d-4447-9e68-f1c11caa09fa.png)

In case this couldn't be done; the extension could also modify the like count to an approximate value (just like the dislike count) if the user wanted to, but I don't see why wouldn't it be possible.

### Ways to implement this!

A way to implement this is checking if the like count is an exact value or an approximate one. Then, change the dislike button based to a different value using the like button.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by cyrildtm** [comment]
Could you provide a link to the video you used for screenshots? 
I looked at Youtube Rewind 2018, it tells me "3M" likes besides the thumbs up (yay), and "20M" dislikes besides thumbs down. I can't find a good example to replicate your case. 

Also, why does your screenshot says 1.7 million dislikes while the exact number is 1752? It doesn't seem to add up to me. 

Anyway, the code related to writing dislike count in "compact" format is here: 
https://github.com/Anarios/return-youtube-dislike/blob/cb2b100a18c86419131d94f881d1cb49800a5e5f/Extensions/UserScript/Return%20Youtube%20Dislike.user.js#L325

**Comment by Eleiber** [comment]
I know this isn't really important, but he probably uses the Spanish version of YouTube, in Spanish, "Mil" means thousand.

**Comment by Pabszito** [comment]
> Also, why does your screenshot says 1.7 million dislikes while the exact number is 1752? It doesn't seem to add up to me.

That's because I'm using the Spanish version of YouTube, as someone already said. Anyways, I don't think this is video-specific since I can click any video and it will be displayed just like the one I used as an example:

![image](https://user-images.githubusercontent.com/37744843/147684163-476362df-7f42-4cdf-94b1-f7cf416144bd.png)

I've also discovered that if the like counter is higher than 1 million it will be displayed with a compact format too:

![image](https://user-images.githubusercontent.com/37744843/147693288-5692bb22-d1f3-4c8f-b94b-a4ad0334da5a.png)

**Comment by cyrildtm** [comment]
tbh I remember watching this video a while ago. Here's what I see, with the abbreviation: 

![Capture](https://user-images.githubusercontent.com/5927301/147694057-a64169d9-18e9-4484-99db-f44aae84534f.PNG)


What extensions have you installed? I've just tried with incognito once and I didn't see the exact number.

**Comment by Pabszito** [comment]
> What extensions have you installed? I've just tried with incognito once and I didn't see the exact number.

Return YouTube Dislike, GitHub Red Issues, uBlock Origin, UniversalBypass and GNOME Shell Integration

I've enabled the extension to be able to run in private mode (firefox), and without signing in, this is what I see:

![image](https://user-images.githubusercontent.com/37744843/147695377-1258cd22-5e74-431c-968a-561b2eecdd80.png)

However, if I sign in, it goes back to the same thing as before:

![image](https://user-images.githubusercontent.com/37744843/147695431-7945166d-898d-4086-a593-e2f0cf46ad9b.png)

**Comment by cyrildtm** [comment]
So when you sign in with firefox private mode, it shows up with six figures? 
Then it's not with the plugins, but your youtube / google account settings, right? Do you remember if you have changed any settings, or does it come with your locale? 

If it's a thing with locale's default, then probably the dislike formatting can include a detection.

**Comment by Pabszito** [comment]
I haven't changed any settings on my Google account, so it seems to be locale related

**Comment by cyrildtm** [comment]
To see the exact number, these lines will need to be modified: 

https://github.com/Anarios/return-youtube-dislike/blob/cb2b100a18c86419131d94f881d1cb49800a5e5f/Extensions/UserScript/Return%20Youtube%20Dislike.user.js#L325

[Leaving the curly bracket empty works fine for me](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat). 

Also, the function `numberFormat()` returns a rounded down number:
https://github.com/Anarios/return-youtube-dislike/blob/cb2b100a18c86419131d94f881d1cb49800a5e5f/Extensions/UserScript/Return%20Youtube%20Dislike.user.js#L329

 using function `roundDown()` defined a few lines above. 

That's what I can see from the source code. But it's still strange to me that your default settings gives you exact numbers below one million, but rounds up for bigger ones. The cut-off line for me is one thousand. I'm still trying to understand this, but perhaps other people more fluent with web programming can explain. To me, it seems that Youtube is using some [customized version of number-shortening mechanism](https://stackoverflow.com/q/9461621/3839249) that is obviously doing differently for you. If that happens on the server side, there is probably nothing we can do, unless we implement an awkward way to visually check how the like counter is displayed. 



Plus on the programming side, correct me if I'm wrong, but why do we need to evaluate `userLocales` and `formatter` each time we need a number? It seems inefficient, and people don't seem to change their primary browser language between watching two videos.

**Comment by cyrildtm** [comment]
Here's a quick fix, just to make the like and dislike counters have the same style, but I don't like how I overwrite the youtube's like counter with the plugin's data --- is it always accurate and the same as yt's official data? 

https://github.com/Anarios/return-youtube-dislike/blob/cb2b100a18c86419131d94f881d1cb49800a5e5f/Extensions/UserScript/Return%20Youtube%20Dislike.user.js#L230

Before this line, insert: 

```
        setLikes(numberFormat(likes));
```


~~btw in function definitions for `setLikes()` and `setDislikes()` the buttons could have been assigned using wrapper functions `getLikeButton()` and `getDislikeButton()` it's not a big deal but I just can't unsee it.~~

**Comment by Pabszito** [comment]
> is it always accurate and the same as yt's official data?

If you open up inspect element you can see the exact amount of likes is not hidden, although you can't see it normally:

![image](https://user-images.githubusercontent.com/37744843/147711606-8ffb3a9a-2ba9-4ab2-8bc4-57400098cc7c.png)

**Comment by cyrildtm** [comment]
You are right. Then this should work: 
```
        setLikes(numberFormat( getLikeButton().querySelector("#text").getAttribute("aria-label").replace(/\D/g, '') ));
```

**Comment by cyrildtm** [comment]
On a second thought, we could have a toggling switch to say whether or not we want exact numbers on _both_ buttons. The function `numberFormat()` will adhere to the user's preference. It's always consistent.
