### ISSUE TITLE
(Bug): Dislikes no longer showing with this extension

### ISSUE THREAD

**Issue by ethrealdude791** [Anarios/return-youtube-dislike#367]
### Browser

Opera GX (i'm using the "add to opera" opera extension to add chrome extensions to opera)

### Browser Version

Opera GX 82.0.4227.50

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.0.0.3

### Video link where you see the problem

Pretty much any video I watch

### What happened?

The extension was working like normal until it just didn't show dislikes anymore. Did YouTube patch it or what?

**Comment by iyantae245** [comment]
Just uninstall the extension then install it again, it will work fine again.

**Comment by CagesThrottleUs** [comment]
I have tried on My Opera, it still works, perhaps look into suggestion by @iyantae245 ?

**Comment by DigidyDog** [comment]
> Just uninstall the extension then install it again, it will work fine again.

Going into Settings > Extensions > and just toggle the extension on then off > refresh the YT page and that fix it for me.

**Comment by Stef16Robbe** [comment]
@ethrealdude791 Has your problem been solved? You should close this issue if it has.

**Comment by Reoxur** [comment]
Restarting it worked for me

**Comment by Anarios** [comment]
Closing due to author inactivity
