### ISSUE TITLE
having trouble on Qutebrowser. Maybe write a greasemonkey script?

### ISSUE THREAD

**Issue by QMaury** [Anarios/return-youtube-dislike#37]
### Extension or Userscript?

Userscript

### Request or suggest a new feature!

Qutebrowser supports greasemonkey much better than whatever u guys are doin. I spent about 15-20 minutes fiddling around and I can't get the userscript workin

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by laughingsheep** [comment]
You will probably have to do this yourself since it's no a highly requested/needed feature.

**Comment by floriegl** [comment]
Is https://github.com/Anarios/return-youtube-dislike/blob/main/Extensions/UserScript/Return%20Youtube%20Dislike.user.js not working in greasemonkey?

**Comment by Frontesque** [comment]
Closed due to inactivity. Reply if this is still an issue.
