### ISSUE TITLE
(Feature Request):  Supporting Shorts

### ISSUE THREAD

**Issue by avi12** [Anarios/return-youtube-dislike#382]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Support showing the number of dislikes for videos under `/shorts/`, e.g. https://www.youtube.com/shorts/gIDU52bK8JM

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by Mouadabdelghafouraitali** [comment]
In fact, it's already supported : 

```
{
"id": "gIDU52bK8JM",
"dateCreated": "2021-12-28T22:56:35.394415Z",
"likes": 2409,
"dislikes": 177,
"rating": 4.716049382716049,
"viewCount": 41489,
"deleted": false
}
```

**Comment by avi12** [comment]
Right, but the "Dislike" label is still in place

**Comment by cyrildtm** [comment]
The short video viewing page on desktop shows several videos in a vertically scrollable list. Each dislike button besides a video should get a dislike count *correspondingly*.

**Comment by stapuft** [comment]
instead of making a new post about this, id like to voice my support for this feature as well.
https://www.youtube.com/shorts/NgviNJ_zhvg
currently ALL shorts show up as if i didn't have the extension installed at all, just saying "dislike" instead of showing an actual dislkie count.

**Comment by RyannDaGreat** [comment]
Can somebody pretty please add this?

**Comment by RyannDaGreat** [comment]
(By the way, to all those suffering: try this extension:
https://chrome.google.com/webstore/detail/youtube-shorts-block
This disabled youtube shorts altogether, making them normal videos - and thus bringing back dislikes with this extension)

**Comment by avi12** [comment]
@RyannDaGreat I don't like this approach
First off, I'm okay with a vertical video being in the Shorts format
Secondly, IMO it;'s not as critical to not show dislikes on Shorts, compared to regular videos, as Shorts are often for entertainment only, whereas regular ones include tutorials and all sorts of stuff that requires validations in a form of dislike counter

**Comment by cyrildtm** [comment]
> @RyannDaGreat I don't like this approach First off, I'm okay with a vertical video being in the Shorts format Secondly, IMO it;'s not as critical to not show dislikes on Shorts, compared to regular videos, as Shorts are often for entertainment only, whereas regular ones include tutorials and all sorts of stuff that requires validations in a form of dislike counter

You are right. The shorts feature was created specifically to induce short-term stimulation on watchers. The entire design, UI, content format, branding, targets the biochemical reward system in your brain and makes you happy. The big upright thumb is supposed to make you happier. There is no point of dislikes on shorts, as the content is too short to build reasonable context, and thus achieve comparable quality as regular videos.

**Comment by stapuft** [comment]
>

    @RyannDaGreat I don't like this approach First off, I'm okay with a vertical video being in the Shorts format Secondly, IMO it;'s not as critical to not show dislikes on Shorts, compared to regular videos, as Shorts are often for entertainment only, whereas regular ones include tutorials and all sorts of stuff that requires validations in a form of dislike counter

You are right. The shorts feature was created specifically to induce short-term stimulation on watchers. The entire design, UI, content format, branding, targets the biochemical reward system in your brain and makes you happy. The big upright thumb is supposed to make you happier. There is no point of dislikes on shorts, as the content is too short to build reasonable context, and thus achieve comparable quality as regular videos.

your are insaneo in the membraneo, i don't agree in the least, shorts are PURE EVIL, and there mere existence is worthy of a dislike from everyone on earth, just seeing one completely drains every bit of biochemical happy juice from my brain INSTANTLY. we all collectively agreed as a species that vertical VIDEOS WERE PURE UNADULTERATED EVIL over 10 years ago, when the old people started getting smartphones in droves and we had to teach them how to use phones properly......how people forgot about that is BEYOND ME...

**Comment by avi12** [comment]
YouTube started rolling out Shorts URLs in subscription feeds
Implementing the dislikes counter in a Shorts video is more relevant now

**Comment by RyannDaGreat** [comment]
I made a pull request for YouTube Shorts: https://github.com/Anarios/return-youtube-dislike/pull/511
