### ISSUE TITLE
(Feature Request): Plugin options

### ISSUE THREAD

**Issue by cyrildtm** [Anarios/return-youtube-dislike#387]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Implement a user option framework so one can change their preferences. Possible use cases are here (I'm counting open issues only): 

Percentage- 
#211 Display percentages by default (I think the point is to work out the math for the user without waiting for mouse hover)
Colors- 
#144 #186 Display a colored percentage besides video title
#218 Modify the ratio bar color scheme and include old-style green-red (maybe custom color code as well)
Number format- 
#201 #364 #407 Format the button counter numbers the way you like: compact & approximated or full exact; also cover more locales

### Ways to implement this!

Storage framework is implemented in #410. Tracking tasks: 
- [ ] Number format (more of a bug than a feature)
- [ ] Colorized bar and buttons
- [ ] Percentage display without clicking or hovering

I don't know how to do this in userscript -- perhaps store options as a constant?

**Comment by cyrildtm** [comment]
I noticed the addition of local/synced storage and advanced settings page. Ok I will try and spend some spare time to implement at least some of those I have mentioned.

**Comment by ErykDarnowski** [comment]
Maybe a dict with would be a nicer option to store that data compared to constants. 🤔

**Comment by sy-b** [comment]
👍

**Comment by cyrildtm** [comment]
Maybe, but depends. Since the function returning color strings is called once for every video, and once every time you select a new scheme in the popup, and since we don't have a million colors to store, there is no real performance gain. Readability does not get improved either, since you will need to keep a separate paragraph to actually write down the colors. There is little to no storage space save; noting that popup and content script must absolutely not share anything per security requirements. 

One possible way to reduce eye strain: 
https://github.com/cyrildtm/return-youtube-dislike/blob/f218443b4c8799491a6662e5ee2be0057c56d40b/Extensions/combined/src/utils.js#L136

```
    case 'classic':
    default:
       colorString = voteIsLike ? 'lime' : 'red';
```

But we are considering light/dark theme adaptive colors at this moment, so this may not help at all.
