### ISSUE TITLE
(Bug): Minor bug when video has the like and dislike buttons disabled

### ISSUE THREAD

**Issue by snail5008** [Anarios/return-youtube-dislike#389]
### Browser

Firefox

### Browser Version

95.0.2 (64 bit, windows 11)

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.0.0.3

### Video link where you see the problem

https://www.youtube.com/watch?v=U3lWVLuc6CE

### What happened?

Found this (very minor) bug on videos where the creator has disabled likes and dislikes, the dislike button count is `0`, and the like button has just the word `LIKE` on it.

What I would expect is that the both buttons should have `LIKE` and `DISLIKE` respectively, it would make it much clearer that the creator had disabled likes and dislikes, rather than seeming as if it has no likes.

Just a cosmetic update, but it could easily be solved (I think, haven't looked at the code a lot, also not familiar with extensions) by just implementing something like this?:

```js
var LIKE_BUTTON_CONTENT = "SOMETHING";
var DISLIKE_BUTTON_CONTENT = "SOMETHING";

...

function check_voting_disabled() {
    if (LIKE_BUTTON_CONTENT == "LIKE" && DISLIKE_BUTTON_CONTENT == "0") {
        DISLIKE_BUTTON_CONTENT = "DISLIKE";
    }
}

...

check_voting_disabled();
```

Anyway just something that might slightly improve this extension, assuming that I am on the latest version, and this isn't known.

**Comment by wesleynepo** [comment]
I agree with you, lets keep the default behaviour on it.

**Comment by ExplodieSway** [comment]
Agreed.

**Comment by cyrildtm** [comment]
Without the plugin the dislike button should always say "DISLIKE"

![Capture](https://user-images.githubusercontent.com/5927301/147832303-5be1d2b8-c147-4475-ad4b-5f50b930e0dd.PNG)

https://github.com/Anarios/return-youtube-dislike/blob/2d23250e80df34e1fee576ad8d7d2b95e362f0a4/Extensions/UserScript/Return%20Youtube%20Dislike.user.js#L221

```
if (getLikeButton().querySelector("#text") && getLikeButton().querySelector("#text").innerText !== 'LIKE') { // like counter is not displayed
....
}
```

**Comment by cupiditys** [comment]
#209

**Comment by leonhma** [comment]
I have the same 'problem'. How about likes are also recorded in addition to dislikes for extension users (either no interpolation or via the view count), so we can enable "targeted like-attacks against creators" again?
