### ISSUE TITLE
(Bug): Woop, here goes youtube and removing dislike count in their api

### ISSUE THREAD

**Issue by TruncatedDinosour** [Anarios/return-youtube-dislike#400]
### Browser

Firefox

### Browser Version

Mozilla Firefox 95.0.1

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.0.0.3

### Video link where you see the problem

https://www.youtube.com/watch?v=dQw4w9WgXcQ

### What happened?

A bug happened!

And it doesn't work anymore

**Comment by Anarios** [comment]
YoutubeAPI is closed since December 13th.

**Comment by TruncatedDinosour** [comment]
> YoutubeAPI is closed since December 13th.

What? It still worked yesterday

**Comment by JacksonChen666** [comment]
> > YoutubeAPI is closed since December 13th.
> 
> What? It still worked yesterday

may want to read this: https://returnyoutubedislike.com/faq

**Comment by hrichiksite** [comment]
i got rick rolled damm it
