### ISSUE TITLE
(Bug): Likes count should be visible even if the extension can't get the dislike count

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [Anarios/return-youtube-dislike#403]
### Browser

Google Chrome

### Browser Version

96.0.4664.110 (Build officiel) (64 bits)

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.0.0.3

### Video link where you see the problem

https://www.youtube.com/watch?v=AWEm4tA2hMc

### What happened?

![image](https://user-images.githubusercontent.com/24398682/147883950-fd2aadb8-8b74-468a-9316-9fc8bdaf6a30.png)

Why the likes count is not available, the extension should return the likes counts from the YouTube API when no data is found for the targeting video

```
{
"id": null,
"dateCreated": "2022-01-02T17:20:41.7736266Z",
"likes": 0,
"dislikes": 0,
"rating": 0,
"viewCount": 0,
"deleted": false
} 
```

**Comment by sy-b** [comment]
@Mouadabdelghafouraitali 
that video has its likes & dislikes disabled by the creator
so dislike extrapolations isn't possible

**Comment by Mouadabdelghafouraitali** [comment]
@sy-b  massive thanks, I didn't know that
