### ISSUE TITLE
(Bug): 404 status on documentation link in readme

### ISSUE THREAD

**Issue by GeneticallyModifiedAlex** [Anarios/return-youtube-dislike#405]
### Browser

Firefox

### Browser Version

95.0.1

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.0.0.3

### Video link where you see the problem

not applicable

### What happened?

whilst browsing the readme file of the GitHub repo I clicked on the documentation link whilst a lofi stream was running in the background. The documentation link opened a new tab and continued to the selected address but I got a 404 status as seen below: The link likely needs updating due to a typo of some kind.
I looked in the pages folder and found the page documentation.vue but also found the documentation folder.
(there is a closing </nuxtchild> without an opening one in documetation.vue idk vue js well enough to know if this is important)

The requested content does not exist.

    HttpStatusCode: 404
    ErrorCode: WebContentNotFound
    RequestId : 14fd8dd0-c01e-0043-2d26-003fee000000
    TimeStamp : 2022-01-02T22:17:50.1745929Z

**Comment by pgamerx** [comment]
+1

**Comment by Anarios** [comment]
No API docs yet, removed the link from readme

**Comment by GeneticallyModifiedAlex** [comment]
alright thanks. is there anything i can do to help with the API, I'm pretty good at documentation building

> No API docs yet, removed the link from readme
