### ISSUE TITLE
(Feature Request): show likes/dislikes below video thumbnails on the home and side pages

### ISSUE THREAD

**Issue by jazzl0ver** [Anarios/return-youtube-dislike#406]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Hi and thanks for the extension! Is there a chance to show an amount of likes/dislikes on the home and side pages? that would be helpful to sort out disliked videos without opening it.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by cyrildtm** [comment]
might be duplicate of #48 see if solution there helps you.

**Comment by jazzl0ver** [comment]
yeah, looks good, thank you! it would be great to add the solution to the FAQ
