### ISSUE TITLE
(Bug): Localized large dislike numbers are incorrect for some languages

### ISSUE THREAD

**Issue by PoomSmart** [Anarios/return-youtube-dislike#407]
### Extension or Userscript?

Both

### Request or suggest a new feature!

For all dislikes greater than 999 and certain non-English languages like Thai, RYD only formats them in K, M and B.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/3608783/148390842-0303e8bb-ca27-4ec7-85ea-7e32bcf1e976.png">

They look apart. Note that "5.8 หมื่น" (Thai) translates to "5.8 ten-thousands" which is 58000. As for dislikes, it is "1.3 พัน" in Thai (1.3 thousands).

### Ways to implement this!

You will write it like this for Thai locale:

```js
new Intl.NumberFormat('th-TH', {
  notation: "compact",
  compactDisplay: "long"
}).format(58000); // return 5.8 หมื่น
```

We may need a mapping between locale and `compactDisplay` value?

Or, do this?

```js
const formattedEn = new Intl.NumberFormat('en-US', { notation: "compact" }).format(dislikes);
let result = new Intl.NumberFormat(targetLocale, { notation: "compact" }).format(dislikes);
if (formattedEn.localeCompare(formattedLocalized) != 0) {
    result = new Intl.NumberFormat(targetLocale, { notation: "compact", compactDisplay: "long" }).format(dislikes);
}
```

### Can you work on this?

- [X] Yes (but it may be somewhat messy)
- [ ] No

**Comment by cyrildtm** [comment]
Current implementation is already taking browser locale for number formatting
https://github.com/Anarios/return-youtube-dislike/blob/2aeb21493319a01f8474c2b70903b07732b46e15/Extensions/combined/src/utils.js#L12
https://github.com/Anarios/return-youtube-dislike/blob/2aeb21493319a01f8474c2b70903b07732b46e15/Extensions/UserScript/Return%20Youtube%20Dislike.user.js#L316

Can you run the cited command in your browser console and see what's the result?

**Comment by PoomSmart** [comment]
@cyrildtm Oh. I totally missed that part. Speaking of that code, the locale will be `document.documentElement.lang` and its value is `th-TH`. The formatted number is `90K` if I input `90000`.

**Comment by PoomSmart** [comment]
I updated the issue title and description to reflect the current code.

**Comment by cyrildtm** [comment]
> It looks like `compactDisplay: "long"` is required for certain languages.

I tried and you are right, it's necessary for what you want to achieve, although I don't understand Thai. 

I'm not sure if preparing every language from our user base in a look up table is practical. Instead I have a possible workaround that is to let user decide the two options: `notation` and `compactDisplay` in user options: #387

**Comment by PoomSmart** [comment]
@cyrildtm That looks like a good workaround. 👍🏻
