### ISSUE TITLE
(Feature Request): Option to not run on unlisted or private videos

### ISSUE THREAD

**Issue by FrostBird347** [Anarios/return-youtube-dislike#41]
### Extension or Userscript?

Both

### Request or suggest a new feature!

There needs to be a way to prevent this script from running on unlisted or private videos.

### Ways to implement this!

This is a large privacy issue that can be fixed by checking the page for a private or unlisted badge before using the API.
![badge](https://user-images.githubusercontent.com/39435218/143024891-5fc06edf-76d0-4b2d-89ae-1958fcf2d960.png)

Below is an unoptimised function that checks if a video is private or unlisted.
```js
function CheckPublic() {
    for (var i = 0; i < document.getElementsByClassName("ytd-badge-supported-renderer").length; i++) {
        if (document.getElementsByClassName("ytd-badge-supported-renderer")[i].textContent == "Unlisted" || document.getElementsByClassName("ytd-badge-supported-renderer")[i].textContent == "Private") {
            return false;
        }
    }
    return true;
}
```

### Can you work on this?

- [ ] Yes
- [ ] No
- [x] Unsure

**Comment by Anarios** [comment]
We don't have any data for unlisted videos right now, so there is nothing to display.

**Comment by Anarios** [comment]
Even though the script runs on unlisted videos - it does nothing. But yeah - we'll add code to skip it.

**Comment by Frontesque** [comment]
Closed due to inactivity. Reply if this is still an issue.
