### ISSUE TITLE
(Feature Request): Freetube Integration

### ISSUE THREAD

**Issue by RippedCornet391** [Anarios/return-youtube-dislike#412]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Hi!

I'm creating this issue to ask about integration with FreeTube (freetubeapp.io), a YouTube desktop client app. When I looked at FreeTube's GitHub page, the developers said that they were considering adding the service, but that they had a few concerns before they would be willing to do so. I have left a link to the developer's message below.

https://github.com/FreeTubeApp/FreeTube/issues/1927#issuecomment-1007121970

Will any of these things be addressed? I'm not a developer myself, so I'm not sure how difficult this would be or whether you would be willing to discuss this with the FreeTube developers, but I would greatly appreciate it if I could use FreeTube with Return Youtube Dislike integration in the future.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by Anarios** [comment]
It's up to Freetube team to integrate it.

**Comment by RippedCornet391** [comment]
Hi,

It seems like you may have misinterpreted my question. I understand that the integration would be up to FreeTube, but I was wondering whether any of the requests their developers made in regard to privacy will be addressed (as it seems like that is the only way they would be willing to add the feature). Here is part of what they said.

> FreeTube is a privacy first application...Adding something that could potentially compromise privacy would not be worth adding as a feature...To summarize, in order for us to consider implementing the ReturnDislike service (Or any of them for that matter), these are my requirements:
>
> - Add a fully detailed privacy policy to your website. I had to dig around to find this Security Page. This information should be much more accessible than it is currently.
>
> - Open source everything. From what I can tell, the back end is still closed source. Add instructions on how to build and deploy this server. I should be able to set this up on my own hardware.
>
> - Include a way to download a dump of your database. It doesn't have to be up to date with the production data. A snapshot even once a week should suffice. I should be able to import this data into your back end software and run a full copy myself.

From what the developer mentioned, it seems like they are holding off on integrating Return Dislike out of privacy concerns. Given this, my question isn't whether integration is possible, but rather: **Will any of these requests will be addressed in the future?**

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @Anarios is it possible to review @BagelSeasoning234 comment. 

We would like to know if your open to implement the requested changes.
