### ISSUE TITLE
(Bug): Content script contains localhost

### ISSUE THREAD

**Issue by kotx** [Anarios/return-youtube-dislike#413]
### Browser

This issue affects both the Chrome and Firefox extensions. 

### Browser Version

Firefox (95.0.2)

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.1.0

### Images
![image](https://user-images.githubusercontent.com/33439542/148663430-19600fd7-c502-4fa7-8496-2675a1353a16.png)

### What happened?

The [Chrome](https://github.com/Anarios/return-youtube-dislike/blob/main/Extensions/combined/manifest-chrome.json#L32) and [Firefox](https://github.com/Anarios/return-youtube-dislike/blob/main/Extensions/combined/manifest-firefox.json#L26) extension manifests request content script access to localhost. This can appear concerning for users, and is only really used in development (hopefully). It would be good to remove it from the manifest for the published extensions.
I could help with a PR for this, but I wasn't sure how it would affect your dev env.

**Comment by JacksonChen666** [comment]
just update again (to v2.1.0.1), Anarios seemed to have made a mistake of pushing the development extension to production, which also didn't work.

**Comment by kotx** [comment]
It seems the Firefox extension still hasn't been fixed @ v2.1.0.1?

**Comment by Anarios** [comment]
Fix is out.

**Comment by Frontesque** [comment]
Yea this was my bad. Forgot to remove this
