### ISSUE TITLE
(Bug): False amount of dislike (because of late update)

### ISSUE THREAD

**Issue by Loeiks** [Anarios/return-youtube-dislike#417]
### Browser

Edge

### Browser Version

Version 97.0.1072.55 (Official build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.0.0.3

### Video link where you see the problem

https://www.youtube.com/watch?v=HNuO1ZEh3Po

### What happened?

This is my own video and real dislike count shown on YouTube Studio is 25 but "Return YouTube Dislike" shows 24 probably it's updating dislikes hourly or daily I don't know if this is the reason please fix because we should see new dislikes after the refreshing video page.

**Comment by Ycmelon** [comment]
Check out https://www.returnyoutubedislike.com/faq

> **Why isn't the dislike count updating?**
> Right now video dislikes are cached and they aren't updated very frequently. It varies depending on a video's popularity but can take anywhere between a few hours and a few days days to update. 

Anyway the dislike counts displayed aren't going to be perfect, it's only an estimation...
