### ISSUE TITLE
(Bug): Chrome says extension requires access to all sites 

### ISSUE THREAD

**Issue by Mart-Bogdan** [Anarios/return-youtube-dislike#418]
### Browser

Google Chrome

### Browser Version

Version 96.0.4664.110 (Official Build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.1.0.2

### Video link where you see the problem

In menu of chrome

### What happened?

Chrome say extension requires to allow access to all sites .

![image](https://user-images.githubusercontent.com/775038/148685127-4f94366b-1b01-4a4f-aa55-ebfd02e8a82c.png)

that's weird because in https://github.com/Anarios/return-youtube-dislike/blob/main/Extensions/combined/manifest-chrome.json it is only:
```json
  "content_scripts": [
    {
      "matches": [
        "*://youtube.com/*",
        "*://www.youtube.com/*",
        "*://m.youtube.com/*"
      ],
      "exclude_matches": ["*://*.music.youtube.com/*"],
      "js": ["bundled-content-script.js"],
      "css": ["content-style.css"]
    },
    {
      "matches": ["*://*.returnyoutubedislike.com/debug"],
      "js": ["debug.js"]
    }
  ],
```

**Comment by duckyb** [comment]
Same issue and clicking on "accept" crashes Chrome.
After reopening it the popup is back.

**Comment by Anarios** [comment]
Not "all sites" but all "returnyoutubedislikeapi" sites. (i.e. all subdomains of this site)

**Comment by avi12** [comment]
Why require accessing the site in the first place?

**Comment by Anarios** [comment]
Because we need to get dislike counts somewhere, and it's our api address.

**Comment by avi12** [comment]
You should leave the issue open so future users won't open an issue about this as well

**Comment by duckyb** [comment]
Future users should search across all issues before creating a new one, not only the open ones.

**Comment by avi12** [comment]
That's what we want to happen, but the reality is often different
A few weeks ago, YouTube broke one of my extensions, and by having an issue open despite the fix being on its way to the CWS, it signaled newcomers not to open a new one as I was aware of the issue

**Comment by Anarios** [comment]
I'll reopen if duplicates will be popping up.

**Comment by SLCH** [comment]
For me it asks to access localhost as well

**Comment by Mart-Bogdan** [comment]
> Not "all sites" but all "returnyoutubedislikeapi" sites. (i.e. all subdomains of this site)

lol chrome is wierd. And they really should've add " as in your reply :D  

Chrome tailored it's messages to not tech savvy people who don't know what is * to confuse people who do know :D
