### ISSUE TITLE
(Bug): sending vote request for non-youtube videos

### ISSUE THREAD

**Issue by 11h00** [Anarios/return-youtube-dislike#420]
### Browser

Google chrome

### Browser Version

 96.0.4664.110 (Build officiel) (64 bits)

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.1.0.2

### Video link where you see the problem

https://youtubelikecounter.com/#!/L6o3GUxb0m0 - this is not a video!

### What happened?

hello, i was watching my comment count on livecount, and then opened the devtool to check some things for fun, then seen some 429 request from your api,
look like it think im on youtube but i am not, now i cant see the dislike count because im rate limited :[
this is the trace id in case you need: 00-4bb175eb602bfee6d5681a5de6805394-7272d22e46154990-00

(if you can restaure my accsess too bacause it suck to no have the dislike)
![the bug on the website](https://i.ibb.co/LYFyKTc/Capture-d-cran-2022-01-09-193040.jpg)

**Comment by Anarios** [comment]
Hi, that's some site that uses our API without a permission, once you reach the limit of requests - you can' make any more requests.

**Comment by Anarios** [comment]
The limit is 100 per minute and 10k per day. Once the limit is reset - you'll have access again.

**Comment by Anarios** [comment]
This site is basically a spam-machine for our API though, and it lacks proper attribution.

**Comment by 11h00** [comment]
https://youtubelikecounter.com/#!/L6o3GUxb0m0
it do no use your API to get video stats,
they have ther own API: https://api.livecounts.io/youtube-live-view-counter/stats/L6o3GUxb0m0
and its happening on all things about youtube related

**Comment by Anarios** [comment]
![image](https://user-images.githubusercontent.com/3018711/148707152-feead1bc-3c23-4198-8694-4dc309966f7f.png)

> it do no use your API to get video stats,
> they have their own API:

Suuure.

**Comment by 11h00** [comment]
also i tried to run the website on inconignto (without the extention) and look like it seem fixed,

werd
