### ISSUE TITLE
(Bug): No longer works

### ISSUE THREAD

**Issue by Pentazer** [Anarios/return-youtube-dislike#424]
### Browser

Brave

### Browser Version

Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

v2.1.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=8L7v3vRA65E

### What happened?

It suddenly stopped working today.
Applies to every video on youtube.

**Comment by JacksonChen666** [comment]
please try [troubleshooting steps](https://returnyoutubedislike.com/help)

**Comment by Mouadabdelghafouraitali** [comment]
![image](https://user-images.githubusercontent.com/24398682/148705392-91aefa96-02e3-42b3-a669-e607a35d0c93.png)


Try to uninstall and install the extension once again

**Comment by 11h00** [comment]
did you got rate limited?
(you can check it on your devtool i think)

**Comment by jahanzebshayan** [comment]
![image](https://user-images.githubusercontent.com/54780443/148708019-273d41c4-8450-4afe-9fd0-500fd1d9a299.png)

chrome disabled it after latest update

**Comment by Anarios** [comment]
@jahanzebshayan , yes because it asks for new permission - access to returnyoutubedislike.com (used to show debug data when visiting https://returnyoutubedislike.com/debug ).

Just re-enable it

**Comment by Pentazer** [comment]
I've uninstalled it, reinstalled it, disabled it and re-enabled it and it's still not working anymore.
![Screenshot 2022-01-09 182336](https://user-images.githubusercontent.com/54109677/148709152-b2057db8-ff42-4cc4-81f0-de626c7f6898.jpg)
Every time I start brave now, it shows as inactive. Disabling and re-enabling removes the mention of it being inactive, but the extension still does not function.

**Comment by 11h00** [comment]
i had this problem too, i need to accept the new permission

**Comment by JacksonChen666** [comment]
> i had this problem too, i need to accept the new permission

...so accept it

**Comment by Anarios** [comment]
Since many people had this problem - all new permissions were removed.

**Comment by Pentazer** [comment]
> i had this problem too, i need to accept the new permission

As far as I can tell, they are:
![Screenshot 2022-01-10 064526](https://user-images.githubusercontent.com/54109677/148776249-f1a56c38-240b-4ec7-959d-f780a92deb34.jpg)

**Comment by Anarios** [comment]
I don't have those permissions requested 
![image](https://user-images.githubusercontent.com/3018711/148777101-6d39d4c8-3209-402a-8347-6e26b85256a6.png)

**Comment by Pentazer** [comment]
Just to be sure, I reinstalled it just now and yeah, still doesn't work.

**Comment by Anarios** [comment]
what do you see when you open https://returnyoutubedislikeapi.com/votes?videoId=QOFEgexls14 ?

Which other extensions do you have?
