### ISSUE TITLE
(Feature Request): Value of like/dislike ratio for existing and new videos

### ISSUE THREAD

**Issue by benjaminvanrenterghem** [Anarios/return-youtube-dislike#429]
### Extension or Userscript?

Both

### Request or suggest a new feature!

**Suggestion 1** 

Nice work on the service. This is a fairly short request, and it'll become more important the longer the feature is no longer natively provided by Youtube:

- to provide an indication as to what percentage of the likes and dislikes originated from interaction with the extension and what amount stems from your pre-removal data set

The reason this would be helpful is that **the value of the like to dislike ratio goes down the more time progresses for existing videos**. 

**For new and more recent videos the problem is already apparent** in that your service may still track new dislikes but it is displayed next to the likes of the platform. 

The ratio is thus of little value as the entire userbase of Youtube is magnitudes larger than that of the service and will thus outweigh the dislikes and skew the ratio with bias for likes.

Quantified example:
- new video posted 30 days ago
- 20K likes produced by a [potential 2b+ users](https://www.statista.com/statistics/1252627/youtube-app-mau-worldwide/)
- 500 dislikes produced by [1m+ users](https://chrome.google.com/webstore/detail/return-youtube-dislike/gebbhagfogifgggkldgodflihgfeippi) of your service
- thus, ratio may indicate that it is a high quality video while it is not

**Suggestion 2**

Might want to consider using Google OAuth so a bad actor can't artificially inflate dislikes using proxies and repeat-requests.
This may be debated from a privacy perspective, not allowing duplicates based on IP seems like the bare minimum.

### Ways to implement this!

Suggestion 1:
- Store both likes and dislikes and differentiate, provide user with this differentiation/ratio

Suggestion 2:
- optionally OAuth
- IP duplicate filtering

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by sy-b** [comment]
Suggestion similar to:
#114,  #353 (closed),  #221(closed)

**Comment by sy-b** [comment]
Suggestion 1 similar to:
#114, #353 (closed), #221(closed)

**Comment by cyrildtm** [comment]
> Suggestion 1

That's not the way it works. The dislike count is extrapolated using available data from extension users.
Read: https://github.com/Anarios/return-youtube-dislike/issues/330#issuecomment-995838302

> Suggestion 2

Already implemented in a different way to protect privacy. 
Read: [Security FAQ](https://github.com/Anarios/return-youtube-dislike/blob/main/SECURITY-FAQ.md)

**Comment by Anarios** [comment]
> Quantified example:
> 
> new video posted 30 days ago
> 20K likes produced by a potential 2b+ users
> 500 dislikes produced by 1m+ users of your service
> thus, ratio may indicate that it is a high quality video while it is not

that's not how it works.

**Comment by benjaminvanrenterghem** [comment]
Thanks for the replies. Good to know that others have pointed this out already.
You describe it as following [here](https://github.com/Anarios/return-youtube-dislike/issues/330#issuecomment-995838302):
```So, in the end - if there's no archived data - you won't see actual number of dislikes, you will see a number of dislikes that the video would have had if all the viewers shared opinion with extension users. Far from ideal - but I didn't come up with anything better.``` which addresses the ratio problem already. Thanks for linking it, cyrildtm.

The remaining part of the suggestion would then be to provide a breakdown of sorts so the user knows the amount has been adjusted and by what logic, could be a simple implementation using a hover tooltip or otherwise.
