### ISSUE TITLE
(Bug): Only shows 91 dislikes on all videos

### ISSUE THREAD

**Issue by barral69gaming** [Anarios/return-youtube-dislike#434]
### Browser

Microsoft Edge

### Browser Version

Version 96.0.1054.62 (Official build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.1.0.3

### Video link where you see the problem

https://youtu.be/NxNi0vDs5tc

### What happened?

A bug happened! I noticed that no matter what video I watch, even ones that have only been live for a few hours, show 91 dislikes. This number is always the same. I used the video linked about as the example, but ALL videos show this number.
For another example..
https://youtu.be/r1zlqdbvf4M
I know this number to be inaccurate here as this is a vod of my live stream. It hasn't even had 20 views, so 91 dislikes is impossible.

**Comment by Cequallium** [comment]
have you tried reinstalling the extension? 
The api itself shows 0 dislikes: https://returnyoutubedislikeapi.com/votes?videoId=r1zlqdbvf4M

**Comment by barral69gaming** [comment]
I will try that now.

**Comment by barral69gaming** [comment]
That seems to have fixed it. Now it seems the count is accurate again. Thank you. :)
