### ISSUE TITLE
(Bug): *Dislike disabled*

### ISSUE THREAD

**Issue by 11h00** [Anarios/return-youtube-dislike#437]
### Browser

Google chrome

### Browser Version

 96.0.4664.110 (Build officiel) (64 bits)

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.1.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=xVlT5zwgg0M

### What happened?

Hello. i again have a problem with the extention (one time again sorry)
this time its about the like dislike count not showing at all.
when i open the devtool it say :

`
[return youtube dislike]: response from api:
bundled-content-script.js:71 [return youtube dislike]: {"id":null,"dateCreated":"2022-01-12T09:57:40.8341496Z","likes":0,"dislikes":0,"rating":0,"viewCount":0,"deleted":false}
bundled-content-script.js:71 [return youtube dislike]: *likes count diabled by creator*
bundled-content-script.js:71 [return youtube dislike]: *removing bar*
`
i think its a bug because the ID of the shearched video say null.

![Capture d’écran 2022-01-12 134353](https://user-images.githubusercontent.com/72752622/149142846-0ae5901a-69b2-4e52-8b45-89e83ccc5775.jpg)

**Comment by Anarios** [comment]
Hi, this video has likes and dislikes disabled by creator, we don't show any stats for such videos yet (we might in future).

**Comment by 11h00** [comment]
thanks your for the fast reply and alright, i forgot about than the creators could hide ther like/dislike before (youtube fucked it up lmfao!!!)
have a nice day :)
