### ISSUE TITLE
How exactly does the dislike count calculate after YouTube API stops returning the dislike count?

### ISSUE THREAD

**Issue by fxavierho123** [Anarios/return-youtube-dislike#438]
In FAQ,
`The backend will switch to using a combination of archived dislike stats, estimates extrapolated from extension user data and estimates based on view/like ratios for videos whose dislikes weren't archived and for outdated dislike archives.`

Can you give us some example and code? e.g the extension got 1 like : 10 dislike from the user. If the video have 100 like, it will then show 1,000 dislike? How exactly does it work? I want to know what data am I watching. 

Maybe it is best to show both number of the exact dislike count from the extension and the estimate dislike count to the user?

**Comment by Anarios** [comment]
> Can you give us some example and code? e.g the extension got 1 like : 10 dislike from the user. If the video have 100 like, it will then show 1,000 dislike?

Correct. Simple, yet efficient. Also proven to be quite close to actual numbers.

> Maybe it is best to show both number of the exact dislike count from the extension and the estimate dislike count to the user?

It is in plans.
