### ISSUE TITLE
(Feature Request): GitHub: Tag release versions and upload CRX/XPI/user.js per version

### ISSUE THREAD

**Issue by Darthagnon** [Anarios/return-youtube-dislike#44]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Please can you use GitHub releases for artifacts (ZIP, CRX, XPI, user.js) for the versions of this extension? Currently, the Mozilla store is refusing to install the XPI in Firefox saying "This extension is corrupt", and it would be easier if it was available here.

### Ways to implement this!

Tag releases as they are on the website using Git, and upload compiled/packaged code under the release tags section on GitHub.

### Can you work on this?
I potentially could help work on this, though I am still a Git rookie, but need to double-check the build/packaging process, and I believe it needs write-access to the repo.
- [ ] Yes
- [X] Maybe
- [ ] No

**Comment by Frontesque** [comment]
Closed due to inactivity. Reply if this is still an issue.
