### ISSUE TITLE
(Bug): 

### ISSUE THREAD

**Issue by SuperStickFigures** [Anarios/return-youtube-dislike#444]
### Browser

Firefox

### Browser Version

Firefox 96.0.1 64-bit

### Extension or Userscript?

Extension

### Extension/Userscript Version

v2.1.0.3

### Video link where you see the problem

https://www.youtube.com/watch?v=QfGFjtNfPwA

### What happened?

I just uploaded a new video to me youtube channel right? and then I just look the the dislikes and it says dislikes disabled? is this a bug or something that cannot be fixed?

**Comment by sy-b** [comment]
@SuperStickFigures 

> I just uploaded a new video

It takes some time, have patience.🙂
Also videos are prioritized according to their popularity.

You can close this issue.

**Comment by moosthuizen42** [comment]
![stick](https://user-images.githubusercontent.com/36568323/149617540-8f913721-49be-4b9a-9e5c-7e4482185166.png)
Looks like it works.

**Comment by DARKDRAGON532** [comment]
Yeah, you just have to like the video once (dislike may take some time to update) and i think it should fix.

**Comment by pcroland** [comment]
I came across multiple videos having this issue. Liking/disliking doesn't fix it.

**Comment by andry81** [comment]
I know the video from 2022.01.31 and it still has it disabled.
