### ISSUE TITLE
Any plans for iOS15 Safari Extensions?

### ISSUE THREAD

**Issue by anon238** [Anarios/return-youtube-dislike#445]
Love this project would love to see a Safari Extension or being brought together with SponsorBlock.

**Comment by Mouadabdelghafouraitali** [comment]
#443

**Comment by anon238** [comment]
I got this fixed by installing Userscripts, https://apps.apple.com/en/app/userscripts/id1463298887?l=en and by your userscript. I’m very happy. Just a workable PIP userscript and i’m more happy! Thanks for this amazing project! 💯

**Comment by onodera-punpun** [comment]
Considering this issue is not actually fixed yet, only though a workaround, I'd say this one can stay open.

**Comment by anon238** [comment]
> Considering this issue is not actually fixed yet, only through a workaround, I'd say this one can stay open.

What is not fixed? This issue was a **question** whether they are going to release a standalone iOS app. And I closed it because they released a userscript to use which makes _this issue_ unnecessary. It’s not a workaround.
