### ISSUE TITLE
(Feature Request): Save a list of liked/disliked videos?

### ISSUE THREAD

**Issue by Darthagnon** [Anarios/return-youtube-dislike#446]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Would it be possible to save a searchable/exportable list of liked/disliked videos in local browser storage? E.g. enable option, and it saves title/URL of every video you like or dislike. Probably would need a maximum length, cull over a certain length, or toggle for unlimited.

### Ways to implement this!

Something similar to how [Tab Session Manager](https://github.com/sienori/Tab-Session-Manager) does it?

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by Anarios** [comment]
You can see a list of liked videos in youtube: https://www.makeuseof.com/how-to-view-your-liked-videos-on-youtube/

List of disliked videos... Is a strange thing to keep. Why would you want to see a video that you dislike?
