### ISSUE TITLE
(Feature Request): Preference option to deny Google "dislike" data

### ISSUE THREAD

**Issue by sediavindivoh** [Anarios/return-youtube-dislike#447]
### Extension or Userscript?

Both

### Request or suggest a new feature!

I have an important question that I cannot find the answer to:

When I tap the dislike button, will my "Dislike" data be sent both to your database and to Google's? Please make this information public on your website, as transparency for this is key.

I'd really like to see an option in the settings/preference of the plugin menu to be able to choose whether my data is sent to both Google and your database, or just to your database. (Only sending data to your database should be the default option for this, as to continue to reprimand Google for this absurd user experience choice. However, some users may want google to still get their data when they press the dislike button to better tailor movie suggestions to their desires.)

Great job on the plugin so far. I've already reviewed with 5 stars. Thank you so much for your work on this project!

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by JacksonChen666** [comment]
AFAIK (collected info from discord) the extension sends if you liked or dislikes a video to the RYD server to use it to estimate the dislike count (extrapolation). google isn't being sent the like/dislike info *by the extension* **(although you should be aware that you must be logged in to dislike or like a video, so such data is sent to google anyways even without the extension involved)**.

there is an option to disable submitting liked/disliked videos to the RYD server, and you can find that in the extension.
however, i must point out there is no option to opt out of sending google liked/disliked videos. it is what it is.

**Comment by DARKDRAGON532** [comment]
im afraid that if we give you an option to not send data to google they might terminate this extension

**Comment by Anarios** [comment]
Disabling dislike submission to youtube would qualify as "breaking site functionality" and could lead to extension termination.

You can disable dislike submission to extension (which would be bad for us, but some people wanted it for privacy)
