### ISSUE TITLE
(Bug): High CPU usage

### ISSUE THREAD

**Issue by NiIex** [Anarios/return-youtube-dislike#448]
### Browser

Opera

### Browser Version

82.0.4227.58

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.1.0.3

### Video link where you see the problem

all

### What happened?

Sometimes the extension causes one of several browser executables to take up 1/3 CPU until I close the browser. Usage jumps on its own seemingly randomly and stays high (34%) even after all tabs are closed. It usually occurs after an hour of YT usage and I have no idea what causes it. Mostly during full screen but it could be always, not sure.
First noticed it about 10 days ago but only managed to pinpoint it yesterday. When I disable extension CPU usage immediately drops to 1% with all browser tabs closed. Before those 10 days everything worked fine. Maybe related to API shutdown?

Win 7 64-bit

**Comment by sy-b** [comment]
> Maybe related to API shutdown?

Not at all. 

>  CPU usage immediately drops to 1% with all browser tabs closed.

This suggests to me that the problem is with the browser & not with the extension.

The extension only works on YouTube's website.  So, if the problem is resolved after you close all the tabs & if the tabs don't have YouTube open, then it's surely not the problem with the extension. However, if the problem vanishes after you close YT, then there could have been something to investigate.

There have been similar reports, but it seems that the problem isn't with the extension. Also, we can't investigate a problem if we can't reproduce it

**Comment by Anarios** [comment]
> This suggests to me that the problem is with the browser & not with the extension.

There is a chance that it's an issue with PoW on extension. I'm trying to reproduce this.

**Comment by NiIex** [comment]
Just to add, both Opera and my system haven't undergone any change before or after the issue. It was a quiet period. There's no reason to conclude browser would suddenly start causing trouble. But Youtube has shutdown its own API during the period and extension received an update to fetch data from own database in order to restore dislike count. It's literary the only thing that changed. Everything else on my PC are set to manual update or disabled. The other thing I suspected is older OS, not much I can change there though. Will provide further troubleshooting info if requested. Thanks for showing interest as it seems I'm alone to experience this.

**Comment by Anarios** [comment]
@NiIex, you are not alone, but it seems to be quite rare.

**Comment by White7561** [comment]
i can confirm. it has happened two times on my Chrome. I'm using a Mac if that helps. but yeah. at first i was like that's weird. a browser restart works fine. the second one i tried disabling the extensions one by one and yeah it's Return Youtube Dislikes. it doesn't happen often though

**Comment by White7561** [comment]
![Chrome Task Manager](https://user-images.githubusercontent.com/40349017/152297621-3d1e5c1f-1afe-4eda-b88d-7d3593a36d0e.png)
![iStat Menus](https://user-images.githubusercontent.com/40349017/152297629-99293db8-ee2b-4faf-80b4-95ef9b12ba0b.png)

Here when it happens the CPU usage goes crazy even though it's idle. When i disabled return youtube dislikes. the CPU usage spike stopped. enabling them again doesn't trigger the bug.

**Comment by bakaho2** [comment]
Same here. I'm using chrome and I get around 30 to 50% CPU usage, and the only fix is to disable the extension. Please fix this issue as soon as possible 'cause even though I love the work you are doing I can't afford those CPU spikes.

**Comment by pablo-cg** [comment]
Have the same problem, and it persist even after removing the extension from Chrome

**Comment by Anarios** [comment]
Thanks for the update. There was some refactoring done, but I never pin-pointed the exact reason.
