### ISSUE TITLE
(Feature Request): disable logging by default

### ISSUE THREAD

**Issue by raingart** [Anarios/return-youtube-dislike#450]
### Extension or Userscript?

Userscript

### Request or suggest a new feature!

You can disable logging by default. In order not to clog the browser console

For example, add the `Debug` variable to the function `cLog`

### Can you work on this?

- [ ] Yes
- [ ] No

**Comment by DivyanshByte** [comment]
I have implemented the feature #474

**Comment by raingart** [comment]
Thanks
