### ISSUE TITLE
(Bug): The Dislike Count is not displaying

### ISSUE THREAD

**Issue by davFaithid** [Anarios/return-youtube-dislike#453]
### Browser

Firefox, Google Chrome

### Browser Version

Firefox 96.0.1 (64-bit), and Chrome 97.0.4692.71 (Official Build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

v2.1.0.3

### Video link where you see the problem

https://www.youtube.com/watch?v=RWrWuXE6RHw

### What happened?

On Firefox, the dislike count was visible for a brief time before being replaced with generic "DISLIKE" text. I refreshed the page and nothing changed, the dislike count was still missing. I uninstalled the extension and reinstalled it, however the issue was still present. I switched browsers to Chrome to see if the issue was with my Firefox browser, and Chrome was experiencing the same bug. The dislike count is hidden across both browser releases.

**Comment by walkxcode** [comment]
API server is down.

**Comment by arghanath007** [comment]
Yup same thing for me as well on Firefox, no counter for dislikes.

**Comment by MitchelPaulin** [comment]
Looks like its back online

**Comment by jac0b-w** [comment]
Would be pretty nifty to have an indicator to show whether or not it's connected.

**Comment by PandoraHayami** [comment]
Yep, it seems to be working again.

**Comment by themaster567** [comment]
Back.

**Comment by Quicksilver151** [comment]
tiz back
lets close this issue now

**Comment by Anarios** [comment]
Postgres hit kernel maxopenfiles limit, sorry.
