### ISSUE TITLE
(Feature Request):  Disable YouTube API Likes and only use user submitted data

### ISSUE THREAD

**Issue by r-afael** [Anarios/return-youtube-dislike#454]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Since the majority of YouTube users aren't using the extension, it would be more accurate if there was an option to see the Like/Dislike ratio composed only by the extension users' data.

I could have misinterpreted how this extension works, but if the current system still gathers native data, it becomes almost impossible to have more dislikes than likes, since the native YouTube Like input easily overwhelms the dislikes from the extension users.
Example: Scammers and cheaters videos with tons of negative comments are still having a strong positive like/dislike ratio.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by cyrildtm** [comment]
Please read #429 and https://github.com/Anarios/return-youtube-dislike/issues/330#issuecomment-995838302
> The "algorithm" to calculate actual dislike number is the following: calculate ratio from extension user votes (say, video has 10% dislikes). [Apply] this ratio to [total] number of likes.

**Comment by r-afael** [comment]
Oh, thanks for the clarification!

But I still think that it would be nice to have an option to see the actual ratio of the extension users, specially in videos with lower views.

A video with 9 extension likes and 1 dislike would apply a 10% ratio but, although they have the same ratio, it wouldn't accurately represent the community approval as if it had 9000 likes and 1000. 

Like, the uploader could be lucky that their initial extension viewers liked the video, or he could cheat the system and like it with other devices. I think that being able to see the actual numbers of the extension dislikes would prevent this false sense of mass acceptance and allow a more transparent judgment.

**Comment by sy-b** [comment]
Related to #108 #114 #268

The work is in progress.

The owner does have the separated data.
