### ISSUE TITLE
"Module Not found: debug.js" when building

### ISSUE THREAD

**Issue by DivyanshByte** [Anarios/return-youtube-dislike#456]
When I try to build as stated in [https://github.com/Anarios/return-youtube-dislike/blob/main/Extensions/combined/readme.md]()

It Gives me the following error:

![bugreport](https://user-images.githubusercontent.com/57246976/150539525-37bd247b-8869-4802-a9de-83406a223209.png)

Is this Bug Related to Webpack or Return Youtube Dislike?

**Comment by cyrildtm** [comment]
Cherry pick #442
