### ISSUE TITLE
(Feature Request): Voting for YouTube users who don't have an account (or who are not logged in)

### ISSUE THREAD

**Issue by JayBrown** [Anarios/return-youtube-dislike#458]
### Extension or Userscript?

Both

### Request or suggest a new feature!

I don't have a Google/YouTube account—I subscribe to channels via RSS—, so I'm always logged out on YouTube. Maybe there's a way to enable voting for these users, too, i.e. send downvote & upvote statistics through the API. This would, of course, have no effect on YouTube's real server-side like & dislike counts for a video, but it could help ReturnYouTubeDislike get a more accurate ratio, especially for videos with only a few views.

### Ways to implement this!

(?) Can't say for sure, but I assume that the extension would have to check whether a user is logged into a YouTube account or not. If he's not logged in, it would then need to load an alternate routine, i.e. replace YouTube's own like/dislike functions with in-extension voting functions. (If that's possible, it would also need to show the user whether he has already liked or disliked a video, e.g. red thumbs down, green thumbs up. Don't know how YT does that UI-wise, because I don't have an account.)

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by Anarios** [comment]
We want to keep numbers close to "real" number of dislikes.

Currently if someone has doubts whether the extension works properly - they can ask video creator to check number of dislikes in creator studio and compare it to what extension shows (hopefully it will be close).

If we allow users without account to submit votes - these numbers will deviate, and trust into extension by users will decrease.
