### ISSUE TITLE
(Bug): Dislike Button just says "DISLIKES DISABLED"

### ISSUE THREAD

**Issue by Gaminguide1000** [Anarios/return-youtube-dislike#461]
### Browser

Google Chrome

### Browser Version

Google Chrome  97.0.4692.99 (64 Bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

Return Youtube Dislikes 2.1.0.3

### Video link where you see the problem

Every Video, after i klick on the dislike button

### What happened?

A bug happened! :OOOO
Well, i klicked on a Video, and noticed, that it wasnt showing dislikes, just minutes ago.
I Reloaded the extension, the site, and everything, but it didnt come back.
When i klicked on the Dislike butten, the "I DONT LIKE" turned into "DISLIKES DISABLED".

**Comment by DaveWoody** [comment]
Can confirm. Got the same issue. 

Chrome Version: Version 97.0.4692.99 (64-Bit)

**Comment by Mouadabdelghafouraitali** [comment]
Same issue here

![image](https://user-images.githubusercontent.com/24398682/150819404-d26af335-6043-4514-b2cc-fe9e3607b9c0.png)

**Comment by Mouadabdelghafouraitali** [comment]
Everything is working fine now ♥

**Comment by Quicksilver151** [comment]
amazing how fast things get fixed in github communities

**Comment by Gaminguide1000** [comment]
lol fixed

**Comment by Anarios** [comment]
Closing now.

**Comment by JacksonChen666** [comment]
alternative title: Extension shows "DISLIKE DISABLED" when API is down

the problem here I see is that the extension still doesn't/can't differentiate between API being down and API returning nothing useful (e.g. ratings disabled by creators). different errors should be handled.
