### ISSUE TITLE
(Feature Request): Toggle Button

### ISSUE THREAD

**Issue by mysticallypixelated** [Anarios/return-youtube-dislike#466]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

A option to toggle the extension in a easy way, kinda annoying to go to the browser's extension page tho, 2 clicks are much simpler.
if you don't get it, i am asking for a option to toggle the extension from this thing
![msedge_vSxX4rGFNM](https://user-images.githubusercontent.com/95834462/151663019-66394c40-4e45-4857-9473-fe50cf5744a3.png)
 

### Ways to implement this!

probably by using one "if" statement in line 360, i have no idea.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by alanmun** [comment]
So... why would you want this as a feature?

**Comment by mysticallypixelated** [comment]
i simply wanted a easier way of turning off the extension, i never turned off the extension before, but maybe some users want it. i don't know how many however
sorry for the late reply tho

**Comment by Anarios** [comment]
Extension can be toggled from browser settings, IMO that's enough.
