### ISSUE TITLE
Why does sponsor `Peter33` link to the Sonic 2 trailer?

### ISSUE THREAD

**Issue by TechStudent11** [Anarios/return-youtube-dislike#468]
When clicking on Peter33, which is under the "SPONSORS" section, it links to this: https://www.youtube.com/watch?v=G5kzUpWAusI

That is the official trailer for Sonic 2. Is this a placeholder, or is it there intentionally?

**Comment by sy-b** [comment]
**Note: I don't have any idea**

I assumed it as an Easter egg. Maybe Peter33 wanted it.

Wait for the owner's answer.

**Comment by Anarios** [comment]
> Maybe Peter33 wanted it.

That is correct.

Being featured in Sponsors list is a standard Patreon perk, so anyone can have it. This guy doesn't have any project to feature there - but he asked to add Sonic link as a joke.

**Comment by TechStudent11** [comment]
> > Maybe Peter33 wanted it.
> 
> That is correct.
> 
> Being featured in Sponsors list is a standard Patreon perk, so anyone can have it. This guy doesn't have any project to feature there - but he asked to add Sonic link as a joke.

Okay. Thanks
