### ISSUE TITLE
Website: switching to the "Help" tab makes the content jump left because of the scrollbar

### ISSUE THREAD

**Issue by enkeyz** [Anarios/return-youtube-dislike#469]
If you switch to the "Help" tab on the website, the content jumps left when the scrollbar appears(because the full content can't fit in the viewport).

**Comment by cyrildtm** [comment]
I don't have this issue with Chrome, tried with maximized and small windows. 
What's your browser? Screen resolution? Is your window maximized?

**Comment by enkeyz** [comment]
Try switch to Help, back and forth.

**Comment by cyrildtm** [comment]
Oh yeah now I see it. The red stripe thingy on top right jumps back and forth. 

Well, either we force the slider to visible or hidden for all pages to be consistent, or just live with it. 
Or custom slider? Is it worth it.

**Comment by enkeyz** [comment]
> 

I'd do it, just don't have any experience with Vue.js :)

**Comment by cyrildtm** [comment]
What about moving it to the left

**Comment by PickleNik** [comment]
the chromium scrollbar has been fixed a while ago
