### ISSUE TITLE
(Bug): Dislike count is displayed in videos with like count disabled

### ISSUE THREAD

**Issue by Ketok4321** [Anarios/return-youtube-dislike#47]
### Browser

Brave

### Browser Version

1.32.106

### Extension or Userscript?

Extension

### Extension/Userscript Version

0.0.0.6

### Video link where you see the problem

https://www.youtube.com/watch?v=E7YhB7iG4dM

### What happened?

![image](https://user-images.githubusercontent.com/70479035/143125501-1fd59862-fa89-49d4-b36e-4abe98273772.png)
Dislike count is displayed even when visibility of like count is disabled in youtube studio.
It seems that in that case its value is always 0, so it's useless anyway.

**Comment by mphelp** [comment]
@Anarios should be closed based on #209
