### ISSUE TITLE
(Feature Request): API Connection Indicator

### ISSUE THREAD

**Issue by jac0b-w** [Anarios/return-youtube-dislike#470]
### Extension or Userscript?

Both

### Request or suggest a new feature!

It would be pretty nice to have some sort of indicator to show if the extension is connected to the API. Currently when the API is down there is no indication that the extension cannot connect to the API.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by sy-b** [comment]
It's already implemented and waiting to be released in webstore.
