### ISSUE TITLE
(Feature Request): Like/dislike next to each thumbnail on YouTube.

### ISSUE THREAD

**Issue by webFunX** [Anarios/return-youtube-dislike#48]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Please add that on every thumbnail in suggestions, main, subscriptions, etc., there is a bar immediately visible with the ratio of paws up and down. :D 

### Ways to implement this!

Simply capture each item with a thumbnail on a given YouTube subpage, retrieve the video id, generate a bar with the ratio of paws up and down and add under each thumbnail.

### Can you work on this?

- [X] No
- [ ] Yes

**Comment by cyrildtm** [comment]
There is a separate plugin available: Thumbnail Rating Bar for YouTube. It uses the API by Anarios.

**Comment by webFunX** [comment]
@cupiditys It works very well. Thanks.

Issue can be closed.
