### ISSUE TITLE
(Bug): Hidden description of button shows wrong text after hovering over like button

### ISSUE THREAD

**Issue by Grolicek** [Anarios/return-youtube-dislike#491]
### Browser

Google Chrome

### Browser Version

v98.0.4758.102

### Extension or Userscript?

Extension

### Extension/Userscript Version

v2.1.0.3

### Video link where you see the problem

https://www.youtube.com/watch?v=Jq-d4Kl8Xh4

### What happened?

After hovering over the buttons both say "Nepáči sa mi" which means "I don't like this".
![image](https://user-images.githubusercontent.com/58747066/155371236-16baac2f-96aa-4ccd-bf83-5708e6ff2878.png)
![image](https://user-images.githubusercontent.com/58747066/155371256-8499fe94-3c92-4362-8044-c514b3acf67b.png)

### How to reproduce/recreate?

Hover over buttons. Can't say if this happend in every language, but it happens in Slovak language.

**Comment by sy-b** [comment]
Most probably that problem is with YouTube itself

Extension does not change that text.

**Comment by Grolicek** [comment]
oh sorry it's probably issue with ytb it self, i just disabled the extension and it still behaves the same, sorry...

**Comment by JacksonChen666** [comment]
> oh sorry it's probably issue with ytb it self, i just disabled the extension and it still behaves the same, sorry...

give youtube a bug report then

your account icon > send feedback
