### ISSUE TITLE
(Feature Request): Archive dislikes for the inevitable API killswitch

### ISSUE THREAD

**Issue by avarayr** [Anarios/return-youtube-dislike#50]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Incrementally archive dislike counts and store them into some kind of permanent storage. 

Alternatively use archive.org or similar websites to retrieve dislike count.

When youtube pulls the killswitch for the dislike API completely, we won't rely on them, rather use archived and our own data.

### Can you work on this?

- [ ] Yes
- [ ] No

**Comment by Anarios** [comment]
Already being done.
