### ISSUE TITLE
(Bug): No source code for backend API. The backend repo should be shared to github.

### ISSUE THREAD

**Issue by spartanatreyu** [Anarios/return-youtube-dislike#51]
### Browser

N/A

### Browser Version

N/A

### Extension or Userscript?

Extension

### Extension/Userscript Version

N/A

### Video link where you see the problem

N/A

### What happened?

N/A

**Comment by pgamerx** [comment]
While it is a good thing to open source your projects fully to ensure transparency, you gotta be sure you aren't leaving any keys or anything in there that will allow people to abuse your API. So in my opinion, think about everything before making it open sourced.
