### ISSUE TITLE
(Bug): Negative dislike count

### ISSUE THREAD

**Issue by Bartek200219** [Anarios/return-youtube-dislike#518]
### Browser

Vivaldi

### Browser Version

5.1.2567.66

### Extension or Userscript?

Userscript

### Extension/Userscript Version

0.9.0

### Video link where you see the problem

https://i.imgur.com/qSGEJ8A.png

### What happened?

When I clicked like on [this video]( https://www.youtube.com/watch?v=sZJokD--EKM) dislike counter changed to -1

### How to reproduce/recreate?

Click like on [this video]( https://www.youtube.com/watch?v=sZJokD--EKM)

**Comment by cyrildtm** [comment]
Now that this video has got a couple of disklikes, can you try again and see if you are still getting negative numbers? 

I'm not familiar with userscript and how it works, but this line seems related: 
https://github.com/Anarios/return-youtube-dislike/blob/2e6ed5298b7851b7ea84dcfa298167689f516496/Extensions/UserScript/Return%20Youtube%20Dislike.user.js#L28

If the userscript survives a page refresh/reload/redirection, then the previous state may not be erased when playing the next video. 
Basically, if you like a video, go to the next one from the same tab/window/page, and like the second video, then the second video will get one less dislike. If it's zero at first, it will go negative. 

If I'm guessing it right, then we need to reset the internal states on every reload. 
Can someone using userscript verify this? 
https://github.com/Anarios/return-youtube-dislike/blob/2e6ed5298b7851b7ea84dcfa298167689f516496/Extensions/UserScript/Return%20Youtube%20Dislike.user.js#L263
https://github.com/Anarios/return-youtube-dislike/blob/2e6ed5298b7851b7ea84dcfa298167689f516496/Extensions/UserScript/Return%20Youtube%20Dislike.user.js#L281
above this line and this line, add: 
```
cLog('state ${previouSstate} likes ${likesvalue} dislikes ${dislikesvalue}')
```

**Comment by cyrildtm** [comment]
I just tried another video with zero likes. I could not replicate this behavior. Can you provide more detailed steps? Since it seems that the previous state may be the cause, can you be more specific with **every step** as early as you open youtube.com ?

**Comment by Bartek200219** [comment]
> I just tried another video with zero likes. I could not replicate this behavior. Can you provide more detailed steps? Since it seems that the previous state may be the cause, can you be more specific with **every step** as early as you open youtube.com ?

I think I could replicate this only once by using mini player, queue and clicking previous/next song while switching between search homepage and subscribe feed.
Then I tried one more time and I couldn't do it, so I think we could close this issue for now.

**Comment by cyrildtm** [comment]
> mini player

That's what I suspected. Mini player switches videos without loading a whole new page. In that way the state variables are not reset properly. In your case, this behavior is not even consistent. Who knows what youtube is doing. Do keep this in mind and keep using mini player. When it shows up again, you may reopen this issue.

**Comment by Bartek200219** [comment]
Maybe someone else succeeds to trigger this behavior, but for now I'll keep that in mind. Thank you for your time
