### ISSUE TITLE
most of the videos on youtube showing 0 Dislikes (Bug): 

### ISSUE THREAD

**Issue by CH4SSEUR** [Anarios/return-youtube-dislike#523]
### Browser

Mozilla Firefox 

### Browser Version

v98.0.2

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.1.0.3

### Video link where you see the problem

https://www.youtube.com/watch?v=K2HDvm3HTa4

### What happened?

almost all videos on youtube showing 0 dislikes(like 95% of the videos i watch) 

this video is one of the few showing 53 dislikes : https://www.youtube.com/watch?v=DhKs0hGeQsc

### How to reproduce/recreate?

i have no idea how to reproduce it just happaned

**Comment by PickleNik** [comment]
@CH4SSEUR, the issue is being investigated, you can join our Discord for updates on this

**Comment by stevenirby** [comment]
I'm only seeing zero as well on most videos

**Comment by PickleNik** [comment]
> I'm only seeing zero as well on most videos

you and me both
... and a few million other people

**Comment by ebtgc** [comment]
Same here. Same exact Firefox version (latest) and extension (latest).
I think Youtube did something on their end to break the script...

**Comment by Sam101011** [comment]
Well, that's a problem

**Comment by PickleNik** [comment]
<img width="424" alt="Screen Shot 2022-04-04 at 8 47 04 PM" src="https://user-images.githubusercontent.com/31113245/161656437-c6161718-469e-49a0-88fe-cbba3cbe9238.png">
well this was fun ~~come back tomorrow for more~~

**Comment by RockBrentwood** [comment]
Actually, it will not produce 0 ... at first. It will show another number, briefly, before it switches to 0.

In fact, many videos will show the dislike number from the most recently accessed video, or else the "DISLIKE" label, before displaying the one for the current page. This may be part of what's going on with that, but not all. It's possible it may also be showing the correct number of dislikes before switching to 0.

**Comment by cyrildtm** [comment]
> many videos will show the dislike number from the most recently accessed video

This part sounds very much like issue #498

**Comment by PickleNik** [comment]
<img width="604" alt="Screen Shot 2022-04-05 at 9 34 40 PM" src="https://user-images.githubusercontent.com/31113245/161877962-90d1fd85-a7a6-455f-af12-1b79d8fab8e1.png">
@RockBrentwood @cyrildtm 
should be good now

**Comment by CH4SSEUR** [comment]
its fixed, thank you so much

**Comment by MooMooMod** [comment]
Any other good first issues?

**Comment by Nightcaat** [comment]
Marking as invalid as this related to API instability and not the extension itself
