### ISSUE TITLE
(Bug): Almost all videos showing up with 0 dislikes.

### ISSUE THREAD

**Issue by ShcemX** [Anarios/return-youtube-dislike#524]
### Browser

Google Chrome

### Browser Version

v93.0.4577.107

### Extension or Userscript?

Userscript

### Extension/Userscript Version

v0.9.0

### Video link where you see the problem

https://www.youtube.com/watch?v=k1BneeJTDcU

### What happened?

Instead of showing a few thousand dislikes, it instead showed 0 dislikes.

### How to reproduce/recreate?

Get the userscript, go to that video, and watch it.

**Comment by PickleNik** [comment]
dups #523
the issue is being investigated
check Discord for status updates
