### ISSUE TITLE
Dislike ratios don't seem right

### ISSUE THREAD

**Issue by stoopingas** [Anarios/return-youtube-dislike#525]
Multiple well received videos in my recommended that used to have high like:dislike ratios currently have a ratio close to 50%. I have no real evidence that this isn't just a coincidence and that the videos don't actually just have these ratios however there are so many videos from trusted creators that I am suddenly seeing this on that it is likely a bug.

**Comment by PickleNik** [comment]
dup of #523 
being worked on
check Discord for updates
