### ISSUE TITLE
(Bug): No longer shows bar/dislike count

### ISSUE THREAD

**Issue by Tenkomanker** [Anarios/return-youtube-dislike#528]
### Browser

Chrome

### Browser Version

Chromium v100 (latest)

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.1.0.3

### Video link where you see the problem

https://www.youtube.com/watch?v=UgypNSOTKn0&ab_channel=MoreSidemen

### What happened?

Dislike count and bar are gone, I expected them to be there lol

### How to reproduce/recreate?

Go to the Youtube homepage and click a video, dislikes should be missing

**Comment by sy-b** [comment]
![image](https://user-images.githubusercontent.com/94835959/162406846-aa728291-6673-4faf-95bc-065a14ab84d8.png)

Its visible to me.

You are a part of YT's A/B testing.
You can try clearing cookies (eventually signing-out of YT).

**Comment by Anarios** [comment]
Temporary failures were happening over last 3 days.
