### ISSUE TITLE
(Bug): Number format is not working on likes

### ISSUE THREAD

**Issue by michelle1574** [Anarios/return-youtube-dislike#543]
### Browser

Firefox Nightly

### Browser Version

101.0a1 (2022-04-16) (64 bits)

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.0

### Video link where you see the problem

All videos

### What happened?

A bug happened!
When I changed the number format, it didn't affect likes. The like format was before change.
I didn't check if the function works on Shorts.
I expected that:
1. The like button counter on a video showed 23000000 instead of 23 MLN (the Polish shortcut for Milion)
2. The dislike button counter on a video showed 839000 instead of 839 TYS (the Polish shortcut for Thousand)

### How to reproduce/recreate?

Tell us how it happened with detailed steps for us.
Change the number format to diffrent one
Refresh the video page.

**Comment by cyrildtm** [comment]
That is the current design. Because we never touch the like numbers even we have the API returns. How should we proceed? 

- Option A: Update format, but don't change the number
- Option B: Use RYD API like number, and use custom format.

**Comment by cyrildtm** [comment]
Sorry I didn't read carefully before my last comment, although it may be related. 

@michelle1574 Could you please write down what is your result from this command, typed in Developer tools? 

```navigator.language```

Example result: 
```'en-US'```

**Comment by cyrildtm** [comment]
Wait I think this is the issue 😄


> That is the current design. Because we never touch the like numbers even we have the API returns. How should we proceed?
> 
> * Option A: Update format, but don't change the number
> * Option B: Use RYD API like number, and use custom format.

**Comment by sy-b** [comment]
> we can solve https://github.com/Anarios/return-youtube-dislike/issues/538 altogether

That will just **show** like count. I think if creator ever disables it, RYD should inform the user. (Or we can just put those vote count in an echo chamber like situation)

**Comment by cyrildtm** [comment]
@sy-b  Is there any difference between disabling likes **when** uploading and disabling **after** uploading? I don't have uploader account so I cannot confirm

**Comment by sy-b** [comment]
I don't think so.
And I can't experiment. I don't see that option anywhere. I am probably not eligible for that.

**Comment by cyrildtm** [comment]
@sy-b I guess we can continue with only applying format for now? Treat dislike disabled as a separate issue as always

**Comment by sy-b** [comment]
yeah 👍
