### ISSUE TITLE
New settings can't be set anywhere?

### ISSUE THREAD

**Issue by StacktraceException** [Anarios/return-youtube-dislike#550]
Both in Chrome and FireFox the update to 3.0.0.0 shows these new settings. How exactly are they meant to be set? 

There are no settings In youtube videos, nor in the extension details in chrome://extensions, nor in the update page.

**Comment by sy-b** [comment]
1. Click on the extension icon.
2. Click the gear icon on the upper right side.

**Comment by sivasunken** [comment]
I am using Chrome and the new 3.0.0.0 version but there is no options menu in the extensions menu

**Comment by PickleNik** [comment]
> I am using Chrome and the new 3.0.0.0 version but there is no options menu in the extensions menu

![Screenshot_20220418-211258.png](https://user-images.githubusercontent.com/31113245/164039606-8ea0d963-657f-4e7a-9b59-3f8fa78bd5b1.png)
