### ISSUE TITLE
(Bug): Focus stealing on extension update to v3

### ISSUE THREAD

**Issue by tomjn** [Anarios/return-youtube-dislike#553]
### Browser

Google Chrome

### Browser Version

Version 99.0.4844.83 (Official Build) (arm64)

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.0

### Video link where you see the problem

not applicable

### What happened?

I was typing something important out when suddenly focus was stolen, the tab disappeared from view, and I was presented with the return youtube dislike in a new tab with no warning.

Suffice to say I lost work, I should not have lost work, this extension is to blame. _It's never done it before, don't do it again._

### How to reproduce/recreate?

Wait for Chrome to update the extension to v3 in the background, then watch as whatever you were doing is interrupted so the extension can tell you what changed

**Comment by cyrildtm** [comment]
Sorry to hear that man
#534  Multiple fixes has been proposed. 
~~#535~~

**Comment by sy-b** [comment]
adding `active: false` will do the job

```JS
api.tabs.create({url: api.runtime.getURL("/changelog/3/changelog_3.0.html"), active: false});
```

**Comment by tihomir-kit** [comment]
Maybe you could just not show the changelog unless there is an opt-in in the extension settings. 

I like the extension and thanks for making and maintaining it. But the purpose of this extension is to (from the user perspective) do one simple thing - return the dislike button. I don't really need to know if anything internally updated, I just want the dislike to still be there when I open youtube - no additional features needed, or if they're added, I don't really care to be notified.

I use 3 different computers (work, home pc, home laptop) and I think I've seen this changelog pop-up about 7-8 times in the past week or so which is a bit excessive.

**Comment by tihomir-kit** [comment]
I got it again this morning.. lol. 

If it's of any worth, I'm using Brave - Version 1.38.111 Chromium: 101.0.4951.54 (Official Build) (64-bit)

And I've seen the new tab changelog for extension versions v3.0.0.0 and v3.0.0.1

**Comment by Anarios** [comment]
3.0.0.2 is out, please close the issue if it's fixed with this update. Or comment if it still repeats.

**Comment by tomjn** [comment]
extension updated and I saw no tabs or prompts, I'd say this is success!
