### ISSUE TITLE
Integrate ReturnYoutubeDislike.com translation in Spanish

### ISSUE THREAD

**Issue by Alejandrogayol** [Anarios/return-youtube-dislike#554]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Hi, I just made a complete Spanish translation for RYD Website and I would like it to be integrated. This is the text document with all website text in English and Spanish.
[translation.txt](https://github.com/Anarios/return-youtube-dislike/files/8522223/translation.txt)

### Ways to implement this!

There could be a button in top menu with spanish flag (🇪🇸) to change languaje. RYD in Spanish might be avaiable on “returnyoutubedislike.com/es” or “es.returnyoutubedislike.com”. In Spanish version, there clould be USA flag (🇺🇸) to change into English. It would be an exact clone of main website but with text in layout changed. If do you want, I can download and edit the website in Spanish and publish here the HTML files.

### Can you work on this?

- [x] Yes
- [ ] No

**Comment by cyrildtm** [comment]
maybe we can do something like this for the website
https://github.com/Anarios/return-youtube-dislike/blob/2e6ed5298b7851b7ea84dcfa298167689f516496/Extensions/combined/popup.js#L26

**Comment by PickleNik** [comment]
localization will be done through i18n, I'll parse the translation.txts into jsons

**Comment by PickleNik** [comment]
done in #575

**Comment by PickleNik** [comment]
thanks to [Alejandrogayol](https://github.com/Alejandrogayol) and [Batuhan445](https://github.com/Batuhan445) for provided translations
