### ISSUE TITLE
Help and Troubleshooting page still shows older version

### ISSUE THREAD

**Issue by amberdambey** [Anarios/return-youtube-dislike#557]
![image](https://user-images.githubusercontent.com/99459304/164372253-56d610e2-97e1-4d5e-b3f1-9ed3acbb4148.png)
As the image shows, if you go to the [help page](https://returnyoutubedislike.com/help), it still shows the latest version as 2.1.0.3, when the latest is 3.0.0.0. Also my apologies for not filling out one of the template forms.

**Comment by sy-b** [comment]
Thanks

> Also my apologies for not filling out one of the template forms.

Not a big issue.
