### ISSUE TITLE
(Bug): YT Shorts - Thumbs are always filled with color

### ISSUE THREAD

**Issue by nilslambertz** [Anarios/return-youtube-dislike#565]
### Browser

Firefox

### Browser Version

100.0b9

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.0

### Video link where you see the problem

https://www.youtube.com/shorts/vjIFQHvkBbs

### What happened?

When the colorized thumbs are enabled, they seem to be filled by default when viewing Shorts.
![grafik](https://user-images.githubusercontent.com/62618726/164986075-195b34d6-529d-4b0e-9049-9f29490af88e.png)

When a thumb is pressed, the color changes to the default Youtube color:
![grafik](https://user-images.githubusercontent.com/62618726/164986102-decb224b-6c81-4eab-8a3b-022d3e8be856.png)

### How to reproduce/recreate?

1. Enable colorized thumbs.
2. Open a Short
3. Press Like/Dislike

**Comment by sy-b** [comment]
> When a thumb is pressed, the color changes to the default Youtube color

At least this serves as a visual cue 🙃.

<br>

I think a theme should consist of 4 colors.

@nilslambertz  What do you think? What do you expect as a viewer?

**Comment by cyrildtm** [comment]
https://github.com/Anarios/return-youtube-dislike/blob/2e6ed5298b7851b7ea84dcfa298167689f516496/Extensions/combined/src/state.js#L121

```
  if (extConfig.coloredThumbs === true) {
    isShorts()
    getLikeButton().querySelector('tp-yt-paper-button#button')?.style.color = getColorFromTheme(true);
    getDislikeButton().style.color = getColorFromTheme(false);
  }
```

I can try and remove non-pressed color. Shorts button styles are different than those in regular videos; we don't have the visual clue of empty/filled. Just don't colorize the non-pressed buttons, then.

**Comment by sy-b** [comment]
Another option - 
Set transparency 50% (or whatever looks good) for unclicked buttons. And 100% for the clicked ones
**or**
Use light colors for unclicked one & darken them after they're clicked.

**Comment by cyrildtm** [comment]
Transparency sounds cool, but it's as complicated as colorizing both pressed and un-pressed conditions, and here's another concern; making the buttons too transparent can make them disappear, while making them not so transparent does not solve the problem at all

Two colors for each button is basically what I'm thinking of. I was thinking not to colorize the un-pressed ones, but maybe we can have a different color.

**Comment by cyrildtm** [comment]
> I think a theme should consist of 4 colors.

@sy-b  But we already have 4 colors 🙃 #552

> @nilslambertz What do you think? What do you expect as a viewer?

Yeah @nilslambertz  what do you want to see?

**Comment by nilslambertz** [comment]
@cyrildtm @sy-b If the styles for the empty thumbs are not available on these pages, maybe both should be grey and if a like/dislike is given, the color could be set for this thumb. Alternatively the SVGs for empty/filled thumbs could be included in the source code and the buttons on the Shorts pages could be replaced with them. But just setting the non-pressed button to some default color should be fine too.

**Comment by cyrildtm** [comment]
Leaving deactivated buttons with the default color is actually easier. Unfortunately I believe the thumb SVGs are copyrighted, so I don't want to include any of them.

**Comment by sy-b** [comment]
> @sy-b But we already have 4 colors 🙃 https://github.com/Anarios/return-youtube-dislike/issues/552

I meant this (overkill!) 😅
- Dark
  -  Like 
  -  Like Clicked
  - Dislike 
  - Dislike Clicked
- Light
  -  Like 
  -  Like Clicked
  - Dislike 
  - Dislike Clicked
 
Note: I don't recommend this (unless something like [color.adobe.com](https://color.adobe.com/) is implemented. But again this is overkill for a string modifying extension)

**Comment by cyrildtm** [comment]
Well I tried some glowing effects, the best I could get was from [this one](https://codepen.io/OpherV/pen/dRoQdN) but it did not look good

Eight colors is not that terrible, if we can use css injection. But I guess that will be a new endeavor. Just write this down now, maybe consider later.

**Comment by sy-b** [comment]
> Just write this down now, maybe consider later.

👍
