### ISSUE TITLE
(Feature Request): Adding like and dislike to the Thumbnail 

### ISSUE THREAD

**Issue by xHeaveny** [Anarios/return-youtube-dislike#566]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

I want to suggest that we see the like and dislike count on the Thumbnail so that we don't have to click on the video to look if its bad (in a tutorial case) 

### Can you work on this?

- [ ] No
- [X] Yes

**Comment by cyrildtm** [comment]
There is a separate plugin available: Thumbnail Rating Bar for YouTube. It uses the API by Anarios.


duplicate of #48
