### ISSUE TITLE
(Bug): Huge security Issue between users on PC

### ISSUE THREAD

**Issue by KyleQ1** [Anarios/return-youtube-dislike#569]
### Browser

Google Chrome

### Browser Version

Chrome 100.0.4896.127

### Extension or Userscript?

Extension

### Extension/Userscript Version

v2.1.0.3

### Video link where you see the problem

Update Page

### What happened?

I use a windows computer with multiple users. When the youtube dislike extension auto-updated or updated either due to it being open on my profile or some other reason, the browser signed into my profile popped up on another user's desktop. This browser was signed into my account which included credit cards, last browser pages left open, history, and everything. This needs to be patched if this extension were to be used on any sort of public computer or laptop.

### How to reproduce/recreate?

Have an outdated version of youtube dislike on one windows profile and start the update or auto-update it. Swap to another profile and continue like normal until the browser pops up with the windows saying it finished updating on the other user's profile.

**Comment by Anarios** [comment]
Extension doesn't do anything with your youtube profile, it can't save it, it can't log into your account, it doesn't save any cookies or other log-on information. All it does is displays a number next to dislike button.
