### ISSUE TITLE
(Feature Request): Optional feature to restore old dislike bar behavior

### ISSUE THREAD

**Issue by SpinThwomp** [Anarios/return-youtube-dislike#571]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Before YouTube changed the colors and icons to black and wireframe, the like portion of the rate bar would be greyed out (hex color #909090) until you rated the video, after which the like portion of the bar would turn blue (hex color #0450dc). This option would work really well with the extension that allows you to restore the old icons and colors to YouTube's user interface as it would fully complete the recreation of YouTube from 2018-2020.

Example of this behavior:

(before rate)

![Screen Shot 2022-04-25 at 2 49 18 PM](https://user-images.githubusercontent.com/102715128/165156539-e916a818-09a8-48f7-bdc7-c23f5c3a51ca.png)

(after rate)

![Screen Shot 2022-04-25 at 3 01 39 PM](https://user-images.githubusercontent.com/102715128/165156576-f0ac738a-75c8-44bf-8eee-37b55bdd4874.png)

![Screen Shot 2022-04-25 at 3 02 33 PM](https://user-images.githubusercontent.com/102715128/165156607-189e76f0-0e98-4c89-9543-c08c62b293d3.png)

### Ways to implement this!

It would be probably as simple as editing a few bits of js, nothing too major

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by cyrildtm** [comment]
Do you have the color codes for the following? 
- Neutral state (I guess it's #909090)
- Liked state (blue & lighter grey)
- Dislike state (lighter grey & blue)

You are right with the js editing, it's a bit more complicated than the current implementation but it's doable. Tell me the color codes and I will include that.

**Comment by SpinThwomp** [comment]
the bar colors for disliked state are the same as liked state, lighter grey should be #cccccc

**Comment by cyrildtm** [comment]
Thanks! No rush, on vacation, no new PR 🙂

**Comment by SpinThwomp** [comment]
oooh enjoy your vacation, when you get the time, the correct colors are as follows:

Bar (unrated):
Likes #909090
Dislikes #cccccc

Bar (rated)
Likes #0450dc
Dislikes #cccccc

Thanks 😁

**Comment by cyrildtm** [comment]
a quick heads up: Polymer design has thumbs hollow when deactivated. When pressed, it gets "filled" by being replaced with an entirely different SVG. The original "always-filled" style cannot be restored without including copyrighted SVGs in the extension. 

If you think the grey filled pattern is really important for restoring the old theme, Please reopen this issue and let others help with this problem

**Comment by SpinThwomp** [comment]
no need for the filled in icons ;P just the bar

**Comment by cyrildtm** [comment]
Thumbs can still be re-colored with blue and grey, it's just that the deactivated (non-pressed) buttons will be hollow, which is different than the old style. Except that, It's the same amount of effort to just implement bar colors and both bar and thumbs.

**Comment by SpinThwomp** [comment]
as long as the bar works as intended then thats all right with me, thanks a ton! 😁

**Comment by SpinThwomp** [comment]
oh! one last thing, the dislikes portion of the rate bar is #606060 in dark mode

**Comment by SpinThwomp** [comment]
yup! everything works as intended, I cannot thank you enough. Theres one more thing I forgot to mention though, and Im super sorry about all my little nitpicks, (if I had the knowledge to do this I would) but when in dark mode, and when the video is liked, the blue on the rate bar and the like/dislike buttons should be #16a0ff in dark mode, this is my fault for not mentioning this, sorry.

**Comment by SpinThwomp** [comment]
unfortunately now it just look like this no matter if ive liked it or if its dark or light theme (im using the Userscript btw but I dont think that matters
![Screen Shot 2022-05-08 at 1 55 41 PM](https://user-images.githubusercontent.com/102715128/167309128-15e9d933-1ceb-4dcb-977c-04b7feca1708.png)
)

**Comment by SpinThwomp** [comment]
well actually, I changed the Userscript I had installed corresponding to your change in the extension, and I noticed you changed the "a" to a "c" maybe when I changed it I messed with something else, ill reinstall the one you just made and compare the two and report back

**Comment by SpinThwomp** [comment]
OMG YES IT WORKS, Thank you!
