### ISSUE TITLE
(Bug): extension not working after clear data browser

### ISSUE THREAD

**Issue by PhamLa72** [Anarios/return-youtube-dislike#58]
### Browser

Google Chrome

### Browser Version

Chromium v95

### Extension or Userscript?

Extension

### Extension/Userscript Version

0.0.0.7

### Video link where you see the problem

extension not working after clear data browser

### What happened?

A bug happened! extension not working after clear data browser

**Comment by thereaper90917** [comment]
can you post screen shot of UI as youtube is rolling out a new UI that looks like this https://cdn.discordapp.com/attachments/910401584326914069/912947337599516732/22.jpeg

**Comment by PhamLa72** [comment]
https://ibb.co/BnStRjz

**Comment by PhamLa72** [comment]
https://ibb.co/rcKfzsn

**Comment by thereaper90917** [comment]
have you tried uninstalling and reinstalling? and the error is still persistent?

**Comment by PhamLa72** [comment]
i tried reinstalling and it worked, but i want dev to fix this, when clearing browsing data this plugin will still work

**Comment by DARKDRAGON532** [comment]
@PhamLa72 what all did you clear from here?
![image](https://user-images.githubusercontent.com/69623818/143376197-9927ad74-0814-4d42-a305-d580f3c04110.png)
or
![image](https://user-images.githubusercontent.com/69623818/143376277-b37684e5-38e9-44d7-9e2e-f726fcc803af.png)

**Comment by DARKDRAGON532** [comment]
@PhamLa72, what all did you clear from here?
![image](https://user-images.githubusercontent.com/69623818/143376468-786d05f2-c55e-49db-a26d-6e97410fd1fe.png)
or
![image](https://user-images.githubusercontent.com/69623818/143376511-802aab88-b8e2-4f62-9f27-a5fcd0d99ebc.png)

**Comment by PhamLa72** [comment]
all except form autofill and password, i clean with ccleaner

**Comment by DARKDRAGON532** [comment]
can you do it again and see if the extension throws any error?

**Comment by PhamLa72** [comment]
it worked when clearing browsing data in chrome, but with ccleaner it's still the same, what do i have to turn off cleanup to keep it working?
![image](https://user-images.githubusercontent.com/95004365/143401304-d4919c83-b1f9-43e0-be40-5bfb1b66872e.png)

**Comment by DARKDRAGON532** [comment]
> it worked when clearing browsing data in chrome, but with ccleaner it's still the same, what do i have to turn off cleanup to keep it working? ![image](https://user-images.githubusercontent.com/95004365/143401304-d4919c83-b1f9-43e0-be40-5bfb1b66872e.png)

Does the extension throw any errors?

**Comment by PhamLa72** [comment]
when cleaning with ccleaner as above, the utility will not run, does not show the number of dislikes, need to reinstall the utility to continue working, but when deleting data with chrome, it still works

**Comment by Cequallium** [comment]
i dont think chrome clears "compact databases" and "session" try disabling those on ccleaner, 
also i dont recommend using ccleaner and instead just using the preinstalled windows "disk cleanup".

**Comment by PhamLa72** [comment]
It's okay, please don't worry about it, you've worked hard. I don't often
use this utility at the moment

Vào 12:36, Th 2, 10 thg 1, 2022 Cequallium ***@***.***> đã
viết:

**Comment by PhamLa72** [comment]
It's okay, please don't worry about it, you've worked hard. I don't often
use this utility at the moment

Vào 10:47, Th 5, 25 thg 11, 2021 DARKDRAGON532 ***@***.***>
đã viết:

**Comment by PhamLa72** [comment]
Sorry I don't check my mail often, I tried clearing browsing data with
ccleaner and it still works, awesome, I appreciate your efforts, I found
your plugin Since the day youtube hides dislike, I installed your plugin
and found it superior to others. I made a video review of your gadgets on
youtube and everyone rated it very well, I hope you develop in the future.

Vào 12:42, Th 2, 10 thg 1, 2022 Phạm Thị Thanh Là Trường THCS Tân Thanh
Lạng Giang ***@***.***> đã viết:

**Comment by Anarios** [comment]
I think this can be closed now? Leva a message if it needs reopening.

**Comment by PhamLa72** [comment]
Thanks a lot. You can close thread

Vào 17:13, Th 2, 10 thg 1, 2022 Dmitrii Selivanov ***@***.***>
đã viết:
