### ISSUE TITLE
(Feature Request): Add one question in Issue/bug report template

### ISSUE THREAD

**Issue by cyrildtm** [Anarios/return-youtube-dislike#580]
### Extension or Userscript?

Both

### Request or suggest a new feature!

At the end of the bug report questionnaire, add a question "Will you be available for follow-up questions and help with developers further diagnose the situation"

It's frustrating when a user writes a report, and forgets about it. Developers don't always run into the same bug within their usage cases, and the bug reports are not always clear enough for re-creating the problem. With this questionnaire, developers can gauge the user interests and therefore put priorities. 

### Ways to implement this!

Edit the template

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by Alejandrogayol** [comment]
Agree
