### ISSUE TITLE
(Bug): opera settings missing

### ISSUE THREAD

**Issue by undertaker8187** [Anarios/return-youtube-dislike#582]
### Browser

opera

### Browser Version

 v85.0.4341.75

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.1

### Video link where you see the problem

dont can record it

### What happened?

i dont see the setting for coloring ect on opera. i looked in Extension and on youtube no chance to find the settings

### How to reproduce/recreate?

Tell us how it happened with detailed steps for us.

**Comment by PickleNik** [comment]
https://youtu.be/18ti0fbBrZ4
