### ISSUE TITLE
(Bug): Like duplicating 

### ISSUE THREAD

**Issue by Emptypng** [Anarios/return-youtube-dislike#584]
### Browser

Firefox Nightly

### Browser Version

Version 102.0a1 (2022-05-03)

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.1

### Video link where you see the problem

https://imgur.com/a/385zXd9

### What happened?

Every so often when I like a video the like count duplicates, it doesn't happen on every video, I'm unsure as to why.  

### How to reproduce/recreate?

1. Install extension on Firefox nightly latest
2. Go through a couple YouTube videos liking them
3. profit

**Comment by Emptypng** [comment]
Thank you for working on it, you're welcome for reporting it

**Comment by parsivan** [comment]
the same happens for me even though i use different formatting settings. For me the number goes from something like 37546 to 3700037546. not a big deal it's just distracting some times.

**Comment by bendy1234** [comment]
![image](https://user-images.githubusercontent.com/83143663/172516065-98506fa0-9d23-4a28-a3bd-ac699f6b3d91.png)
the count was 532 before I clicked like

Extension version 3.0.0.2

I think the new/updated like count just gets added on to the old like count

**Comment by flumiie** [comment]
Is this still an issue? Mine repeats like this, showing the formatted and the shortened version.
![image](https://user-images.githubusercontent.com/8995187/197731444-8eaa4de9-8afe-4e96-ae57-214b4bd046e2.png)

**Comment by PickleNik** [comment]
as far as I can tell it's been resolved in the latest version, please reopen or ping if it's still happening for you
