### ISSUE TITLE
(Feature Request): Please stop updating the extension every single day

### ISSUE THREAD

**Issue by AustinGitHub** [Anarios/return-youtube-dislike#589]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

I keep having to update my browser every other day because of the extension and it's really frustrating. Please look into doing updates in terms of releases because I'm very close to uninstalling the extension just because of how frequent an update is. It seems to me an update gets pushed as soon as a PR gets merged in. I don't think this is the right way to do things in my honest opinion. Please look into doing releases rather than an update every single day really annoying. 

### Ways to implement this!

Don't push update to chrome extension store every time a PR gets merged. Pace them out to be every other week or so, that way it's worth updated. Because if something gets regressed and you have to revert a PR, then you'll end up having to push another update to the extension to update this revert. The way it appears and with how many times I've had to update my browser due to this extension, that updates are being pushed constantly and that isn't the way to go about this in my opinion. 

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by ibeluga** [comment]
ok

**Comment by AndrewCPU** [comment]
Thank god. This has been driving me insane
