### ISSUE TITLE
(Feature Request):Add user's input to the counter

### ISSUE THREAD

**Issue by sooswastaken** [Anarios/return-youtube-dislike#59]
### Extension or Userscript?

Both

### Request or suggest a new feature!

It would be great if the user input was incorporated in the counter...

EX; Press dislike, dislike counter goes up by one.

### Can you work on this?

- [ ] Yes
- [ ] No

**Comment by sooswastaken** [comment]
Actually, it might be hard to implement this, as the YouTube's data might change at any time, so just adding 1 to the counter if the user has the dislike button clicked cant be a optimal solution.

**Comment by SirLich** [comment]
Can't it just be a UX thing? i.e., bump the number by one if the dislike counter is clicked. It will potentially be a bit "false" but will provide better feedback to user of extension.
