### ISSUE TITLE
(Bug): 0 dislikes

### ISSUE THREAD

**Issue by pixkk** [Anarios/return-youtube-dislike#603]
### Browser

Google Chrome

### Browser Version

Chrome v100

### Extension or Userscript?

Extension

### Extension/Userscript Version

30,0,0,1

### Video link where you see the problem

https://www.youtube.com/watch?v=RcZ1jPFLqq4

### What happened?

The video watched 62k people, 4.2k liked it, but 0 dislikes
![image](https://user-images.githubusercontent.com/30828435/167843734-3dde723a-c0c4-488f-8eb7-e0e65ad1e67d.png)

### How to reproduce/recreate?

Open video https://www.youtube.com/watch?v=RcZ1jPFLqq4

**Comment by sy-b** [comment]
This is what I see

```JSON
{
"id":"RcZ1jPFLqq4",
"dateCreated":"2022-05-11T17:00:17.11493Z",
"likes":4441,
"dislikes":82,
"rating":4.927481759893876,
"viewCount":69010,
"deleted":false}
```

**Comment by sy-b** [comment]
If you are accessing from Russia, you might have some problems.

refer:

**Comment by pixkk** [comment]
> If you are accessing from Russia, you might have some problems.
> 
> refer: [#497 (comment)](https://github.com/Anarios/return-youtube-dislike/issues/497#issuecomment-1085522380)

No, i am from Ukraine.

**Comment by pixkk** [comment]
The problem was the lack of dislikes.
