### ISSUE TITLE
(Bug): Seemingly random like number on videos

### ISSUE THREAD

**Issue by Kapocsi** [Anarios/return-youtube-dislike#605]
### Browser

Brave Browser 

### Browser Version

1.38.111

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.1

### Video link where you see the problem

https://www.youtube.com/watch?v=f-HtmE0U7T8

### What happened?

MacOS - 12.4 Beta

Not an isolated incident, but this number keeps coming up on random videos for some reason.
![CleanShot 2022-05-11 at 18 35 09](https://user-images.githubusercontent.com/84490604/167969243-5b35d6d5-7df1-4254-b97c-2b43d5648b2e.png)
 

### How to reproduce/recreate?

Not sure how to reproduce it seems to be at random for me.

**Comment by PickleNik** [comment]
@tomkap011 it duplicates the like number when it updates, please disable "Like Re-Formatting" in settings for now
<img width="326" alt="Screen Shot 2022-05-11 at 8 50 20 PM" src="https://user-images.githubusercontent.com/31113245/167970321-7ff66347-2c4b-4339-9c47-2d1364af0670.png">
.

**Comment by tomkap011** [comment]
> @tomkap011 it duplicates the like number when it updates, please disable "Like Re-Formatting" in settings for now <img alt="Screen Shot 2022-05-11 at 8 50 20 PM" width="326" src="https://user-images.githubusercontent.com/31113245/167970321-7ff66347-2c4b-4339-9c47-2d1364af0670.png"> .

That seems to have fixed it; should I leave the ticket open?

**Comment by PickleNik** [comment]
yeah, till the PR closes
