### ISSUE TITLE
Extension code size reduction

### ISSUE THREAD

**Issue by cyrildtm** [Anarios/return-youtube-dislike#611]
Strip comments from source code when building extension

webpack.config.js

https://github.com/Anarios/return-youtube-dislike/blob/df8d72c379e6c5e1ba4fd3bee252289b5c2b7cd2/webpack.config.js#L22

https://webpack.js.org/configuration/optimization/#optimizationminimize
https://github.com/webpack-contrib/terser-webpack-plugin#terseroptions
https://github.com/terser/terser#minify-options
https://github.com/terser/terser#format-options

```
  optimization: {
    minimize: true,
    minimizer: [
      new TerserPlugin({
        parallel: true,
        terserOptions: {
          format: {
            comments: false, 
          },
        },
      }),
    ],
  },
```

**Comment by Anarios** [comment]
Difference is neglibible, but it affects the review process negatively.
