### ISSUE TITLE
(Feature Request): Ability to hide the extention icon from the toolbox

### ISSUE THREAD

**Issue by AFCMS** [Anarios/return-youtube-dislike#614]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Here is how my toolbox looks like on my browser:

![image](https://user-images.githubusercontent.com/61794590/168621233-d324fa87-4f68-4e82-ba72-836642056ea2.png)

It takes much space on my laptop screen, just for extensions I use every day.

Since the icon is just used for credits and some basic settings, I would like to be able to hide it and configure the extension from the extensions tab.

### Ways to implement this!

idk

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by sy-b** [comment]
Right click --> unpin (for Chromium based browsers)

**Comment by AFCMS** [comment]
Oops, didn't know this :)

Trust me, I searched multiple times before  how to get rid of an icon like that.
