### ISSUE TITLE
(Bug): numberFormat rounds the dislike number

### ISSUE THREAD

**Issue by DARKDRAGON532** [Anarios/return-youtube-dislike#62]
### Browser

Brave (But should happen on all browsers)

### Browser Version

Version 1.31.91 Chromium: 95.0.4638.69 

### Extension or Userscript?

Extension

### Extension/Userscript Version

v0.0.0.9

### Video link where you see the problem

https://www.youtube.com/watch?v=YbJOTdZBX1g

### What happened?

```javascript
function numberFormat(numberState) {
    const userLocales = navigator.language;
    const formatter = Intl.NumberFormat(userLocales, { notation: "compact" });
    return formatter.format(numberState);
  }
```
This function rounds the `numberState`
![image](https://user-images.githubusercontent.com/69623818/143563766-5ff771e8-4984-4881-b7c3-f98ab96eb374.png)
This happens to be an issue on videos (notably being the video I attached) showing more dislikes than what there actually is. Open the video above with the extension and it will show 20M dislikes, if I open the same video (dislike still isnt removed for me) youtube displays it floored.
![image](https://user-images.githubusercontent.com/69623818/143564036-e3a41ac8-c4e7-407c-9ac7-d25fe694d707.png)

## Soultion
If theres something you can pass to the options to prevent this for happening then do that (i checked the docs and couldnt find anything)
Alternatively you can code a function to floor it and then pass it.

I can work on it

**Comment by Dr-S-Otter** [comment]
Sounds like something that should be relatively easy, maybe it's a "good first issue". In turn, that means I'd like to do it if that's okay

**Comment by j14-c** [comment]
Something like this maybe?

```js
function roundDown(num) {
    if (num < 1000) return num;
    const decimal = Math.floor(Math.log10(num) - 1);
    const value = Math.floor(num / 10 ** decimal);
    return value * (10 ** decimal);
}

function numberFormat(numberState) {
    const userLocales = navigator.language;

    const formatter = Intl.NumberFormat(userLocales, {
        notation: 'compact',
        minimumFractionDigits: 1,
        maximumFractionDigits: 1
    });

    return formatter.format(roundDown(numberState)).replace('.0', '');
}

numberFormat(19500000); // 19M
numberFormat(19500); // 19K
numberFormat(1790); // 1.7K
numberFormat(950); // 950
```

**Comment by DARKDRAGON532** [comment]
@j14-c that works, you can open a pr.

**Comment by j14-c** [comment]
I just noticed that `roundDown(123456)` returns `120000`.
This should be a better solution.

```js
function roundDown(num) {
    if (num < 1000) return num;
    const int = Math.floor(Math.log10(num) - 2);
    const decimal = int + (int % 3 ? 1 : 0);
    const value = Math.floor(num / 10 ** decimal);
    return value * (10 ** decimal);
}

roundDown(1); // 1
roundDown(12); // 12
roundDown(123); // 123
roundDown(1234); // 1200
roundDown(12345); // 12000
roundDown(123456); // 123000
roundDown(1234567); // 1200000
```
