### ISSUE TITLE
(Bug): Dislikes temporarily unavailable.

### ISSUE THREAD

**Issue by QazCetelic** [Anarios/return-youtube-dislike#621]
### Browser

Firefox

### Browser Version

100

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.1

### Video link where you see the problem

see description

### What happened?

Dislikes temporarily unavailable.

![image](https://user-images.githubusercontent.com/51381523/169284461-8195470d-a2a2-4b5c-acca-062bf1654ec1.png)

### How to reproduce/recreate?

1. Open YouTube
2. Watch Video
3. Look at amount of dislikes

**Comment by Gaminguide1000** [comment]
Bro, it is TEMPORARILY Unavailable. Just wait

**Comment by Anarios** [comment]
Please reopen if still persists.

**Comment by QazCetelic** [comment]
Why was it unavailable?
