### ISSUE TITLE
(Feature Request): Special cut label

### ISSUE THREAD

**Issue by erkinalp** [Anarios/return-youtube-dislike#630]
### Extension or Userscript?

Both

### Request or suggest a new feature!

There are videos that only consist of trailers, teasers and special cuts of other videos. It would be useful to identify those cuts using a label system.

### Ways to implement this!

This would be a label with a required reference to another video.

- Trailers/teasers
- So-called director's cut
- Outtake-only videos

Previously: https://github.com/ajayyy/SponsorBlock/issues/1325

### Can you work on this?

- [ ] Yes
- [ ] No

**Comment by PickleNik** [comment]
seems like a great idea for a new extension
