### ISSUE TITLE
(Bug): Formatting (repetitive tiling of label)

### ISSUE THREAD

**Issue by LahaLuhem** [Anarios/return-youtube-dislike#633]
### Browser

Microsoft Edge

### Browser Version

Version 101.0.1210.53 (Official build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=HbH8BhgKXbM

### What happened?

<img width="579" alt="image" src="https://user-images.githubusercontent.com/47954571/170873169-cdcfa890-9075-4057-b0f2-cde340313819.png">

The number of likes seem to be formatted incorrectly. This issue went away on reloading the page

### How to reproduce/recreate?

Watch the video.

**Comment by PickleNik** [comment]
as far as I can tell it's been resolved in the latest version, please reopen or ping if it's still happening for you
