### ISSUE TITLE
(Feature Request): BACKEND: bot to spam comments with dislike count #engagement #evil

### ISSUE THREAD

**Issue by allanlaal** [Anarios/return-youtube-dislike#634]
### Extension or Userscript?

Backend

### Request or suggest a new feature!

this is the best dislike db

the more users we have, the more accuracy the db will get

so, why not have a bot automatically post a comment on videos with the Current Dislike Count and edit that post to keep it up to date (with updated-at timestamp)

+ ofc a reference to this extension (without URL to not get shadowbanned?)

### Ways to implement this!

use existing yt bot code: https://github.com/search?o=desc&q=youtube+comment+bot&s=stars&type=Repositories

bot posts on videos above X (million?, to not get banned by YT (that often)) views 

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by sy-b** [comment]
Like this https://github.com/ForrestKnight/yt-dislikes?

Also refer: https://youtu.be/1uAH93tzfQY

**Comment by allanlaal** [comment]
solved then :)
