### ISSUE TITLE
(Bug): YouTube changed "Watch10" HTML

### ISSUE THREAD

**Issue by aubymori** [Anarios/return-youtube-dislike#651]
### Browser

Mozilla Firefox

### Browser Version

78.15.0 ESR

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.1

### Video link where you see the problem

Any

### What happened?

YouTube has (frankly, unnecessarily) changed the HTML code for the "Watch10" layout for some users. This has caused the ratio bar to appear on the right side of the bar.
![image](https://user-images.githubusercontent.com/44238627/174422227-aadd0ddb-c7cc-442c-beb9-21d5fe5b834b.png)
(NOTE: I have a CSS stylesheet applied here, however it does break without it, although I don't feel like showing that, you'll see why  below)

### How to reproduce/recreate?

1. Open an incognito window, go to YouTube, click a random video.
2. Is the bug there? If so, great! Replicated. If not, go back to step 1.

This bug is iffy to recreate because it relies on your YouTube "visitor data" being set to one that gives you the new update, which is completely random.

**Comment by aubymori** [comment]
only temporary
also i know for a fact this is because they changed the html, i compared myself
this isn't because i'm on an old browser

**Comment by TheBSODAndWSODFan** [comment]
or maybe add toggle to hide or unhide ratio bar 
because i still on old design but after extension update, ratio bar missing
![image](https://user-images.githubusercontent.com/78845241/185722739-e6b172dc-775f-4598-b530-9c1fe519fb18.png)

**Comment by ErykDarnowski** [comment]
Hey, I've worked on the bar in [this](https://github.com/Anarios/return-youtube-dislike/pull/771) PR!
Let me know if the issue still persists.

**Comment by Nightcaat** [comment]
Fixed in #771
