### ISSUE TITLE
(Bug): "Temporarily unavailable"

### ISSUE THREAD

**Issue by IronClaw99** [Anarios/return-youtube-dislike#652]
### Browser

Google Chrome

### Browser Version

102.0.5005.115

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=SiU46pwzhqg

### What happened?

I am getting "Temporarily unavailable" on every video I watch. This extension isn't working properly.

### How to reproduce/recreate?

I tried using both Firefox and Chrome. Same issue.

**Comment by Ghostrider231** [comment]
Getting the same problem too, although it just shows "dislike" instead of "Temporarily unavailable"

**Comment by sy-b** [comment]
It is working perfectly for me. Seems like the problem is at your end. 

What do you see here?
https://returnyoutubedislikeapi.com/votes?videoId=kxOuG8jMIgI

**Comment by IronClaw99** [comment]
> It is working perfectly for me. Seems like the problem is at your end.
> 
> What do you see here? https://returnyoutubedislikeapi.com/votes?videoId=kxOuG8jMIgI

I am getting a 500 Internal Server Error message when trying to view this link.

**Comment by sy-b** [comment]
Seems like some problem with cloudfare
shields.io is down too

**Comment by sy-b** [comment]
![Cloudflare status 220621 0656 UTC](https://user-images.githubusercontent.com/94835959/174736128-e030deaa-6510-4ba6-8d99-d6f0dbc7becb.PNG)

**Comment by sy-b** [comment]
@IronClaw99
You can close this issue if its resolved.

**Comment by IronClaw99** [comment]
Turns out, this was a CloudFlare issue after all.
