### ISSUE TITLE
GoTube option

### ISSUE THREAD

**Issue by GKid94** [Anarios/return-youtube-dislike#657]
Add the Return Youtube Dislike option in GoTube https://play.google.com/store/apps/details?id=premium.gotube.adblock.utube

**Comment by Martinligabue** [comment]
this should be a feedback for gotube, not for return dislike

**Comment by sy-b** [comment]
@GKid94 

RYD's owner has no control over GoTube's codebase. Same goes for everything except Return YouTube Dislike Extension and RYD API.

To request this feature you will have to [contact GoTube's Developer(s)](mailto:gotube.feedback@gmail.com)

**Comment by sy-b** [comment]
You can now close this issue.
