### ISSUE TITLE
(Feature Request): Bring like bar back for the new Youtube UI

### ISSUE THREAD

**Issue by yashptel** [Anarios/return-youtube-dislike#658]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Youtube recently changed their UI which has disabled the UI like bar. I miss that. So I am thinking of adding it back to the UI. 

### Ways to implement this!

Target a new element called "actions-inner" to inject the the like bar component. And make some changes to the like bar dimensions for the particular case so it matches the new UI. And also take care that It does not break the UI for the older Youtube UI.

### Can you work on this?

- [X] Yes
- [ ] No

**Comment by Nightcaat** [comment]
This appears to be a duplicate and has long been resolved.
