### ISSUE TITLE
(Bug): Double Dislike ratio bar

### ISSUE THREAD

**Issue by MagentaPuppy** [Anarios/return-youtube-dislike#66]
### Browser

Firefox

### Browser Version

Firefox 93.0

### Extension or Userscript?

Extension

### Extension/Userscript Version

0.0.0.9

### Video link where you see the problem

https://www.youtube.com/watch?v=g2p4P36VtQE

### What happened?

This may be to do with how where i am dislikes haven't yet been removed, [here is an example on the video linked above](https://imgur.com/a/fHHYOZO) as you can see there are two ratio bars rather than one

**Comment by MagentaPuppy** [comment]
Update: i tested disliking the video and it did [this](https://imgur.com/a/9bYuT0A)

**Comment by MagentaPuppy** [comment]
> Update: i tested disliking the video and it did [this](https://imgur.com/a/9bYuT0A)

^ that only happens when you dislike then re-like a video

**Comment by DARKDRAGON532** [comment]
You answered yourself :P
I'll try to add an option to remove the ratio bar.

**Comment by DARKDRAGON532** [comment]
> Update: i tested disliking the video and it did [this](https://imgur.com/a/9bYuT0A)



> > Update: i tested disliking the video and it did [this](https://imgur.com/a/9bYuT0A)
> 
> ^ that only happens when you dislike then re-like a video

This happens because your dislikes aren't gone yet

**Comment by MagentaPuppy** [comment]
ok
