### ISSUE TITLE
(Bug): Videos show 0 dislikes

### ISSUE THREAD

**Issue by IronClaw99** [Anarios/return-youtube-dislike#660]
### Browser

Google Chrome

### Browser Version

103.0.5060.53

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=5vkrh1c8RR8

### What happened?

The video is showing 0 dislikes.

### How to reproduce/recreate?

I tried using two different browsers.

**Comment by Zorgodon** [comment]
+1. It seems client-side development has ground to a halt since May, and now the API isn't allowing dislike submissions for new videos (it still returns dislikes for old videos). If I had to speculate, it may be that anarios has run out of storage space on https://returnyoutubedislike.com.

**Comment by Zorgodon** [comment]
Actually, it seems that older videos are affected too: https://www.youtube.com/watch?v=rY413t5fArw

**Comment by Gavinboley** [comment]
Can confirm broken on firefox v101.0.1 and RYD v3.0.0.1 as well.

**Comment by xenago** [comment]
Yes, it's not working on any client I've tested.

**Comment by KweezyPlay** [comment]
same issue

**Comment by dkf-lab** [comment]
Sharing issue on Firefox 101.0.1 RYD v3.0.0.1

**Comment by Benj2005** [comment]
Yep, same issue here on Firefox Developer Edition 102.0b9.

**Comment by wobsoriano** [comment]
API issue

Non-working video: https://returnyoutubedislikeapi.com/votes?videoId=EJxeMbDTkVI
Working: https://returnyoutubedislikeapi.com/votes?videoId=kfVsfOSbJY0

**Comment by Peterscraps** [comment]
I noticed this too, older videos preserved with newer videos showing 0
Google Chrome Version 103.0.5060.53 RYD v3.0.0.1

**Comment by JasonHorkles** [comment]
From their discord:
> henlo chat, you may be seeing 0s for counts on newer videos, something brokey, do not worry, it will be fixed soon™️

**Comment by teganburns** [comment]
It looks to me like Youtube officially removed the dislike count across the platform. It used to be, if you open a video in incognito, you see the dislike button with count (and this is where you can scrape the data); this no longer appears to be the case.  

As far as I'm aware, there's no other way to retrieve a true dislike count now that this has been removed. You can still use the cached data but new videos will only show dislikes if other users with the extension dislike videos and this will not give you a _true_ dislike count.

Someone please tell me I'm wrong. 😔

**Comment by Anarios** [comment]
Fixed, sorry about that.

**Comment by smurat** [comment]
I think problem dissepeared. Currently dislikes counts show up for me.

**Comment by IronClaw99** [comment]
Looks like this issue has returned, this time on the newest videos. #671.
