### ISSUE TITLE
Help with firefox extension

### ISSUE THREAD

**Issue by bitakshat** [Anarios/return-youtube-dislike#670]
Hi, I'm working on a firefox extension to calculate video playback time for youtube. The extension works fine when its loaded on tab with youtube for the first time. When I open multiple youtube tabs it only works for the recent tab. How can I fix this? 
(its been a while since I'm working on this extension I've tried the most I can but still can't figure out. 
Here is the github link for the project [https://github.com/bitakshat/VPTC_Extension](Repository)

**Comment by PickleNik** [comment]
Seems like a good place for this would be https://github.com/Anarios/return-youtube-dislike/discussions or Discord.
