### ISSUE TITLE
(Bug): Videos are showing 0 dislikes

### ISSUE THREAD

**Issue by IronClaw99** [Anarios/return-youtube-dislike#671]
### Browser

Google Chrome

### Browser Version

103.0.5060.114

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=oABLRCdJMmQ

### What happened?

Videos are showing 0 dislikes.

### How to reproduce/recreate?

It's also happening on Firefox.

**Comment by HaselLoyance** [comment]
Bumping, because I just noticed the same thing on this exact video and decided to check if that's a known problem or not :smile:

**Comment by IronClaw99** [comment]
> Bumping, because I just noticed the same thing on this exact video and decided to check if that's a known problem or not 😄 Edit: actually, this seems to be every video? At least the recently uploaded ones (since ~12h ago).

Yes, the newest ones seem to have an issue.

**Comment by MrAmos123** [comment]
Funny, I'm just watching this video and noticed it was showing 0 also. 

Note this is several hours after he posted it yet it's still not populated.

Unless he got 117k likes and 0 dislikes (which is unlikely) :D

**Comment by Anarios** [comment]
Fixed
