### ISSUE TITLE
(Bug): 

### ISSUE THREAD

**Issue by AF1011** [Anarios/return-youtube-dislike#676]
### Browser

Google Chrome

### Browser Version

103.0.5060.114

### Extension or Userscript?

Userscript

### Extension/Userscript Version

3.0.1

### Video link where you see the problem

https://www.youtube.com/watch?v=ML2U4FGWoow

### What happened?

This happened after loading video and the counter doesn't works.

For the first attempt still works and the 2nd or 3rd attempt it's doesn't work.
<img width="371" alt="Captured01" src="https://user-images.githubusercontent.com/54230948/178274993-a9dc4fb3-a2ee-4c3f-a88e-fe03dc021761.PNG">

### How to reproduce/recreate?

When i'll open any tabs in video, it's seem doesn't work except other tabs...

The console shows after loading the pages "Received Count", but the "Dislike" text is not replaced.

**Comment by Anarios** [comment]
It was temporary
