### ISSUE TITLE
(Bug): Newest videos show 0 dislikes

### ISSUE THREAD

**Issue by IronClaw99** [Anarios/return-youtube-dislike#679]
### Browser

Google Chrome

### Browser Version

103.0.5060.114

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=NW0rdYGQtRs

### What happened?

The newest videos on YouTube show 0 dislikes. This has been an on and off bug for the past couple weeks.

### How to reproduce/recreate?

Older videos show dislikes, meanwhile the newest videos show 0 dislikes.

**Comment by 0xCUB3** [comment]
Same for me on latest version of firefox.

**Comment by Anarios** [comment]
Thanks, great catch. The votes were being recoded, just weren't being updated in the result. Fixed now
