### ISSUE TITLE
Support for Firefox Andoid(FR)

### ISSUE THREAD

**Issue by VihagChaturvedi** [Anarios/return-youtube-dislike#68]
Hello! Appreciate the initiative (^^)

The extension isnt supported on Firefox for Android(cannot confirm for iOS).

Tamper monkey isn't available for mobile either.

Are there plans to support this extension for mobile platforms? If not, what are our options

Thank you for this project, have a great day (^^)

**Comment by DARKDRAGON532** [comment]
Unfortunately we have no control over whether this extension can be downloaded on Firefox for Android.

> We would like to enable support for more extensions on the new Firefox for Android experience and we are currently evaluating ways we can do so without introducing the compatibility and security issues from the previous version of our mobile browser for Android. We'll provide updates as soon as we have more details.
This is Mozilla's statement about this.

**Comment by Hans5958** [comment]
You could, buy use the Nightly version.

https://www.ghacks.net/2020/10/01/you-can-now-install-any-add-on-in-firefox-nightly-for-android-but-it-is-complicated/

**Comment by VihagChaturvedi** [comment]
Thank you for your replies.

I have installed Nightly FF.

Weirdly enough, after creating my firefox account and logging in, I can no longer view non-reccomeded extensions.

So I am not able to add the extension to my custom collection either.

Is it somehow possible for me to download the .xpi file and use usb-debugging to install it?

**Comment by DARKDRAGON532** [comment]
> Is downloading the .xpi file and use usb-debugging to install it a viable option?

You'd have to keep reinstalling whenever there is an update, but if that's fine by you then go ahead.

**Comment by VihagChaturvedi** [comment]
Thank you

Are there any other methods to get the extension working, though?

**Comment by DARKDRAGON532** [comment]
> Thank you
> 
> Are there any other methods to get the extension working, though?

Maybe using an older version of firefox where all extensions were supported, but I highly discourage from doing this due to safety issues.
Or wait until support is added.
What issues are you getting when creating a collection? If

**Comment by VihagChaturvedi** [comment]
Thank you for your response.

I have followed the steps mentioned in the link above about FF Nightly

The issue is as follows.

While you aren't logged in to FF Addons manager, you will not have access to collections.

Only upon creating an account, will you be able to create a collection, understandably so.

The problem with creating a collection, is that it only allows "reccomended" (aka the add ons that mozilla sees fit for mobile) add ons.

Meaning, if an add on has not been "Reccomended" by Mozilla, you cannot add it to your collection.

So essentially, there is no way of getting the extension on mobile via the Mozilla Add ons Manager.

**Comment by DARKDRAGON532** [comment]
@VihagChaturvedi I was checking the extension on android to see if it is working and there a few major bugs, I dont think the extension will work on android. I'll try fixing it.

**Comment by VihagChaturvedi** [comment]
@DARKDRAGON532 thanks a lot man!

Should this issue remain open until the bugs are ironed out?

**Comment by DARKDRAGON532** [comment]
> @DARKDRAGON532 thanks a lot man!
> 
> Should this issue remain open until the bugs are ironed out?

Yes, or else we might forget about it :P

**Comment by VihagChaturvedi** [comment]
Sure lmfao

**Comment by NotHuza** [comment]
![Screenshot_20211129_142939](https://user-images.githubusercontent.com/37085494/143877145-fa95e155-df19-444d-b57a-ade2abd1de10.jpg)
Hmmm i not sure is this bug?

**Comment by DARKDRAGON532** [comment]
> ![Screenshot_20211129_142939](https://user-images.githubusercontent.com/37085494/143877145-fa95e155-df19-444d-b57a-ade2abd1de10.jpg) Hmmm i not sure is this bug? But in destop version only work but buggy this in minute show right number and then all go wrong

that is the "major bug" i was talking about :P

**Comment by NotHuza** [comment]
> > ![Screenshot_20211129_142939](https://user-images.githubusercontent.com/37085494/143877145-fa95e155-df19-444d-b57a-ade2abd1de10.jpg) Hmmm i not sure is this bug? But in destop version only work but buggy this in minute show right number and then all go wrong
> 
> thats the "major bug" i was talking about :P

Oh i delite this my replay sorry

**Comment by VihagChaturvedi** [comment]
Oddly specific number 🤔

**Comment by godspeedfw** [comment]
I installed the userscript on tampermonkey on the icecraven browser(firefox fork).
It works fine on the desktop version of youtube. 
![Screenshot_20211130-091309852~01](https://user-images.githubusercontent.com/74945202/143982180-43ed9c75-a08b-4e37-a7e4-a777d2314501.jpg)
But not on the mobile version.
![Screenshot_20211130-091316622~01](https://user-images.githubusercontent.com/74945202/143982211-4c7e6f56-ba76-4a78-8613-129d5d46a2ee.jpg)

**Comment by PandoraHayami** [comment]
There are some ways around to not being able to add different Add-ons to a collection, you can change the link to something like [this](addons.mozilla.org/en-US/firefox/) 

This will show you all the add-ons, not let you install them, but you are able to add the to collections

Or use an already created Add-on Collection, like the one one from Iceraven called "What I want on fenix" Which has Violentmonkey and Tampermonkey for userscripts, or another I personally have called "Get better Fenix" Anyway should work.

**Comment by AgentConDier** [comment]
Installing on Firefox Android Nightly via a collection created with PandoraHayami's link worked well for me.

As far as I can tell, the wrong like/dislike numbers are caused by the addon's fetch for `https://www.youtube.com/watch?v=oXEspXEMP-M` being redirected to `https://www.youtube.com/watch?v=oXEspXEMP-M` because the mobile user header is used, even if the addon was triggered from a desktop mode tab.

**Comment by AgentConDier** [comment]
I created a test version of the addon that always adds a user-agent header to the api request, which fixes the dislike count in desktop mode.
https://addons.mozilla.org/en-US/firefox/addon/temporary_testing_r-yt-dislike/
Collection: `15368551` `my-android-addons`

**Comment by godspeedfw** [comment]
Can the script also be updated to support m.youtube.com?

**Comment by vehosah** [comment]
> > Thank you
> > Are there any other methods to get the extension working, though?
> 
> Maybe using an older version of firefox where all extensions were supported, but I highly discourage from doing this due to safety issues. Or wait until support is added. What issues are you getting when creating a collection? I might be able to help.

I'm using an old Firefox version, but the extension doesn't work

**Comment by vehosah** [comment]
> @DARKDRAGON532 thanks a lot man!
> 
> Should this issue remain open until the bugs are ironed out?

He closed it lol

**Comment by nose-gnome** [comment]
> Thank you for your response.
> 
> I have followed the steps mentioned in the link above about FF Nightly
> 
> The issue is as follows.
> 
> While you aren't logged in to FF Addons manager, you will not have access to collections.
> 
> Only upon creating an account, will you be able to create a collection, understandably so.
> 
> The problem with creating a collection, is that it only allows "reccomended" (aka the add ons that mozilla sees fit for mobile) add ons.
> 
> Meaning, if an add on has not been "Reccomended" by Mozilla, you cannot add it to your collection.
> 
> So essentially, there is no way of getting the extension on mobile via the Mozilla Add ons Manager.
> 
> 

@VihagChaturvedi You can add non recommended extensions to your collection, I've done it with my collection a few weeks ago
