### ISSUE TITLE
Update the Discord Invite Link

### ISSUE THREAD

**Issue by SealedSaucer** [Anarios/return-youtube-dislike#69]
Update the Discord Invite Link on [returnyoutubedislike.com](https://www.returnyoutubedislike.com/).

**Comment by DARKDRAGON532** [comment]
it's working for me, what does it say for you?

**Comment by Anarios** [comment]
Hm, works for me. Which message do you see?

**Comment by SealedSaucer** [comment]
https://discord.com/invite/mYnESY4Md5

![Capture](https://user-images.githubusercontent.com/71928730/143695779-9df74e6f-ea8a-40e7-8911-8124b8076902.PNG)

**Comment by DARKDRAGON532** [comment]
Maybe you hit the 100 server limit, what is your username?

**Comment by SealedSaucer** [comment]
Oh, yeah... It's a problem on my end, I guess... Still not sure what the problem is tho... Because, if you hit the 100 Server Limit, it should show another error.

![image](https://user-images.githubusercontent.com/71928730/143709040-c026999d-fc93-4932-896f-9934f1c48d34.png)

**Comment by DARKDRAGON532** [comment]
> Oh, yeah... It's a problem on my end, I guess... Still not sure what the problem is tho... Because, if you hit the 100 Server Limit, it should show another error.
> 
> ![image](https://user-images.githubusercontent.com/71928730/143709040-c026999d-fc93-4932-896f-9934f1c48d34.png)

maybe youre ratelimited, try again after a few hours

**Comment by SealedSaucer** [comment]
> > Oh, yeah... It's a problem on my end, I guess... Still not sure what the problem is tho... Because, if you hit the 100 Server Limit, it should show another error.
> > ![image](https://user-images.githubusercontent.com/71928730/143709040-c026999d-fc93-4932-896f-9934f1c48d34.png)
> 
> maybe youre ratelimited, try again after a few hours

I see, I will try again later.

**Comment by SealedSaucer** [comment]
Also, is this a known error, @Anarios ?

![image](https://user-images.githubusercontent.com/71928730/143718680-93dc2d2b-f3b3-4a2d-b5a8-fa38caf7ab42.png)

**Comment by Anarios** [comment]
It's not an error. Just a warning.
