### ISSUE TITLE
Temporary Unavailable

### ISSUE THREAD

**Issue by SagXD** [Anarios/return-youtube-dislike#696]
### Browser

Opera

### Browser Version

Opera 89.0.4447.48

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.2

### Video link where you see the problem

https://youtu.be/wJi0xeNI6ho

### What happened?

Dislike Not Showing

### How to reproduce/recreate?

I Just Watch A Video 

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by allenrobberson** [comment]
Same in MS Edge

**Comment by IEmptyI** [comment]
Firefox nightly here, same issue

**Comment by petercunha** [comment]
Same in Chrome

**Comment by IEmptyI** [comment]
> Firefox nightly here, same issue

Clicking on the dislike button makes the dislike number show but goes back to Temporary Unavailable once you change videos or refresh

**Comment by WillFP** [comment]
Same with Brave

**Comment by petercunha** [comment]
Seems to be fixed. Thanks!
