### ISSUE TITLE
 Dislikes "Temporarily Unavailable" on all YT-Videos 

### ISSUE THREAD

**Issue by osumeister** [Anarios/return-youtube-dislike#700]
### Browser

Google Chrome

### Browser Version

Version 103

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=2zqTEhA-orI

### What happened?

 Dislikes are "Temporarily Unavailable" on all YT-Videos. I reinstalled the extension and restarted the browser, which didnt help. 

![yt-dislikes](https://user-images.githubusercontent.com/102928001/181064944-13a62372-96e1-4839-81ff-f2573dfaa7c6.jpg)

### How to reproduce/recreate?

It happens on every video, i didnt do anything special.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Alokita-Biosense01** [comment]
@osumeister I guess there was an outage sort of thing for a few minutes. It's working well for me rn. wbu?

**Comment by osumeister** [comment]
@Alokita-Biosense01 you are right, it works perfectly now, thank you
