### ISSUE TITLE
Every video shows "temporarily unavailable"

### ISSUE THREAD

**Issue by IronClaw99** [Anarios/return-youtube-dislike#702]
### Browser

Google Chrome

### Browser Version

103.0.5060.134

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=iiE4rvK12uA

### What happened?

Every video I watch shows "temporarily unavailable".

### How to reproduce/recreate?

This issue is also happening on Mozilla Firefox. I have also tried uninstalling and reinstalling the extension.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Anarios** [comment]
It was temporary
