### ISSUE TITLE
Color Theme Like and Dislike on YouTube Vanced, UYouPlus, and Upcoming ReVanced!

### ISSUE THREAD

**Issue by Loading617** [Anarios/return-youtube-dislike#705]
### Extension or Userscript?

Userscript

### Request or suggest a new feature!

I want to request color theme on like and dislike on youtube vanced, uyouplus, and revanced when it's done 

### Can you work on this?

- [ ] Yes
- [X] No

### Will you be available for follow-up questions to help developers implement this?

Yes

**Comment by PickleNik** [comment]
Request it at the Githubs of the respective apps, we only provide the public API for them, we have nothing to do with the development of those apps themselves.
