### ISSUE TITLE
Automatic click "This video may be inappropriate for some users"

### ISSUE THREAD

**Issue by bob-carter** [Anarios/return-youtube-dislike#709]
### Extension or Userscript?

Both

### Request or suggest a new feature!

I realize this is sorta outside of what this addon is for, but it would be a simple feature that a lot of people have been requesting. Just a simple script that automatically clicks or bypasses the content warning screen that most people are annoyed by. After all I think an old man smoking a pipe, or a view game review of Might and Magic, or the like isn't a big deal.

I ticked both, because I figure it could be either.

### Ways to implement this!

Just check if the page displays the content warning screen, and auto-click approve or bypass it.

### Can you work on this?

- [ ] Yes
- [x] No

### Will you be available for follow-up questions to help developers implement this?

Yes

**Comment by PickleNik** [comment]
Never seen a content warning, so idk about most people, perhaps that's region-based, or age-based.
Sounds like a cool feature for a different extension, or more likely a userscript.
