### ISSUE TITLE
(Feature Request): Storing dislike information on own server

### ISSUE THREAD

**Issue by NightLancer** [Anarios/return-youtube-dislike#71]
### Extension or Userscript?

Both

### Request or suggest a new feature!

That said, that YouTube will probably remove their API requesting feature for dislike quantity, and if so, any API-based extension will fail when that happens. So, storing video ids alongside with their dislike quantity may be a solution.

### Ways to implement this!

I understand this is very presumptuous request and if you decide close it at once. I doubt you can obtain IDs of profiles from which dislikes where put(for better accuracy), so even theoretically there be could only raw amount of dislike count, adding with own count from your extension on top of that(more accurate - unique count from recorded users ids list, way less accurate - just adding "+1" to current one). That should be not so hard for someone familiar with server-side database coding, but sadly I'm not and can't contribute on that. Also obviously the whole idea could possibly work only if people will be willing for donating for servers rent and maintaining(not saying the work needed to be done for that). 

I wish that YT will not modify their API but I doubt they willn't. And when that happens your extension is gonna broke anyway, so its either you will try to maintain it while you can(which is also great and appreciating) or add server to it and make it outlive API removal.

It's just a suggestion, you are free to decline it if you know you couldn't have desire for all of that. But if you could, I think there would be very *many* people who appreciate this)

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by Anarios** [comment]
Already doing this
