### ISSUE TITLE
Like counter duplication

### ISSUE THREAD

**Issue by Tali64** [Anarios/return-youtube-dislike#711]
### Browser

Avast Security Browser

### Browser Version

Chromium v103.0.17730.134

### Extension or Userscript?

Extension

### Extension/Userscript Version

Version 3.0.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=fEaHdvKxNFU

### What happened?

The dislike counter displays fine, but the like counter duplicates. It only happens if the like counter isn't abbreviated (less than 1K)
![Screenshot (54)](https://user-images.githubusercontent.com/63979637/182262058-bc9ce1d4-cee0-4a8d-b2a5-b5f4cfc4523d.png)

### How to reproduce/recreate?

You can reproduce it by clicking the dislike button, then clicking the like button.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Tali64** [comment]
Update: It just happened by me clicking the like button (but not the dislike button)

**Comment by PickleNik** [comment]
as far as I can tell it's been resolved in the latest version, please reopen or ping if it's still happening for you
