### ISSUE TITLE
It shows a like count, and connects it with "Like"

### ISSUE THREAD

**Issue by michelle1574** [Anarios/return-youtube-dislike#712]
### Browser

Firefox Developer Edition

### Browser Version

103.0b4 (64) - aurora

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.4

### Video link where you see the problem

https://www.youtube.com/watch?v=WromRhmmMkM

### What happened?

So I was watching this video, when I saw something weird.
It was looking like this:
![obraz](https://user-images.githubusercontent.com/70703680/182611261-ea046216-8ea6-41e1-b982-12b058d8ab61.png)

I don't know what it is, but can you fix it?

### How to reproduce/recreate?

Enter this video,
See the like counter
That's all.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

No

**Comment by cristianer** [comment]
I think I have a similar problem. Reinstalling the extension doesn't work. It was working well some days before.
Firefox beta 104.0b5 (64bit).
![1](https://user-images.githubusercontent.com/5828685/182982051-8d97c78c-07ac-4497-9280-6a69d47a0502.jpg)
![2](https://user-images.githubusercontent.com/5828685/182982059-60e089f1-9622-4808-bfc5-33e0fc15cf16.jpg)

**Comment by michelle1574** [comment]
I refreshed it, and it is working. Issue closed.
