### ISSUE TITLE
Can't see dislikes at the moment. Shows "Temoporarily Unavailable".

### ISSUE THREAD

**Issue by magizhchi99** [Anarios/return-youtube-dislike#713]
### Browser

Mozilla Firefox, YouTube Vanced

### Browser Version

Firefox V103.0.1

### Extension or Userscript?

Extension

### Extension/Userscript Version

Version 3.0.0.4

### Video link where you see the problem

https://www.youtube.com/watch?v=pLC0FUnko-M

### What happened?

Shows temporarily unavailable like in the picture: 
![image](https://user-images.githubusercontent.com/49996218/182913329-6ad628ca-325b-4fb3-a702-139adc07925f.png)

### How to reproduce/recreate?

Any video on any browser and also youtube vanced

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by magizhchi99** [comment]
> 

Guess the server is down?

**Comment by NicoTheCinderace** [comment]
Seems like it.

**Comment by fuongbregas** [comment]
It is fixed

**Comment by magizhchi99** [comment]
Yes, it's fixed now!
