### ISSUE TITLE
Request to be mantainer

### ISSUE THREAD

**Issue by KendallDoesCoding** [Anarios/return-youtube-dislike#722]
Hi @Anarios ,

I would like to be a mantainer of this project.

**Comment by PickleNik** [comment]
Feel free to fork, resolve Issues, and submit PRs, no need to ask 👍🏼 
Thank you

**Comment by KendallDoesCoding** [comment]
> Feel free to fork, resolve Issues, and submit PRs, no need to ask 👍🏼 Thank you

Ok!!
