### ISSUE TITLE
Odd looking dislike button

### ISSUE THREAD

**Issue by Maciejka1** [Anarios/return-youtube-dislike#730]
### Browser

Firefox

### Browser Version

103.0.2-1 

### Extension or Userscript?

Extension

### Extension/Userscript Version

 v3.0.0.5 

### Video link where you see the problem

https://imgur.com/a/2oULJzt

### What happened?

Dislike looks odd on new version of youtube. It should look like like button.

### How to reproduce/recreate?

Go to any video and look on dislike button.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by SlideMovies** [comment]
<img width="71" alt="Screenshot 2022-08-20 at 5 26 13 PM" src="https://user-images.githubusercontent.com/87663026/185746115-f485dec1-034f-4326-856a-e477205edeb4.png">
Also in shorts

**Comment by arghanath007** [comment]
Yeah Same for me as well.

![image](https://user-images.githubusercontent.com/54589605/185781982-2be89618-bb95-4244-82a6-e07a3c9b1680.png)

**Comment by Xmetalfanx** [comment]
odd ... I am not seeing that here on Firefox 103.0.1 and version 3.0.0.5 of the addon ... I have gone to a number of different video links to try to recreate it but am unable to.   From the pictures i see it looks like the word "dislike" is displaying for those with the issue when it shouldn't

**Comment by arghanath007** [comment]
> 

> I am also on Firefox 103.0(Ubuntu Linux) and the Extension is v3.0.0.5

![image](https://user-images.githubusercontent.com/54589605/186078991-16ff9a16-3a6b-4a9c-9c28-cd6e068d2bc5.png)
Looks like it is fixed now.

**Comment by Painless68** [comment]
I swapped profiles in Firefox and then checked on Edge, looks like its a test feature that is linked to your account. Sign out and it goes away but comes back when you sign in. It went away for me for a few days but is back now, they're probably getting ready to roll it out publicly.

**Comment by SlideMovies** [comment]
@arghanath007 broken again
<img width="228" alt="Screenshot 2022-08-24 at 3 11 49 PM" src="https://user-images.githubusercontent.com/87663026/186392737-edeb1bfb-f4bf-4c16-b1f8-c36827d02f8d.png">

**Comment by Maciejka1** [comment]
yes still broken

**Comment by PickleNik** [comment]
should be fixed in latest version, please reopen if still broken
