### ISSUE TITLE
Broken userscript - show nothing

### ISSUE THREAD

**Issue by Dark3n89** [Anarios/return-youtube-dislike#739]
### Browser

chrome

### Browser Version

95

### Extension or Userscript?

Userscript

### Extension/Userscript Version

3.0.1

### Video link where you see the problem

https://www.youtube.com/watch?v=-Zgnk7P10mU

### What happened?

Youtube change many classes, userscript dont show disslike count

### How to reproduce/recreate?

Simply, script never can be started

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

No

**Comment by PickleNik** [comment]
not available for follow-up questions, youtube layout unknown, nothing I can do to help
