### ISSUE TITLE
(Feature Request): No replacing if the dislike count is present by itself

### ISSUE THREAD

**Issue by Hans5958** [Anarios/return-youtube-dislike#74]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Avoid replacing the dislike counter if the user still can see the dislike count by itself.

### Ways to implement this!

Just check if the text is "Dislike" than some kind of number? Maybe also check if the like count also have the "Like" text to solve #47. I think there is a object that contains the translated strings that you can refer.

### Can you work on this?

- [X] Yes
- [X] No

**Comment by CSALS** [comment]
Are you working on this?

**Comment by Anarios** [comment]
note: do not check for "like" or "dislike" text - we have international users.

**Comment by michaeljaeger95** [comment]
Inspection shows no reliable CSS-style identifier that uniquely yields either the Dislike Button or Nothing. I can't see anything in the resultant html that sets like, dislike and share button appart from each other. Counting these elements would be very liable to breakage as YouTube could just as well add or remove another one.

**Comment by ajlee2006** [comment]
> note: do not check for "like" or "dislike" text - we have international users.

i guess can just check for number instead. ((I am not sure if there are different numeral writing systems used though))

**Comment by Hans5958** [comment]
> note: do not check for "like" or "dislike" text - we have international users.

Hence, the sentence "I think there is a object that contains the translated strings that you can refer."

By the way, I observe that there is no translation key as I expected, but I think there is a way by checking other types of data.

Something like this. I found two data for both the like button and the dislike button.

1. Like `ytInitialData.contents.twoColumnWatchNextResults.results.results.contents[0].videoPrimaryInfoRenderer.videoActions.menuRenderer.topLevelButtons[0].toggleButtonRenderer`
2. Dislike `ytInitialData.contents.twoColumnWatchNextResults.results.results.contents[0].videoPrimaryInfoRenderer.videoActions.menuRenderer.topLevelButtons[1].toggleButtonRenderer`

One difference is that those with the number will have an `accessibilty` property on the `defaultText` function, and those that doesn't, doesn't.

There may be other properties or other ways to detect it, but I think this can be considered.

**Comment by cyrildtm** [comment]
Not sure if this issue is still relevant now that YT has removed the API entirely. Should this issue be closed? 


> > note: do not check for "like" or "dislike" text - we have international users.
> 
> i guess can just check for number instead. ((I am not sure if there are different numeral writing systems used though))

Here's a possible way: 

```
likebuttontextdom = getLikeButton().querySelector("#text");
if likebuttontextdom.innerText.replace(/\D/g, '')  === '' { 
....
}
```

**Comment by Hans5958** [comment]
I agree that this is not relevant anymore. I'm closing this to decrease the load on the issues board. Thanks, all.
