### ISSUE TITLE
Dislike button displaying "Dislike" text next to count.

### ISSUE THREAD

**Issue by OMG-Abaddon** [Anarios/return-youtube-dislike#742]
### Browser

Chrome

### Browser Version

104.0.5112.102 (Official Build) (64-bit) (cohort: Stable) 

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.5

### Video link where you see the problem

https://www.youtube.com/watch?v=PzOLDt8fLT8 (but this can be reproduced in every video)

### What happened?

Every video's Like/dislike bar shows the format "Dislike[count]" instead of just the count. Please see the attached screenshot. 

![chrome_iWAUlFcBOX](https://user-images.githubusercontent.com/8758544/187631719-804839c7-0830-4efb-a3ff-7fe4b15ba394.png)

I have also formatted my PC yesterday, so I can confirm it can be reproduced both before and after the clean up.

### How to reproduce/recreate?

Just need to open any video on Youtube.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by PotDeSel** [comment]
Hi I have the same problem with French youtube.
![Screenshot_1](https://user-images.githubusercontent.com/97355798/187774480-1a9b6730-e58a-474d-826e-43afe2ff6fb2.png)

**Comment by DanTGL** [comment]
Same thing in swedish.
![ratio](https://user-images.githubusercontent.com/33489389/189550199-bd77703d-baa8-44dd-9d49-8e0dab2a5b29.PNG)

**Comment by DaffyExtra** [comment]
Same Issue
![image](https://user-images.githubusercontent.com/103275947/189894163-7830a80e-db43-48ef-aaac-cb7bd1702a8f.png)

**Comment by SapuSeven** [comment]
This is what I could find out:

Old 'Dislike' container:
```
<yt-formatted-string id="text" class="style-scope ytd-toggle-button-renderer style-text">Dislike</yt-formatted-string>
```


New 'Dislike' container:
```
<span class="yt-core-attributed-string yt-core-attributed-string--white-space-no-wrap" role="text">Dislike</span>
```

**Comment by DanTGL** [comment]
> This is what I could find out:
> 
> Old 'Dislike' container:
> 
> ```
> <yt-formatted-string id="text" class="style-scope ytd-toggle-button-renderer style-text">Dislike</yt-formatted-string>
> ```
> 
> New 'Dislike' container:
> 
> ```
> <span class="yt-core-attributed-string yt-core-attributed-string--white-space-no-wrap" role="text">Dislike</span>
> ```

Okay, so it replaces the content in an element which has the id "text" with the number of dislikes, In which case the only thing that should need to be updated is the `querySelector` calls so that they target the correct elements.

![Capture](https://user-images.githubusercontent.com/33489389/190027939-2eb7ecfc-6956-4451-a42c-2e4f8ba87e54.png)
