### ISSUE TITLE
RYD Not Working on YouTube New UI

### ISSUE THREAD

**Issue by AbsurdIdealist** [Anarios/return-youtube-dislike#748]
### Browser

Apple Safari

### Browser Version

Version 15.6.1 (17613.3.9.1.16)

### Extension or Userscript?

Userscript

### Extension/Userscript Version

Version 4.2.3

### Video link where you see the problem

All videos so far

### What happened?

See title.

### How to reproduce/recreate?

Every time I load up a video it does not show YouTube dislikes.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by gguy825** [comment]
Having the same issue on Microsoft edge. Waiting for an update.
