### ISSUE TITLE
Buggy on Latest YouTube UI

### ISSUE THREAD

**Issue by futureflash01** [Anarios/return-youtube-dislike#752]
### Browser

Google Chrome

### Browser Version

105.0.5195.102

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.5

### Video link where you see the problem

https://www.youtube.com/watch?v=Y3fi9pc81NY

### What happened?

The dislike count still shows, however there's still the "Dislike" text showing next to the number.

In other words, Return YouTube Dislike is not fully supported for the latest YouTube UI update.

### How to reproduce/recreate?

1. Open YouTube
2. Click on any video
3. Bug shows instantly

![image](https://user-images.githubusercontent.com/50788891/189975576-bff50aff-117e-4642-ae94-e5ab76189689.png)

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by unbeatable-101** [comment]
This looks the same as #742

**Comment by vizthex123** [comment]
Ah, I was gonna come post about this issue too. Some tabs keep the normal UI, and some do this weird bug.

And oh god, is this the new YouTube UI? Please tell me there's a way to change it back.

**Comment by TukangM** [comment]
![image](https://user-images.githubusercontent.com/91467886/191740228-f80926f7-ee14-45ad-bfcc-94b1d6ae10c1.png)
 shorts video

**Comment by PickleNik** [comment]
seems to be fixed in latest version
