### ISSUE TITLE
YouTube dislike numbers not showing up

### ISSUE THREAD

**Issue by IronClaw99** [Anarios/return-youtube-dislike#757]
### Browser

Mozilla Firefox

### Browser Version

104.0.2

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.5

### Video link where you see the problem

https://www.youtube.com/watch?v=DWWK05t98os

### What happened?

The dislike count is not showing whatsoever.

### How to reproduce/recreate?

Refreshing the page works. This is happening on both Firefox and Chrome.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by rhkoulen** [comment]
I have this issue as well.
![image](https://user-images.githubusercontent.com/96697985/190842085-8633028f-5982-4280-a8e3-267efc8451eb.png)

**Comment by policetonyR** [comment]
Cannot repro

![image](https://user-images.githubusercontent.com/31581859/190842160-7e7b37f1-0c7d-4ec9-bc18-0f38a2abb95d.png)

**Comment by LONINFINITY** [comment]
Can also confirm, dislikes not appearing at all. Opera GX, version 90.0.4480.100, extension version 3.0.0.5

**Comment by R-033** [comment]
Having this on Chrome

**Comment by IronClaw99** [comment]
> I am also getting this issue on Firefox, refreshing usually seems to fix the issue. ![Screenshot 2022-09-16 230913](https://user-images.githubusercontent.com/111381439/190843255-7b9b3a34-3846-420e-89f8-79feff8ba5e2.png)

This is the exact issue I'm dealing with.

**Comment by ilyamikheevcoder** [comment]
my issue is even cooler, i don't have any statistics now
![изображение](https://user-images.githubusercontent.com/37904672/190856298-6a935f59-f22a-4af8-b497-680f76d14279.png)

**Comment by aratinau** [comment]
> my issue is even cooler, i don't have any statistics now
> 
> Librewolf 101.0 (Mozilla Firefox fork) ![изображение](https://user-images.githubusercontent.com/37904672/190856298-6a935f59-f22a-4af8-b497-680f76d14279.png)

But you have beautiful colors! I am jealous! Its a skin?

**Comment by ilyamikheevcoder** [comment]
> But you have beautiful colors! I am jealous! Its a skin?

@aratinau there's "color scheme" (or similarly named option) in return youtube dislikes, i've selected "neon" there

**Comment by aratinau** [comment]
I deleted the extension, then reinstalled (I saw that I went from v2 to v3) and everything works now.

(thank you @ilyamikheevcoder)

**Comment by TorutheRedFox** [comment]
it's worse for me (maybe due to also using youtube redux?)
![image](https://user-images.githubusercontent.com/15708278/190865291-1bc66391-7f4a-4bf8-9945-f9cfb04d1b88.png)

**Comment by rhkoulen** [comment]
Reproduced on latest versions of Edge, Chrome, Firefox, Opera.

**Comment by MildPanda** [comment]
I've reinstalled and still have this issue on Firefox version 104.0.2

**Comment by BlueSwordM** [comment]
I can reproduce the bug on my end, but it goes away if I click on the dislike button.

**Comment by Potato22** [comment]
Reinstalling has the potential to fix this issue.

v2.x
![image](https://user-images.githubusercontent.com/39096741/190867114-057125bd-dc75-44e8-a794-4b30cb95a9c7.png)

v3x
![image](https://user-images.githubusercontent.com/39096741/190867238-a3ceed8e-09ce-4708-86a2-daafe5b0e9d6.png)

**Comment by IronClaw99** [comment]
I'm on version 3.0.0.5 and I am having this issue.

**Comment by C0dingschmuser** [comment]
Same issue for me with 3.0.0.5 on Firefox 104.0.2
Reinstalling fixed it temporarily but unfortunately it's back now

**Comment by Ozzy4201** [comment]
v3.0.0.5
Chrome 105.0.5195.127
Can reproduce every once in a while, cant see anything common between what videos the issue occurs in and which ones it doesnt. If it happens, it starts off by showing no numbers at all, just like @aratinau, then, if i like, the number of likes shows up, + the ratio, but if i dislike it just says disabled by owner. Refreshing has always fixed it. Tested here https://www.youtube.com/watch?v=yRmOWcWdQAo

**Comment by hyperstown** [comment]
Same issue on 
Extension v3.0.0.5
Firefox 104.0.2
Chromium Version 105.0.5195.102 (Official Build) Arch Linux (64-bit).
It seems that it breaks when I click from playing one video to another. 
Funny thing, it works every 2 videos. 
Steps to reproduce:
- Open some video (works)
- Click some other video from recommended (breaks)
- Click another from recommended (works)
