### ISSUE TITLE
Like count disappears when i like the video

### ISSUE THREAD

**Issue by Caddy8970** [Anarios/return-youtube-dislike#758]
### Browser

Firefox

### Browser Version

104.0.2

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.5

### Video link where you see the problem

https://www.youtube.com/watch?v=AVW_M5_SjrM

### What happened?

Like count disappears when i like the video 
![immagine](https://user-images.githubusercontent.com/113631055/190895770-bffb8acf-6df6-4eab-b1e0-0f9adeafd292.png)
It doesn't happen with the extention disabled

### How to reproduce/recreate?

I Just liked the video

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by mrkrabs206** [comment]
Not for me. the Dislike button.

**Comment by Caddy8970** [comment]
> Not for me. the Dislike button.

Do you mean that the dislike button disappears to you?

**Comment by Gaminguide1000** [comment]
For me it also happens

**Comment by TrueJoSephGD** [comment]
This seems to be an issue with all videos and just seems to happen randomly. For me, it just alternates between there and not there whenever a new video loads.
![](https://user-images.githubusercontent.com/110477682/190925753-c995dceb-29ff-487f-9d52-61226b4e711e.png)

**Comment by mrkrabs206** [comment]
No, I mean the dislike count next to the dislike button. The like/dislike
bar on the bottom still shows, however.

**Comment by Plaque-fcc** [comment]
It is happening when you enable the «Re-format like numbers» option in the settings.
You open a video in a new tab, it has both numbers, and you like/dislike the video — and the number disappears.
Once you reload the tab, the number appears again. Then you can remove your like or dislike — and behold the counter vanishing.

**Comment by mrkrabs206** [comment]
Thanks for the tip!

**Comment by Caddy8970** [comment]
Fixed the issue by disabling "format like numbers "

**Comment by mrkrabs206** [comment]
Awesome, thanks!
