### ISSUE TITLE
"Could not unzip extension for install" while sideloading extenstion in Chrome

### ISSUE THREAD

**Issue by S4adam** [Anarios/return-youtube-dislike#762]
Following [these](https://github.com/Anarios/return-youtube-dislike/wiki/Downloading,-Installing-&-Using#from-unzipped-folder) instructions.
1. Downloaded the [latest RYD release](https://github.com/Anarios/return-youtube-dislike/releases/tag/v3.0.0.3).
2. Went to `chrome://extensions/`
3. Dragged the .zip file onto Chrome.
4. Instantly an error appears: **Could not unzip extension for install.**

Chrome version: 105.0.5195.127 (64-bit)

//Edit:
Just tried on a fresh Chrome Beta and got the same error.

**Comment by Paws-Deep** [comment]
Did you turn the developer mode on?

**Comment by S4adam** [comment]
Of course, without it you can't even sideload extensions.

>

**Comment by Paws-Deep** [comment]
> Of course, without it you can't even sideload extensions.

Yea, alright. Tested it in my Chrome 105.0.5195.127 (Official Build) (64-bit)
Same error you receive.
Unpacked the archive and tried to load in the un-zipped folder. Got this:
![image](https://user-images.githubusercontent.com/74794023/191838465-485171b2-0700-4a33-9c9d-c17c5717485e.png)
So seemingly there is an issue with the manifest file. On top of it, current addon version is 3.0.0.6 but zip is 3.0.0.3

**Comment by PickleNik** [comment]
@S4adam, that zip contains more than just the extension itself, you need to go to Extensions > combined and sideload that folder
