### ISSUE TITLE
(Mobile) Can anything be done on new mobile UI?

### ISSUE THREAD

**Issue by KrGuy** [Anarios/return-youtube-dislike#765]
Extension or userscript: Both

![Screenshot_2022-09-30-12-55-35-699_org mozilla fenix](https://user-images.githubusercontent.com/84209806/193193947-892cef7f-5ef6-418c-9f30-884980ae47bd.jpg)

Can anything be done on the new mobile UI (apparently still in testing)?

As could be seen, there is no Dislike word present next to the icon for the extension to replace. I believe it could be inserted next to the icon though.

(note: I use the userscript because the extension does not seem to work well on the mobile site, userscript works on old mobile UI though)

So far, similar issues have been filed for the new **desktop** UI, but I found none for the new **mobile** UI.

**Comment by KrGuy** [comment]
Apparently there seems to be a pending pull request #749 which aims to fix this.

**Comment by hyperstown** [comment]
Just like @KrGuy said. However as a temporary solution you can install fixed version from my repo. You can install userScript form [here](https://github.com/hyperstown/return-youtube-dislike/raw/combined-canary/Extensions/UserScript/Return%20Youtube%20Dislike.user.js).
This version also has all of the fixes that has been added in the meantime. 
I made it so I can already use it on my dailydrive devices. Feel free to use it as well. Just keep in mind that you MAY encounter some issues that I haven't seen/fixed yet. 
For now I think the only thing that I haven't fixed yet is dislike count in fullscreen mode. But youtube decided to rollback to old design all of my devices so I can't event work on it yet.

**Comment by KrGuy** [comment]
I am already using that version of the userscript from that pull request.
