### ISSUE TITLE
add reason why youtube will remove dislike count from their api

### ISSUE THREAD

**Issue by IvanVnucec** [Anarios/return-youtube-dislike#77]
In README.md file under What it Does heading it is stated that YouTube will remove dislikes count from its api but it does not says why.

**Comment by Zi7ar21** [comment]
what

**Comment by Chew** [comment]
Reason: They hate us and want us to suffer.

Actual reason: We'll never know. Not much we can do.

**Comment by IvanVnucec** [comment]
Oh sorry,
In README.md file under What it Does heading it is stated that YouTube will remove dislikes count from its api but it does not says why.

**Comment by szamanr** [comment]
i like how the description of this issue is empty, much like the list of valid reasons for removing the dislike count.

**Comment by IvanVnucec** [comment]
> i like how the description of this issue is empty, much like the list of valid reasons for removing the dislike count.

updated

**Comment by Anarios** [comment]
Well, you'd better ask youtube, not us :)
