### ISSUE TITLE
Display dislikes on videos whose creator disabled dislikes

### ISSUE THREAD

**Issue by EthanBnntt** [Anarios/return-youtube-dislike#773]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Enable the display of dislikes on videos whose creator disabled dislikes.

### Can you work on this?

- [ ] Yes
- [x] No

### Will you be available for follow-up questions to help developers implement this?

Yes

**Comment by L00pEE** [comment]
Was just about to make this post, I know some JS to dabble in it for making my first pull request, but idk where to start.

**Comment by Rizxcviii** [comment]
Personally, I disagree with this. There are definitely some ethical ramifications of implementing this. It would be possible to use the extensions internal database, but I don't think youtubers would be too happy with this implementation. Let alone the possible legal ramifications of this from YouTube. But this is just my own opinion.

**Comment by PickleNik** [comment]
not planned as of right now, sorry, there's been a discussion about this on Discord last year

**Comment by feenx** [comment]
I'm late to the party so I might not see a reply, but how is "it would be possible to use the extensions internal database" not what the extension already does?

Guess I assumed YouTube didn't allow polling any dislikes count, and the whole reason for the extension was to maintain an external database.

**Comment by PickleNik** [comment]
> I'm late to the party so I might not see a reply, but how is "it would be possible to use the extensions internal database" not what the extension already does?

not sure what your question is but the extension does use it's own db
