### ISSUE TITLE
YouTube's changed their UI (-_-)

### ISSUE THREAD

**Issue by Foxydapirate12** [Anarios/return-youtube-dislike#774]
### Browser

Google Chrome

### Browser Version

Version 106.0.5249.103 (Official Build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.6

### Video link where you see the problem

https://www.youtube.com/watch?v=AmekhRy8f7E

### What happened?

YouTube Changed their UI, and it now causes a few graphical interferences with most of the customisations in the plugin.

### How to reproduce/recreate?

1. Click on a video.
2. Scroll down.

![SharedScreenshot](https://user-images.githubusercontent.com/101042481/195048714-49badb2f-9dfb-41f3-949e-689c7f7f5491.jpg)

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by FlorianWendelborn** [comment]
I also got the new UI today, same issue here

**Comment by EricE549X** [comment]
fellow dathings enjoyer i see

**Comment by deniscerri** [comment]
![image](https://user-images.githubusercontent.com/64997243/196505366-006fe804-158f-4860-aedd-d638e1344ef2.png)
It looks worse if you don't have the download button available.

**Comment by TheBSODAndWSODFan** [comment]
i'm not affected kinda.. ( i use firefox )
![image](https://user-images.githubusercontent.com/78845241/198221497-627ad0f6-d123-4c06-a546-7466f4077387.png)
