### ISSUE TITLE
RYD no longer working on Safari 16 with Tampermonkey script

### ISSUE THREAD

**Issue by t0astbr0t** [Anarios/return-youtube-dislike#775]
### Browser

Safari 16.0

### Browser Version

Version 16.0 (17614.1.25.9.10, 17614)

### Extension or Userscript?

Userscript

### Extension/Userscript Version

3.0.1

### Video link where you see the problem

https://www.youtube.com/watch?v=IxlbsfuYH8A

### What happened?

The script worked fine in the past but today I recognised that the dislikes are no longer counted. I can't determine when the script stopped working, but it cannot be that long.

No changes on the browser or Tampermonkey, the script just seized working. Reinstalling Tampermonkey and the script was not successful. All YouTube videos are affected. 

![SCR-20221012-4](https://user-images.githubusercontent.com/115592643/195206367-21b1f960-cb27-435d-a76d-bc40a2a99071.jpeg)

### How to reproduce/recreate?

Safari 16 with Tampermonkey (AppStore) and Script 3.0.1 => no functionality anymore on my installation

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by hyperstown** [comment]
There is pending pull request [!749](https://github.com/Anarios/return-youtube-dislike/pull/749).
You can install updated version from [there.](https://github.com/hyperstown/return-youtube-dislike/raw/main/Extensions/UserScript/Return%20Youtube%20Dislike.user.js)
Just keep in mind that if you encounter any issues, you should report it in that pull request.

**Comment by t0astbr0t** [comment]
Issue has been fixed with the updated version linked by hyperstown in the comments above. 

Thank you!
