### ISSUE TITLE
(Feature Request): Likes and dislikes

### ISSUE THREAD

**Issue by QPorro** [Anarios/return-youtube-dislike#78]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Create a separate like and dislike counter that the users of this add-on can use to express their feelings about a video.

### Ways to implement this!

To deny bots the user have to verify its eligibility to use this feature. We could do this by using Google's OAuth2 implementation, in other words the "Sign in with a Google account" feature.

### Can you work on this?

- [X] Yes
- [X] No

**Comment by DARKDRAGON532** [comment]
Already being worked on.

**Comment by QPorro** [comment]
I'm sorry. I probably missed that issue.

**Comment by DARKDRAGON532** [comment]
> I'm sorry. I probably missed that issue.

Nah, dont worry, it wasnt explicitly mentioned anywhere.

**Comment by astrynzha** [comment]
Wanted to suggest this same feature as well. It would be best to have a like-dislike engine, independent of youtube. Otherwise, we would collect the dislikes only from the users of this addon and likes from everyone, which will make the ratio skewed.
And also this would piss off youtube a great deal.

**Comment by ken107** [comment]
The extension may already be doing this.  But I think it should intercept when the user clicks the Like button as well as the Dislike button on YouTube videos and use that to deduce the like/dislike ratio.  Extrapolate to approximate actual Dislike count. This extrapolated Dislike count should become more and more accurate as the user base increases and would be more than enough to fulfill the original purpose.  I don't think the extension should add too much extra stuff.

**Comment by Frontesque** [comment]
Closed due to inactivity. Reply if this is still an issue.
