### ISSUE TITLE
RYD userscript doesn't work with new UI

### ISSUE THREAD

**Issue by EricE549X** [Anarios/return-youtube-dislike#784]
### Browser

Safari

### Browser Version

16.0

### Extension or Userscript?

Userscript

### Extension/Userscript Version

3.0.1

### Video link where you see the problem

https://youtu.be/JHzx_-HA2ts

### What happened?

got the new UI today, dislike counter doesn't work. not even when i refresh the page.

### How to reproduce/recreate?

1. open safari
2. go to any video
3. see error

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by hyperstown** [comment]
Duplicate of #748
There is pending pull request [!749](https://github.com/Anarios/return-youtube-dislike/pull/749).
You can install updated version from [there.](https://github.com/hyperstown/return-youtube-dislike/raw/main/Extensions/UserScript/Return%20Youtube%20Dislike.user.js)
Just keep in mind that if you encounter any issues, you should report it in that pull request.

**Comment by EricE549X** [comment]
thanks
