### ISSUE TITLE
The extension seems to have stopped working for me

### ISSUE THREAD

**Issue by positron96** [Anarios/return-youtube-dislike#786]
### Browser

Google Chrome

### Browser Version

106.0.5249.119 (Official Build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.6

### Video link where you see the problem

https://www.youtube.com/watch?v=qMIIqsmTY3A

### What happened?

For a week or so I do not see any dislikes in youtube. The page either shows "Temporarily unavailabledislike", or just nothing near the thumb down icon. The indicator line below the thumbs seems to show something, but it does not look correct. 
I am sure that the extension is not showing the dislikes on the videos it used to show before.

![image](https://user-images.githubusercontent.com/2095278/197339738-da3c8410-e375-4e4a-b1b3-f78f2afbd1c1.png)

![image](https://user-images.githubusercontent.com/2095278/197339812-30f288b4-4cf3-4c33-a2a6-b38bf5f4cc15.png)

### How to reproduce/recreate?

I just open any video on youtube, and dislikes counter is wrong.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by TheBSODAndWSODFan** [comment]
same 
![image](https://user-images.githubusercontent.com/78845241/197390116-07dc1164-b628-46e8-a08c-31eb30a17b77.png)

**Comment by billbarni** [comment]
Same. Project is dead?

**Comment by PickleNik** [comment]
<img width="838" alt="Screenshot 2023-01-25 at 5 04 45 PM" src="https://user-images.githubusercontent.com/31113245/214702036-1deec6a2-b3bf-4c0c-bb2c-925ba5ed33f6.png">
should be working
if it still doesn't work, make sure 3.0.0.7 is installed and your browser is up to date
