### ISSUE TITLE
Color themes have double quotes

### ISSUE THREAD

**Issue by Sopor** [Anarios/return-youtube-dislike#790]
Why do these have double quotes?

![image](https://user-images.githubusercontent.com/5789283/197572566-d4e5347d-323f-4f2d-822c-33736b58cee5.png)

**Comment by ErykDarnowski** [comment]
Hey, not sure if the `"` were intentional or not, but here's my proposed fix:

```javascript
<select name="color_theme" id="color_theme">
  <option value="classic" id="color_theme_classic">
    __MSG_textColorTheme1__
  </option>
  <option value="accessible" id="color_theme_accessible">
    __MSG_textColorTheme2__
  </option>
  <option value="neon" id="color_theme_neon">
    __MSG_textColorTheme3__
  </option>
</select>
```

(Line: `143` in `./Extensions/combined/dist/chrome/popup.html`)
