### ISSUE TITLE
New YouTube UI Problem

### ISSUE THREAD

**Issue by QVGK** [Anarios/return-youtube-dislike#791]
### Browser

Brave

### Browser Version

1.44.112 Chromium: 106.0.5249.119 (Official Build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.6

### Video link where you see the problem

All of YouTube

### What happened?

Due to the new YouTube UI that they're slowly rolling out to users, the extension has broken a bit.

Here is an example from **_PlayOverwatch_**'s **Halloween Terror** video.

![image](https://user-images.githubusercontent.com/45526481/197780414-199ef564-7f48-4cef-96f8-7ae9abffc7a5.png)

As you can see, the **Dislike Ratio** bar is NOT under the **like** and **dislike** count.

### How to reproduce/recreate?

1) Wait for the new YouTube UI access.
2) Go to any video and you'll see the problem.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by brainwo** [comment]
Also good to mention is the padding here
![image](https://user-images.githubusercontent.com/45139213/198116729-08495cc3-5797-4e66-93bc-a609b64e2a11.png)

**Comment by Joshua-Wilcox** [comment]
The number doesn't show up for me at all on the new UI
(I am using the userscript on safari - used to work)

**Comment by Vreex** [comment]
Tried to mess around with some privacy related extensions and found this!!! 


![Screenshot from 2022-10-27 08-18-34](https://user-images.githubusercontent.com/83933964/198162815-c08d48de-1411-4240-a56f-079625a6f67b.jpg)
![Screenshot from 2022-10-27 08-19-01](https://user-images.githubusercontent.com/83933964/198162838-4eee34d9-27bd-4233-80c7-bc9317282426.jpg)

**Comment by TheBSODAndWSODFan** [comment]
It's Supposed To Be Like This
![image](https://user-images.githubusercontent.com/78845241/198220587-a11e562f-3500-406d-8be7-313d5d7c295b.png)

**Comment by evilsh3ll** [comment]
I've the same problem in Brave 1.45.113 64bit Arch Linux AUR Build
![image](https://user-images.githubusercontent.com/63223659/198295233-62e42fc3-45f1-4f92-b353-cb7ea916224a.png)

**Comment by ToothyDev** [comment]
Same problem here for weeks, on the old UI mind you

**Comment by RedstonePfalz** [comment]
Same Problem in Windows 10 21H2 on Chrome 106.0.5249.119:
![image](https://user-images.githubusercontent.com/55254344/198389447-25421bad-f82c-48aa-8f79-9b2939f9765d.png)

**Comment by MixusMinimax** [comment]
Same on Windows 10 Firefox
![image](https://user-images.githubusercontent.com/30178185/198400704-14a9f372-2e87-4b6a-95c3-6d617adb1d55.png)

**Comment by supern64** [comment]
replicated on Windows 11 22H2 with Chrome 106.0.5249.119
![image](https://user-images.githubusercontent.com/41817899/198582561-6517580f-b295-48ff-ada7-f33e65150240.png)

**Comment by donthaveaneme** [comment]
hi guys, i think i have same problem here
![image](https://user-images.githubusercontent.com/105922090/198753886-97a6794b-faa3-42de-a9f8-800707252aa8.png)
on Microsoft Edge Version 106.0.1370.52 (Official build) (64-bit), and Firefox 106.0.2 (64-bit)
the new ui makes the dislike counter placement on like button, sometimes its disabled by owner for no reason

**Comment by donthaveaneme** [comment]
wait is my issue same or what?

**Comment by v777** [comment]
> hi guys, i think i have same problem here ![image](https://user-images.githubusercontent.com/105922090/198753886-97a6794b-faa3-42de-a9f8-800707252aa8.png) on Microsoft Edge Version 106.0.1370.52 (Official build) (64-bit), and Firefox 106.0.2 (64-bit) the new ui makes the dislike counter placement wrong to the like button, sometimes its disabled by owner for no reason

With the "SaveFrom.net helper" extension, it's even worse, as we can see on your screenshot. But sometimes, it's properly displayed. It's totally random.

**Comment by Manzanitabot123** [comment]
This is my proposal for the dislikes bar, greetings to all.
![image](https://user-images.githubusercontent.com/84603580/198923067-63cc0110-00fe-4217-ada1-e4dc3b6f939c.png)

**Comment by misaligar** [comment]
On Firefox the issue presents itself a bit differently than the OP

<img width="565" alt="Screenshot 2022-10-31 at 5 29 02 PM" src="https://user-images.githubusercontent.com/42714627/199114081-654435f1-be7c-4583-8c42-0f59358c7223.png">

**Comment by l3nnartt** [comment]
same here, but in chrome
![image](https://user-images.githubusercontent.com/69513317/199116958-048c20e6-866e-4b0d-976c-1f6832796348.png)

**Comment by pixkk** [comment]
![image](https://user-images.githubusercontent.com/30828435/199191951-24c8d90a-c6ff-4b76-a83e-dc5eedc7fd87.png)
Same problem

**Comment by ArtyIF** [comment]
The bar looks out of place, maybe detect if YouTube has a new UI and not render it if it is new and move the tooltip to the like/dislike buttons?

**Comment by k0lourful** [comment]
I'd very much like an option to disable the ratio bar since it was removed in the official redesign, and for some the counter alone may be preferable.

**Comment by TheBSODAndWSODFan** [comment]
Even Worse 
![image](https://user-images.githubusercontent.com/78845241/200185000-6ca6f720-7d88-422a-a9fe-dc84bdbaa84a.png)
