### ISSUE TITLE
Safari User Script Doesn't Work

### ISSUE THREAD

**Issue by chigozie18** [Anarios/return-youtube-dislike#795]
### Browser

Safari

### Browser Version

16.1

### Extension or Userscript?

Userscript

### Extension/Userscript Version

3.0.1

### Video link where you see the problem

https://www.youtube.com/watch?v=LVKFwdlNMUw

### What happened?

The superscript doesn't work on Safari anymore. Nothing dislike count shows up on any video, though the dislike button always shows up. I'm using the user script with Tamper Monkey (version 4.17.6162).

### How to reproduce/recreate?

Click on the video link attached above and install the TamperMonkey script with Safari. 

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Moondarker** [comment]
Has the YouTube UI just been updated for you?
Sounds like a duplicate of #748

You can try fixes proposed in #748 ([script](https://github.com/hyperstown/return-youtube-dislike/raw/69d4a68656e5b2d08f4d899120c541e094c99f19/Extensions/UserScript/Return%20Youtube%20Dislike.user.js)) and #792 ([script](https://github.com/Moondarker/return-youtube-dislike/raw/ba0814b9043561594a3a2ecf901022205de64fd0/Extensions/UserScript/Return%20Youtube%20Dislike.user.js)) - but keep in mind, these were not approved by maintainers yet and it's only safe to use this code if you or somebody you know can read through the changes in pull requests and make sure it's safe 

Well, I did check that it's safe, but you should never trust random people on the internet :)

**Comment by chigozie18** [comment]
Thanks this worked for me!
