### ISSUE TITLE
Youtube does not show Dislikes

### ISSUE THREAD

**Issue by Ee465** [Anarios/return-youtube-dislike#798]
### Browser

Google Chrome

### Browser Version

106.0.5249.119

### Extension or Userscript?

Userscript

### Extension/Userscript Version

3.0.1

### Video link where you see the problem

All Youtube Videos that Ive seen

### What happened?

The Youtube dislike button is not shown anymore. 

### How to reproduce/recreate?

Open any youtube video and look at the dislike button

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Moondarker** [comment]
Do you mean dislike button or dislike count?
If it's the latter, make sure to check the list of issues (both open and closed) before submitting an issue next time :)
Sounds like a duplicate of #797 (<- see my comment there), which itself is a duplicate of #748

**Comment by isaac-doobs** [comment]
You can install updated version from [there.](https://github.com/hyperstown/return-youtube-dislike/raw/main/Extensions/UserScript/Return%20Youtube%20Dislike.user.js)
