### ISSUE TITLE
Confusing readme

### ISSUE THREAD

**Issue by Greedquest** [Anarios/return-youtube-dislike#8]
In the readme: 

> [The] dislike field in the YouTube API will be removed on December 13th, 2021

 ... then later:

> our API [...] relies upon YouTube's Data API [...] YouTube **_might_** prevent this in the future

So I'm confused, why do you say YouTube 'might' prevent using the data API even though they have stated they will remove the dislike field. Is the API different to the normal one or are you not relying on the dislike field and instead some other metric?

**Comment by dmitry-selivanov** [comment]
Yeah, it shouldn't be "might" but "will" instead.

**Comment by Anarios** [comment]
https://github.com/Anarios/return-youtube-dislike/commit/31475b81bbc985c5909235991a6a68905c0f6fa3

Tried wording it better here. Tell me if it's still confusing.

**Comment by Greedquest** [comment]
Much better 👍 

Also you should check out the discussion on https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/issues/50 and https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/issues/51
