### ISSUE TITLE
Unable to see anything

### ISSUE THREAD

**Issue by Arora-Sir** [Anarios/return-youtube-dislike#802]
### Browser

Google Chrome

### Browser Version

106.0.5249.119

### Extension or Userscript?

Userscript

### Extension/Userscript Version

3.0.1

### Video link where you see the problem

https://www.youtube.com/watch?v=oFOM9EbMZoQ

### What happened?

Unable to see anything after the dislike button

![YouTube-Thumbnail](https://user-images.githubusercontent.com/29508236/199262723-e7caf47b-10b4-4f4c-a1f6-9ab5515461a7.png)

[ConsoleLogs.log](https://github.com/Anarios/return-youtube-dislike/files/9911063/www.youtube.com-1667314232576.log)

### How to reproduce/recreate?

Just refresh the page. Everytime it isn't working.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by hyperstown** [comment]
Pull request [!749](https://github.com/Anarios/return-youtube-dislike/pull/749) that address this problem has been merged. This issue can be closed now.

**Comment by Arora-Sir** [comment]
Thanks, it works now; the only problem with this fix is you forgot to add one (x+1) in dislike when clicked (currently, it disappearing when clicked on dislike button)
