### ISSUE TITLE
Does not show the number of likes

### ISSUE THREAD

**Issue by sssHpion007** [Anarios/return-youtube-dislike#805]
### Browser

Opera GX

### Browser Version

LVL4 (core: 91.0.4516.95)

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.6

### Video link where you see the problem

All videos

### What happened?

Does not show the number of likes. In place of likes, the number of dislikes is displayed.
![image](https://user-images.githubusercontent.com/30200363/199303012-8c5e8da4-45c0-44de-93ab-d26e647a30c9.png)

### How to reproduce/recreate?

I didn't do anything, it's right after installation.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Ee465** [comment]
For me, the number of unlikes didn't show only if I had clicked on the unlike button and then took it back, but when I reloaded the webpage, it was back to normal. (Userscript V. 3.1.0)

**Comment by JadeMin** [comment]
@Ee465 where did you downloaded v3.1.0?? isnt v3.0.1 the latest version?

**Comment by DemitrixQ** [comment]
Similar problem with showing likes in firefox

**Comment by TheGoldenSun** [comment]
I'm having the same issue on YouTube revanced as well

**Comment by JadeMin** [comment]
@TheGoldenSun have you tried turning on the disable new layout and fix RYD issue option?

**Comment by PickleNik** [comment]
looks fixed now 
<img width="730" alt="Screenshot 2023-01-25 at 7 17 40 PM" src="https://user-images.githubusercontent.com/31113245/214723915-39515ccd-28b5-4d22-a923-e962c247742b.png">
https://user-images.githubusercontent.com/31113245/214723569-29be9885-ad6d-4776-ba70-b9cd00b19722.mp4
