### ISSUE TITLE
Dislike count isn't shown (Safari - Mac)

### ISSUE THREAD

**Issue by mas0nwest** [Anarios/return-youtube-dislike#807]
### Browser

Safari

### Browser Version

16.1

### Extension or Userscript?

Userscript

### Extension/Userscript Version

3.0.0.3

### Video link where you see the problem

any video

### What happened?

dislike count isn't shown

### How to reproduce/recreate?

(New YouTube Web Ui)

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by isaac-doobs** [comment]
You can install updated version from [there.](https://github.com/hyperstown/return-youtube-dislike/raw/main/Extensions/UserScript/Return%20Youtube%20Dislike.user.js)

**Comment by CristianMoisei** [comment]
Awesome, thanks a lot @isaac-doobs . I kept checking for updates on the main website and the version there is 3.0.1
3.1 from your link works perfectly.

**Comment by hyperstown** [comment]
Pull request [!749](https://github.com/Anarios/return-youtube-dislike/pull/749) has been merged. This issue can be closed now.
