### ISSUE TITLE
Like to dislike bar appearing misaligned

### ISSUE THREAD

**Issue by shamshitty** [Anarios/return-youtube-dislike#809]
### Browser

Firefox

### Browser Version

106.0.5

### Extension or Userscript?

Extension

### Extension/Userscript Version

 v3.0.0.6

### Video link where you see the problem

https://youtu.be/8vOAMh3NIeg

### What happened?

The ike to dislike ratio bar appears completely misaligned under the like and dislike buttons due to (i assume) the new UI redesign. I expected the bar to be either under the buttons or not there at all
![image](https://user-images.githubusercontent.com/68004605/200146985-ae839fdb-fe10-4a8c-98b9-40c0bdc879a8.png)

### How to reproduce/recreate?

Go to any youtube video with the latest version of the extension installed

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/200855431-2a95423e-a515-45e5-9117-a1c84a8ed146.png)

Same

**Comment by aceilort** [comment]
Same thing using Userscript

**Comment by TheTrashCrafter** [comment]
as a workaround you can block the bar using ublock origin or so.

**Comment by nsde** [comment]
> as a workaround you can block the bar using ublock origin or so.

how did you do it?

**Comment by TheTrashCrafter** [comment]
@nsde I right clicked the bar, selected Block Element and selected the create button.

**Comment by nsde** [comment]
ok

**Comment by meisme-dev** [comment]
![image](https://user-images.githubusercontent.com/49573906/201438079-d0562955-2820-4acd-af1a-758a5e2f6554.png)
Not as misaligned for me but it still looks weird

**Comment by ErykDarnowski** [comment]
Hey, this was fixed in [this](https://github.com/Anarios/return-youtube-dislike/pull/771) PR!
Let me know if the issue still persists (I couldn't re-create it on my end).

**Comment by vikdean** [comment]
Same in Brave
![image](https://user-images.githubusercontent.com/16238514/201746165-224f8ab9-a424-40bd-bbc3-f51d7bde6bc4.png)

**Comment by ErykDarnowski** [comment]
Ohhh yeah I saw this bug too but couldn't replicate it 😅 (it's a separate thing to what I've worked on though).

Would you mind specifying Brave's version and the YouTube video link?

**Comment by vikdean** [comment]
> ## Wrong ratio
> Ohhh yeah, I saw this bug too but couldn't replicate it 😅 (it's a separate thing to what I've worked on though).
> 
> ## Misalignment
> Please install the extension from the repo (NOT the Chrome Web Store) and check again as I can't replicate anything similar to your screenshot. Although I have noticed that something's up with the centering (it's only a couple `px` though, nothing close to what the screenshot shows).
> 
> Would you mind specifying Brave's version and the YouTube video link?

Brave [Version 1.45.123 Chromium: 107.0.5304.110 (Official Build) (64-bit)])
Video: https://www.youtube.com/watch?v=x4CqnTF0lkc

**Comment by ErykDarnowski** [comment]
Okay, it looks like we're both on the same Brave version.
After testing this on ~`30` videos, besides the really small misalignment I've talked about earlier (only a couple `px`) I just can't seem to get something as bad as on the screenshots even with:

- reloading multiple times
- clearing cookies
- logging in
- logging out

It's important to keep in mind that this testing was of course done using the **GitHub** version.

![image](https://user-images.githubusercontent.com/81530705/201882345-c486a25a-5c6b-43e4-b077-c532500c2c4c.png)

---

Here are a couple videos that have `0` dislikes: 

- <https://www.youtube.com/watch?v=9i4gsTIS4S0>
- <https://www.youtube.com/watch?v=ZxJ88LFe0Ps>
- <https://www.youtube.com/watch?v=lLHEi0bqi6A>

**Comment by vikdean** [comment]
I'm on v3.0.0.6, and yes, the issue appears when there are no dislikes.
![image](https://user-images.githubusercontent.com/16238514/201894182-f849150e-1bb5-4a6d-93ac-a5b845f12bf0.png)
![image](https://user-images.githubusercontent.com/16238514/201894242-c2be5c5e-3e0c-4a97-a852-0fb7c01f52cd.png)
![image](https://user-images.githubusercontent.com/16238514/201894289-9e146cf1-75ba-460c-8e52-b9bae06394e3.png)

**Comment by ErykDarnowski** [comment]
Wow... Now I'm really confused. I've tried to replicate this on both the main repo, my fork and the Chrome Web version and the only way I could get that misalignment was of course with the Chrome Web Store version.

I'm wondering what else could contribute to that. Have you tried the things I did?

- reloading multiple times
- clearing cookies
- logging in
- logging out

Ohh and are you absolutely sure you're **not** using the Chrome Web Store version?

**Comment by vikdean** [comment]
3.0.0.6 for me is the Google Web Store version, yes, thats what I’m using.
Havent really spent much time on this to be honest, since its purely cosmetic…

**Comment by ErykDarnowski** [comment]
Ok, so that's the issue. If you'd switch to the repo version you wouldn't encounter the issue anymore.

**Comment by Ansh4011** [comment]
@ErykDarnowski Hey Bro! I got a quick and probably easy solution to fix the whole dislike counter misalignment.

Use Halfwidth Hangul Filler Unicode Character `(U+FFA0)` before the dislike counter text (No spaces in between) which basically shifts the dislike text a bit towards the right and the whole issue gets resolved, and no issue while zooming in and out either. Halfwidth Hangul Filler is basically a transparent yet selectable via cursor character, this is the thing-> `ﾠ`. 
Website for more details about the character- https://www.compart.com/en/unicode/U+FFA0

**Sample-**
(Before)
<img valign="left" src="https://user-images.githubusercontent.com/84930340/201972401-7ac212e4-94c2-48db-9c84-e5c850e1c723.png" width="450px">

(After)
<img valign="left" src="https://user-images.githubusercontent.com/84930340/201973708-bda50b0c-5c61-4e34-9e16-c59965490644.png" width="450px">

**Comment by ErykDarnowski** [comment]
Hey @Ansh4011 that's a great solution. Thing is this issue is referring to the missalignment of the **ratio bar**! 😅

There are however a couple issues that would greatly benefit from your fix though. They ones that caught my eye are these 2 (but I haven't looked through every issue):

- #776
- #801

**Comment by Ansh4011** [comment]
> Hey @Ansh4011 that's a great solution. Thing is this issue is referring to the missalignment of the **ratio bar**! 😅
> 
> There are however a couple issues that would greatly benefit from your fix though. They ones that caught my eye are these 2 (but I haven't looked through every issue so there may be more):
> 
> * [Dislike margins and DOM tree are messed up #776](https://github.com/Anarios/return-youtube-dislike/issues/776)
> * [YouTube New UI Problems #801](https://github.com/Anarios/return-youtube-dislike/issues/801)

Lol nvm for posting in the wrong place.😂
Thanks!

**Comment by ToothyDev** [comment]
Still a problem after the update...
![image](https://user-images.githubusercontent.com/55001472/203111503-76b9f877-8cb0-4077-bd26-d6a73117058b.png)

**Comment by User-444** [comment]
now it's not even there for me
<img width="226" alt="Screen Shot 2022-11-21 at 9 26 32 PM" src="https://user-images.githubusercontent.com/102774895/203221318-d4f1c52d-3030-4f81-9941-0a231a91bf0f.png">

**Comment by vortaj** [comment]
Still misaligned, but now only slightly
![dsl](https://user-images.githubusercontent.com/95566457/203256874-8d89711e-69fa-433b-8968-12e92e427954.png)

**Comment by ErykDarnowski** [comment]
Yes, I've recently also noticed this!
I'll try to resolve it as soon as I can.

**Comment by ErykDarnowski** [comment]
Okay, I think I've found what's wrong.

The main coulprit seems to be `left: -4` CSS in the `.ryd-tooltip-new-design` class!
I'll work on a PR for this soon.

**Comment by ErykDarnowski** [comment]
Okay I've decided to take the approach of making the **bar** width, the same as the **like + dislike buttons container**.

---

This will be done by:

1. Removing `left: -4` CSS from the `.ryd-tooltip-new-design` class.
2. Using a different approach to calculate the **bar's** width (one that doesn't round):

```javascript
// New:
parseFloat(window.getComputedStyle(getLikeButton()).width); // e.g. `150.55`

// Old:
getLikeButton().clientWidth // e.g. `151`
```

The new approach will be implemented because I've noticed that the **bar** was protruding a little too much on the right side, compared to the **like + dislike button container**.

**Comment by ToothyDev** [comment]
For some reason, the dislike bar is in the right spot again without an extension update, but for me its slightly offcentered to the left now

**Comment by ErykDarnowski** [comment]
Yes, I'm aware of that I fixed it in [this](https://github.com/An/return-youtube-dislike) PR!

**Comment by ToothyDev** [comment]
Alright, just wasnt sure why the bar suddenly appeared (at all) in the right spot again without any extension update

**Comment by ErykDarnowski** [comment]
There must've been an update (maybe an automatic one) as I've implemented that fix (just didn't notice the `4px` shift to the left, which I'm fixing with the PR I've linked in my previous comment).

What version of the extension are you running @ToothyDev?

**Comment by ToothyDev** [comment]
3.0.0.7

**Comment by ErykDarnowski** [comment]
Yup! Must have auto updated.
