### ISSUE TITLE
No value whatsoever shows on the dislike button

### ISSUE THREAD

**Issue by C-InfDef** [Anarios/return-youtube-dislike#811]
I fear that they may have entirely blitzed the stored info of dislikes
![really strange](https://user-images.githubusercontent.com/71182637/200158378-e6e84abf-8da9-4676-bcb6-e3c951bf41f3.png)

You can see at the dislike icon there isn't anything to be seen. I've refreshed multiple times and I know it wasn't like this before

**Comment by RoggerTan** [comment]
Found 502 error in my browser console. Probably there are some issues from the server side. 
![image](https://user-images.githubusercontent.com/16277022/200158649-c4aee63c-4e0c-408b-82ef-e4e13c49ea29.png)

**Comment by rahimratnani** [comment]
Facing the same issue.

**Comment by BobbyWibowo** [comment]
Yeah, it appears RYD's server itself is entirely down
Swagger API docs also returns 502 https://returnyoutubedislikeapi.com/swagger/index.html (linked in README)

**Comment by Anarios** [comment]
Some issues servers side, fixed now
