### ISSUE TITLE
Dislikes are not shown.

### ISSUE THREAD

**Issue by RafExinate** [Anarios/return-youtube-dislike#812]
### Browser

Opera GX

### Browser Version

LVL4 (core: 91.0.4516.106)

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.6

### Video link where you see the problem

Any YouTube video

### What happened?

It does not show dislikes. When i click dislike it shows only 1 dislike.
i disabled-enabled it, reinstalled it. Nothing seemed to work.
![unknown_2022 11 06-13 48](https://user-images.githubusercontent.com/110781737/200159902-0b1af250-51c6-4a27-91d6-6f74151dde1c.png)

### How to reproduce/recreate?

I honestly don't know.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by mvoloskov** [comment]
Same here in Firefox

**Comment by jatiinyadav** [comment]
+1

**Comment by DeterminedTorres** [comment]
Yep, I am having this issue too with the new UI kicking in, this now also affects Chromium-based browsers (ex: Ungoogled Chromium) and possibly Chrome itself. Reinstalling it unfortunately left me with no luck.

**Comment by Khateebxtreme** [comment]
Reinstalling doesn't work for chromium based browsers , i think it might be some issue with the servers.

**Comment by sabrt00th** [comment]
Visiting the [API website](https://returnyoutubedislikeapi.com/votes?videoId=QOFEgexls14) returns a bad gateway error, so definitely server-side issue.

**Comment by DeterminedTorres** [comment]
> Visiting the [API website](https://returnyoutubedislikeapi.com/votes?videoId=QOFEgexls14) returns a bad gateway error, so definitely server-side issue.

Oh, dang. Went to the website myself and you're right, it is a server side issue! I'm sure it'll be back soon.

**Comment by IronClaw99** [comment]
I am hoping this gets fixed soon.

**Comment by fourteen-1** [comment]
+1 Firefox on Win10

**Comment by DominicSaladin** [comment]
I'm also getting a CORS error in the console
![image](https://user-images.githubusercontent.com/43037258/200161273-ad998b4c-c5b2-4ac5-9d0f-8a9f2d8e8b75.png)

**Comment by cheadrian** [comment]
It works now. Didn't in the at least past few minutes. The [API ](https://returnyoutubedislikeapi.com/) website was down.

**Comment by RafExinate** [comment]
Its back. It works now.

**Comment by Anarios** [comment]
Some issues server-side, fixed now

**Comment by IronClaw99** [comment]
#815 Issue came back.

**Comment by osumeister** [comment]
The server is down again
