### ISSUE TITLE
YouTube dislike counter is not showing

### ISSUE THREAD

**Issue by IronClaw99** [Anarios/return-youtube-dislike#815]
### Browser

Mozilla Firefox

### Browser Version

106.0.5

### Extension or Userscript?

Extension

### Extension/Userscript Version

Version v3.0.0.6

### Video link where you see the problem

https://www.youtube.com/watch?v=1aZR_XX7eGY

### What happened?

The dislike numbers are not showing at all, as seem in the screenshot below.
![Screenshot 2022-11-08 at 04-05-57 Columbia Pictures Television_Televentures (1988)](https://user-images.githubusercontent.com/106572629/200536551-debc4dd5-0839-4d93-ae36-1bb3d3d39f19.png)

### How to reproduce/recreate?

This is happening on both Chrome and Firefox.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by IronClaw99** [comment]
Issue seems to have been fixed.

**Comment by IronClaw99** [comment]
Seems like the issue is back again.

**Comment by DominicSaladin** [comment]
The API ist up and running, I think and for me, it works.
https://returnyoutubedislikeapi.com/swagger/index.html

**Comment by evguu** [comment]
> The API ist up and running, I think and for me, it works.

Nope, response 502.

**Comment by NicoTheCinderace** [comment]
Yup, API is down.

**Comment by NicoTheCinderace** [comment]
API is back up, but dislikes are still not showing.

**Comment by TheGoldenSun** [comment]
Same for me on YouTube revanced, I'm assuming it's regular YouTube experimenting their dislike ratio sequence to have it removed.
Sent from miss moriarty  
 
  On Tue, Nov 8, 2022 at 12:40 PM, ***@***.***> wrote:   



API is back up, but dislikes are still not showing.

**Comment by Sangoku** [comment]
> API is back up, but dislikes are still not showing.

Not any more it is down for me at leas in Austria

**Comment by DominicSaladin** [comment]
Okay, now its down for me too.

**Comment by lightningHoneypot** [comment]
just checked, it is not showing up

**Comment by Mouadabdelghafouraitali** [comment]
It's down right now (in Morocco)

**Comment by Khateebxtreme** [comment]
The dislike counter seems to be not working as intended , down for me too.

**Comment by User-444** [comment]
It's also down for me and i use Google Chrome

**Comment by rxpsam420** [comment]
Down for me too, using Brave browser

**Comment by Serpensin** [comment]
Me too.

**Comment by rlarg** [comment]
Same here - on Chrome.

**Comment by rawIce** [comment]
Same here running Chrome 107.0.5304.88

**Comment by olsonperrensen** [comment]
Same on Firefox 108.0a1

**Comment by aolko** [comment]
Same here, Chrome 107

**Comment by gameshowrecaps** [comment]
![Screenshot 2022-11-08 145007](https://user-images.githubusercontent.com/57842610/200672597-799fbf1f-8843-4141-9b4b-07821b055614.png)

**Comment by deteriorated** [comment]
still not working

**Comment by deteriorated** [comment]
working for me now on firefox

**Comment by Anarios** [comment]
There was an infrastructure upgrades, some issues arose in process, so there was a period of downtime, now everything is fixed
