### ISSUE TITLE
Dislike count in Shorts

### ISSUE THREAD

**Issue by Vipin2003** [Anarios/return-youtube-dislike#819]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Can RYD team work on returning dislike count for shorts too ?

### Can you work on this?

- [ ] Yes
- [ ] No

### Will you be available for follow-up questions to help developers implement this?

Yes

**Comment by RyannDaGreat** [comment]
I thought I implemented this months ago?

**Comment by Vipin2003** [comment]
Nope..it is not..bro....

And If u are going to work on this, then can ualso try for posts too...
![Screenshot_20221116-155743](https://user-images.githubusercontent.com/93650504/202156286-f9eb0441-8c7b-44ec-8b26-b6ca2ad36159.png)

**Comment by TrueJoSephGD** [comment]
I'm assuming that this has to do with prior implementations of the dislike count in Shorts. Prior to the recent UI update, creators could see the dislike count when watching their own short. However, this is not available anymore. I'm aassuming all code related to presentation of the dislike count in the YouTube Shorts UI (as with the UI in standard YouTube videos) was removed in the update.

**Comment by LisousEinaiKyrios** [comment]
Revanced has it's own implementation of RYD.

**Comment by Skip75** [comment]
also interested. I just noticed that dislikes disapeared from Shorts recently :(

**Comment by TheGoldenSun** [comment]
And yet the percentage and number dislike feature always disappears whenever I load the next YouTube video to watch, how bizarre that it happens all the time.  
   


Revanced has it's own implementation of RYD.

**Comment by PickleNik** [comment]
Dislike count in Shorts is already implemented. Please keep in mind that this is a browser extension.
<img width="578" alt="Screenshot 2023-05-29 at 2 01 06 PM" src="https://github.com/Anarios/return-youtube-dislike/assets/31113245/f45af1c9-24f6-47d9-99c5-c1fa57754b15">

**Comment by Vipin2003** [comment]
Bro, pls check the date when I posted it and  when u are replying. After my request, @inotia00 implemented it.
