### ISSUE TITLE
(Bug): Different dislikes number while using tanpermonkey and add-on

### ISSUE THREAD

**Issue by Ygarr** [Anarios/return-youtube-dislike#82]
### Browser

Firefox

### Browser Version

94.0.2

### Extension or Userscript?

Userscript

### Extension/Userscript Version

last

### What happened?

A bug happened!
Tampermonkey script show 8 dislikes
Firefox add-on 586 dislikes

**Comment by DARKDRAGON532** [comment]
I'm pretty sure as to why this happens.
The extension first uses `averageRating` or something to get the like/dislike count, and if it doesnt find it it displays the count from the API.
Firefox is doing this and getting the like count, whereas the API has cached the `8 dislikes` and the userscript continues to show that, I'll fix it, thanks for bring it to attention
