### ISSUE TITLE
View dislikes in the youtube shorts on android

### ISSUE THREAD

**Issue by speedlorenzo12** [Anarios/return-youtube-dislike#824]
### Extension or Userscript?

Userscript

### Request or suggest a new feature!

The possibility of see the dislikes in the android app in the shorts of yt like in the pc

### Ways to implement this!

No response

### Can you work on this?

- [ ] Yes
- [x] No

### Will you be available for follow-up questions to help developers implement this?

Yes

**Comment by hyperstown** [comment]
> The possibility of see the dislikes in the android app in the shorts of yt like in the pc

By android app you mean YT Vanced, Revanced or some mobile browser like Fennec or Kiwi Browser?
Official YouTube app is completely controlled by Google and Vanced is discontinued. 
Revanced however is under active development and you can post issue [here](https://github.com/revanced/revanced-patches/issues)
As for mobile browser UserScript supports shorts but there is a problem with number being constantly overwritten. So it oscillates between number and word 'dislike'. 
I've made a workaround that addresses this issue that you can download [here](https://github.com/hyperstown/return-youtube-dislike/raw/combined-canary/Extensions/UserScript/Return%20Youtube%20Dislike.user.js)
I haven't posted pull request for it yet as I want to write whole thing in more readable way.

**Comment by speedlorenzo12** [comment]
Revanced and revanced extended

**Comment by hyperstown** [comment]
Revanced is written Kotlin so it doesn't support UserScript which is written in JavaScript. 
All you can do post an issue on [Revanced Patches project page](https://github.com/revanced/revanced-patches/issues).
Or alternatively use youtube in the browser that supports extensions eg Fennec, Kiwi Browser.
