### ISSUE TITLE
It’s not working!

### ISSUE THREAD

**Issue by malicerainbow** [Anarios/return-youtube-dislike#825]
I installed the userscript app in the App Store I opened the app set the directory folder to “my iPhone” and created the folder scripts 

I went to the link https://www.returnyoutubedislike.com/

I clicked install I selected userscript (tampermonkey) a new tab opened up with the script I clicked on aA puzzle icon selected userscript it said tap to install 

I than opened a new tab went into YouTube picked a video I went into the aA puzzle icon again selected userscript again I saw the script I tapped on it to be lit 

I refreshed the YouTube video page I still did not see the dislike count!
![5AA9BEB3-924C-471B-A033-45F9AE5886A8](https://user-images.githubusercontent.com/118444664/202595422-cf94ff80-bc15-44e3-8eb9-6e2eed2e7e4f.png)
![50910436-C544-4A85-8C9B-175890A9593A](https://user-images.githubusercontent.com/118444664/202595427-959f02ab-7c9e-4115-b786-6802305f622c.png)
![D935C8E3-6138-43E3-A8AD-32444C239851](https://user-images.githubusercontent.com/118444664/202595428-8f32cb60-8c1d-4f9e-b5f6-9cea971d25e4.png)
![E2533036-6DDF-47BB-B11D-17B39C2FBF6E](https://user-images.githubusercontent.com/118444664/202595429-d9de097f-a658-494b-8c0e-dd94f224fd95.png)
![A65512D4-8568-4F45-9F11-42DDE4E96C78](https://user-images.githubusercontent.com/118444664/202595430-dd5148b8-305a-4d71-82d9-0ccfc9c1ebaa.png)
![F84D867E-DE82-4EF7-834B-8DAB1526DBEB](https://user-images.githubusercontent.com/118444664/202595431-252e8e61-bc1b-401d-b46e-633628754217.jpeg)
![C5787D4A-CCA0-4715-8D3E-7EDB2CAC6C40](https://user-images.githubusercontent.com/118444664/202595432-53cceb75-672b-4824-a56e-cbc61aa1e6bf.jpeg)
![EE67BF07-E94C-4E42-B770-D8C404944C9E](https://user-images.githubusercontent.com/118444664/202595433-53b4fe90-b7f3-4580-8e2c-7dc18cfe03de.png)
![F3471942-9739-49C7-B4C1-56F42960FC95](https://user-images.githubusercontent.com/118444664/202595434-cf25a3a3-6a8c-4fd4-9d3a-d51b0877f7bd.png)
![F8395E5E-F185-4009-9AF2-1AB09A751A90](https://user-images.githubusercontent.com/118444664/202595436-28b8ad72-b4ff-4aed-9d8d-e0c61c055d42.jpeg)
![AD186FD8-E55A-4553-BF5B-B9D429AE2B2E](https://user-images.githubusercontent.com/118444664/202595438-4a39e4cd-9dd8-4714-8be8-fe6bd27ddcab.jpeg)

**Comment by hyperstown** [comment]
There is pending pull request [!749](https://github.com/Anarios/return-youtube-dislike/pull/749).
You can install updated version from [there.](https://github.com/hyperstown/return-youtube-dislike/raw/main/Extensions/UserScript/Return%20Youtube%20Dislike.user.js)
Just keep in mind that if you encounter any issues, you should report it in that pull request.

**Comment by hyperstown** [comment]
Pull request [!749](https://github.com/Anarios/return-youtube-dislike/pull/749) has been merged. This issue can be closed now.

**Comment by ronny941** [comment]
with this new update v3.0.0.7 the extension doesn't work it's not showing the dislikes and the likes are bugged
it appears "disabled by the owner" instead of the number of likes in all the videos
please fix it
