### ISSUE TITLE
Ratio bar only loads on refresh of browser tab

### ISSUE THREAD

**Issue by Rizxcviii** [Anarios/return-youtube-dislike#837]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Opera GX and Google Chrome

### Browser Version

Chrome/106.0.0.0 and Chrome/107.0.0.0 respectively

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.6

### Video link where you see the problem

All of them

### What happened?

It appears on the first load of a browser TAB (that's right, every tab, not just a window) the ratio bar will not load. Only on a refresh of the browser tab, will the ratio bar appear. Not even switching to another video will work. Only appears from a browser refresh, from what I've gathered.

I'm currently using the main branch as well, so all updates must be present on my version.

### How to reproduce/recreate?

Load a new browser tab, and you will notice the ratio bar missing. Refresh the browser tab for the ratio bar to appear.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by IMNdi** [comment]
I have this on Edge (Chrome extension). I tried the API to see if it's a connectivity issue and no, API is working fine.

Sorry if this is a hijack, but can we have a "retry" button? Since YT has all kinds of aces up its sleeve, many addons (like Sponsorblock) have a "retry" button.

**Comment by Rizxcviii** [comment]
I'm going to close this issue, it's over a year now (besides, this might be clogging up others from making their own). And there was an issue that fixed this one, back in 2022. For anything new, you might as well make a new issue.
