### ISSUE TITLE
Problem revanced extended

### ISSUE THREAD

**Issue by speedlorenzo12** [Anarios/return-youtube-dislike#843]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Revanced extended 

### Browser Version

No

### Extension or Userscript?

Userscript

### Extension/Userscript Version

19.45.36

### Video link where you see the problem

All

### What happened?

![IMG_20221203_195059](https://user-images.githubusercontent.com/111771663/205457145-03784617-83a6-4302-bf8f-d267e51b8874.jpg)
![IMG_20221203_195034](https://user-images.githubusercontent.com/111771663/205457147-c4c87bf4-f5e2-4146-a14e-d70a93e785ca.jpg)

### How to reproduce/recreate?

Install revanced extended and prove

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

No

**Comment by hyperstown** [comment]
I already said that in https://github.com/Anarios/return-youtube-dislike/issues/824  but... Revanced does not use RYD UserScript nor Extension. They use their own implementation. This issue should be posted in Revanced project page. [HERE](https://github.com/revanced/revanced-patches/issues).

**Comment by PickleNik** [comment]
that is indeed a problem for ReeVamced to solve :)
