### ISSUE TITLE
Suicide help banner causes the like/dislike bar to be misplaced

### ISSUE THREAD

**Issue by nugel** [Anarios/return-youtube-dislike#847]
### Have you tried to find similar open issues?

- [x] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

Chrome 108.0.5359.98

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.7

### Video link where you see the problem

https://www.youtube.com/watch?v=LACbVhgtx9I

### What happened?

Videos that promote suicide have the banner with phone numbers etc, but that causes the dislike bar to be moved much higher and not below the dislike buttons. 

![image](https://user-images.githubusercontent.com/54183462/206547073-6ae2891b-abcf-4063-91d5-ca3ebef8e071.png)

### How to reproduce/recreate?

- Open a video that promotes suicide
- look at the like/dislike bar

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by jaff80** [comment]
Happening with these type of banners too
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/113552154/207177819-4a7d0ab9-fa16-4acf-b614-59a76342be8a.png">

**Comment by Jordy3D** [comment]
Just for further reference, it also occurs with these
![image](https://user-images.githubusercontent.com/19144524/213108966-31cf99c9-6448-4879-9f24-2ab76df0fcde.png)
I assume the extension is looking for the first element in the #below div that has children and then placing it where it thinks it should go, or something along those lines

**Comment by ErykDarnowski** [comment]
Hey, I've also noticed this and will try to fix it in [this](https://github.com/Anarios/return-youtube-dislike/pull/835) PR!

**Comment by PickleNik** [comment]
is this still an issue? I haven't been able to reproduce on 3.0.0.9

**Comment by jaff80** [comment]
@PickleNik Seems to be working for me
![RYD working](https://github.com/Anarios/return-youtube-dislike/assets/113552154/67d10272-0680-47d3-9f4b-18c754b60d54)

**Comment by PickleNik** [comment]
reopen if reproduced
