### ISSUE TITLE
Show like, dislike count in video card or below Title near views after Searching a video or in recommendations.

### ISSUE THREAD

**Issue by dpthegrey** [Anarios/return-youtube-dislike#849]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

I want to suggest a feature which can show like and dislike counts over video thumbnail or below title near view count so we can see like and dislike counts without opening a video. This feature will help in judging if the video is even worth clicking to see or not.

### Ways to implement this!

We can implement this by putting like and dislike numbers near view count or on hover there must be some way to show like and dislike count for that specific video. 

### Can you work on this?

- [ ] Yes
- [X] No

### Will you be available for follow-up questions to help developers implement this?

Yes

**Comment by PickleNik** [comment]
sorry, that is not a planned feature for this extension, but another extension can use our [API](https://returnyoutubedislike.com/docs) to do that.
