### ISSUE TITLE
add margin to dislike icon

### ISSUE THREAD

**Issue by erpetek** [Anarios/return-youtube-dislike#852]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

add margin to the dislike button to have consistency with the like button, since the dislike count was removed from the site there's no more need for the margin-right in the icon (how the like button has it)

### Ways to implement this!

adding margin-right to the dislike button icon element, i've made this script but i'm not sure about compability so i don't want to make a pull request with this
`
var elems = document.getElementsByClassName("yt-spec-button-shape-next__icon");
for (let i = 0; i < elems.length; i++) {
  var curElemStyle = window.getComputedStyle(elems[i]);
  if (curElemStyle.marginLeft + curElemStyle.marginRight === "-6px0px") {
    elems[i].style.marginRight = "6px";
  }
}
`

### Can you work on this?

- [X] Yes
- [ ] No

### Will you be available for follow-up questions to help developers implement this?

Yes

**Comment by PickleNik** [comment]
<img width="159" alt="Screenshot 2023-05-29 at 1 08 20 PM" src="https://github.com/Anarios/return-youtube-dislike/assets/31113245/e2062656-d0e1-43dc-85ea-da94eb8ef8c4">
:)
