### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by GoldenBoiASDASD** [Anarios/return-youtube-dislike#853]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Opera

### Browser Version

Opera 94

### Extension or Userscript?

Userscript

### Extension/Userscript Version

Version 3.1.0

### Video link where you see the problem

Every single video.

### What happened?

i can't see how many dislikes there are on a video

### How to reproduce/recreate?

make it so it always shows the dislikes on a video

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by PickleNik** [comment]
it works
<img width="641" alt="Screenshot 2023-01-25 at 4 55 40 PM" src="https://user-images.githubusercontent.com/31113245/214700322-d70bfe31-0897-4dfb-ad4a-8bfd54877071.png">

https://user-images.githubusercontent.com/31113245/214699869-3ea937d7-61de-4247-b00f-b7ca6ae15fe1.mp4
