### ISSUE TITLE
Likes and dislikes counter swapped

### ISSUE THREAD

**Issue by IvanAstran** [Anarios/return-youtube-dislike#855]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

108.0.5359.125

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.7

### Video link where you see the problem

This problem occurs on all videos

### What happened?

![chrome_IwxIUPkPyI](https://user-images.githubusercontent.com/96918464/209848648-828d4f82-1720-4cea-8a97-51389935f1ea.gif)

### How to reproduce/recreate?

This error occurs every time I open a video

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by PickleNik** [comment]
it could be due to other extensions you have installed, could you try running it in incognito window with only RYD?

**Comment by PickleNik** [comment]
seems to be related to #801 towards the bottom of the issue
