### ISSUE TITLE
Soluciones 

### ISSUE THREAD

**Issue by 10jhoan** [Anarios/return-youtube-dislike#856]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

https://github.com/Anarios/return-youtube-dislike/blob/d12539d3bbe7cae30941110c8a1f3939fbb8e8d3/CONTRIBUTING.md

### Can you work on this?

- [X] Yes
- [ ] No

### Will you be available for follow-up questions to help developers implement this?

Yes

**Comment by 10jhoan** [comment]
>

**Comment by PickleNik** [comment]
stale, need more info
