### ISSUE TITLE
High CPU usage when used with Zoom Page WE on some videos

### ISSUE THREAD

**Issue by bottleblue** [Anarios/return-youtube-dislike#859]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Firefox

### Browser Version

108.0.1

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.7

### Video link where you see the problem

https://www.youtube.com/watch?v=F7XAQNRn638

### What happened?

When used in combination with the Zoom Page WE extension it can cause high cpu usage and browser freezing/lag on some videos like https://www.youtube.com/watch?v=F7XAQNRn638 or https://www.youtube.com/watch?v=F03gEzdLa2g 
I don't know why it only happens on a few particular videos.

The userscript version of return youtube dislike doesn't seem to cause this problem. 

### How to reproduce/recreate?

Install Return Youtube Dislike extension and Zoom Page WE (https://addons.mozilla.org/en-US/firefox/addon/zoom-page-we/)

In Zoom Page WE Options/ General tab - Zoom mode is set to per-site. The only boxes I have checked are "Show full or text zoom level on button" and "Show zoom/font/subsite states on button" under User Interface.

Before going to one of those problematic youtube links open up the youtube homepage and set zoom type to Text and increase zoom to 133%.

Open those youtube links and see if there's high cpu usage/freezing/lag/

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Dheatly23** [comment]
Hello, i did open the linked video, and it lagged on my device too. The difference is that i **did not** use the Zoom Page WE. Maybe it's similiar to #846? Anyways can you provide the console log? Thanks.

**Comment by bottleblue** [comment]
Hmm maybe other extensions can cause the same problem? Sometimes when I load those youtube videos I get the firefox error Zoom Page WE is making the page load very slowly and it asks me if I want to stop it. 

Yea it probably has something to do with the error you discovered. You've gone more in-depth than I have.

I don't know how to provide a console log sry.

**Comment by Anarios** [comment]
Doesn't happen to me on that video. 

Песенка прям ностальгия :)

**Comment by bottleblue** [comment]
What about the other video?

**Comment by Anarios** [comment]
Both are fine for me, but I didn't install the zoom extension yet, will test it as well.

**Comment by Dheatly23** [comment]
@bottleblue Press F12 to open console log.

**Comment by bottleblue** [comment]
> @bottleblue Press F12 to open console log.

yes I also got the recursion error when Return Dislike extension and Zoom Page WE is enabled.
![2023-01-16_084715](https://user-images.githubusercontent.com/3678136/212730308-eeac6d4f-bf57-47a3-aea8-26bb216c0e33.jpg)

If Zoom Page WE is disabled I don't get the error.

**Comment by Dheatly23** [comment]
Hmm okay, so there might be some weird interaction with other extension (?)

For now i'll update my issue to document it

**Comment by Anarios** [comment]
Should be fixed in 3.0.0.17, similar to #1074
