### ISSUE TITLE
(Bug): number is shown twice

### ISSUE THREAD

**Issue by Fytch** [Anarios/return-youtube-dislike#86]
### Browser

Firefox

### Browser Version

Firefox 94.0.2

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.0.0.0

### Video link where you see the problem

https://www.youtube.com/watch?v=5KBqOfv-8HI

### What happened?

After disliking, the number was shown twice (was 861 before):

![image](https://user-images.githubusercontent.com/10600373/143930765-c375b2ad-1f85-4e25-b8ac-7bf6a18a8045.png)

**Comment by TheSecurityDev** [comment]
I reported this issue just before yours: #85 ;)

**Comment by Prasantacharya** [comment]
odd, im using firefox 94 aswell, and this is what i dont see the same thing when i dislike it. it just shows the numbers normally
![dislike-test](https://user-images.githubusercontent.com/23312333/143966495-2ef7f608-78bf-41de-af02-6e55507c9620.png)

**Comment by TheSecurityDev** [comment]
It seems to happen only on live videos that are actively being disliked. And you have to wait a bit for it sometimes.

**Comment by Stef16Robbe** [comment]
@Fytch @TheSecurityDev I can't reproduce this anymore on Chrome or Firefox, can you?

**Comment by TheSecurityDev** [comment]
> @Fytch @TheSecurityDev I can't reproduce this anymore on Chrome or Firefox, can you?

No, it doesn't seem to happen anymore. Maybe because the YouTube API isn't updating the count anymore? Or maybe it's been fixed.

**Comment by Stef16Robbe** [comment]
> > @Fytch @TheSecurityDev I can't reproduce this anymore on Chrome or Firefox, can you?
> 
> No, it doesn't seem to happen anymore. Maybe because the YouTube API isn't updating the count anymore? Or maybe it's been fixed.

Pretty sure this has been fixed, just without mentioning this or your issue.

**Comment by Fytch** [comment]
Can't reproduce either anymore. Closing.
