### ISSUE TITLE
Return YouTube Dislikes No Longer Works!

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [Anarios/return-youtube-dislike#862]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Opera GX

### Browser Version

Chromium v108.0.5359.125

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.7

### Video link where you see the problem

https://www.youtube.com/watch?v=oWzc8gZb634&ab_channel=penguinz0

### What happened?

I don't know if it's only me but it stopped working!

### How to reproduce/recreate?

Watch any video! It no longer works!

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by ENTPRESTIGIOUS** [comment]
![image](https://user-images.githubusercontent.com/45579671/212460464-4bd45f88-dda6-47b8-b4ac-f782053c2965.png)

**Comment by ENTPRESTIGIOUS** [comment]
Fixed today! I'd assume Opera GX has released a patch to this problem!

**Comment by MaCrO093** [comment]
this problem is still happening to me on opera gx
