### ISSUE TITLE
Video on top right corner offen got hidden in Youtube homepage

### ISSUE THREAD

**Issue by vathanac** [Anarios/return-youtube-dislike#867]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

Version 109.0.5414.119 (Official Build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.7

### Video link where you see the problem

https://www.youtube.com/

### What happened?

Video got hidden

### How to reproduce/recreate?

Video got hidden even if I refresh the page.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by PickleNik** [comment]
that's unrelated to the extension, youtube's just running experiments.
