### ISSUE TITLE
It stopped working

### ISSUE THREAD

**Issue by Temepest74** [Anarios/return-youtube-dislike#868]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Firefox

### Browser Version

109.0 (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.7

### Video link where you see the problem

https://www.youtube.com/watch?v=ng438SIXyW4

### What happened?

The extension just stopped working
![image](https://user-images.githubusercontent.com/28103890/215142923-6007de78-b5cd-4ca6-b08c-44ee5ffe1d4c.png)

### How to reproduce/recreate?

I have no idea. It just happened

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by PickleNik** [comment]
<img width="1728" alt="Screenshot 2023-01-27 at 3 53 04 PM" src="https://user-images.githubusercontent.com/31113245/215194913-fa441011-17a4-4178-996d-338b0ffc1c17.png">
it's temporary, if it doesn't resolve itself in a day, please reopen
