### ISSUE TITLE
Disabled by owner on every video

### ISSUE THREAD

**Issue by Voltixdark** [Anarios/return-youtube-dislike#869]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Firefox

### Browser Version

109.0 64-bit

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.7

### Video link where you see the problem

https://www.youtube.com/watch?v=Mw10AmA93hE

### What happened?

All videos on Youtube I click on there is a "Disabled by owner" where likes and dislikes are supposed to be.

### How to reproduce/recreate?

Just click on any video and it shows up.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by PickleNik** [comment]
<img width="1312" alt="Screenshot 2023-01-29 at 1 05 16 PM" src="https://user-images.githubusercontent.com/31113245/215346387-4781a07b-c4e9-46c0-9fdd-a4440b62b4ec.png">
maybe it was a temporary bug? is it still hapenning for you?
