### ISSUE TITLE
Firefox for Android

### ISSUE THREAD

**Issue by brothersw** [Anarios/return-youtube-dislike#87]
Would it be possible/within scope to add this extension to Firefox for android? It seems to be currently unavaliable.

**Comment by brothersw** [comment]
I am writing this on android currently, should go back and follow contributing guidelines when can edit using a PC.

**Comment by PandoraHayami** [comment]
I think more accurately would be that the extension (And/or userscript) Worked with the youtube mobile website, it takes a while, but with Fennec (F-droid version of Firefox) Or just kiwi browser to get extensions on mobile, so it would help a lot if it would work on the mobile website.

**Comment by DARKDRAGON532** [comment]
Duplicate of #68
