### ISSUE TITLE
The Dislike counter and bar are gone for good.

### ISSUE THREAD

**Issue by TsukiZero** [Anarios/return-youtube-dislike#870]
Perhaps you would want to know that it no longer works...
![image](https://user-images.githubusercontent.com/78157224/216674796-6e12a908-1cec-4943-ae90-3e05417d0faa.png)
Using the Userscript option, for the record.

**Comment by PickleNik** [comment]
<img width="1381" alt="Screenshot 2023-02-03 at 2 10 39 PM" src="https://user-images.githubusercontent.com/31113245/216687148-64e55c9e-d9c6-4436-99da-0a62046f16d6.png">

**Comment by PickleNik** [comment]
if you're having issues checkout the [Troubleshooting Guide](https://returnyoutubedislike.com/help) 
or reach out on Discord (linked in step *4.* of the Troubleshooting Guide)

**Comment by TsukiZero** [comment]
There may have been a brief downtime maybe... Or something related to Youtube's API, I don't have a clue, as another script I used wasn't functioning either, but now is. Thanks still.

**Comment by PickleNik** [comment]
> There may have been a brief downtime maybe... Or something related to Youtube's API, I don't have a clue, as another script I used wasn't functioning either, but now is. Thanks still.

we don't rely on YouTube APIs at all, but some downtime for our API might've been the issue

**Comment by TsukiZero** [comment]
That makes a lot of sense. Thanks!
