### ISSUE TITLE
Video mutes for a half a second after starting playback while dislikes are loading (works fine without extension)

### ISSUE THREAD

**Issue by Enerccio** [Anarios/return-youtube-dislike#878]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Firefox 

### Browser Version

108.0.2

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.7

### Video link where you see the problem

any

### What happened?

Video mutes for a half a second after starting playback while dislikes are loading (works fine without extension)

### How to reproduce/recreate?

Start a video. It will start playback of sound, then it will immediately mute while dislikes are loaded and then it resumes

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Anarios** [comment]
Wasn't widely reported and seems to be fixed by now. Please reopen if still experiencing the issue.
