### ISSUE TITLE
Incorrect spacing on dislike count

### ISSUE THREAD

**Issue by dogemanttv** [Anarios/return-youtube-dislike#879]
### Have you tried to find similar open issues?

- [x] Yes, this issue is not a duplicate

### Browser

Firefox

### Browser Version

Firefox 110.0

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.7

### Video link where you see the problem

every video

### What happened?

My expectation was for there to be spacing between the dislike icon and the text, but there was none.

### How to reproduce/recreate?

go to a youtube video and look at the dislike count

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Anarios** [comment]
Fixed in 3.0.0.8, it's in review
