### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by FiberAhmed** [Anarios/return-youtube-dislike#88]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Can you add Microsoft Edge Extension?

### Ways to implement this!

idk

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by Felix14-v2** [comment]
Microsoft Edge supports Chrome extensions. I've been testing this and it seems to be working well.

**Comment by Mola19** [comment]
Chrome is built on a opensource browser called Chromium. This Chromium browser can be used by anyone to build their own browser and most actually do. Opera, Brave, Edge, Vivaldi, and many more. Essentially anything that isn't Firefox or Safari is Chromium. This means that extension for all of these browser should be the same and should work from the chrome web store.

**Comment by MagicRB** [comment]
This can therefore be closed, Edge users can install extensions manually. No need to add it to Microsoft's store

**Comment by laughingsheep** [comment]
@Anarios can you please close this?

**Comment by dftf-stu** [comment]
Hi @Anarios.  Just wondering if there's been any-more thought on adding your extension to the [Edge Add-Ons Store](https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home)?

Two reasons I'd suggest.

First: another extension in there is stealing your name and logo, obviously capitalising on the fact that users are looking for your extension, but as it's not there, they've taken your place:

![Image](https://github.com/user-attachments/assets/c6d69470-212d-4805-8a01-ad79bcc19bb1)

And their extension is less-safe, given it requests access to "data on all websites" 😲😬, not just YouTube-owned domains.

Second: other similar-extensions in the Edge Store have between them at-least ~115,000 downloads.  I'd suspect many of those may have become users of your extension, were it to have been available:

![Image](https://github.com/user-attachments/assets/ab104c78-0eb8-4e64-b731-e8fc9902be61)

And possibly third: were Microsoft ever to stop allowing add-ons from the Google Chrome store to be added, clearly that would then mean your one couldn't be used there.  Not aware of any plans for that currently, but you never know.  (I believe via the Group Policies for when Edge is managed by enterprises though, limiting to the Edge Add-Ons store and blocking Google's is possible.)

Thanks
