### ISSUE TITLE
Return Youtube Dislikes shows a wierd, unreadable number of dislikes.

### ISSUE THREAD

**Issue by sanchayanghosh** [Anarios/return-youtube-dislike#881]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Firefox

### Browser Version

Firefox v109.0

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.8

### Video link where you see the problem

https://www.youtube.com/watch?v=Wif1EAgEQKI

### What happened?

The number of dislikes show a very wierd unit, of 1.5T. if we had 1500 dislikes, we'd show 1.5k, 1.5T or 1.5 trillion dislikes, is literally [250] times more than the human population, so this makes no sense, so is 1.5T 1500 dislikes?

![dislike_counter](https://user-images.githubusercontent.com/86283153/221418513-114b4719-8c97-4106-b8dd-bf7dea9f8180.png)

### How to reproduce/recreate?

1. Open Firefox
2. Browse to the video
3. Read the dislikes

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Anarios** [comment]
T is for thousand in your chosen locale.
