### ISSUE TITLE
(Minor issue): The plugin shows useless fraction on the dislike counter

### ISSUE THREAD

**Issue by Monsterovich** [Anarios/return-youtube-dislike#89]
### Browser

Firefox

### Browser Version

89.0

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.0.0.0

### Video link where you see the problem

Any video: https://www.youtube.com/watch?v=By_Cn5ixYLg

### What happened?

![изображение](https://user-images.githubusercontent.com/3750982/143962669-096a8e96-fde9-4015-869d-3cd30db590c6.png)

**Comment by hisamafahri** [comment]
Can't reproduce:

![image](https://user-images.githubusercontent.com/65691613/144159828-a60b1335-a074-4e59-8e7c-4b94c3c5fb62.png)

**Comment by DARKDRAGON532** [comment]
> Can't reproduce:
> 
> ![image](https://user-images.githubusercontent.com/65691613/144159828-a60b1335-a074-4e59-8e7c-4b94c3c5fb62.png)

different locales probably, @Monsterovich whats your locale?

**Comment by Monsterovich** [comment]
> > Can't reproduce:
> > ![image](https://user-images.githubusercontent.com/65691613/144159828-a60b1335-a074-4e59-8e7c-4b94c3c5fb62.png)
> 
> different locales probably, @Monsterovich whats your locale?

Russian.

**Comment by juozaspo** [comment]
This is reproduceable on my end as long as dislike count is low enough. Browser locale is Lithuanian, youtube is set to English.
![Screenshot 2021-12-02 at 17-16-00 Why is it so small - YouTube](https://user-images.githubusercontent.com/6626242/144449783-54cbb5b1-7fca-42ec-bc8e-dd2ed319ae40.png)

**Comment by mPiotrek** [comment]
@Monsterovich Can it be closed now, or does the issue still occur for you?
