### ISSUE TITLE
RYD userscript not showing dislike count (again)

### ISSUE THREAD

**Issue by EricE549X** [Anarios/return-youtube-dislike#905]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Safari

### Browser Version

16.4

### Extension or Userscript?

Userscript

### Extension/Userscript Version

3.1.1

### Video link where you see the problem

any video

### What happened?

the dislike count randomly disappeared today i guess lol

### How to reproduce/recreate?

1. go to any video
2. see error

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Anarios** [comment]
Known issue, working on a fix.

**Comment by EricE549X** [comment]
thanks

**Comment by WaviestBalloon** [comment]
Somewhat related, 
![image](https://user-images.githubusercontent.com/31796727/236919701-6ef9fe73-4528-45c9-80e8-b2d7a788f1d0.png)
But I also no longer see the dislike counter anymore

**Comment by ENTPRESTIGIOUS** [comment]
yeah having the same issue, coming here to look version 3.0.0.8

**Comment by virtuallyunknown** [comment]
I am having a similar same issue, but I am using the extension instead of a user script.

```
TypeError: getDislikeButton() is undefined
    addLikeDislikeEventListener moz-extension://8e58f0e3-5973-4406-a3cf-818e06aaabad/ryd.content-script.js:905
    checkForJS_Finish moz-extension://8e58f0e3-5973-4406-a3cf-818e06aaabad/ryd.content-script.js:983
```
```js
// moz-extension://8e58f0e3-5973-4406-a3cf-818e06aaabad/ryd.content-script.js:983
function setEventListeners(evt) {
  function checkForJS_Finish() {
    if (isShorts() || (getButtons()?.offsetParent && isVideoLoaded())) {
      addLikeDislikeEventListener();
      setInitialState();
      getBrowser().storage.onChanged.addListener(storageChangeHandler);
      clearInterval(jsInitChecktimer);
      jsInitChecktimer = null;
    }
  }

  jsInitChecktimer = setInterval(checkForJS_Finish, 111);
}

// moz-extension://8e58f0e3-5973-4406-a3cf-818e06aaabad/ryd.content-script.js:905
function addLikeDislikeEventListener() {
  if (!window.returnDislikeButtonlistenersSet) {
    getLikeButton().addEventListener("click", likeClicked);
    getDislikeButton().addEventListener("click", dislikeClicked);
//  ^^^^^^^^^^^^^^^^ 
    getLikeButton().addEventListener("touchstart", likeClicked);
    getLikeButton().addEventListener("touchstart", dislikeClicked);
    window.returnDislikeButtonlistenersSet = true;
  }
}

```

RYD: 3.0.0.8
Firefox: 112.0.2

**Comment by drozumek** [comment]
Browser - MS Edge - same problem. Dislikes aren't visible

**Comment by Drogobo** [comment]
I am a Firefox user on Linux. This is an issue.

**Comment by captainnintendo** [comment]
I'm using Brave on Linux, and I'm having the same issue.

**Comment by commanderh** [comment]
I also wanted to add it's also an issue on Chrome and mac OS Ventura 13.3.1

**Comment by itkind** [comment]
Same issue on Vivaldi and mac OS Ventura 13.3.1

**Comment by AlmostHuman34** [comment]
brave same issue

**Comment by nanowell** [comment]
MS edge same problem

**Comment by friendly-misanthrope** [comment]
Using extension, dislike count stopped showing today. Using Brave on Win10.

**Comment by Pentazer** [comment]
Same, today, using Win 10 and Opera GX

**Comment by a12dongithub** [comment]
Not working with Win 10 and brave + Edge

**Comment by CroaBeast** [comment]
Opera GX and Win 11, with extension v3.0.0.8 has the same issue.

**Comment by NathanX-S** [comment]
Also occurring on extension.

**Comment by DragShot** [comment]
Firefox 84 on Windows. Same issue.

**Comment by Orion81200** [comment]
Chrome Version 113.0.5672.93 same issue

**Comment by RudovEgor** [comment]
Firefox 112.0 on Windows 10. Same issue.

**Comment by Henrylau127** [comment]
Brave 1.51.110 on Windows 11, same issue

**Comment by ARogueOtaku** [comment]
Seems it is fixed on Edge/Chrome? Was a fix implemented in the extension code or did YouTube revert the breaking change?

**Comment by SamGitHub1807** [comment]
It's working again now. Thank you!

**Comment by avindra** [comment]
Userscript is working. Firefox hasn't published the latest version yet.

**Comment by WaviestBalloon** [comment]
> Userscript is working. Firefox hasn't published the latest version of the add-on yet.

Got it. Thank you
