### ISSUE TITLE
Dislikes not showing with YouTube Redux.

### ISSUE THREAD

**Issue by MarisaKirisame-ze** [Anarios/return-youtube-dislike#908]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

Chrome v112

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.9

### Video link where you see the problem

Any video.

### What happened?

Dislikes aren't showing when paired with the YouTube Redux extension.

### How to reproduce/recreate?

Go to any video to try and see the dislikes.

![image](https://github.com/Anarios/return-youtube-dislike/assets/86389939/20def020-dea0-4191-bbb5-799f3ec25dde)

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Nightcaat** [comment]
This has been fixed and broken multiple times since this issue was created but as of the time of this comment it is currently fixed in https://github.com/omnidevZero/YouTubeRedux/commit/dbaa4392e724d5d7b4570c526496767e8d6cfb1b. Updating Redux to v3.2.0 should solve your problem.
