### ISSUE TITLE
(Feature Request): independent browser addon instead of using YouTube api to dislike videos on a 3rd party service. 

### ISSUE THREAD

**Issue by natewrench** [Anarios/return-youtube-dislike#91]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Have a browser addon to have a simple dislike button and counter for users outside YouTube

### Ways to implement this!

Fork discussions.app to use the block chain to store dislikes so they can't be modified or erased or censored

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by Frontesque** [comment]
This will already be the case come December 13th as per the [faq](https://returnyoutubedislike.com/faq)
