### ISSUE TITLE
Not working with Safari

### ISSUE THREAD

**Issue by mdecaro** [Anarios/return-youtube-dislike#910]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Safari

### Browser Version

16.4

### Extension or Userscript?

Userscript

### Extension/Userscript Version

3.1.1

### Video link where you see the problem

https://www.youtube.com/watch?v=YEFV6ub6WV4

### What happened?

The dislike count is not shown

### How to reproduce/recreate?

Navigate to page with script enabled

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by mdecaro** [comment]
Sorry, I misread the version of Safari on the prior post.  

By the way, I. was using Tampermonkey to run the script then switched to Userscripts.  There is a setting to allow injection, when I toggled that, it seems to be working OK.

**Comment by EricE549X** [comment]
an [updated version](https://raw.githubusercontent.com/Anarios/return-youtube-dislike/main/Extensions/UserScript/Return%20Youtube%20Dislike.user.js#bypass=true) of the userscript has since been released.
