### ISSUE TITLE
Firefox is not working anymore

### ISSUE THREAD

**Issue by Mmeckawy** [Anarios/return-youtube-dislike#912]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Firefox

### Browser Version

113.0

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.8

### Video link where you see the problem

https://www.youtube.com/watch?v=EOnSh3QlpbQ

### What happened?

A bug happened!

### How to reproduce/recreate?

The same version of the extension is working on Chrome on any video, however, on Firefox it's not working anymore on any video.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Jorchking** [comment]
how do you fix that? why is closed? still not working on firefox.

**Comment by Mmeckawy** [comment]
> how do you fix that? why is closed? still not working on firefox.

Closed it because I found another issue that mentions the same bug. Anyway. it's working now on Firefox sorry for any inconvenience
