### ISSUE TITLE
Cant download v3.0.0.9.

### ISSUE THREAD

**Issue by Vardravor** [Anarios/return-youtube-dislike#914]
### Have you tried to find similar open issues?

- [x] Yes, this issue is not a duplicate

### Browser

Firefox

### Browser Version

Firefox 113.0

### Extension or Userscript?

Extension

### Extension/Userscript Version

Version 3.0.0.9.

### Video link where you see the problem

none

### What happened?

Dislikes are not showing up in version 3.0.0.8. anymore and i cant download the new version 3.0.0.9.

### How to reproduce/recreate?

I went on the Website clicked on install and was sent to the firefox page from Return Youtube Dislike but could only install version 3.0.0.8.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by shadowking1443** [comment]
Can replicate the problem as well. Workaround is to uninstall the extension and reinstall.
