### ISSUE TITLE
v3.0.0.9 @ Firefox: buttons counters are messed up

### ISSUE THREAD

**Issue by codeabuse** [Anarios/return-youtube-dislike#919]
### Discussed in https://github.com/Anarios/return-youtube-dislike/discussions/918

<div type='discussions-op-text'>

<sup>Originally posted by **codeabuse** May 18, 2023</sup>
First of all, hello and thank you for your add-on!

Here's my report on v3.0.0.9 for Firefox.
- 'Like' counter on thumbs-up button is showing dislikes count,
- 'Dislike' button shows no counter,
- The only valid info is shown when hovering likes/dislikes bar.
Everything is shown on the screenshot:
![image](https://github.com/Anarios/return-youtube-dislike/assets/47417014/09c02274-9cbd-4de7-891e-3b09fa05d856)
</div>

**Comment by Anarios** [comment]
Caused by the download addon.
