### ISSUE TITLE
Not showing dislikes

### ISSUE THREAD

**Issue by foursplaysroblox** [Anarios/return-youtube-dislike#921]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Microsoft Edge Dev

### Browser Version

Microsoft Edge Dev 115.0.1851.0 (Official build) dev (64-bit) 

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.9

### Video link where you see the problem

https://www.youtube.com/watch?v=9cIptoe0VtA&ab_channel=AydenGeorge

### What happened?

Hello it just happened today that I cannot see the dislike count and I am wondering if it is just my browser or not.
![image](https://github.com/Anarios/return-youtube-dislike/assets/82078139/e15a8fdb-a4ef-476d-812b-b0da29161adb)

### How to reproduce/recreate?

Tell us how it happened with detailed steps for us.
Not sure

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by haiku-balls** [comment]
Can reproduce in Firefox 112.0-1 using the latest release of RYTD.
It's been broken for a while now.
![image](https://github.com/Anarios/return-youtube-dislike/assets/65756037/2085382f-720a-475c-b600-90ece9a89503)

**Comment by avindra** [comment]
It stopped working. This is after #907 got fixed. Maybe another breaking UI change?

**Comment by svaranasi-corporate** [comment]
113.0.1 Firefox, 3.0.0.9 RYTD. Broken as of a few hours ago.

**Comment by minhperry** [comment]
YT Revanced 18.16.37 with packaged RYD also not working, most of the time giving 502 error.

**Comment by haiku-balls** [comment]
Seems like it can get dislikes, it just doesn't display them. At least on my end.
![image](https://github.com/Anarios/return-youtube-dislike/assets/65756037/06ed655a-ba34-40e1-82f2-facb41dd9ca7)

**Comment by avindra** [comment]
Started working for me again. Using userscript `3.1.2`.

**Comment by PickleNik** [comment]
seems to be resolved
<img width="1728" alt="Screenshot 2023-05-29 at 12 50 49 PM" src="https://github.com/Anarios/return-youtube-dislike/assets/31113245/1e09b095-cfbd-4614-88c8-953113bed780">
<img width="1728" alt="Screenshot 2023-05-29 at 12 58 50 PM" src="https://github.com/Anarios/return-youtube-dislike/assets/31113245/a3c3fa3b-5db4-4c17-9652-01bc53f13f15">
