### ISSUE TITLE
YouTube dislikes temporarily unavailable (5/21/23)

### ISSUE THREAD

**Issue by IronClaw99** [Anarios/return-youtube-dislike#922]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Mozilla Firefox

### Browser Version

Firefox v113.0.1

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.9

### Video link where you see the problem

Any video

### What happened?

Dislikes are all showing as "temporarily unavailable"

### How to reproduce/recreate?

This issue is happening in both Firefox and Chrome.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by MinecraftNight4** [comment]
API is currently down.
<https://www.returnyoutubedislike.com/help>

API Test link:
![image](https://github.com/Anarios/return-youtube-dislike/assets/42017416/9c199e57-0a63-4e25-a111-13493eb8a480)

Error:
![image](https://github.com/Anarios/return-youtube-dislike/assets/42017416/9a7d08f2-64ba-4146-a2fb-4a80a2e55f11)

**Comment by IronClaw99** [comment]
I'm hoping for this to get fixed soon.

**Comment by alekhm-code** [comment]
a lot of things are down right now

**Comment by Anarios** [comment]
Fixed
