### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by fillwithjoy1** [Anarios/return-youtube-dislike#927]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Where is the next release? There are few things to work on that I think this extension needs such as the ability to like/dislike videos that a creator has disabled, only to exist on a database that can be pulled

### Ways to implement this!

Last release was last year, and there are numerous pull requests and issues that haven't been attended

### Can you work on this?

- [ ] Yes
- [X] No

### Will you be available for follow-up questions to help developers implement this?

No

**Comment by sonic2kk** [comment]
The last release was last year, but the version that gets installed from browsers doesn't match the GitHub releases. I'm running v3.0.0.9, the latest GitHub release is v3.0.0.3, and is the only release.

_Some_ work is still being done, but as pointed out various PRs appear to be in limbo.

Clarification on the state of the project would be good to know.

**Comment by Anarios** [comment]
Ain't dead, even getting fixes when YouTube UI changes. But I don't have much time to go through github, sorrry.

**Comment by fillwithjoy1** [comment]
> Ain't dead, even getting fixes when YouTube UI changes. But I don't have much time to go through github, sorrry.

all good, got scared when the commits stopped incoming

**Comment by Anarios** [comment]
>  got scared when the commits stopped incoming

Wasn't much to do, it was working, so I wasn't touching it. Not to mention migration to bigger machines in backend which took some of my attention.
