### ISSUE TITLE
RYD broken again with youtube's new "likes" real-time update feature

### ISSUE THREAD

**Issue by bolabola6789** [Anarios/return-youtube-dislike#928]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Firefox Stable

### Browser Version

115.0.2

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.9

### Video link where you see the problem

Every video

### What happened?

As the title suggests, dislikes now will not display. I have no idea if this issue has been reported on Discord, since I no longer using it. The real-time likes count update is an A/B feature, and my main Google account is in that unfortunate group. Please fix.
![image](https://github.com/Anarios/return-youtube-dislike/assets/105188534/57860fe9-1d3a-43e7-a35b-82619ed02302)
My own screenshot crop, Youtube Redux extension was used and I tried turning off the extension, stayed the same. Tried with another Google account, no issue happened
The like counter increases every few seconds while I watch the video.

### How to reproduce/recreate?

Have your account to be unluckily selected in the A/B testing lot. 

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Sypher2k** [comment]
It stopped working for me too days ago but for some reason now it works again XD i have no idea why

**Comment by dundunn** [comment]
The Firefox extension stopped working for me as of yesterday, Greasemonkey script is working in the same browser profile. Seems like the DOM changed and now the JS can't find the right element anymore. 
![image](https://github.com/Anarios/return-youtube-dislike/assets/10534189/31015d9d-82ae-4afd-b594-8bda4158b0cd)

**Comment by bolabola6789** [comment]
Both didn't work for me. Guess it's different between accounts


Vào 16:17, Th 4, 2 thg 8, 2023 Dun ***@***.***> đã viết:

**Comment by MesaBlack** [comment]
![image](https://github.com/Anarios/return-youtube-dislike/assets/132141735/8366d239-9c75-418a-9bf5-131d7035b3c5)
This like-dislike count isn't as I'd remember it...

**Comment by Gersonzao** [comment]
Working again for me on Firefox

**Comment by Anarios** [comment]
Fixed in 3.0.0.14
