### ISSUE TITLE
userscript broke again (07.27.23)

### ISSUE THREAD

**Issue by EricE549X** [Anarios/return-youtube-dislike#929]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Safari

### Browser Version

16.5.2

### Extension or Userscript?

Userscript

### Extension/Userscript Version

3.1.2

### Video link where you see the problem

every video

### What happened?

dislike count doesn't show as of this morning (eastern time)

### How to reproduce/recreate?

1. go to any video
2. see error

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by EricE549X** [comment]
nvm dislike count shows again

**Comment by icynstant** [comment]
I just opened like 10 videos and after that dislikes just gone. I tryed reinstall extension. (Firefox)
