### ISSUE TITLE
123,456 number format is inconsistent

### ISSUE THREAD

**Issue by MesaBlack** [Anarios/return-youtube-dislike#932]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

Chrome v115

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.10

### Video link where you see the problem

https://www.youtube.com/watch?v=t5Nwgd_T1-4

### What happened?

Here, the likes on the left are in the 123K format, but the dislikes are in the 123,456 format.
![image](https://github.com/Anarios/return-youtube-dislike/assets/132141735/754a63cc-3a40-42d1-8b98-d4243f25e881)

### How to reproduce/recreate?

You just head there and you see it.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

No

**Comment by cheneyni-451** [comment]
The default extension configuration does not re-format the likes number. You have to enable the "Re-format like numbers" option in the extension settings to see the likes number formatted the same way as the dislikes number.

**Comment by Nightcaat** [comment]
Works as intended; as mentioned there is an option to reformat the like numbers. Click the extension icon then the gear to access settings.
