### ISSUE TITLE
The ratio bar shrinks

### ISSUE THREAD

**Issue by legycsapo1** [Anarios/return-youtube-dislike#933]
### Have you tried to find similar open issues?

- [x] Yes, this issue is not a duplicate

### Browser

Chrome

### Browser Version

Version 115.0.5790.171 (Official Build) 

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.10

### Video link where you see the problem

https://www.youtube.com/watch?v=RTT5k2imblA&t

### What happened?

If you hit like, dislike and then again like the ratio bar will reduce in size a lot. On a fairly popular video with some dislikes it's the most noticeable.

![ratiobar](https://github.com/Anarios/return-youtube-dislike/assets/81675270/4b0bbdc2-1dc9-4334-a6a3-55d74ef47ebc)

### How to reproduce/recreate?

If you hit like, dislike then again like it will happen, the ratio bar will shrink noticeably.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by pcroland** [comment]
![](https://telegra.ph//file/8a2b54bc235e2c76169b0.png)
This would be the proper way to show the bar if you ask me.

**Comment by MesaBlack** [comment]
3 comma 1?

**Comment by Anarios** [comment]
Fixed in 3.0.0.14
