### ISSUE TITLE
Add a dislike counter for comments

### ISSUE THREAD

**Issue by foursplaysroblox** [Anarios/return-youtube-dislike#939]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Add to ryd (return youtube dislike) an option to see dislike counters on comments

### Ways to implement this!

1. Putting the dislike counter next to the dislike counter

### Can you work on this?

- [ ] Yes
- [X] No

### Will you be available for follow-up questions to help developers implement this?

Yes

**Comment by AminoffZ** [comment]
While I'm not on the team, I believe implementing this feature is feasible. However, I question whether the demand warrants the substantial increase in storage and API calls it would necessitate. It's worth noting that such implementation would largely fall to the backend team, as that portion of the code isn't open-source.

**Comment by eclipsek20** [comment]
> increase in storage and API calls it would necessitate.

If only there where other alternatives to the API, *cough* *cough*  #473

**Comment by AminoffZ** [comment]
> > increase in storage and API calls it would necessitate.
> 
> If only there where other alternatives to the API, _cough_ _cough_ #473

Good point

**Comment by Nightcaat** [comment]
This has already been ruled out due to the ridiculously large database that would be required for it, even if only top comments were stored.
