### ISSUE TITLE
(Feature Request): YTVanced integration?

### ISSUE THREAD

**Issue by SimonFoxcoon** [Anarios/return-youtube-dislike#94]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Any way we can get it integrated into YT Vanced so that dislikes are even more accessible on mobile?

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by brycecorbitt** [comment]
I don't work on Vanced, but I thought I'd share a relevant request on the YouTube Vanced Repo: [https://github.com/YTVanced/Vanced/issues/1394](https://github.com/YTVanced/Vanced/issues/1394)

**Comment by Anarios** [comment]
We'd be happy to, but it's up to Vanced.
