### ISSUE TITLE
(Feature Request): Option so likes/dislikes aren't sent to youtube

### ISSUE THREAD

**Issue by danielocdh** [Anarios/return-youtube-dislike#942]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

A new option so like/dislike data is not sent to youtube.

It probably shouldn't be enabled by default as most users wouldn't expect the behavior, still users could be notified that the feature exists after updating the extension.

I think it could make return-youtube-dislike have extra data that doesn't rely on youtube, I feel like youtube doesn't deserve to have the like/dislike data if the dislikes are not gonna be public.

### Ways to implement this!

With the option enabled the likes/dislikes would not be sent to youtube so the data would be a bit different, I think the return-youtube-dislike api call should be different and something would be needed to be implemented server side to receive and count/process this different data

### Can you work on this?

- [ ] Yes
- [ ] No

### Will you be available for follow-up questions to help developers implement this?

Yes

**Comment by CodingArctic** [comment]
i feel like this wouldn't punish youtube as much as it would punish independent content creators. if your like data isn't being sent, at a big enough scale, your favorite creator would be missing out on the likes they need to get pushed in the algorithm. that's just my opinion though

**Comment by Nightcaat** [comment]
RYD is mostly meant to be a bandaid for the lack of a dislike count but I think the bigger problem regarding this suggestion is implementing it:
* How do we keep track of a user’s ratings and show it to them when the rating buttons load?
* How do we differentiate between normal and RYD ratings in YouTube’s UI?
* What do we show if someone has rated on YouTube but rated differently on RYD by toggling the extension or rating from another device?
These aren’t super difficult problems to solve but the question is if anyone’s willing to and if it’s worth adding to RYD and maintaining.

**Comment by danielocdh** [comment]
@CodingArctic You are likely right, RYD for creators functionality would need to be added or another extension with it created
@Nightcaat 
- It would have to be saved on the extension or server side having to authenticate the user, both options seem not great
- RYD would give the value of stored likes, the extension would then sum the likes(or show only either amount according to settings)
- Priority could be chosen on extension settings

So now it seems to me that this suggestion would have to make RYD a fully independent alternative for the youtube dislike+like system, which might be too far from the purpose of RYD
