### ISSUE TITLE
Return Youtube Dislike v3.0.0.11 - new UI fixes

### ISSUE THREAD

**Issue by AbilashVenkatesan** [Anarios/return-youtube-dislike#946]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Chrome

### Browser Version

118.0.5993.71

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.11 - new UI fixes

### Video link where you see the problem

i dont have any video

### What happened?

I have downloaded the zip folder for Chrome v3.0.0.11 - new UI fixes - return YouTube dislike, the extension works for YT shorts and shows dislikes, but the videos do not show the dislike number.

### How to reproduce/recreate?

None of the videos shows the dislike count.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Astral1280** [comment]
I don't know how to use GitHub because I'm not an expert in programming, would you be kind enough to create something that doesn't require programming.

**Comment by ParkerGit2328** [comment]
Waitin' for the updates to hit extension stores....

**Comment by itsmetoolala** [comment]
"but the videos do not show the dislike number."
Yes, same here. "Normal" Videos aren't showing up the dislike numbers. But "Shorts" are functional working.
Using official Version 3.0.0.9 from chrome webstore or what that name is for getting some extensions for chrome.
Sorry, not an expert (anymore).

**Comment by NicoTheCinderace** [comment]
> "but the videos do not show the dislike number." Yes, same here. "Normal" Videos aren't showing up the dislike numbers. But "Shorts" are functional working. Using official Version 3.0.0.9 from chrome webstore or what that name is for getting some extensions for chrome. Sorry, not an expert (anymore). EDIT: I did a re-install of the addon w/o success.

You need to wait for the update to be approved, much like everyone else.

**Comment by tdreams2** [comment]
Temporary solution https://github.com/Anarios/return-youtube-dislike/issues/950#issuecomment-1762669008

**Comment by Anarios** [comment]
> I found a solution and the dislike count appears but I'm not sure if it's reliable this way or not
> 
> I changed this line of code in createDislikeTextContainer() function: `const textNodeClone = (getLikeButton().querySelector("button > div[class*='cbox']") || getLikeButton().querySelector('div > span[role="text"]').parentNode).cloneNode(true);`
> 
> changed to this: `const textNodeClone = (getLikeButton() || getLikeButton().parentNode).cloneNode(true);`

moving this commnet here from the clone-issue.

**Comment by AminoffZ** [comment]
Working PR #952

**Comment by NicoTheCinderace** [comment]
Welp, here we are again. YouTube ONCE AGAIN decided to update their UI, breaking Return YouTube Dislike.

Sigh.

**Comment by Nightcaat** [comment]
It seems this specific problem has already been resolved. Please try updating RYD to 3.0.0.12 (and if you have YouTube Redux, to 3.2.0) before making a new issue.
