### ISSUE TITLE
Dislike isn't working anymore ! 

### ISSUE THREAD

**Issue by Shiroo77** [Anarios/return-youtube-dislike#947]
### Have you tried to find similar open issues?

- [ ] Yes, this issue is not a duplicate

### Browser

Firefox

### Browser Version

Multithreading

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.10

### Video link where you see the problem

https://www.youtube.com/watch?v=d6F4B5KxRo8

### What happened?

13th Oct, I'm not able to view the dislikes 

![image](https://github.com/Anarios/return-youtube-dislike/assets/141759574/1c445c42-c2bf-4d0c-bbed-e98f7bf0e91d)

### How to reproduce/recreate?

Videos aren't showing the dislikes. I've also got a prompt on Youtube that "Ad Blocker aren't allowed" (Maybe that's related to uBlock) 

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Anarios** [comment]
Clone of #944
