### ISSUE TITLE
Number of dislikes is shown on the "Share" icon

### ISSUE THREAD

**Issue by Tasosgemah** [Anarios/return-youtube-dislike#948]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Firefox

### Browser Version

110.0.1

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.10

### Video link where you see the problem

https://www.youtube.com/watch?v=kpGo2_d3oYE

### What happened?

The number of dislikes is shown on the "Share" icon.\

Dislike icon doesn't have any number but you can still see it on the ratio bar pop-up. And it's always the same number as the one shown on the "shares" icon.

The video linked is an example of many dislikes and how it's the same number as the share number.

### How to reproduce/recreate?

Watch any video.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by TheRealBlazeKing** [comment]
This might be a Firefox bug since it doesn't happen on 118.0.2

**Comment by Nightcaat** [comment]
Hi, is this still happening for you?

**Comment by alpe12** [comment]
> Hi, is this still happening for you?

Don't know about OP.
But for me, yes. :/

**Comment by Tasosgemah** [comment]
> Hi, is this still happening for you?

Yes.

**Comment by Enrico9431** [comment]
Has been for me as well for quite a while now on chrome

**Comment by Bravo555** [comment]
Same issue in Firefox 119.0 on Windows 11 with RYD v3.0.0.12.

Looks like the share button is erroneously returned on this line:

https://github.com/Anarios/return-youtube-dislike/blob/2c7dd8d8caef8c584002d49c3013ea9d8d079453/Extensions/combined/src/buttons.js#L54

or on line 787 when viewed in a debugger:

![image](https://github.com/Anarios/return-youtube-dislike/assets/10912424/12ae43a9-9173-4e20-aa15-1d88d9799ea6)

![image](https://github.com/Anarios/return-youtube-dislike/assets/10912424/d61c5a21-9ca3-4b46-9532-4b322bcee6eb)

**Comment by Bravo555** [comment]
I created a fix, If you want to test it, you can download the extension for your browser from here: https://github.com/Bravo555/return-youtube-dislike/releases/tag/v3.0.0.13r1.

You'll need to sideload the extension into the browser.

Alternatively, if you don't want to load unverified zip files, you can clone my [branch with the fix](https://github.com/Bravo555/return-youtube-dislike/tree/fix/948/dislike-count-on-share-button) and build it yourself by following the [CONTRIBUTING.md](https://github.com/Anarios/return-youtube-dislike/blob/main/CONTRIBUTING.md) guide.
