### ISSUE TITLE
Manifest missing

### ISSUE THREAD

**Issue by ScruffR** [Anarios/return-youtube-dislike#955]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome & MS Edge

### Browser Version

Chrome 118.0.5993.71, Edge 118.0.2088.46

### Extension or Userscript?

Extension

### Extension/Userscript Version

latest per 10/14/2023

### Video link where you see the problem

any

### What happened?

I tried to load the unpacket extension I just downloaded from GitHub and got this Chrome
![image](https://github.com/Anarios/return-youtube-dislike/assets/6604878/8fca321b-de15-4e2d-a1f4-0eb167604a41)
and this in Edge
![image](https://github.com/Anarios/return-youtube-dislike/assets/6604878/313af414-6585-4f0e-83dc-a20bdbd64692)

I also tried selecting the subfolder containing the manifest `C:\Program Files\Tools\return-youtube-dislike\Extensions\combined\manifest-chrome.json` and any folder in between.

### How to reproduce/recreate?

see above

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by tazlsucks** [comment]
You downloaded the source code. Download the file named chrome.zip

**Comment by Nightcaat** [comment]
As mentioned, you need to download the corresponding ZIP file for your browser, not the whole source code.
