### ISSUE TITLE
Dislikes does not work If you are logged into an account

### ISSUE THREAD

**Issue by GladistonXD** [Anarios/return-youtube-dislike#965]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Chrome

### Browser Version

118.0.5993.88

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.11

### Video link where you see the problem

All links

### What happened?

When I log out the count appears, as soon as I log in to any account it disappears again

### How to reproduce/recreate?

When I log out the count appears, as soon as I log in to any account it disappears again

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Senbonzakura1234** [comment]
@GladistonXD currently mine isn't working in any case at all
![image](https://github.com/Anarios/return-youtube-dislike/assets/43206347/ee9f77e9-9996-4f00-b276-a2b45e720265)

**Comment by michalrozek90** [comment]
I can confirm that it's **not** working only when you are logged in. After log out I was able to see dislikes but only then.

**Comment by SaltyCucumber** [comment]
At first it worked in incognito, then I tried reinstalling the extension, and now it doesn't work at all, just like @Senbonzakura1234

**Comment by Senbonzakura1234** [comment]
> It does work if you are not logged in @Senbonzakura1234 Try enabling extension in incognito mode, I think you forgot that judging by the screenshot

Is there any info out there indicate that youtube is disabling the dislike count api output?

**Comment by SaltyCucumber** [comment]
> Is there any info out there indicate that youtube is disabling the dislike count api output? @SaltyCucumber I only notice the dislike count problem all because of the new anti adblock policies

I think the API works fine, it's some other issue, cause you can open console (F12) and see the dislike counter there:
[return youtube dislike]: SET dislikes 571

so it does get the data itself, it's just an UI issue it seems

**Comment by Senbonzakura1234** [comment]
> > Is there any info out there indicate that youtube is disabling the dislike count api output? @SaltyCucumber I only notice the dislike count problem all because of the new anti adblock policies
> 
> @Senbonzakura1234 I think the API works fine, it's some other issue, cause you can open console (F12) and see the dislike counter there: [return youtube dislike]: SET dislikes 571
> 
> so it does get the data itself, it's just an UI issue it seems `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')` this line indicates that they probably changed some HTML/CSS and the extension code can't parse it properly

Anyway this show youtube could change the ui frequently and it will disfunction our extension, we should create our own like and dislike bar, or in the extension popup, like what they do with ghostery.

**Comment by SaltyCucumber** [comment]
> Anyway this show youtube could change the ui frequently and it will disfunction our extension, we should create our own like and dislike bar, or in the extension popup, like what they do with ghostery. @SaltyCucumber

It's just the most convenient way to see the ratio where it's suppose to be naturally, the problem with this approach is that sometimes it will be broken, like it is right now.

**Comment by Toni500github** [comment]
try to use the latest version 3.0.0.12 from here or wait until the webstore updates the extensions, because it works to me now with this version

**Comment by GladistonXD** [comment]
Version 3.0.0.12 released today resolved this issue.

**Comment by GladistonXD** [comment]
The same problem came back

**Comment by Toni500github** [comment]
Bruh
