### ISSUE TITLE
Doesn't work with Brave Browser, Possible YouTube Interference

### ISSUE THREAD

**Issue by Palmsunday** [Anarios/return-youtube-dislike#968]
Cannot see dislikes on Youtube videos running Brave browser with extension version 3.0.0.11 installed. The issue seemed to appear around the same time Youtube started enforcing ads on their platform just recently. I believe this to be caused by Youtube blocking whatever violates their policies.

**Comment by Toni500github** [comment]
i would have said go for the new 3.0.0.12 version, but it broke again even with this. it worked a week ago, but now i get "Temporarily Unavailable" near dislike button
![image](https://github.com/Anarios/return-youtube-dislike/assets/88878648/3ae6069f-6722-4358-a1b9-c223090e40f9)
