### ISSUE TITLE
Like/dislike bar starts acting crazy on some videos (it drops all the likes down to "0")

### ISSUE THREAD

**Issue by ricardonevesmusic** [Anarios/return-youtube-dislike#969]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

118.0.5993.72

### Extension or Userscript?

Extension

### Extension/Userscript Version

Version 3.0.0.12

### Video link where you see the problem

https://www.youtube.com/watch?v=1PwNo17fiWA • https://www.youtube.com/watch?v=qgc6bvs2QHY

### What happened?

The extension started acting crazy on certain randomly opened YouTube videos and drops all the "likes/dislikes" down to "0".

Watch this video to see what I'm talking about:
[Here's the video](https://github.com/Anarios/return-youtube-dislike/assets/64813627/337a53d4-4631-48b5-8ce5-70cde04f6b5d)

There you go.

Just wanted to share/show this, just in case you didn't yet knew about it.

### How to reproduce/recreate?

After updating the extension manually from v3.0.0.11 to v3.0.0.12, the "dislikes" were shown again, but then when I opened 2 random videos from YouTube's main/home page, the "like/dislike" bar started acting crazy and had "a life of its own".

Watch this video to see what I'm talking about:
[Here's the video](https://github.com/Anarios/return-youtube-dislike/assets/64813627/337a53d4-4631-48b5-8ce5-70cde04f6b5d)

There you go.

Just wanted to share/show this, just in case you didn't yet knew about it.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Anarios** [comment]
Thanks for report, YouTube are implementing some kind of weird "live" updates to like counts - it could be the reason

**Comment by ricardonevesmusic** [comment]
> Thanks for report, YouTube are implementing some kind of weird "live" updates to like counts - it could be the reason

I'll close this thread.

After updating Chrome to the latest version, everything got solved.

But it might be what you're saying: the "live" updates might be messing all of this.

If this consistently happens again later, I'll reopen this thread/post (for now it just doesn't make sense to leave this one open, as there might be more important issues to be solved at the moment than my own).

Thank you.
