### ISSUE TITLE
YouTube Dislikes aren't showing up - New Youtube UI Update.

### ISSUE THREAD

**Issue by NicoTheCinderace** [Anarios/return-youtube-dislike#971]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Firefox

### Browser Version

Version 118.0.2

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.1

### Video link where you see the problem

https://www.youtube.com/watch?v=xR94Cc6Z9uQ

### What happened?

YouTube dislikes stopped showing up. Again.

### How to reproduce/recreate?

Just watch a YouTube video. That's it.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by NicoTheCinderace** [comment]
Fuckin' hell, YouTube. Can you **stop** breaking this for one goddamn month?

**Comment by Nightcaat** [comment]
Unsure if you missed a 1 but v3.0.0.1 is _very_ outdated. Try updating to v3.0.0.12 if possible. If you still have problems, try disabling other extensions that affect YouTube like YouTube Redux.

**Comment by highflux7** [comment]
v3.0.0.12 Failing for me as well.

**Comment by NicoTheCinderace** [comment]
> Unsure if you missed a 1 but v3.0.0.1 is _very_ outdated. Try updating to v3.0.0.12 if possible. If you still have problems, try disabling other extensions that affect YouTube like YouTube Redux.

It somehow refused to update, so... it works now. ty. <3

**Comment by Nightcaat** [comment]
> v3.0.0.12 Failing for me as well.

Please [create a new issue](https://github.com/Anarios/return-youtube-dislike/issues/new/choose) for this :)
