### ISSUE TITLE
v3.0.0.12 not showing dislikes w/firefox 

### ISSUE THREAD

**Issue by highflux7** [Anarios/return-youtube-dislike#972]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Firefox

### Browser Version

118.0.2 (linux)

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.12

### Video link where you see the problem

https://www.youtube.com/watch?v=4Vwz36zkHz0

### What happened?

Dislike button displayed without a count.

### How to reproduce/recreate?

Hit the thumbs down button and observe no number/tally ever appears indicating your 'vote'.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Nightcaat** [comment]
Do you have YouTube Redux? If so, Redux 3.2.0 should fix this issue.

**Comment by highflux7** [comment]
why would i install yet another extension to fix a broken extension?

**Comment by NicoTheCinderace** [comment]
Rebumping this, as it's broken now.

**Comment by necrovamp** [comment]
Happens for me here on firefox.  
I did notice there is a small white line under the thumb icons, which if I hover over it, it does show likes/dislikes count

The link you provided does show likes and dislikes, with or without "Return YouTube Dislike" turned on.
If I get time I will send some screenshots

**Comment by jakeyounglol** [comment]
also happens on the same version with chromium on latest macOS. it just shows the dislike count on the share button

**Comment by OKok-3** [comment]
Same here. It appears that the dislike count is showing up in the share button instead
![image](https://github.com/Anarios/return-youtube-dislike/assets/53050459/3913df77-809a-4e77-9cbe-0b428160b989)

**Comment by iiPythonx** [comment]
![image](https://github.com/Anarios/return-youtube-dislike/assets/35084023/8613e30f-4800-4a85-91d8-537d9664af33)
Same issue as OKok-3.

**Comment by Anarios** [comment]
Fixed in 3.0.0.14
