### ISSUE TITLE
Dislikes are broken again. Temporarily Unavailable

### ISSUE THREAD

**Issue by proninyaroslav** [Anarios/return-youtube-dislike#975]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

118.0.5993.88

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.12

### Video link where you see the problem

https://youtu.be/UyA93RbBndM

### What happened?

This happened a few minutes ago from the moment the issue was created. It just says "Temporarily Unavailable".
![image](https://github.com/Anarios/return-youtube-dislike/assets/7840559/ce06ae42-8e98-47f4-9573-ae3bdd5b46b5)

I see this in the log:
![image](https://github.com/Anarios/return-youtube-dislike/assets/7840559/103d03c0-5aed-4537-8381-0640db66f146)

### How to reproduce/recreate?

Just open any video and wait a bit for an error message.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Anarios** [comment]
![image](https://github.com/Anarios/return-youtube-dislike/assets/3018711/8c475ec2-955f-4945-b92b-c98c353ffea1)

hoster-side issue, status can be tracked here https://status.hetzner.com/incident/7b20d42c-8943-4209-82e8-3c5f88946eda

**Comment by Dacatzgoescodin5267** [comment]
Getting the same issue, i think dumbass youtube is being a bastard and keeps patching it out to censor us

**Comment by Tr3yWay996** [comment]
> Getting the same issue, i think dumbass youtube is being a bastard and keeps patching it out to censor us

You serious ? like frfr ? You dont see this freaking message from Anarios ??? its a hoster side issue not ur nonsense

**Comment by Anarios** [comment]
> > Getting the same issue, i think dumbass youtube is being a bastard and keeps patching it out to censor us
> 
> You serious ? like frfr ? You dont see this freaking message from Anarios ??? its a hoster side issue not ur nonsense

the messages were almost simultaneous :) no need to crucify him

**Comment by Drflash55** [comment]
> the messages were almost simultaneous :) no need to crucify him

I believe GitHub regularly updates posts without needing refreshes, so even though the window was slightly marginal... could've still seen it before the post was made.

Either way, will wait and see if it fixes itself soon.

**Comment by Anarios** [comment]
Fixed, plz reopen if still facing issues
