### ISSUE TITLE
(Bug): Dislike is not up to date

### ISSUE THREAD

**Issue by PlayerXYT** [Anarios/return-youtube-dislike#98]
### Browser

Firefox

### Browser Version

94.0.2 (64)

### Extension or Userscript?

Extension

### Extension/Userscript Version

Latest

### Video link where you see the problem

N/A

### What happened?

The dislike count seems to lag behind, I know that the database is only updated every 2-3 days but while the V3 API still allows it use it as a live update while you still can

**Comment by mgcountss** [comment]
It's the way they are fetching the dislikes.

**Comment by Anarios** [comment]
Faster updates coming, but right now some data is several days old

**Comment by Anarios** [comment]
"while the V3 API still allows it"

V# api allows 10k requests per day. We receive 10k requests in a half a minute.
