### ISSUE TITLE
No features work as of 11/21/23 with chrome extension on latest Brave

### ISSUE THREAD

**Issue by kyleb1111** [Anarios/return-youtube-dislike#980]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Brave

### Browser Version

Version 1.60.118 Chromium: 119.0.6045.163 (Official Build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.12

### Video link where you see the problem

https://www.youtube.com/watch?v=QeaJPqKDOPE

### What happened?

Something is preventing all of the extensions features from working; including not showing dislike count, numbers not being reformatted, percentages not shown, and colorization feature not working. None of these features work on any YouTube video.

Uninstalling and re-installing the extension does not fix this problem.

### How to reproduce/recreate?

- Install latest extension for chrome/brave
- Set preferences
- View any YouTube video and observe the results
- See screenshots
![ss2](https://github.com/Anarios/return-youtube-dislike/assets/85330782/bdaf031a-cadb-4ec4-9948-807485c04a04)
![ss1](https://github.com/Anarios/return-youtube-dislike/assets/85330782/6ec1d605-0b7c-4634-84ef-6115710ed77f)

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by ElliotFoley** [comment]
Same issue here. Hope it gets fixed soon.

**Comment by kyleb1111** [comment]
Fixed in 3.0.0.14
