### ISSUE TITLE
Dislike number is on the share button

### ISSUE THREAD

**Issue by IronClaw99** [Anarios/return-youtube-dislike#990]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Mozilla Firefox

### Browser Version

Firefox v120.0

### Extension or Userscript?

Extension

### Extension/Userscript Version

Version 3.0.0.12

### Video link where you see the problem

Any video

### What happened?

The dislike number is on the share button instead of where it should be.

### How to reproduce/recreate?

I disabled the extension and the number disappeared.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by xxSeys1** [comment]
Got the same problem here. 
![image](https://github.com/Anarios/return-youtube-dislike/assets/111653551/71c5a850-c72f-4bbd-8117-4990dd31a13e)

**Comment by Mikkel136** [comment]
Can confirm on MS Edge 121. It looks like YouTube pushed a structural change that kills the dislike text container and changes the "Dislike" icon to refer to an "undefined" class, likely to mess with plugins like these

**Comment by MesaBlack** [comment]
also, Share177
![image](https://github.com/Anarios/return-youtube-dislike/assets/132141735/d6fdf65f-8661-4c48-9b39-aeda62ec66a3)

**Comment by Scotty-Trees** [comment]
Same issue here on Fedora Gnome using Firefox v120 with v3.0.0.12 of Dislike Button. Hope it gets fixed before Xmas! :+1:

**Comment by Lefthornet** [comment]
Same issue here with Edge and Brave on Windows. Also on Linux Mozilla

**Comment by 10Meisterbaelle** [comment]
Can confirm, Firefox (latest) on MacOS (latest)

**Comment by EricE549X** [comment]
same for userscript on safari

**Comment by iG8R** [comment]
Same here.
 - OS: Microsoft Windows [Version 10.0.19045.2673] 64bit
 - Browser: Firefox 120.0 64bit

![image](https://github.com/Anarios/return-youtube-dislike/assets/11407417/58e15015-efbe-4728-a9f8-a08b55e06f9f)

**Comment by NicoTheCinderace** [comment]
Ditto for Firefox.

**Comment by benjaminmesser** [comment]
I'm still getting this issue on Chrome 119.0.6045.200 Windows 11

**Comment by mrkrabs206** [comment]
windows 10 same here Chrome 119.0.6045.200
