### ISSUE TITLE
Number of dislikes on the share button

### ISSUE THREAD

**Issue by AvenCores** [Anarios/return-youtube-dislike#993]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

119.0.6045.200

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.12

### Video link where you see the problem

None

### What happened?

![image](https://github.com/Anarios/return-youtube-dislike/assets/64781822/c9357dbf-ecd2-4ec7-a7fb-2c7c1ee8de5d)

### How to reproduce/recreate?

Open any video 

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by NicoTheCinderace** [comment]
Happening to me via Firefox.

**Comment by julausrie** [comment]
I have this issue on Firefox aswell

**Comment by AvenCores** [comment]
> It's already fixed in the repo, now we just need to wait for the update to be approved in extension stores - #991

Approximately how long before the update comes to the chrome extension store?

**Comment by fadster** [comment]
The extension was updated on December 4th but it's still broken.

**Comment by AvenCores** [comment]
> The extension was updated on December 4th but it's still broken.

+

**Comment by Anarios** [comment]
Fixed in 3.0.0.14

**Comment by bigkwii** [comment]
yes, it works as normal now. tysm
