### ISSUE TITLE
Dislikes are going to the share tab when logged into an account.

### ISSUE THREAD

**Issue by GladistonXD** [Anarios/return-youtube-dislike#998]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Chrome

### Browser Version

118.0.5993.88

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.12

### Video link where you see the problem

All links

### What happened?

Whenever I'm logged into an account this happens, apparently the information that was supposed to go to the dislike button ends up in the sharing tab.

![image](https://github.com/Anarios/return-youtube-dislike/assets/50533550/167b9b56-9404-46dc-a1be-e016a238aeb1)

### How to reproduce/recreate?

Login.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by tendan** [comment]
I can confirm that issue also occurs on Firefox 120.0b9. Furthermore, the number on it increases when you click share button. I really thought that YouTube added share counting...

**Comment by GladistonXD** [comment]
> Please do not create duplicates, #993

It doesn't explain that the reason is to be logged into the account, the button changes when you log in, hence the error, so theoretically it is not a duplicate.

**Comment by UnderscoreAngel** [comment]
> It doesn't explain that the reason is to be logged into the account, the button changes when you log in, hence the error, so theoretically it is not a duplicate.

this happens because the account has the flag experiment that enables it, YouTube has a test system where they roll out new experiments on random user accounts, if you get unlucky they roll it out to a few accounts first before rolling it out to everyone, and you can be one of those.

**Comment by GladistonXD** [comment]
I myself made a correction to the code using xpath to ensure that even if a button changes location or has a similar button it always goes to the dislike button, I will send an implementation note to the developer.

**Comment by UnderscoreAngel** [comment]
> I myself made a correction to the code using xpath to ensure that even if a button changes location or has a similar button it always goes to the dislike button, I will send an implementation note to the developer.

yeah, i'm sure this issue was caused because YouTube changed their buttons to "view-models" on their experiment, since the dislike counter isn't supposed to work with them, they just appear next to the share counter because it's the only button that doesn't use the whole "view-model" thing.

**Comment by UnderscoreAngel** [comment]
> I made this very rough correction, but it works both logged in and out.
> 
> ```js
> function getDislikeButton() {
>   return document.querySelector("#segmented-dislike-button, dislike-button-view-model");
> }
> 
> function getLikeButton() {
>   return document.querySelector("#segmented-like-button, like-button-view-model");
> }
> ```

amazing.

**Comment by hiddenmask58** [comment]
> I made this very rough correction, but it works both logged in and out.
> 
> ```js
> function getDislikeButton() {
>   return document.querySelector("#segmented-dislike-button, #dislike-button, dislike-button-view-model");
> }
> 
> function getLikeButton() {
>   return document.querySelector("#segmented-like-button, #like-button, like-button-view-model");
> }
> ```

how to use this?

**Comment by UnderscoreAngel** [comment]
> I made this very rough correction, but it works both logged in and out.
> 
> ```js
> function getDislikeButton() {
>   return document.querySelector("#segmented-dislike-button, #dislike-button, dislike-button-view-model");
> }
> 
> function getLikeButton() {
>   return document.querySelector("#segmented-like-button, #like-button, like-button-view-model");
> }
> ```

hey, i wasn't able to get this working on a userscript sheet am i doing something wrong?

**Comment by GladistonXD** [comment]
> how to use this?

Edit the `ryd.content-script.js` file by replacing the `getDislikeButton()` and `getLikeButton()` functions and update the extension through the manager or restart the browser.

**Comment by GladistonXD** [comment]
> 
> hey, i wasn't able to get this working on a userscript sheet am i doing something wrong?

What is userscript sheet?
You can test whether the button was found by playing `document.querySelector("#segmented-dislike-button, #dislike-button, dislike-button-view-model");` in the browser console.
